Arize-ai/phoenix

src/phoenix/server/api/context.py, src/phoenix/server/api/dataloaders/span_annotations.py, src/phoenix/server/api/types/Span.py
=> fix: use dataloader for span annotations

app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx, app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts, app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts, app/src/pages/project/__generated__/SpansTable_spans.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
=> fix: reduce page size of project page queries

examples/manually-instrumented-chatbot/chat-service/chat/app.py
Captures thumbs up rate as emoji to make the demo clear.
=> chore: make feeback annotations more clear in the UI

app/src/components/annotation/AnnotationTooltip.tsx, app/src/components/trace/TraceTreeContext.tsx, app/src/pages/project/AnnotationTooltipFilterActions.tsx, app/src/pages/project/ProjectPage.tsx, app/src/pages/project/SpanFilterConditionContext.tsx, app/src/pages/project/SpanFilterConditionField.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
resolves #2506 
This adds the ability for you to add annotation filters from the table when you see a value that you either want to match or not match.
https://github.com/user-attachments/assets/7b432864-c604-4bf0-97e6-6ad16ad89826
=> feat(UI): annotation filter actions on span/trace tables

tutorials/evals/evaluate_human_vs_ai_classifications.ipynb, tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb, tutorials/evals/evaluate_user_frustration_classifications.ipynb, tutorials/experiments/txt2sql.ipynb, tutorials/internal/openai_request_types.ipynb, tutorials/tracing/autogen_tutorial.ipynb, tutorials/tracing/openai_tracing_tutorial.ipynb
the phoenix.trace instrumentors do not have this param
=> fix: remove skep_deps_check param on phoenix.instrumentors

app/src/pages/trace/SpanDetails.tsx
=> fix(UI): show IO if embedding span is missing embeddings

app/schema.graphql, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/User.py
resolves #4049 
```graphql
{
users {
edges {
node {
username
email
}
}
}
}
```
=> feat(auth): user gql query

app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/UsersTable.tsx, app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
=> feat(auth): users table in settings

app/schema.graphql, app/src/pages/settings/UsersTable.tsx, app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts, pyproject.toml, src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py, src/phoenix/db/models.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/User.py, src/phoenix/server/api/types/UserRole.py
resolves #4227 
resolves: #4222 
```graphql
{
users {
edges {
node {
username
email
role {
role
}
}
}
}
}
```
=> feat(auth): add user role, exclude system in user lists

app/schema.graphql, src/phoenix/db/models.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/ApiKey.py, src/phoenix/server/api/types/SystemApiKey.py, src/phoenix/server/api/types/UserApiKey.py
resolves #4233
resolves #4061
```graphql
{
userApiKeys { name }
}
=> feat(auth): user / system api key resolvers

schemas/openapi.json
- Update OpenAPI spec due to route change in #4259
=> fix: Update OpenAPI spec

.github/workflows/python-CI.yml, packages/phoenix-evals/pyproject.toml, packages/phoenix-otel/pyproject.toml, pyproject.toml, tox.ini
add `-x` to fail fast
https://docs.pytest.org/en/8.3.x/reference/reference.html#command-line-flags
=> ci: standardize testpaths and fail fast

pyproject.toml, src/phoenix/db/engines.py
resolves #4301 
it was using the wrong driver name
=> fix(db): postgresql migrations

src/phoenix/trace/dsl/helpers.py
Filter context with None values.
fixes #4300
=> fix: handle None values in the context

src/phoenix/server/app.py, src/phoenix/server/main.py
Closes #4198, #4248 
fix: Fix main.py boolean flags
=> feat: Add fixtures only for new DBs, add flag to force fixture ingestion

.github/workflows/docker-build-nightly.yml, .github/workflows/docker-build-release.yml
add docker software bill of materials (SBOM) and attestations (https://docs.docker.com/build/metadata/attestations/) to track the materials
=> ci: add docker sbom and attestation flags

tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb, tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
I wanted to add two new .ipynb stored on repo instead of being stored in my personal GitHub account.
=> docs: new hosted_phoenix tutorials

packages/phoenix-otel/pyproject.toml
=> fix(otel): add semantic conventions dependency

src/phoenix/server/dml_event_handler.py
=> fix: annotation events should refresh trace project

pyproject.toml
adding `tox`, `uv` and `tox-uv`
=> chore: update development tooling dependencies

app/src/pages/settings/APIKeysCard.tsx, app/src/pages/settings/DeleteSystemAPIKeyButton.tsx, app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/SystemAPIKeysTable.tsx, app/src/pages/settings/UsersCard.tsx, app/src/pages/settings/__generated__/DeleteSystemAPIKeyButtonMutation.graphql.ts, app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts, app/src/pages/settings/__generated__/SystemAPIKeysTableQuery.graphql.ts
resolves #4360 
Adds the ability to delete system keys
https://github.com/user-attachments/assets/388cc3a6-bd03-4b45-afab-cd74ecb3fe66
=> feat(auth): delete system keys

app/schema.graphql, src/phoenix/server/api/mutations/api_key_mutations.py
Returns a `Query` object from the deleteSystemApiKey mutation
=> feat: Return Query from DeleteSystemApiKey mutation

integration_tests/auth/conftest.py, src/phoenix/db/models.py, src/phoenix/server/bearer_auth.py, src/phoenix/server/jwt_store.py, src/phoenix/server/types.py
correct typos and inconsistencies
=> fix: clean up token auth

app/schema.graphql, src/phoenix/server/api/context.py, src/phoenix/server/api/dataloaders/__init__.py, src/phoenix/server/api/dataloaders/user_roles.py, src/phoenix/server/api/dataloaders/users.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/User.py, src/phoenix/server/api/types/UserApiKey.py, src/phoenix/server/api/types/UserRole.py, src/phoenix/server/app.py
As an admin, I need to know who the "owner" user of a key is. This adds a user field to each userApiKey so that we can display who owns the key in the settings page.
```graphql
{
userApiKeys {
id
user {
username
email
}
}
}
```
=> feat(auth): user of a given key

integration_tests/auth/conftest.py, integration_tests/auth/test_auth.py, src/phoenix/auth.py, src/phoenix/db/facilitator.py, src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py, src/phoenix/db/models.py, src/phoenix/server/api/mutations/auth_mutations.py, src/phoenix/server/api/mutations/user_mutations.py
=> feat: per-user password salt

src/phoenix/config.py, src/phoenix/session/client.py
=> feat: api-key for client headers

src/phoenix/config.py
=> fix: allow secret when auth is disabled

.github/workflows/python-CI.yml, .pre-commit-config.yaml, dev-requirements.txt, integration_tests/auth/conftest.py, integration_tests/auth/test_auth.py, pyproject.toml, src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py, src/phoenix/db/models.py
=> fix: sqlite should autoincrement integer primary keys

docs/Makefile, docs/quickstart/evals.md, docs/tracing/llm-traces-1.md, tutorials/quickstarts/evals_quickstart.ipynb, tutorials/quickstarts/tracing_quickstart_openai.ipynb
Adds a makefile that will convert any tutorials in its list to markdown using nbconvert, then copies them to their listed destination.
To add to this makefile, add a notebook path and docs destination path to the list at the top
=> docs: create nbconvert makefile

app/src/pages/settings/APIKeysCard.tsx, app/src/pages/settings/DeleteAPIKeyButton.tsx, app/src/pages/settings/SystemAPIKeysTable.tsx, app/src/pages/settings/UserAPIKeysTable.tsx, app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts, app/src/pages/settings/__generated__/SystemAPIKeysTableDeleteAPIKeyMutation.graphql.ts, app/src/pages/settings/__generated__/UserAPIKeysTableFragment.graphql.ts, app/src/pages/settings/__generated__/UserAPIKeysTableQuery.graphql.ts
resolves #4361 
- adds user api keys table
- adds delete button - note https://github.com/Arize-ai/phoenix/issues/4059 is not yet finished so deleting is not wired up
- does not block viewing or deleting for non admins - need to make a viewer context to plumb this through #4454
=> feat(auth): add user api keys table

app/schema.graphql, src/phoenix/server/api/mutations/api_key_mutations.py
resolves #4058 
Adds a mutation that allows an authenticated user to create a UserApiKey
=> feat: Add CreateUserApiKey mutation

app/schema.graphql, src/phoenix/server/api/context.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/User.py, src/phoenix/server/api/types/UserApiKey.py
=> chore(auth): implement viewer on query

app/.eslintrc.js, app/package.json, app/src/components/auth/index.tsx, app/src/pages/profile/ProfilePage.tsx, app/src/pages/settings/DeleteSystemAPIKeyButton.tsx, app/src/pages/settings/SettingsPage.tsx
resolves [4454](https://github.com/Arize-ai/phoenix/issues/4454)
=> feat(auth): auth rbac components

src/phoenix/server/main.py
=> feat: render db schema in welcome message when applicable

src/phoenix/server/app.py
switch to the new param to eleminate warning
=> chore: update graphiql param in strawberry

app/src/components/project/PythonProjectGuide.tsx
Remove extra api key reference in slideover
=> style: remove extra api key reference in slideover

integration_tests/auth/test_auth.py, src/phoenix/server/api/routers/v1/__init__.py, src/phoenix/server/app.py, src/phoenix/server/bearer_auth.py
Secures the GraphQL API when authentication is enabled.
resolves #4507
=> feat(auth): secure graphql api when auth is enabled

src/phoenix/server/api/dataloaders/average_experiment_run_latency.py, src/phoenix/server/api/dataloaders/dataset_example_spans.py, src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py, src/phoenix/server/api/dataloaders/experiment_error_rates.py, src/phoenix/server/api/dataloaders/experiment_run_annotations.py, src/phoenix/server/api/dataloaders/experiment_run_counts.py, src/phoenix/server/api/dataloaders/experiment_sequence_number.py, src/phoenix/server/api/dataloaders/span_dataset_examples.py, src/phoenix/server/api/dataloaders/span_projects.py
Ensures that dataloaders return results that correspond to input keys
=> fix: Ensure dataloader output ordering by input keys

src/phoenix/auth.py, src/phoenix/config.py
=> feat: environment variable for `Secure` attribute on cookies

app/src/pages/Layout.tsx
removes error notification on successful logout
=> fix(auth): don't show error on successful logout

app/package.json, src/phoenix/config.py
=> chore(auth): rename env vars

app/src/contexts/ViewerContext.tsx, app/src/pages/auth/ResetPasswordForm.tsx, app/src/pages/profile/ProfilePage.tsx, app/src/pages/profile/ProfilePicture.tsx, app/src/pages/profile/ViewerProfileCard.tsx, app/src/pages/profile/__generated__/ViewerProfileCardMutation.graphql.ts
resolves #4223 
Adds the ability for the user to modify their username
=> feat(auth): edit profile UI

pyproject.toml, src/phoenix/db/migrations/future_versions/README.md
=> chore(auth): clean up unused auth-related commands, checks, and folders

.github/workflows/python-CI.yml, dev-requirements.txt, integration_tests/pytest.ini, pyproject.toml
=> ci: run integration tests on python 3.12

app/src/components/auth/OneTimeAPIKeyDialog.tsx
=> feat(auth): Add API key guidance

.github/workflows/docker-build-auth.yml, .github/workflows/docker-build-experimental.yml
=> ci(auth): add workflow to publish experimental auth docker image

src/phoenix/db/facilitator.py, src/phoenix/server/app.py
=> refactor: remove redundant db facilitator

app/src/components/settings/UserForm.tsx, app/src/pages/settings/NewUserDialog.tsx
=> feat(auth): force password repeat on new user addition

src/phoenix/trace/dsl/query.py, tests/trace/dsl/conftest.py, tests/trace/dsl/test_helpers.py
=> fix: get_retrieved_documents should handle missing values

tutorials/tracing/groq_tracing_tutorial.ipynb
Adds a basic tutorial showing tracing a groq application
=> docs: create groq_tracing_tutorial.ipynb

src/phoenix/__init__.py
=> fix: submodule packaging for bazel

integration_tests/_helpers.py, integration_tests/conftest.py
=> ci: print name of test alongside httpx payload in the log

integration_tests/_helpers.py
=> ci: print decoded token ids in the log

src/phoenix/server/api/routers/oauth2.py
Ensure return URLs are relative.
resolves #4686
=> fix(auth): ensure return urls are relative

pyproject.toml, src/phoenix/trace/trace_dataset.py, tests/trace/test_trace_dataset.py
=> fix: `TraceDataset.to_span()` should unflatten dot separators at all levels

app/playwright.config.ts, app/src/pages/auth/LoginForm.tsx, app/tests/login.rate-limit.spec.ts, integration_tests/auth/conftest.py, src/phoenix/config.py, src/phoenix/server/api/routers/auth.py, src/phoenix/server/api/routers/oauth2.py
=> fix: Correct auth login rate limit routes

app/src/pages/auth/LoginPage.tsx, app/src/pages/auth/ResetPasswordForm.tsx, app/src/pages/auth/ResetPasswordWithTokenForm.tsx, app/src/pages/auth/ResetPasswordWithTokenPage.tsx, app/src/pages/authenticatedRootLoader.ts, app/src/utils/__tests__/routingUtils.test.ts, app/src/utils/routingUtils.ts
=> feat(auth): add user friendly messages to the login page

src/phoenix/auth.py, src/phoenix/db/enums.py, src/phoenix/db/facilitator.py, src/phoenix/db/models.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/routers/auth.py, src/phoenix/server/api/types/User.py
Adds computed attribute for `auth_method` on user table.
resolves #4687
=> refactor(auth): add computed attribute for `auth_method` on `users` table

integration_tests/_helpers.py, integration_tests/auth/test_auth.py, src/phoenix/server/api/routers/auth.py
=> fix: allow logging out with just the refresh token

.tours/app.tour, app/README.md
Adds playwright to the onboarding docs
=> docs: Playwright in READE

app/schema.graphql, app/src/components/user/UserPicture.tsx, app/src/contexts/ViewerContext.tsx, app/src/contexts/__generated__/ViewerContextRefetchQuery.graphql.ts, app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts, app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts, app/src/pages/profile/ViewerProfileCard.tsx, app/src/pages/settings/UsersTable.tsx, app/src/pages/settings/__generated__/UsersCardQuery.graphql.ts, app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts, app/src/pages/settings/__generated__/UsersTable_users.graphql.ts, src/phoenix/server/api/types/User.py
=> feat(auth): Profile picture

src/phoenix/server/jwt_store.py
=> feat: fetch from db on token cache miss

integration_tests/requirements.txt, pyproject.toml, src/phoenix/server/jwt_store.py
resolves #4650 
Only use `authlib` for JWT implementations in production source
=> chore: Remove pyjwt dependency

src/phoenix/server/api/routers/oauth2.py, src/phoenix/server/jwt_store.py
- Catches DecodeErrors when trying to parse invalid jwts
=> fix: Catch decode error

.gitignore, examples/agent_framework_comparison/code_based_agent/main.py, examples/agent_framework_comparison/code_based_agent/router.py, examples/agent_framework_comparison/db/database.py, examples/agent_framework_comparison/langgraph/analyze_data.py, examples/agent_framework_comparison/langgraph/generate_sql_query.py, examples/agent_framework_comparison/langgraph/main.py, examples/agent_framework_comparison/li_workflow/main.py, examples/agent_framework_comparison/prompt_templates/router_template.py, examples/agent_framework_comparison/utils/save_agent_traces.py
Includes some tracing fixes to the langgraph agent to improve how traces appear in Phoenix
=> fix: fixes to the langgraph example agent

pyproject.toml
needs to exclude everything else that also has `__init__.py`
=> chore: update dist build exclusions

.gitignore, app/README.md, app/src/pages/project/DatasetSelectorPopoverContent.tsx
=> fix: Add padding to empty dataset list (#4812)

dev-requirements.txt, pyproject.toml, src/phoenix/server/app.py
[Cross-Site Request Forgery (CSRF) in strawberry-graphql](https://github.com/advisories/GHSA-79gp-q4wv-33fr)
=> fix: bump strawberry-graphql version

pyproject.toml, src/phoenix/pointcloud/clustering.py
=> fix: replace hdbscan with fast-hdbscan

pyproject.toml, src/phoenix/server/main.py
Enables users to run Phoenix with `phoenix serve` and `arize-phoenix serve` and adds a minimalist help message.
=> feat: phoenix cli

app/global-setup.ts, app/tests/member-access.spec.ts
Co-authored-by: Parker Stafford <52351508+Parker-Stafford@users.noreply.github.com>
=> test: add e2e for member creating user api key

.github/workflows/clean_up_caches.yml
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
=> ci: clean up caches by a branch

app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/PlaygroundRunButton.tsx, app/src/pages/playground/PlaygroundTemplate.tsx
https://github.com/user-attachments/assets/88c6805b-114e-4ab3-854a-e88984dbc4e9
=> refactor(playground): move run, test input mode selection the top bar

src/phoenix/server/app.py, src/phoenix/server/bearer_auth.py
provides authentication for websocket connections
resolves #4793
=> fix(playground): authenticate websockets

.git-branches.toml, .github/workflows/git-town.yml
https://www.git-town.com/questions
=> chore: use git town for making stacked changes

app/src/hooks/useChatMessageStyles.ts, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/SpanPlaygroundPage.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/store/playgroundStore.tsx
https://github.com/user-attachments/assets/6536f1f5-1a0e-4560-a0f0-eb02978fb7af
=> feat(playground): make chat messages match style in traces

app/package.json, app/pnpm-lock.yaml, app/src/components/dnd/DragHandle.tsx, app/src/components/dnd/helpers/move.ts, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/store/playgroundStore.tsx
Adds support for drag and drop for messages
https://github.com/user-attachments/assets/665f29df-4e65-4f5c-a4a3-4041ab0825ab
=> feat(playground): re-ordering of messages using dnd

app/src/components/dnd/DragHandle.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundInstance.tsx, app/src/pages/playground/PlaygroundTemplate.tsx
Add the ability to add / remove messages
https://github.com/user-attachments/assets/0a6980f5-7431-42e1-91cd-e318f0aa58a3
=> feat(playground): add / delete messages

app/src/pages/playground/PlaygroundChatTemplate.tsx
resolves #4997 
Copy playground message info to the clipboard
=> feat(playground): copy messages to clipboard

app/schema.graphql, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/ModelPicker.tsx, app/src/pages/playground/ModelProviderPicker.tsx, app/src/pages/playground/PlaygroundCredentialsDropdown.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts, app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts, app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/queries.py, src/phoenix/server/api/subscriptions.py, src/phoenix/server/api/types/GenerativeModelProvider.py, src/phoenix/server/api/types/GenerativeProvider.py, src/phoenix/server/api/types/ModelProvider.py
https://github.com/user-attachments/assets/06a3e467-b6cf-431e-9e38-d8852157a77d
resolves #4989
=> fix(playground): plumb through model name and providers

app/package.json, app/pnpm-lock.yaml, app/src/components/templateEditor/types.ts, app/src/pages/playground/Playground.tsx, app/src/pages/playground/TemplateLanguageRadioGroup.tsx, app/src/store/playground/playgroundStore.tsx
resolves #4996
Adds a toggle for template language to the prompts section
https://github.com/user-attachments/assets/ae8ca877-7fb6-44ea-81e2-1f1932cb8c66
=> feat(playground): toggle for the template language

app/package.json, app/pnpm-lock.yaml, app/src/pages/playground/Playground.tsx
=> chore: bump components to allow for better styling of accordions

src/phoenix/trace/fixtures.py
Consolidates our agent demo traces into one project. Will work with @fjcasti1 once this is merged to update the demo project yaml
=> chore: update fixtures to consolidate demo traces

.github/workflows/docker-build-experimental.yml, .github/workflows/playwright.yaml, .github/workflows/python-CI.yml, .github/workflows/python-cron.yml, .github/workflows/typescript-CI.yml
enable ci on the sessions feature branch
=> ci: add CI to sessions

tox.ini
weird things happen when it's not
=> chore: make symlink operation idempotent

app/schema.graphql, app/src/components/templateEditor/constants.ts, app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/subscriptions.py, src/phoenix/utilities/template_formatters.py, tests/utilities/test_template_formatters.py
Applies template variables.
https://github.com/user-attachments/assets/b523b5de-d2f8-4efb-9047-27369e8f9da1
resolves #5034
=> feat(playground): plumb through and apply template variables

app/schema.graphql, app/src/constants/generativeConstants.ts, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/store/playground/types.ts, src/phoenix/server/api/subscriptions.py, tox.ini
resolves #5039 
- adds azure openai support in client and server
- todo: add persistence to local storage for endpoint, api_version, and deployment name params
=> feat(playground): support azure openai

.gitignore
=> chore: fix gitignore for symlinks

app/src/pages/playground/PlaygroundOutput.tsx
=> fix(playground): remove toolChoice if no tools provided

app/src/pages/playground/PlaygroundOutput.tsx
Results in a cleaner input in the instrumented playground span.
=> fix(playground): optional type in playground tool calls

app/src/RelayEnvironment.ts, app/src/config.ts
=> feat: add support for secure wss connection

app/src/pages/playground/PlaygroundRunTraceDialog.tsx, app/src/pages/playground/RunMetadataFooter.tsx
https://github.com/user-attachments/assets/40b2a9e4-d569-47cd-8e38-7092d8f93978
=> refactor(playground): switch view trace to be a slideover

app/src/contexts/FeatureFlagsContext.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundStreamToggle.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/16a0ba7b-f726-45a6-b3a5-b789e714ac51
=> chore: feature flag for playground streaming and datasets

app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
=> fix(playground): do nothing on credential form submit

pyproject.toml
Update pinned version of LlamaIndex to fix Colab
resolves #5139
Co-authored-by: Roger Yang <roger.yang@arize.com>
=> fix: update llama-index versions in extra

tutorials/credit_card_fraud_tutorial.ipynb, tutorials/find_cluster_export_and_explore_with_gpt.ipynb, tutorials/image_classification_tutorial.ipynb, tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb, tutorials/llama_index_search_and_retrieval_tutorial.ipynb, tutorials/llm_generative_gpt_4.ipynb, tutorials/llm_ops_overview.ipynb, tutorials/llm_summarization_tutorial.ipynb, tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb, tutorials/mistral/evaluate_rag--mistral.ipynb, tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb, tutorials/quickstarts/inferences_quickstart.ipynb, tutorials/ragas_retrieval_evals_tutorial.ipynb, tutorials/sentiment_classification_tutorial.ipynb
resolves https://github.com/Arize-ai/phoenix/issues/5130
=> chore: add embeddings extra to notebook pip installs

pyproject.toml
=> fix: remove `embeddings` from core dependencies

.github/workflows/python-CI.yml, tox.ini
```shell
uvx --with tox-uv tox r -e ruff
```
=> ci: add tox testenv for ruff

app/schema.graphql, src/phoenix/server/api/subscriptions.py, tests/unit/conftest.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
Add test for OpenAI tool call response
=> test(playground): add test for openai tool call response

tutorials/tracing/autogen_tutorial.ipynb
Adds register call, api key prompt, and swaps pyautogen for autogen to match autogen's new best practices
=> docs: update autogen tracing tutorial

app/schema.graphql, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/input_types/ChatCompletionMessageInput.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_messages_emits_expected_payloads_and_records_expected_span[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
Adds unit test for OpenAI tool call messages
resolves #4984
=> test(playground): add unit test for tool call messages

requirements/unit-tests.txt, tests/unit/conftest.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_anthropic_text_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
Adds tests for Anthropic
resolves #4984
=> test(playground): add api test for anthropic

src/phoenix/server/api/subscriptions.py, tests/unit/server/api/test_subscriptions.py
Adds token counts for Anthropic
resolves #5160
=> feat(playground): add token counts for anthropic

README.md
Corrected "Costomizable" to "Customizable" in [README.md].
This pull request addresses a minor typo found in repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.
=> docs: Typo Fix

tutorials/tracing/langchain_tracing_tutorial.ipynb
fixes legacy import issue with langchain notebook
resolves #5196
=> fix(docs): update langchain tutorial

src/phoenix/config.py, src/phoenix/server/app.py, src/phoenix/server/main.py, src/phoenix/server/templates/index.html, src/phoenix/services.py, src/phoenix/session/session.py, tests/unit/conftest.py
=> feat: Detect websocket availability and pass to client

src/phoenix/db/insertion/span.py
=> fix(sessions): for each session record first user by span start time

app/schema.graphql, app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/input_types/InvocationParameters.py, src/phoenix/server/api/subscriptions.py
resolves #4901
see https://platform.openai.com/docs/guides/structured-outputs
=> feat(playground): add `response_format` to invocation parameters

app/schema.graphql, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/subscriptions.py, tests/unit/server/api/test_subscriptions.py
- dry things out a bit by using a context manager for creating llm spans
- remove `ChatCompletionSubscriptionError` type
resolves #5241
=> refactor(playground): use context manager for creating playground llm spans

.gitignore, app/schema.graphql, app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts, app/src/pages/playground/__tests__/fixtures.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/spanPlaygroundPageLoader.ts, pyproject.toml, src/phoenix/server/api/types/Span.py, uv.lock
https://github.com/user-attachments/assets/b88e5a3f-1ace-4086-af8e-ee8218ee26ed
Resolves #5234 
Resolves #5235
=> feat: Provide and then parse invocation params from Span into Playground page store

app/src/components/code/PythonBlock.tsx, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/ModelProviderPicker.tsx, app/src/pages/playground/NoInstalledProvider.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts, app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts, app/src/pages/playground/__generated__/PlaygroundQuery.graphql.ts
https://github.com/user-attachments/assets/9d79a839-20f6-417a-a261-fbfc07bd7280
Resolves #5253
=> feat: Add empty state, helper tooltips, when provider clients are not installed in Playground

app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/schemas/toolChoiceSchemas.ts, requirements/dev.txt, src/phoenix/server/api/helpers/playground_clients.py
resolves #5097 
Supports Anthropic tool calling e2e in the playground
=> feat: Support playground anthropic tool calls

app/schema.graphql, app/src/pages/project/SessionsTable.tsx, app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts, src/phoenix/server/api/input_types/ProjectSessionSort.py, src/phoenix/server/api/types/Project.py, tests/unit/_helpers.py, tests/unit/server/api/types/test_Project.py
resolves #5279 
resolves #5278
=> feat(sessions): enable sorting on sessions table

app/schema.graphql, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/helpers/playground_spans.py, src/phoenix/server/api/subscriptions.py, src/phoenix/server/api/types/ChatCompletionSubscriptionPayload.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionOverDatasetSubscription.test_all_spans_yielded_when_number_of_examples_exceeds_batch_size[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
- eagerly yields experiment, experiment runs, and spans as soon as they become available to improve the streaming experience
- adds experiment runs to subscription results
resolves #5276
=> refactor(playground): improve streaming experience for chat completions over datasets

app/global-setup.ts, app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts, app/src/pages/home/homeLoader.ts, app/tests/admin-access.ts, app/tests/member-access.spec.ts, app/tests/user-management.spec.ts
=> feat: route to the projects page as the default

app/src/components/code/JSONText.tsx, app/src/components/dataset/DatasetPicker.tsx, app/src/components/dataset/__generated__/DatasetPickerQuery.graphql.ts, app/src/components/table/CellWithControlsWrapper.tsx, app/src/components/table/index.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundDatasetSection.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetSectionQuery.graphql.ts, app/src/pages/playground/playgroundUtils.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
=> feat(playground): display streaming outputs for playground runs on datasets

.github/.scripts/collect-customer-issues.js
```
Error fetching comments for issue #5254: TypeError: Cannot read properties of undefined (reading 'owner')
at getParticipants (/home/runner/work/phoenix/phoenix/.github/.scripts/collect-customer-issues.js:28:31)
at formatIssueLine (/home/runner/work/phoenix/phoenix/.github/.scripts/collect-customer-issues.js:101:32)
at /home/runner/work/phoenix/phoenix/.github/.scripts/collect-customer-issues.js:129:11
```
=> chore: fix issues script

packages/phoenix-evals/src/phoenix/evals/models/bedrock.py, packages/phoenix-evals/src/phoenix/evals/models/litellm.py, packages/phoenix-evals/src/phoenix/evals/models/openai.py, packages/phoenix-evals/src/phoenix/evals/models/vertex.py, packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
increases the default number of max tokens for evaluation models
=> fix(evals): increase default max tokens

app/src/Routes.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundDatasetPicker.tsx, app/src/pages/playground/PlaygroundExamplePage.tsx, app/src/pages/playground/PlaygroundPage.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/a2f14fae-fbf4-4a39-b12f-80f54910d534
resolves #5300
=> feat(playground): add playground dataset example slideover

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
resolves #5328
https://github.com/user-attachments/assets/7d991502-e8e7-41a5-89b0-3f673c2e6969
=> feat(playground): update PlaygroundDatasetExamplesTable UI to support mutation (in addition to subscription)

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
https://github.com/user-attachments/assets/f2e05d58-e0a9-4d96-9549-8918e726088a
resolves #5353
=> fix(playground): add tooltip for dataset examples

app/schema.graphql, app/src/@types/generative.d.ts, app/src/constants/generativeConstants.ts, app/src/pages/playground/ChatMessageToolCallsEditor.tsx, app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/PlaygroundCredentialsDropdown.tsx, app/src/pages/playground/PlaygroundTool.tsx, app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts, app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts, app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/constants.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/schemas/toolCallSchemas.ts, app/src/schemas/toolChoiceSchemas.ts, app/src/schemas/toolSchemas.ts, app/src/utils/generativeUtils.ts, requirements/dev.txt, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/types/GenerativeProvider.py
resolves #5154 
w/ @cephalization
=> feat: Add Google AI Studio support (for Gemini models w/ an API key)

app/src/pages/auth/AuthLayout.tsx
https://github.com/user-attachments/assets/44f17fee-e584-495e-a5c4-fa58a604251d
resolves #5365
=> fix(auth): allow login form scroll

app/src/pages/dataset/DatasetPage.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundDatasetSection.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableFragment.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableQuery.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableRefetchQuery.graphql.ts, tutorials/experiments/datasets_and_experiments_quickstart.ipynb
resolves #5382 
- fixes pagination on dataset examples table on playground
- reduces initial and subsequent page sizes
- adds button to navigate to playground from dataset
pagination:
https://github.com/user-attachments/assets/a16bef47-afc0-4e71-91f6-ee4eb0376b95
dataset -> playground nav:
https://github.com/user-attachments/assets/3a871557-0b32-462b-a031-870225e20191
=> fix(playground): fix pagination on playground dataset examples table

app/schema.graphql, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundExperimentRunDetailsDialog.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundExperimentRunDetailsDialogQuery.graphql.ts, src/phoenix/server/api/types/ExperimentRun.py
Adds simple slideover for experiment run details in playground
https://github.com/user-attachments/assets/a8d6a539-1476-47c7-8e91-770500ac6a8d
resolves #5286
=> feat(playground): example run slideover

src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/subscriptions.py, tests/unit/server/api/test_subscriptions.py
=> fix(playground): add llm provider and llm system attributes to playground spans

src/phoenix/server/api/subscriptions.py
- Adds a limit of 10 concurrent streams to be run in playground over a dataset.
- Ensures that at most one task is writing to the DB at any given time.
resolves #5394
=> fix(playground): add limit on the number of concurrent streams for streaming chat completions over a dataset

app/src/pages/playground/PlaygroundDatasetPicker.tsx
=> fix: deselect dataset when selecting active dataset from dropdown

src/phoenix/server/api/mutations/chat_mutations.py
=> fix(playground): batch chat completion requests for mutation

src/phoenix/config.py, src/phoenix/db/facilitator.py
=> feat: add environment variable for default admin initial password

src/phoenix/utilities/json.py
See https://github.com/pandas-dev/pandas/blame/7c9ba89c8ca8bb0f71a3fd1467b61d515611b361/pandas/io/json/__init__.py#L10
only recently changed in aug last year
=> fix: add backup import for ujson_dumps from pandas.io.json

app/schema.graphql, app/src/components/templateEditor/TemplateEditor.tsx, app/src/components/templateEditor/constants.ts, app/src/components/templateEditor/templateEditorUtils.ts, app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/TemplateLanguageRadioGroup.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/playgroundUtils.ts, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/subscriptions.py, src/phoenix/server/api/types/TemplateLanguage.py, src/phoenix/utilities/template_formatters.py
=> feat(playground): add `None` as template formatter option

src/phoenix/server/api/helpers/playground_clients.py
=> fix(playground): capture gemini token count for playground spans

app/src/pages/project/SessionsTable.tsx, app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts
resolves #5357 
resolves #5358
=> feat(sessions): add p50 and p99 trace latency to ui table

src/phoenix/server/api/helpers/playground_clients.py
https://github.com/google-gemini/generative-ai-python/pull/609/files#diff-c21bd4e15abdc392150b9559d9ce77d4e01cdd1e276e4154ea51976718b6dc95L176
=> fix: Remove seed parameter (no longer accepted by server)

tox.ini
=> chore(dx): revert add uv to tox allowlist

schemas/openapi.json, src/phoenix/server/api/routers/v1/evaluations.py
- Adds evaluations routes to OpenAPI schema
=> feat: Add evaluations to openapi schema

app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundResponseFormat.tsx
resolves #5555
Remove the css cascade of padding and just opt for a stable "uneven" padding on the right
=> fix(playground): remove cascade of padding on prompts

app/src/pages/playground/PlaygroundDatasetSection.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundOutputMoveButton.tsx
- **chore: align text vertically in experiments**
- **chore(playground): add explicit text to add message to the end of the propmt**
- **chore(playground): add explicit text to add message to the end of the propmt**
=> chore: add aria text to move messag to the end of the prompt"

app/package.json, app/pnpm-lock.yaml, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts
CI will fail until https://github.com/Arize-ai/openinference/pull/1135 is deployed and this PR is updated with the new version of openinference in package.json
Resolves #5516
=> fix: Detect provider from span attribute, fallback to model name heuristic

src/phoenix/server/api/helpers/playground_clients.py
https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cjavascript-keyless%2Ctypescript-keyless%2Cpython-new&pivots=programming-language-python#create-a-new-python-application
=> fix(playground): add AZURE_OPENAI_API_KEY

app/src/components/experiment/ExperimentActionMenu.tsx, app/src/components/table/styles.ts, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts, app/src/pages/experiments/ExperimentsTable.tsx
=> fix: add copy to clipboard icon for experiment ids on experiment compare page

app/src/pages/playground/Playground.tsx
Since you could be comparing against another model with the same prompt
=> chore: change + prompt to compare

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
resolves #5599
https://github.com/user-attachments/assets/33b20aaf-bd48-48cc-afb2-df914cb988ab
=> fix(playground): handle experiment id's for non streaming

src/phoenix/trace/fixtures.py, tutorials/tracing/project_sessions_llama_index_query_engine.ipynb
=> chore: add fixture and notebook

app/src/pages/project/TypeScriptSessionsGuide.tsx
=> fix(sessions): remove deno style imports

app/src/pages/trace/SessionDetailsTraceList.tsx
=> chore(sessions): minor styling changes to session deetails

src/phoenix/db/insertion/span.py, tests/integration/_helpers.py, tests/integration/project_sessions/test_project_sessions.py
=> fix(sessions): remove requirement that session_id has to be on root span

app/schema.graphql, src/phoenix/db/insertion/span.py, src/phoenix/db/migrations/data_migration_scripts/populate_project_sessions.py, src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py, src/phoenix/db/models.py, src/phoenix/server/api/types/ProjectSession.py, tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py, tests/integration/db_migrations/test_up_and_down_migrations.py, tests/unit/_helpers.py, tests/unit/server/api/types/test_ProjectSession.py
=> fix(sessions): remove session_user from database table

src/phoenix/db/engines.py, tests/unit/db/test_engines.py
=> fix: postgresql url query param

src/phoenix/session/client.py
=> feat(client): add timeout parameters to log_evaluations, get_evaluations

src/phoenix/config.py, src/phoenix/metrics/wrappers.py, src/phoenix/server/api/types/EmbeddingDimension.py, tests/unit/graphql.py, tests/unit/metrics/test_retrieval_metrics.py, tests/unit/metrics/test_wrappers.py
=> ci: fix scikit-learn 1.6 compatibility for unit tests

app/src/components/generative/ToolChoiceSelector.tsx
=> fix(ui): support light mode for tool coice picker

app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/SessionDetailsTraceList.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
https://github.com/user-attachments/assets/729502c8-6bbb-414b-8139-818cd9ce2a52
Resolves #5627
=> feat(sessions): Prettify rendered json mimeType inputs/outputs in session details pane

src/phoenix/server/api/helpers/playground_clients.py
Add gemini-2.0 to phoenix playgrounds
=> feat(playground): Support gemini-2.0-flash-exp model

app/src/components/templateEditor/TemplateEditor.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx
https://github.com/user-attachments/assets/1ce6d6c5-a889-41e6-b8c0-7063ea83db72
As an aside, how do we feel about introducing line numbers now that we have line wrap? I've always found line wrapping kind of confusing without line numbers.
Resolves #5712
Resolves #5713
=> feat(playground): Enhance template editor ergonomics

app/src/Routes.tsx, app/src/components/combobox/ComboBox.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/PromptComboBox.tsx, app/src/pages/playground/__generated__/PromptComboBoxQuery.graphql.ts, app/src/pages/prompt/PromptPage.tsx, app/src/pages/prompt/PromptPlaygroundPage.tsx, app/src/pages/prompt/promptLoader.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/adda9456-482a-4d03-a238-c4a85ca4c22e
Resolves #5736 
Resolves #5735
=> feat(prompts): Add prompt combobox to playground page + deeplink to prompt specific playground

app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/SavePromptForm.tsx, app/src/pages/prompts/PromptsPage.tsx
https://github.com/user-attachments/assets/e4942c4e-9485-42d0-8af3-8ab000cbc40c
Resolves: #5734
=> feat(prompts): Implement SavePromptForm for creating new prompts

app/src/pages/prompt/ChatTemplateMessage.tsx, app/src/pages/prompt/PromptPage.tsx, app/src/pages/prompt/PromptTabContent.tsx, app/src/pages/prompt/__generated__/PromptTabContentAside.graphql.ts, app/src/pages/prompt/__generated__/PromptTabContent__aside.graphql.ts, app/src/pages/prompt/__generated__/PromptTabContent__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/promptLoader.tsx
resolves #5471 
Adds the skeleton of the prompt details view
=> feat(prompts): rudimentary prompt details page #5741

src/phoenix/server/api/dataloaders/session_io.py
=> fix(sessions): exclude null i/o values in dataloader query for sessions table

app/src/pages/project/AnnotationTooltipFilterActions.tsx, app/src/pages/trace/SpanDetails.tsx
=> fix: fix light mode filters and colors

src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, src/phoenix/db/models.py
=> fix(prompts): rename tables

src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, tests/integration/db_migrations/test_autoincrement_primary_keys.py
=> fix(prompts): add sqlite_autoincrement for primary key on prompt_versions table

src/phoenix/server/main.py
=> fix: increase wait time allowance for uvicorn server process start

src/phoenix/server/api/helpers/playground_clients.py
=> fix(playground): add common base class for OpenAI and AzureOpenAI streaming clients

app/src/components/icon/Icons.tsx, app/src/pages/prompt/PromptIndexPage.tsx, app/src/pages/prompt/PromptLatestVersionsList.tsx, app/src/pages/prompt/__generated__/PromptIndexPage__aside.graphql.ts, app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
=> feat(prompts): preview of last 5 versions

app/src/GlobalStyles.tsx, app/src/components/auth/CreateAPIKeyDialog.tsx, app/src/components/code/CodeEditorFieldWrapper.tsx, app/src/components/combobox/ComboBox.tsx, app/src/components/combobox/styles.tsx, app/src/components/content/Text.tsx, app/src/components/dataset/DatasetForm.tsx, app/src/components/field/styles.ts, app/src/components/index.tsx, app/src/components/textfield/TextField.tsx, app/src/components/textfield/index.tsx, app/stories/Button.stories.tsx, app/stories/Gallery.stories.tsx, app/stories/TextField.stories.tsx
resolves #5850
Adds a TextField to Phoenix that's more aligned with aria components composition. Also has 2 sizes.
=> feat(components): TextField

app/schema.graphql, app/src/pages/prompt/PromptCodeExportCard.tsx, app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, src/phoenix/db/models.py, src/phoenix/server/api/helpers/prompts/models.py, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/mutations/__init__.py, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/oauth2.py, src/phoenix/server/api/types/JSONSchema.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersion.py, src/phoenix/server/api/types/PromptVersionTemplate.py, src/phoenix/server/api/types/ToolDefinition.py, tests/unit/server/api/mutations/test_prompt_mutations.py
=> feat(prompts): create prompt mutation

app/schema.graphql, src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, src/phoenix/db/models.py, src/phoenix/server/api/helpers/prompts/models.py, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/mutations/prompt_mutations.py, tests/integration/db_migrations/test_autoincrement_primary_keys.py, tests/unit/server/api/mutations/test_prompt_mutations.py
=> fix(prompts): add types for create prompt mutation input

app/src/components/button/Button.tsx, app/src/components/button/styles.tsx, app/src/components/icon/Icons.tsx, app/src/components/index.tsx, app/src/components/overlay/Popover.tsx, app/src/components/overlay/PopoverArrow.tsx, app/src/components/overlay/index.tsx, app/src/components/tag/Tag.tsx, app/src/components/view/View.tsx, app/src/pages/prompt/PromptCodeExportCard.tsx, app/src/pages/prompt/PromptVersionDetailsPage.tsx, app/src/pages/prompt/TagPromptVersionButton.tsx, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/promptVersionLoader.tsx, app/stories/Popover.stories.tsx
=> chore: add popover for using in prompt version tagging

app/schema.graphql, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/types/Prompt.py, tests/unit/server/api/mutations/test_prompt_mutations.py
=> feat(prompts): create prompt version mutation

app/schema.graphql, app/src/pages/prompt/PromptLatestVersionsList.tsx, app/src/pages/prompt/PromptVersionsList.tsx, app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts, app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, src/phoenix/server/api/types/PromptVersion.py
=> feat(prompts): show version timestamp

schemas/openapi.json, src/phoenix/server/api/routers/v1/__init__.py, src/phoenix/server/api/routers/v1/prompts.py, tests/unit/server/api/routers/v1/test_prompts.py
=> feat(prompts): REST endpoint to get prompt version by tag name

app/schema.graphql, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/promptVersionLoader.tsx, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/types/PromptVersion.py, tests/integration/auth/test_auth.py, tests/unit/server/api/mutations/test_prompt_mutations.py
=> fix(prompts): record user who mutates prompt

app/src/schemas/toolSchemas.ts
=> feat(playground): Support anyOf json schema

app/src/pages/prompt/NewPromptVersionTagDialog.tsx, app/src/pages/prompt/TagPromptVersionButton.tsx, app/src/pages/prompt/__generated__/NewPromptVersionTagDialogMutation.graphql.ts, app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts, app/src/pages/prompt/__generated__/TagPromptVersionButtonTagsQuery.graphql.ts
https://github.com/user-attachments/assets/9acf54f0-2da6-4b15-abb0-224f7ff80775
resolves #5864
=> feat(prompts): UI for setting tags

app/src/components/combobox/styles.tsx, app/src/components/field/styles.ts, app/stories/ComboBox.stories.tsx, app/stories/Gallery.stories.tsx
Make the combobox component consistent
=> chore(components): make combobox consistent

app/src/constants/index.ts, app/src/constants/promptConstants.ts, app/src/pages/prompt/PromptVersionTagsConfigCard.tsx, app/src/pages/prompt/TagPromptVersionButton.tsx, app/src/pages/prompt/__generated__/DeletePromptVersionTagButtonMutation.graphql.ts, app/src/pages/prompt/__generated__/PromptVersionTagsConfigCard_data.graphql.ts, app/src/pages/prompt/__generated__/promptConfigLoaderQuery.graphql.ts
resolves #5966
Adds default tags for easy getting started
https://github.com/user-attachments/assets/d15b7d05-0925-46b5-8862-bcbb0690cba7
=> feat(prompts): default tags for prod / staging / dev

.github/workflows/typescript-packages-CI.yml, .github/workflows/typescript-packages-publish.yml
resolves #6000 
Adds code that forces CI to fail if codegen generates code that is un-accounted for.
=> ci: exit if there is a diff to build artifacts, changesets

app/schema.graphql, src/phoenix/server/api/context.py, src/phoenix/server/api/dataloaders/__init__.py, src/phoenix/server/api/dataloaders/prompt_version_sequence_number.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersion.py, src/phoenix/server/app.py
=> feat: Add sequence number fields to prompt versions

app/schema.graphql, src/phoenix/server/api/types/Prompt.py
=> feat: Resolve source prompts

src/phoenix/experiments/evaluators/__init__.py
=> fix: allow import of LLMRelationalEvaluator

.github/workflows/docker-build-experimental.yml
=> ci: Update docker-build-experimental.yml

app/schema.graphql, app/src/pages/prompts/DeletePromptDialog.tsx, app/src/pages/prompts/PromptActionMenu.tsx, app/src/pages/prompts/PromptsTable.tsx, app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts, src/phoenix/server/api/mutations/prompt_mutations.py
resolves #6072 
Adds the ability to delete a prompt in the UI
=> feat(prompts): delete prompt

app/src/constants/promptConstants.ts, app/src/pages/prompt/TagPromptVersionButton.tsx, app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts, app/src/pages/prompts/PromptsPage.tsx
resolves #6058 
refetch tags and versions on set.
https://github.com/user-attachments/assets/772b0055-24bb-4846-b0d3-d232966baa63
=> fix(prompts): refetch tags after set

app/relay.config.js, app/schema.graphql, src/phoenix/db/models.py, src/phoenix/db/types/identifier.py, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/mutations/prompt_version_tag_mutations.py, src/phoenix/server/api/routers/v1/prompts.py, src/phoenix/server/api/types/Identifier.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersionTag.py, tests/integration/db_migrations/test_autoincrement_primary_keys.py, tests/unit/db/types/test_identifier.py, tests/unit/server/api/mutations/test_prompt_mutations.py, tests/unit/server/api/routers/v1/test_prompts.py
=> refactor(prompts): add `Identifier` scalar with regex validation

schemas/openapi.json, src/phoenix/server/api/routers/v1/prompts.py
resolves #6042 
- Add GET /prompts to list all prompts
- cursor pagination
=> feat: Add GET /prompts route to REST API

app/package.json, app/src/components/disclosure/styles.tsx, app/src/hooks/useChatMessageStyles.ts, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/prompt/PromptChatMessagesCard.tsx, app/src/pages/prompt/PromptIndexPage.tsx, app/src/pages/prompt/PromptInvocationParameters.tsx, app/src/pages/prompt/PromptLatestVersionsList.tsx, app/src/pages/prompt/PromptOutputSchema.tsx, app/src/pages/prompt/PromptTools.tsx, app/src/pages/prompt/PromptVersionDetailsPage.tsx, app/src/pages/prompt/PromptVersionSummary.tsx, app/src/pages/prompt/PromptVersionTagsList.tsx, app/src/pages/prompt/PromptVersionsList.tsx, app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts, app/src/pages/prompt/__generated__/PromptVersionSummaryFragment.graphql.ts, app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts, app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/stories/Disclosure.stories.tsx
=> feat(prompts): display author, tags, etc. in version list

app/src/pages/dataset/RunExperimentButton.tsx
=> fix: correct errors in run experiment python code snippet

src/phoenix/server/api/dataloaders/dataset_example_revisions.py
partially reverts https://github.com/Arize-ai/phoenix/commit/71484e09407e4d73f7641820b7f642bec3a388c0
=> fix: reduce query memory usage in DatasetExampleRevisionsDataLoader

app/.storybook/preview.tsx, app/src/App.tsx, app/src/GlobalStyles.tsx
moves global css vars into app for extension
=> chore(components): move to having design tokens in-app

packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
- Adds regression test for the bug fixed in #6102
=> chore: Add regression test for alternate delimiters

packages/phoenix-otel/src/phoenix/otel/otel.py
Fixes the case when no protocol is passed in
thanks @axiomofjoy
=> fix: Handle default protocol

src/phoenix/trace/trace_dataset.py, tests/unit/trace/test_trace_dataset.py
resolves #4720 
related https://github.com/Arize-ai/phoenix/pull/6111
=> fix: handle span events as ndarray for `TraceDataset.to_span`

app/schema.graphql, app/src/pages/dimension/__generated__/DimensionCardinalityTimeSeriesQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionCountTimeSeriesQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionDriftBreakdownSegmentBarChartQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionDriftTimeSeriesQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionPageQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionPercentEmptyTimeSeriesQuery.graphql.ts, app/src/pages/dimension/__generated__/DimensionQuantilesTimeSeriesQuery.graphql.ts, app/src/pages/embedding/__generated__/EmbeddingPageUMAPQuery.graphql.ts, app/src/pages/embedding/__generated__/MetricTimeSeriesQuery.graphql.ts, app/src/pages/project/__generated__/AnnotationSummaryQuery.graphql.ts, app/src/pages/project/__generated__/AnnotationSummaryValueQuery.graphql.ts, app/src/pages/project/__generated__/DocumentEvaluationSummaryQuery.graphql.ts, app/src/pages/project/__generated__/DocumentEvaluationSummaryValueQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts, app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts, app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts, src/phoenix/server/api/input_types/Granularity.py, src/phoenix/server/api/input_types/TimeRange.py, src/phoenix/server/api/types/Dimension.py, src/phoenix/server/api/types/EmbeddingDimension.py, src/phoenix/server/api/types/Model.py, src/phoenix/server/api/types/TimeSeries.py, tests/unit/server/api/input_types/test_TimeRange.py
=> refactor(gql): make start and end times optional for graphql TimeRange input

src/phoenix/config.py, src/phoenix/experiments/functions.py, src/phoenix/utilities/client.py, src/phoenix/utilities/re.py, tests/unit/datasets/test_experiments.py
=> fix: incorporate headers from environment for experiment trace span exporter

app/schema.graphql, src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, src/phoenix/db/models.py, src/phoenix/server/api/types/PromptVersion.py
=> feat: Add label color and version metadata

internal_docs/README.md, internal_docs/on_call.md
=> docs(inernal): add on_call guide

schemas/openapi.json, src/phoenix/server/api/routers/v1/prompts.py, tests/unit/server/api/routers/v1/test_prompts.py
=> feat(prompts): REST endpoint to get the latest prompt version

app/schema.graphql, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts, app/src/pages/playground/fetchPlaygroundPrompt.ts, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/mutations/prompt_mutations.py, tests/integration/auth/test_auth.py, tests/unit/server/api/mutations/test_prompt_mutations.py
=> fix(prompts): remove template type from input for create prompt mutations

schemas/openapi.json, src/phoenix/server/api/helpers/prompts/models.py, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/mutations/prompt_mutations.py, tests/integration/db_migrations/test_autoincrement_primary_keys.py, tests/unit/server/api/routers/v1/test_prompts.py
=> fix(prompts): use discriminated union for content parts

tutorials/tracing/agentic_rag_tracing.ipynb
Adds an agentic rag tracing example notebook, used to pair with a recent video walkthrough on agentic rag
=> docs: agentic rag notebook

src/phoenix/server/api/helpers/playground_clients.py
=> feat: Add OpenAI `o3-mini` support to playground

app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/input_types/GenerativeModelInput.py, tests/unit/server/api/test_subscriptions.py
=> feat(playground): record url info in playground spans

packages/phoenix-evals/src/phoenix/evals/models/openai.py
- both o1 and o3 class models do not support these parameters
=> fix: Update parameter filtering logic

app/src/pages/prompts/PromptsTable.tsx, app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts, app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts, app/src/pages/prompts/__generated__/PromptsTable_prompts.graphql.ts, app/src/pages/prompts/__generated__/promptsLoaderQuery.graphql.ts
Add description and last updated at to the prompts table
=> feat(prompts): add description, last updated at to the prompts table

app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/schemas/toolSchemas.ts, app/src/store/playground/playgroundStore.tsx
https://github.com/user-attachments/assets/57819cb5-f52e-4490-91a9-4c691e7a6e0c
Created https://github.com/Arize-ai/phoenix/issues/6338 in response to this issue
=> fix(prompts): Do not wipe playground response format when switching providers

.github/workflows/playwright.yaml, app/global-setup.ts, app/src/components/field/styles.ts, app/tests/login.rate-limit.spec.ts, app/tests/user-management.spec.ts
=> fix: restore playwright passing

src/phoenix/server/api/routers/v1/prompts.py
=> fix: eliminate cartesian join in REST endpoint

app/src/components/templateEditor/language/__tests__/languageUtils.test.ts, app/src/components/templateEditor/language/languageUtils.ts
=> fix(prompts): trim leading and trailing whitespace from mustache template variables

app/src/components/settings/UserForm.tsx, app/src/pages/auth/LoginForm.tsx, app/src/pages/auth/ResetPasswordForm.tsx, app/src/pages/auth/ResetPasswordPage.tsx, app/src/pages/auth/__generated__/ResetPasswordFormQuery.graphql.ts, app/src/pages/auth/__generated__/resetPasswordLoaderQuery.graphql.ts, app/src/pages/auth/resetPasswordLoader.ts
adds the appropriate autocomplete values and form fields for a11y.
=> fix: login a11y via autocomplete

app/src/pages/prompts/PromptsTable.tsx
=> fix(prompts): Perform prompt table sorting on the client

js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb, js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb, js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb
=> chore(prompts): Fix deno notebook syntax

app/src/components/templateEditor/TemplateEditor.tsx
=> fix(prompts): Fix syntax highlighting in template editors

src/phoenix/session/client.py
=> fix: missing slash in examples url printed after dataset upload

app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts, app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/pages/prompt/PromptPlaygroundPage.tsx
resolves #6365 
This restores the ability to load in an azure openai prompt. It also makes the version a combobox.
=> fix(promts): load invocation parameters for azure openai

app/package.json, app/pnpm-lock.yaml
Appeasing dependabot. I mostly want to see if CI passes when I make my own PR
=> chore(prompts): Upgrade vite + vitest

app/src/pages/dataset/DatasetPage.tsx
=> fix(promts): dataset URL

packages/phoenix-otel/pyproject.toml, packages/phoenix-otel/src/phoenix/otel/otel.py
=> feat: enable one-line instrumentation with phoenix.otel.register

tutorials/prompts/from_anthropic.ipynb, tutorials/prompts/from_openai.ipynb
instead of px.Client (which refers to px.session.Client)
=> chore: use px.client.Client in tutorials for prompts

api_reference/source/api/client.resources.prompts.rst, api_reference/source/api/client.resources.rst, api_reference/source/api/client.rst, api_reference/source/api/client.types.prompts.rst, api_reference/source/api/client.types.rst, api_reference/source/conf.py, packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py, packages/phoenix-client/src/phoenix/client/types/prompts.py
=> chore: update sphinx for phoenix client

src/phoenix/server/prometheus.py
`psutil` reports host-level metrics which can be confusing if run in a container. Try to use Linux `cgroup` based metrics instead if available.
https://docs.docker.com/engine/containers/runmetrics/
=> fix: Use container-aware system resource usage metrics if possible

src/phoenix/server/api/types/Span.py, tests/unit/server/api/types/test_Span.py
resolves https://github.com/Arize-ai/phoenix/issues/6534
=> fix: return None for graphql for null input output values on spans 

app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
=> fix(perf): remove double fetching of spans

app/src/components/trace/TraceTree.tsx
restores scroll on the trace tree
=> fix(ui): fix lack of scrolling on trace tree

app/src/pages/settings/DBUsagePieChart.tsx, app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/__generated__/DBUsagePieChart_data.graphql.ts, app/src/pages/settings/__generated__/settingsPageLoaderQuery.graphql.ts, app/src/pages/settings/settingsPageLoader.ts, app/src/utils/storageSizeFormatUtils.ts
=> feat(admin): introspection into DB usage

app/schema.graphql, app/src/pages/project/TracesTable.tsx, app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/project/__generated__/TracesTable_spans.graphql.ts, src/phoenix/db/models.py, src/phoenix/server/api/dataloaders/span_descendants.py, src/phoenix/server/api/input_types/SpanSort.py, src/phoenix/server/api/types/Span.py, tests/__generated__/graphql/__init__.py, tests/unit/server/api/types/test_Span.py
=> fix(performance): put depth limit on descendant spans query

app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
=> fix(ui): span status on the left of table

app/src/pages/project/TracesTable.tsx, app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
=> feat(perf): show + n more spans in traces table

packages/phoenix-client/README.md
=> fix: add README for phoenix client

app/.storybook/preview-body.html, app/.storybook/preview.tsx, app/src/GlobalStyles.tsx, app/src/components/index.tsx, app/src/components/token/Token.tsx, app/src/components/token/index.tsx, app/src/contexts/ThemeContext.tsx, app/stories/Token.stories.tsx
Note: This does not do automatic color band rotation... May need inspiration on how to do this in pure css when I am using css vars for color extensively
Resolves #5831
=> feat(components): Add Token component

src/phoenix/server/api/helpers/playground_clients.py
add support for 4.5. preview https://openai.com/index/introducing-gpt-4-5/
=> feat(playground): add gpt-4.5-preview

js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/db/insertion/document_annotation.py, src/phoenix/db/insertion/span_annotation.py, src/phoenix/db/insertion/trace_annotation.py, src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py, src/phoenix/db/models.py, src/phoenix/server/api/dataloaders/annotation_summaries.py, src/phoenix/server/api/routers/v1/spans.py, src/phoenix/server/api/routers/v1/traces.py, src/phoenix/server/api/types/AnnotationSummary.py, tests/integration/db_migrations/test_up_and_down_migrations.py, tests/unit/db/insertion/test_helpers.py, tests/unit/server/api/dataloaders/conftest.py, tests/unit/server/api/dataloaders/test_annotation_summaries.py
=> feat: Allow multiple annotations per span with the same name

CONTRIBUTING.md, DEVELOPMENT.md
=> docs: update python developer guide to use tox

app/schema.graphql, src/phoenix/config.py, src/phoenix/server/api/queries.py
=> feat: add environment variable for database storage capacity

js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py, schemas/openapi.json, src/phoenix/server/api/helpers/prompts/models.py, tests/integration/prompts/test_prompts.py, tests/unit/server/api/helpers/test_models.py
=> feat: add anthropic thinking config param for python client

packages/phoenix-otel/src/phoenix/otel/otel.py
=> feat: Add SimpleSpanProcessor warning

app/src/pages/experiments/DownloadExperimentActionMenu.tsx, app/src/pages/experiments/ExperimentsTable.tsx, js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/server/api/routers/v1/experiments.py
REST route to download experiment run data as JSON and action menu in experiments table
resolves #6660
=> feat: experiment json downloads

app/src/pages/dataset/DatasetPage.tsx, app/src/pages/datasets/DatasetFromCSVForm.tsx
=> fix: ensure fetch requests include base path prefix

app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/SessionDetailsTraceList.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
=> fix: broken url from session to trace

src/phoenix/experiments/types.py
=> fix: ensure type is correct on run_experiment

app/schema.graphql, app/src/pages/project/SpanSelectionToolbar.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx, app/src/pages/project/__generated__/SpanSelectionToolbarDeleteTracesMutation.graphql.ts, src/phoenix/server/api/mutations/__init__.py, src/phoenix/server/api/mutations/trace_mutations.py, tests/unit/server/api/mutations/test_trace_mutations.py
https://github.com/user-attachments/assets/178f1a34-fd70-4baf-b805-39c430f6d33d
resolves #6523
=> feat: delete selected traces

src/phoenix/server/api/helpers/playground_clients.py
=> fix: ignore top_p if extended thinking is enabled for playground

app/src/pages/settings/DBUsagePieChart.tsx, app/src/pages/settings/__generated__/DBUsagePieChart_data.graphql.ts, app/src/pages/settings/__generated__/settingsPageLoaderQuery.graphql.ts, app/src/utils/storageSizeFormatUtils.ts, tox.ini
=> feat(admin): show percent used of DB

app/.eslintrc.js, app/src/components/field/NumberField.tsx, app/src/components/field/TextField.tsx, app/src/components/field/index.tsx, app/src/components/index.tsx, app/src/components/slider/Slider.tsx, app/src/components/slider/index.tsx, app/src/pages/playground/InvocationParametersFormFields.tsx, app/stories/Slider.stories.tsx
Additionally expose NumberField from the TextField primitive
=> feat: Port slider component to react-aria

.github/workflows/python-CI.yml, scripts/ci/ensure_graphql_mutations_have_permission_classes.py, tox.ini
resolves #6687 
error example:
=> ci: ensure graphql mutations are decorated with permission classes

app/package.json, app/pnpm-lock.yaml, app/src/GlobalStyles.tsx, app/src/components/ExternalLink.tsx, app/src/components/Link.tsx, app/src/components/button/styles.tsx, app/src/components/code/JSONBlock.tsx, app/src/components/code/JSONEditor.tsx, app/src/components/code/PythonBlock.tsx, app/src/components/code/TypeScriptBlock.tsx, app/src/components/markdown/MarkdownModeRadioGroup.tsx, app/src/components/nav/Navbar.tsx, app/src/components/templateEditor/TemplateEditor.tsx, app/src/components/toggleButtonGroup/ToggleButton.tsx, app/src/components/trace/SpanKindIcon.tsx, app/src/components/trace/TraceTree.tsx, app/src/pages/embedding/ExportSelectionButton.tsx, app/src/pages/experiment/ExperimentRunFilterConditionField.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/VariableEditor.tsx, app/src/pages/project/SessionSearchField.tsx, app/src/pages/project/SpanFilterConditionField.tsx, app/src/pages/projects/ProjectActionMenu.tsx, app/src/pages/projects/ProjectsPage.tsx, app/src/pages/prompt/PromptCodeExportCard.tsx, app/src/pages/prompts/PromptsPage.tsx, app/src/pages/trace/SpanDetails.tsx
- **black and white**
- **feat(ui): high contrast theme**
=> feat(ui): high contrast ui

app/src/components/generative/ToolChoiceSelector.tsx, app/src/schemas/toolChoiceSchemas.ts, pyproject.toml, requirements/canary/sdk/anthropic.txt, requirements/ci.txt, requirements/dev.txt, requirements/packages/phoenix-client.txt, requirements/type-check.txt, requirements/unit-tests.txt, src/phoenix/server/api/helpers/prompts/conversions/anthropic.py
=> fix: add none as option for anthropic tool choice

src/phoenix/db/models.py, src/phoenix/server/api/routers/v1/experiments.py, tests/unit/server/api/routers/v1/test_experiments.py
=> fix: add annotations to experiment json download

app/src/components/slider/Slider.tsx
=> fix: Tighten padding and height tolerances for Slider component

app/.eslintrc.js, app/src/components/counter/Counter.tsx, app/src/components/index.tsx, app/src/components/project/PythonProjectGuide.tsx, app/src/components/tabs/Tabs.tsx, app/src/components/tabs/index.tsx, app/src/pages/apis/APIsPage.tsx, app/src/pages/dataset/DatasetCodeDropdown.tsx, app/src/pages/dataset/DatasetPage.tsx, app/src/pages/embedding/EmbeddingPage.tsx, app/src/pages/embedding/PointSelectionPanelContent.tsx, app/src/pages/model/ModelPage.tsx, app/src/pages/project/ProjectPage.tsx, app/src/pages/prompt/PromptLayout.tsx, app/src/pages/settings/APIKeysCard.tsx, app/src/pages/trace/SpanDetails.tsx, app/stories/Tabs.stories.tsx
https://github.com/user-attachments/assets/d4786961-f64e-465e-b530-16ec64772eb7
=> feat(components): Add react-aria Tabs components

app/src/pages/project/MetadataTableCell.tsx, app/src/pages/project/SessionsTable.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx, app/src/store/tracingStore.tsx
https://github.com/user-attachments/assets/11856104-c9c0-4167-adae-04ba5ea0d08f
Resolves #6753
=> feat: Add resize capability to Span, Trace, and Session table

docs/Makefile, docs/prompt-engineering/use-cases-prompts/chain-of-thought-prompting.md, docs/prompt-engineering/use-cases-prompts/few-shot-prompting.md, docs/prompt-engineering/use-cases-prompts/prompt-optimization.md, docs/prompt-engineering/use-cases-prompts/react-prompting.md, tutorials/prompts/chain_of_thought_prompting.ipynb, tutorials/prompts/few_shot_prompting.ipynb, tutorials/prompts/react_prompting.ipynb
Getting 4 prompts notebooks onto docs branch
=> docs: prompt notebooks

README.md, app/src/components/button/styles.tsx, app/src/components/code/CodeEditorFieldWrapper.tsx, app/src/components/dataset/NewDatasetButton.tsx, app/src/components/toggleButtonGroup/ToggleButton.tsx, app/src/contexts/ThemeContext.tsx, app/src/pages/project/SpanSelectionToolbar.tsx
resolves #6829 
Most likely caused by react-aria changing the even propagation on buttons.
=> fix(ui): broken popovers

app/src/components/experiment/ExperimentActionMenu.tsx, app/src/components/experiment/__generated__/ExperimentActionMenuDeleteExperimentMutation.graphql.ts, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiments/ExperimentsTable.tsx
https://github.com/user-attachments/assets/b776d333-3faf-4e24-829b-05cce5c6491a
resolves #6729
=> feat: add delete experiment to action menu

pyproject.toml, src/phoenix/config.py, src/phoenix/db/facilitator.py, tests/unit/db/test_facilitator.py, tests/unit/test_config.py
=> feat: environment variable for inserting admin users at startup

app/src/pages/project/ProjectIndexPage.tsx, app/src/pages/projects/ProjectsPage.tsx
=> fix: Remove sticky project nav history

app/src/pages/trace/SpanFeedback.tsx, app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
resolves https://github.com/Arize-ai/phoenix/issues/6877
=> fix(annotations): show metadata

app/src/pages/trace/SpanFeedback.tsx, scripts/testing/send_spans.py
=> fix(feedback): show full metadata

app/src/Routes.tsx, app/src/components/annotation/AnnotationLabel.tsx, app/src/components/radio/RadioGroup.tsx, app/src/pages/settings/AnnotationConfigDialog.tsx, app/src/pages/settings/AnnotationConfigSelectionToolbar.tsx, app/src/pages/settings/AnnotationConfigTable.tsx, app/src/pages/settings/SettingsAnnotationsPage.tsx, app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/__generated__/AnnotationConfigTableFragment.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateCategoricalAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateContinuousAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateFreeformAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageFragment.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateCategoricalAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateContinuousAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateFreeformAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/settingsAnnotationsPageLoaderQuery.graphql.ts, app/src/pages/settings/settingsAnnotationsPageLoader.ts, app/src/pages/settings/types.ts
https://github.com/user-attachments/assets/bc48278e-bf86-4a5c-a577-6bcfa7687271
=> feat(annotations): Annotation Config UI

app/schema.graphql, src/phoenix/server/api/mutations/annotation_config_mutations.py, src/phoenix/server/api/types/AnnotationConfig.py
=> feat: mutation to remove project annotation config association

app/src/components/field/NumberField.tsx, app/src/pages/settings/GlobalRetentionPolicyCard.tsx, app/src/pages/settings/SettingsGeneralPage.tsx, app/src/pages/settings/__generated__/GlobalRetentionPolicyCardMutation.graphql.ts, app/src/pages/settings/__generated__/GlobalRetentionPolicyCardQuery.graphql.ts
Not sure how I feel about debounced input vs modal vs inline save button.
Let me know your opinion
Resolves #6824
=> feat: Add input for configuring global retention policy

app/schema.graphql, src/phoenix/server/api/types/AnnotationConfig.py
create an annotation config base interface that's shared across all annotation configs
=> refactor(annotaitons): add a annotationConfigBase interface

src/phoenix/server/api/mutations/annotation_config_mutations.py
=> fix(annotations): ensure that remove annotation config from project mutation does not remove all

app/schema.graphql, app/src/components/trace/NewSpanAnnotationForm.tsx, app/src/components/trace/__generated__/NewSpanAnnotationFormMutation.graphql.ts, js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py, src/phoenix/db/models.py, src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py, src/phoenix/server/api/input_types/CreateTraceAnnotationInput.py, src/phoenix/server/api/input_types/PatchAnnotationInput.py, src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/v1/spans.py, src/phoenix/server/api/routers/v1/traces.py, src/phoenix/server/api/types/AnnotationSource.py, src/phoenix/server/api/types/SpanAnnotation.py, src/phoenix/server/api/types/Trace.py, src/phoenix/server/api/types/TraceAnnotation.py, tests/integration/_helpers.py, tests/integration/auth/test_auth.py, tests/unit/server/api/dataloaders/conftest.py, tests/unit/server/api/mutations/test_dataset_mutations.py, tests/unit/server/api/routers/v1/test_traces.py, tests/unit/server/api/types/test_Project.py, tests/unit/server/api/types/test_SpanAnnotation.py, tests/unit/server/api/types/test_TraceAnnotation.py, tests/unit/trace/dsl/conftest.py
=> fix(annotations): add fields to annotations table

app/schema.graphql, js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py, schemas/openapi.json, src/phoenix/db/engines.py, src/phoenix/db/insertion/helpers.py, src/phoenix/db/types/identifier.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/v1/prompts.py, src/phoenix/server/api/types/PromptVersionTag.py, tests/__generated__/graphql/__init__.py, tests/integration/_helpers.py, tests/integration/prompts/test_prompts.py
=> feat: add REST endpoints to list or create prompt version tags

README.md, js/packages/phoenix-mcp/LICENSE, js/packages/phoenix-mcp/README.md
=> docs: fix readmes for MCP

js/.changeset/calm-cities-post.md, js/packages/phoenix-client/README.md, packages/phoenix-client/README.md, packages/phoenix-otel/README.md
- **docs: add nice headers**
- **cleanup**
=> chore: add changesets

js/packages/phoenix-mcp/src/promptSchemas.ts, js/packages/phoenix-mcp/src/promptTools.ts
=> feat(mcp): add prompt descriptions and tagging endpoints

app/src/pages/playground/ModelConfigButton.tsx
=> fix: Don't close model settings dialog when picking azure version

app/src/components/datetime/TimeRangeSelector.tsx
- autofocus with arrow key nav
- close on click outside or esc
Resolves #7054
Resolves #6946
=> fix: Make time range selector more accessible

src/phoenix/server/api/types/Annotation.py, src/phoenix/server/api/types/SpanAnnotation.py
resolves #7075 
Add created_at, updated_at to annotations for sorting etc.
=> feat(annotations): add timestamps to annotation gql type

.github/workflows/docker-build-experimental.yml, .github/workflows/playwright.yaml, .github/workflows/python-CI.yml, .github/workflows/typescript-CI.yml, .github/workflows/typescript-packages-CI.yml, app/schema.graphql, app/src/components/chat/MessageBar.tsx, app/src/components/chat/MessageBubble.tsx, app/src/components/chat/MessageBubbleSkeleton.tsx, app/src/components/chat/index.tsx, app/src/components/chat/styles.ts, app/src/components/loading/Skeleton.tsx, app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanNotesEditor.tsx, app/src/pages/trace/__generated__/SpanNotesEditorAddNoteMutation.graphql.ts, app/src/pages/trace/__generated__/SpanNotesEditorQuery.graphql.ts, app/src/utils/timeFormatUtils.ts
resolves #6947 
Note that this PR is missing a few things like filtering and timestamps.
=> feat(annotations): add notes UI

app/src/components/trace/AnnotatorKindToken.tsx, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/pages/trace/SpanFeedback.tsx
resolves #7053 
Consolidates human and programatic feedback and adds scroll.
=> feat(tracing): make feedback table scroll

app/src/components/trace/AnnotationActionMenu.tsx, app/src/components/trace/SpanAnnotationActionMenu.tsx, app/src/pages/trace/SpanFeedback.tsx, app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
resolves #7083 
Add the ability to delete annotations in the table
=> feat(tracing): delete annotation from the table

app/src/components/trace/AnnotatorKindToken.tsx, app/src/pages/trace/SpanFeedback.tsx, app/src/pages/trace/SpanNotesEditor.tsx, app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts, app/src/pages/trace/__generated__/SpanNotesEditorQuery.graphql.ts
resolves #7079
Shows the full table with everything needed to decipher what happened with an annotation.
=> feat(annotations): full annotations table

app/schema.graphql, src/phoenix/server/api/input_types/SpanAnnotationFilter.py, src/phoenix/server/api/types/Span.py, tests/unit/server/api/input_types/test_SpanAnnotationFilter.py
=> feat(annotations): span annotation filters

app/package.json, app/pnpm-lock.yaml, app/src/Routes.tsx, app/src/pages/settings/RetentionPoliciesTable.tsx, app/src/pages/settings/SettingsDataPage.tsx, app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/__generated__/RetentionPoliciesTablePoliciesQuery.graphql.ts, app/src/pages/settings/__generated__/RetentionPoliciesTable_policies.graphql.ts, app/src/pages/settings/__generated__/settingsDataPageLoaderQuery.graphql.ts, app/src/pages/settings/settingsDataPageLoader.tsx
First part of the retention policy UI elements. Just shows a list of retention policies in the settings page.
=> feat(admin): system level retention policies table

src/phoenix/server/api/helpers/playground_clients.py
[source](https://github.com/openai/openai-python/commit/7d2b97d660882f68283cb2b54303660d1f73bec1)
=> fix: update gpt models for playground

app/schema.graphql, src/phoenix/server/api/dataloaders/annotation_summaries.py, src/phoenix/server/api/types/AnnotationSummary.py, src/phoenix/server/api/types/Span.py, tests/unit/server/api/types/test_Span.py
=> feat: graphql query for annotation summaries per span

app/package.json, app/pnpm-lock.yaml, app/src/pages/settings/CreateRetentionPolicy.tsx, app/src/pages/settings/RetentionPoliciesTable.tsx, app/src/pages/settings/RetentionPolicyForm.tsx, app/src/pages/settings/SettingsDataPage.tsx, app/src/pages/settings/__generated__/CreateRetentionPolicyMutation.graphql.ts, app/src/pages/settings/__generated__/RetentionPoliciesTablePoliciesQuery.graphql.ts, app/src/pages/settings/__generated__/RetentionPoliciesTable_policies.graphql.ts, app/src/pages/settings/__generated__/settingsDataPageLoaderQuery.graphql.ts
Add create retention policy dialog
=> feat(admin): create retention policy UI

tutorials/integrations/ragas_agents_cookbook_phoenix.ipynb
Small PR to update the description in the ragas cookbook
=> docs: updating ragas

pyproject.toml
resolves https://github.com/Arize-ai/phoenix/issues/7186
this is a stopgap solution for the time being
=> fix: require starlette>=0.46.0

src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py, src/phoenix/db/migrations/versions/8c9ff7c78bce_add_annotation_indexes.py, src/phoenix/db/migrations/versions/bb8139330879_create_project_trace_retention_policies_table.py, src/phoenix/db/models.py, src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py, src/phoenix/server/api/routers/v1/spans.py, tests/integration/db_migrations/test_up_and_down_migrations.py, tests/unit/server/api/dataloaders/conftest.py, tests/unit/server/api/mutations/test_span_annotation_mutations.py
resolves #7007 
resolves #7080
resolves #7009
=> feat: Upsert on annotation identifier conflict

js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py, src/phoenix/db/models.py, src/phoenix/db/types/annotation_configs.py, src/phoenix/db/types/db_models.py, src/phoenix/server/api/helpers/prompts/models.py, src/phoenix/server/api/mutations/annotation_config_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/v1/annotation_configs.py, src/phoenix/server/api/types/AnnotationConfig.py, src/phoenix/server/api/types/Project.py
Use a JSON column for annotation configs.
resolves #7210
=> refactor(annotations): use json column for annotation configs

app/src/pages/settings/EditRetentionPolicy.tsx, app/src/pages/settings/RetentionPoliciesTable.tsx, app/src/pages/settings/RetentionPolicyActionMenu.tsx, app/src/pages/settings/RetentionPolicyForm.tsx, app/src/pages/settings/__generated__/EditRetentionPolicyMutation.graphql.ts, app/src/pages/settings/__generated__/EditRetentionPolicyQuery.graphql.ts, app/src/pages/settings/__generated__/RetentionPolicyActionMenuDeletePolicyMutation.graphql.ts
resolves #7191 
resolves #7218 
Adds the ability to edit or delete retention policies.
=> feat(admin): add the ability to edit / delete retention policies

tutorials/deployment/AWS Cloudformation/app.yml, tutorials/deployment/AWS Cloudformation/permissions.json, tutorials/deployment/AWS Cloudformation/phoenix-auth.yml, tutorials/deployment/AWS Cloudformation/phoenix-network.yml
created folder for cloudformation deployment
testing
rebasing for correct email on commit
**changing user to pjindal@arize.com**
=> docs: adding files for aws deployment tutorial

tests/integration/_helpers.py, tests/integration/auth/conftest.py, tests/integration/auth/test_auth.py
This PR adds comprehensive test coverage for OpenID Connect (OIDC) authentication:
- Add `_OIDCServer` mock implementation for testing OAuth2/OIDC flows
- Add test cases for OIDC signup flow including:
- Successful user creation and token generation
- Conflict redirect for existing users with password
- Access and refresh tokens in Phoenix cookies
- Add helper function `_list_users` to support OIDC test scenarios
- Update test configuration to support OIDC testing environment
No functional changes to the codebase - purely test additions.
```mermaid
sequenceDiagram
actor User
participant Phoenix as Phoenix App
participant OIDC as OIDC Server
participant DB as Database
User->>Phoenix: Click "Login with OIDC"
Phoenix->>Phoenix: Generate state & nonce
Phoenix->>OIDC: Redirect to OIDC auth …
```
=> test: OpenID Connect (OIDC) signup flow

app/src/pages/settings/SettingsPage.tsx
=> fix(annotations): Allow all settings pages to overflow

src/phoenix/server/app.py
=> feat: Add /readyz endpoint to confirm database connectivity

app/src/components/alert/Alert.tsx, app/src/pages/project/ProjectAnnotationConfigCard.tsx
Makes the UI a bit more clear and consistent to show the type.
=> feat(annotations): more clear project annotation configs

tutorials/self-improving_agent.ipynb
Could not run notebook in its current state here are some of my fixes.
mustache formatting & fixed prompt versioning flow
Got up to the following cell where I got another error:
```py
tool_call_eval = eval_and_log_tool_calls()
```
error:
```
llm_classify 
 0/0 (0.0%) | ⏳ 00:00<? | ?it/s
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-57-afae08aebcd1>](https://localhost:8080/#) in <cell line: 0>()
----> 1 tool_call_eval = eval_and_log_tool_calls()
3 frames
[<ipython-input-56-d75dee397a72>](https://localhost:8080/#) in eval_and_log_tool_calls()
1 def eval_and_log_tool_calls():
2     tool_calls_df = get_tool_calls()
----> 3     tool_call_eval, dataframe = …
```
=> chore: mustache formatting & fixed prompt versioning flow

app/src/pages/settings/SettingsPage.tsx
=> fix: Allow scroll on settings pages

app/schema.graphql, src/phoenix/server/api/types/Span.py
=> feat: Span note resolver

packages/phoenix-client/.cursor/rules/general.mdc
resolves #7288 
Adds some general guidelines about methods, kwargs, and the pandas-native interface.
=> docs(client): add general rules for the client

js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/server/api/routers/v1/annotation_configs.py
- consolidate create routes into a single route
- add update put route
resolves #7294 
resolves #7295
=> refactor(annotations): consolidate rest routes

src/phoenix/server/api/routers/v1/annotation_configs.py
=> fix(annotations): paginate list annotation configs route

app/src/pages/settings/RetentionPolicyForm.tsx
=> fix(admin): make retention days step 1

js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/db/types/annotation_configs.py, src/phoenix/server/api/mutations/annotation_config_mutations.py, src/phoenix/server/api/routers/v1/annotation_configs.py, tests/unit/db/types/test_annotation_configs.py, tests/unit/server/api/mutations/test_annotation_config_mutations.py, tests/unit/server/api/routers/v1/test_annotation_configs.py
- adds unit tests for annotation config routes
- adds more tests for annotation config mutations
- file off rough edges
resolves #7303
=> test(annotations): improve tests for annotation config rest and graphql api

app/src/pages/projects/ProjectActionMenu.tsx
=> feat: Add "copy name" button to project menu

app/src/components/media/Video.tsx, app/src/components/media/index.tsx, app/stories/Video.stories.tsx
=> feat(components): video for tutorials

packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py, src/phoenix/server/api/routers/v1/annotations.py
=> feat: add `get_span_annotations_dataframe` to client

app/src/components/datetime/TimeRangeContext.tsx, app/src/components/trace/SpanAnnotationsEditor.tsx
=> fix: Prevent time range context error when opening trace details slideover

app/src/components/trace/AnnotationConfigList.tsx
=> fix: use leading visual for the icon

.github/workflows/python-CI.yml, packages/phoenix-client/src/phoenix/client/__init__.py, packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
Getting `pyright` errors in CI for the Python client
=> ci: phoenix client ci

app/src/components/FocusHotkey.tsx, app/src/components/ShareLinkButton.tsx, app/src/components/annotation/AnnotationInputExplanation.tsx, app/src/components/annotation/AnnotationSummaryGroup.tsx, app/src/components/annotation/ContinuousAnnotationInput.tsx, app/src/components/icon/Icons.tsx, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/contexts/ViewerContext.tsx, app/src/pages/settings/AnnotationConfigDialog.tsx, app/src/pages/settings/AnnotationConfigTable.tsx, app/src/pages/settings/SettingsAnnotationsPage.tsx, app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateAnnotationConfigMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigsMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateAnnotationConfigMutation.graphql.ts, app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/pages/trace/TracePage.tsx
Addressing feedback from https://github.com/Arize-ai/phoenix/issues/5917
=> fix: Polish annotations UI

src/phoenix/server/api/routers/v1/spans.py
=> refactor(annotations): revert upsert logic

src/phoenix/server/api/dataloaders/annotation_summaries.py, tests/unit/server/api/dataloaders/conftest.py, tests/unit/server/api/dataloaders/test_annotation_summaries.py
=> fix: Avoid division by zero

MIGRATION.md
Add warnings about annotation migrations (e.g. that they might take some time).
=> docs(annotations): add MIGRATION warning

requirements/unit-tests.txt
un-pin litellm so clear dependabot alert
=> fix: bump litellm minimum version

app/src/pages/settings/RetentionPolicyForm.tsx, app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
cannot enter things that are not an increment of 100. This is cursor at its worst.
=> fix: step for number of days should be 1

app/src/pages/project/ProjectRetentionPolicyCard.tsx, app/src/pages/settings/RetentionPoliciesTable.tsx, app/src/pages/settings/RetentionPolicyForm.tsx, app/src/utils/retentionPolicyUtils.ts
It wasn't clear that the times were in UTC.
=> fix: make it clear in the UI that cron expression applies to times in UTC

scripts/generate_data_via_plpgsql/README.md, scripts/generate_data_via_plpgsql/generate_spans.py, scripts/generate_data_via_plpgsql/generate_spans.sql, scripts/perf/get_spans_dataframe_for_random_conversation_id.py, src/phoenix/server/api/routers/v1/spans.py, src/phoenix/session/client.py, src/phoenix/trace/dsl/query.py
resolves #7451 
- changed the orphan span query in  `_get_spans_dataframe` to CTE
=> fix: add flag for `orphan_span_as_root_span` on client for span query

tests/integration/db_migrations/__init__.py
This PR enhances the database migration testing infrastructure by adding comprehensive schema verification capabilities.
1. Added `_TableSchemaInfo` dataclass to encapsulate table schema information (columns, indices, constraints)
2. Implemented `_get_table_schema_info` function to retrieve schema details for both PostgreSQL and SQLite backends
3. Added `_verify_table_schema_info` function to validate schema consistency before and after migrations
4. Added `_verify_clean_state` function to ensure database is in a clean state before migrations
5. Added type hints and improved code organization with proper imports
These changes will help catch schema inconsistencies during database migrations and ensure more reliable migration testing.
=> chore: db migration test helpers

app/src/components/ShareLinkButton.tsx, app/src/components/button/styles.tsx, app/src/components/content/Keyboard.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/pages/trace/TraceDetailsPaginator.tsx, app/src/pages/trace/TracePage.tsx
=> refactor: move share to the top of the page

app/src/components/annotation/AnnotationInputExplanation.tsx, app/src/components/annotation/AnnotationSummaryPopover.tsx, app/src/components/counter/Counter.tsx, app/src/pages/project/AnnotationTooltipFilterActions.tsx, app/src/pages/project/SpanColumnSelector.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx, app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanDetails.tsx
re-names more places annotations
=> refactor: change more places to say annotations

src/phoenix/server/api/helpers/annotations.py, src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py, src/phoenix/server/api/routers/v1/spans.py, src/phoenix/server/api/routers/v1/traces.py, tests/integration/client/test_annotations.py
=> feat(annotations): record users from user api keys in annotation routes

internal_docs/vignettes/sqlalchemy/polymorphic_user/README.md, internal_docs/vignettes/sqlalchemy/polymorphic_user/users.py
This example demonstrates SQLAlchemy's single table inheritance (STI) pattern through a practical implementation of user authentication. It shows how to model different types of users (local and external) in a single database table while maintaining type safety and clean code organization.
- All user types share the same database table
- A discriminator column (`auth_method`) determines which class to instantiate
- Efficient storage while maintaining object-oriented design
- Each subclass has a unique identifier in the `auth_method` column
- SQLAlchemy automatically instantiates the correct class based on this value
- Enables type-safe querying of specific user types
- The `User` class cannot be instantiated directly
- Defines common structure and behavior for all user types
- Enforces …
=> chore: add internal vignette for polymorphic user

js/.changeset/ripe-readers-sniff.md, js/packages/phoenix-client/.cursor/rules/general.mdc, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/spans/addSpanAnnotation.ts, js/packages/phoenix-client/src/spans/index.ts, js/packages/phoenix-client/src/spans/logSpanAnnotations.ts, js/packages/phoenix-client/src/spans/types.ts, js/packages/phoenix-client/test/spans/addSpanAnnotation.test.ts, js/packages/phoenix-client/test/spans/logSpanAnnotations.test.ts
adds annotation methods to phoenix
=> feat(arize-phoenix-client): annotation methods

js/.changeset/itchy-frogs-burn.md, js/examples/apps/phoenix-experiment-runner/index.ts, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/experiments/runExperiment.ts, js/packages/phoenix-client/src/types/experiments.ts, js/pnpm-lock.yaml
rather than running in Promise.all, run experiments in queues.
=> feat(ts): experiments run in queues

js/.changeset/big-yaks-relate.md, js/examples/apps/phoenix-experiment-runner/index.ts, js/packages/phoenix-client/src/experiments/runExperiment.ts, js/packages/phoenix-client/src/types/annotations.ts, js/packages/phoenix-client/src/types/experiments.ts
Resolves #5852 
Resolves #5853
=> feat(phoenix-client): Record experiment results to Phoenix server

app/package.json, app/pnpm-lock.yaml, app/src/App.tsx, app/src/Routes.tsx, app/src/components/icon/Icons.tsx, app/src/contexts/FeatureFlagsContext.tsx, app/src/pages/Layout.tsx, app/src/pages/dashboard/DashboardPage.tsx, app/src/pages/dashboard/index.tsx, app/src/pages/dashboards/DashboardsPage.tsx, app/src/pages/dashboards/index.tsx
Add rudimentary dashboard routes behind a feature flag.
=> feat(dashboards): rudamentary routes for dashboards

src/phoenix/experiments/functions.py
resolves https://github.com/Arize-ai/phoenix/issues/7566
=> docs: update docstring for description of experiment evaluators

src/phoenix/server/api/types/Project.py, tests/unit/server/api/types/test_Project.py
=> fix: check sql validity of filter expression

app/package.json, app/pnpm-lock.yaml, app/src/App.tsx, app/src/GlobalStyles.tsx, app/src/Routes.tsx, app/src/pages/dashboard/DashboardBarChart.tsx, app/src/pages/dashboard/DashboardPage.tsx, app/src/pages/dashboard/DashboardPanel.tsx, app/src/pages/dashboard/ProjectDashboardPage.tsx, app/src/pages/dashboard/__generated__/projectDashboardLoaderQuery.graphql.ts, app/src/pages/dashboard/index.tsx, app/src/pages/dashboard/projectDashboardLoader.tsx, app/src/pages/dashboards/DashboardsPage.tsx, app/src/pages/dashboards/DashboardsRoot.tsx, app/src/pages/dashboards/ProjectDashboardsTable.tsx, app/src/pages/dashboards/__generated__/ProjectDashboardsTableProjectsQuery.graphql.ts, app/src/pages/dashboards/__generated__/ProjectDashboardsTable_projects.graphql.ts, app/src/pages/dashboards/__generated__/dashboardsLoaderQuery.graphql.ts, app/src/pages/dashboards/dashboardsLoader.tsx, app/src/pages/dashboards/index.tsx
resolves #7561 
rudimentary dashboard panel primitives
=> feat(dashboards): dashboard panel

app/src/pages/dataset/RunExperimentButton.tsx
resolves https://github.com/Arize-ai/phoenix/issues/7562
=> feat(experiments): typescript example

app/src/pages/playground/PlaygroundOutput.tsx, src/phoenix/server/api/helpers/playground_clients.py
=> fix: anthropic 3.7 sonnet mis-spelled

app/schema.graphql, src/phoenix/server/api/types/Span.py, src/phoenix/server/api/types/TokenCountPromptDetails.py, src/phoenix/server/api/types/TokenPromptDetails.py
=> feat(cost): add token prompt details resolver on span node

src/phoenix/server/api/routers/v1/datasets.py, tests/unit/server/api/routers/v1/test_datasets.py
=> fix(datasets): support csv + jsonl download of datasets with unicode file names

tutorials/agents/smolagents/smolagents_evaluator_optimizer.ipynb, tutorials/agents/smolagents/smolagents_orchestrator.ipynb, tutorials/agents/smolagents/smolagents_parallelization.ipynb, tutorials/agents/smolagents/smolagents_prompt_chaining.ipynb, tutorials/agents/smolagents/smolagents_router.ipynb
This is the PR to add the smolagents tutorials going through different workflows and architectures.
=> docs: smolagents tutorials

docs/datasets-and-experiments/quickstart-datasets.md
=> docs: add_ts_experiment_quickstart_to_docs

docs/datasets-and-experiments/quickstart-datasets.md
=> docs: fix ts imports on experiment doc

app/src/components/combobox/styles.tsx, app/src/pages/playground/PromptComboBox.tsx, app/src/pages/playground/SavePromptForm.tsx, app/src/pages/playground/__generated__/PromptComboBoxQuery.graphql.ts, app/src/pages/playground/__generated__/SavePromptFormQuery.graphql.ts
=> fix: increase prompt fetch limit to 200 and update component to be scrollable

pyproject.toml, requirements/build-graphql-schema.txt, requirements/type-check.txt
[0.270.1](https://github.com/strawberry-graphql/strawberry/releases/tag/0.270.1)
=> fix: update strawberry to fix multipart subscription

js/.changeset/evil-towns-tie.md, js/packages/phoenix-mcp/README.md, js/packages/phoenix-mcp/src/index.ts, js/packages/phoenix-mcp/src/projectTools.ts
=> feat: Mcp list projects

app/src/components/trace/TokenCount.tsx, app/src/components/trace/__generated__/TokenCount_TokenDetailsQuery.graphql.ts
=> feat(cost): display audio, cache read, and cache write tokens on span token tooltip

app/src/components/annotation/AnnotationInputLabel.tsx, app/src/components/annotation/AnnotationSummaryPopover.tsx, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/components/trace/__generated__/SpanAnnotationsEditorCreateAnnotationMutation.graphql.ts, app/src/components/trace/__generated__/SpanAnnotationsEditorDeleteAnnotationMutation.graphql.ts, app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts, app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/pages/trace/__generated__/SpanAsideAnnotationList_span.graphql.ts, app/src/pages/trace/__generated__/SpanAside_span.graphql.ts, app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
https://github.com/user-attachments/assets/2c2d0936-a03a-478c-ae61-357dcd2596c9
resolves #7489
=> feat: Replace "my annotations" with Annotation Summaries

app/src/components/nav/GitHubStarCount.tsx, app/src/components/nav/Navbar.tsx, app/src/pages/Layout.tsx
adds a star count callout.
resolves #7093
=> chore: add github link with stars

.github/workflows/docker-build-release.yml
=> fix: docker-workflow-permissions

app/src/pages/project/ProjectConfigPage.tsx
=> chore: migrate projectconfig to select

docs/section-self-hosting/SUMMARY.md, docs/section-self-hosting/configuration.md, docs/section-self-hosting/email.md, docs/section-self-hosting/provisioning.md
=> docs: add provisioning to self-hosting

README.md
=> docs: add helm logo to readme

.github/workflows/docker-build-release.yml
Co-authored-by: Jonathan Beltran <jonathanbeltran35@gmail.com>
=> fix: ensure sed command works for helm chart update

MIGRATION.md, app/src/components/listbox/ListBox.tsx, app/stories/Select.stories.tsx
=> fix: remove min-height for select dropdown

app/.eslintrc.js, app/stories/Select.stories.tsx
=> refactor: final migration from picker to select

src/phoenix/experiments/functions.py, src/phoenix/experiments/tracing.py, src/phoenix/server/telemetry.py, src/phoenix/trace/projects.py, tests/integration/_helpers.py
Co-authored-by: Ge Li <77590974+GeLi2001@users.noreply.github.com>
=> ci: fix mypy types for opentelemetry-sdk==1.34.0

api_reference/source/index.md
preview in the readthedoc workflow below
resolves #7649
=> docs: update main readthedoc

docs/tracing/integrations-tracing/langchain.md
resolves https://github.com/Arize-ai/phoenix/issues/4529
=> docs: correct typo error

app/schema.graphql, app/src/pages/settings/CloneModelButton.tsx, app/src/pages/settings/EditModelButton.tsx, app/src/pages/settings/ModelForm.tsx, app/src/pages/settings/NewModelButton.tsx, app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts, app/src/utils/generativeUtils.ts, app/stories/ModelForm.stories.tsx, src/phoenix/server/api/mutations/model_mutations.py
=> fix(cost): allow custom providers in model form

app/schema.graphql, app/src/pages/settings/CloneModelButton.tsx, app/src/pages/settings/EditModelButton.tsx, app/src/pages/settings/NewModelButton.tsx, app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts, src/phoenix/server/api/mutations/model_mutations.py
=> fix(cost): adjust model crud mutations to allow for arbitrary cost types

tests/unit/server/api/mutations/test_model_mutations.py
=> test(cost): add unit tests for model crud mutations

app/schema.graphql, app/src/pages/settings/ModelsTable.tsx, app/src/pages/settings/__generated__/ModelsTableModelsQuery.graphql.ts, app/src/pages/settings/__generated__/ModelsTable_generativeModels.graphql.ts, app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts, src/phoenix/server/api/context.py, src/phoenix/server/api/dataloaders/__init__.py, src/phoenix/server/api/dataloaders/last_used_times_by_generative_model_id.py, src/phoenix/server/api/types/GenerativeModel.py, src/phoenix/server/app.py
resolves #8155
https://github.com/user-attachments/assets/6e36e326-b11b-4bca-bc75-520e7a7d3d0b
=> feat(cost): add last used at column to models table

app/src/pages/settings/CloneModelButton.tsx, app/src/pages/settings/DeleteModelButton.tsx, app/src/pages/settings/EditModelButton.tsx, app/src/pages/settings/ModelsTable.tsx
=> feat(cost): add build-in vs custom indicator

src/phoenix/server/api/input_types/SpanSort.py, src/phoenix/server/api/types/Project.py
=> fix(cost): fix sort spans by cost

app/src/utils/numberFormatUtils.ts
=> fix(costs): Bump minimum displayed costs to $0.01

src/phoenix/server/api/queries.py
=> fix(cost): order custom models first

src/phoenix/server/api/queries.py
=> fix(experiments): paginate sql query on compare experiments page

src/phoenix/server/api/queries.py, src/phoenix/server/daemons/db_disk_usage_monitor.py
changed to the same query as the one for the UI
=> fix: change postgresql query for db disk usage monitoring

.github/.scripts/sync_models.py, src/phoenix/server/cost_tracking/model_cost_manifest.json
=> fix: remove regex anchors for model names

app/src/Routes.tsx, app/src/pages/experiment/ExperimentComparePage.tsx, app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts, app/src/pages/experiment/experimentCompareLoader.ts, app/src/pages/experiments/ExperimentSelectionToolbar.tsx, app/src/pages/experiments/ExperimentsTable.tsx, app/src/pages/playground/PlaygroundDatasetSection.tsx
=> fix(experiments): restore routing for comparing experiments

.github/workflows/helm-release.yaml
=> ci(helm): fix helm permissions

app/.storybook/preview-body.html, app/.storybook/preview.tsx
Add a split view to view all themes at once.
=> feat(storybook): split mode

js/.changeset/thick-clowns-cheer.md, js/packages/phoenix-mcp/src/supportTools.ts
=> fix: update phoenix support to search

js/.changeset/ten-parts-return.md, js/packages/phoenix-evals/src/llm/createClassifier.ts, js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts, js/packages/phoenix-evals/src/types/evals.ts, js/packages/phoenix-evals/test/llm/createClassifier.test.ts, js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
- **feat(evals): add more telemetry control, tests**
- **more tests**
=> feat(evals): add telemetry controls, tests

packages/phoenix-client/src/phoenix/client/experiments/__init__.py, packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py, packages/phoenix-client/src/phoenix/client/resources/experiments/types.py, tests/integration/client/test_experiments.py
=> fix: Do not access API for experiment evaluations in dry_run mode

app/schema.graphql, app/src/components/trace/SessionTokenCostsDetails.tsx, app/src/components/trace/SpanTokenCostsDetails.tsx, app/src/components/trace/TraceTokenCostsDetails.tsx, app/src/components/trace/__generated__/SessionTokenCostsDetailsQuery.graphql.ts, app/src/components/trace/__generated__/SpanTokenCostsDetailsQuery.graphql.ts, app/src/components/trace/__generated__/TraceTokenCostsDetailsQuery.graphql.ts, app/src/pages/settings/CloneModelButton.tsx, app/src/pages/settings/EditModelButton.tsx, app/src/pages/settings/ModelsTable.tsx, app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/CloneModelButtonQuery.graphql.ts, app/src/pages/settings/__generated__/DeleteModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts, app/src/pages/settings/__generated__/EditModelButtonQuery.graphql.ts, app/src/pages/settings/__generated__/ModelsTable_generativeModels.graphql.ts, app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts, app/src/pages/settings/__generated__/SettingsModelsPageQuery.graphql.ts, app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts, app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts, src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment.py, src/phoenix/server/api/types/CostBreakdown.py, src/phoenix/server/cost_tracking/cost_details_calculator.py, src/phoenix/server/daemons/span_cost_calculator.py, tests/unit/server/cost_tracking/test_cost_details_calculator.py
=> fix(cost): ensure token counts are recorded in span costs table even if the model name does not match

app/package.json, app/pnpm-lock.yaml
=> revert: recharts upgrade

README.md
add top level documentation for java, upgrade integrations
=> docs: update docs with java, dify integration links

app/schema.graphql, src/phoenix/server/api/input_types/CreateProjectInput.py, src/phoenix/server/api/mutations/project_mutations.py, src/phoenix/server/api/types/Project.py, src/phoenix/server/dml_event.py, tests/unit/server/api/mutations/test_project_mutations.py
Add `createProject` GraphQL mutation to allow creating new projects.
=> feat: createProject GraphQL mutation

app/.storybook/main.ts, app/package.json, app/pnpm-lock.yaml, app/src/components/button/IconButton.tsx, app/stories/CredentialField.stories.tsx, app/stories/IconButton.stories.tsx
Adds storybook extension to show figma.
Resolves #8160
=> feat(design): add icon button figma link

app/src/pages/settings/DBUsagePieChart.tsx
=> feat: display allocated db capacity

app/schema.graphql, app/src/pages/prompts/PromptsPage.tsx, app/src/pages/prompts/PromptsSearch.tsx, app/src/pages/prompts/PromptsTable.tsx, app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts, app/src/pages/prompts/__generated__/PromptsPagePromptsFragment.graphql.ts, app/src/pages/prompts/__generated__/PromptsPagePromptsQuery.graphql.ts, app/src/pages/prompts/__generated__/PromptsPageQuery.graphql.ts, app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts, app/src/pages/prompts/promptsLoader.ts, src/phoenix/server/api/input_types/PromptFilter.py, src/phoenix/server/api/queries.py, tests/unit/server/api/test_queries.py
=> feat: Add search bar functionality to prompts page

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
https://github.com/Arize-ai/phoenix/issues/5867
*Note: migrated only playgroundDatasetExample so not adding "resolve" to the number.
=> refactor: playgroundDatasetExample remove dialogContainer

app/src/pages/trace/SpanDetails.tsx
=> fix: make span event list scrollable

tests/unit/server/api/types/test_Project.py
=> ci: add tests for top models queries

app/.eslintrc.js
=> refactor: eslint dialogContainer

app/.eslintrc.js, app/src/components/Empty.tsx, app/src/components/exception/BugReportErrorBoundaryFallback.tsx, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/pages/ErrorElement.tsx, app/src/pages/embedding/EventDetails.tsx, app/src/pages/playground/NoInstalledProvider.tsx, app/src/pages/trace/SpanAnnotationsEmpty.tsx, app/src/pages/trace/SpanDetails.tsx
Deprecates empty state for now
=> refactor: remove empty graphics

app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/pages/playground/playgroundUtils.ts
=> fix: sanitize invocation parameters before saving

packages/phoenix-client/src/phoenix/client/client.py, tutorials/experiments/datasets_and_experiments_quickstart.ipynb, tutorials/experiments/langchain_email_extraction.ipynb, tutorials/experiments/summarization.ipynb, tutorials/experiments/txt2sql.ipynb
resolves #8773 
resolves #8681 
resolves #8680
=> fix: Update notebooks to use new client

packages/phoenix-client/src/phoenix/client/experiments/__init__.py
resolves #8941 
- Simplifies imports of important experiment utilities
=> feat: Reexport experiment utilities in top-level client module

app/src/pages/experiment/ExperimentMultiSelector.tsx, app/src/pages/experiment/__generated__/ExperimentMultiSelector__data.graphql.ts, app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts, app/src/pages/experiment/experimentCompareLoader.ts
=> fix(experiments): ensure experiment compare selector can select all experiments for a dataset

packages/phoenix-evals/src/phoenix/evals/llm/adapters/langchain/adapter.py
=> fix: Properly return objects from Anthropic adapter

src/phoenix/server/api/queries.py, tests/unit/server/api/test_queries.py
=> fix(experiments): make examples in experiments compare table based off dataset version of base experiment

js/.changeset/fifty-doors-strive.md, js/packages/phoenix-evals/examples/classifier_example.ts, js/packages/phoenix-evals/examples/hallucination_example.ts, js/packages/phoenix-evals/src/default_templates/HALLUCINATION_TEMPLATE.ts, js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts, js/packages/phoenix-evals/src/llm/createClassifierFn.ts, js/packages/phoenix-evals/src/llm/createDocumentRelevancyEvaluator.ts, js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts, js/packages/phoenix-evals/src/llm/index.ts, js/packages/phoenix-evals/src/types/evals.ts, js/packages/phoenix-evals/test/llm/createClassifier.test.ts, js/packages/phoenix-evals/test/llm/createClassifierFn.test.ts, js/packages/phoenix-evals/test/llm/createDocumentRelevancyEvaluator.test.ts, js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
resolves #8999
Adds optional optimization direction and a name to evaluators
=> feat(js): add optimizationDirection and kind / source

app/src/components/slider/Slider.tsx, app/src/pages/playground/InvocationParametersFormFields.tsx, src/phoenix/server/api/helpers/playground_clients.py
resolves #8940
https://www.loom.com/share/dda2c331657b4be1bf1d0b9b1b015bfc
=> fix(playground): #8940 allow bounded slider fields to be unset

app/src/pages/project/metrics/ProjectMetricsPage.tsx
=> fix(metrics): make query errors scrollable

docs/evaluation/preview/README.md, docs/evaluation/preview/evaluators.md, docs/evaluation/preview/llm.md, docs/evaluation/preview/metrics.md, docs/evaluation/preview/templating.md, packages/phoenix-evals/docs/source/api/preview.llm.adapters.langchain.rst, packages/phoenix-evals/docs/source/api/preview.llm.adapters.litellm.rst, packages/phoenix-evals/docs/source/api/preview.llm.adapters.openai.rst, packages/phoenix-evals/docs/source/api/preview.llm.adapters.rst, packages/phoenix-evals/docs/source/api/preview.llm.rst, packages/phoenix-evals/docs/source/api/preview.metrics.rst, packages/phoenix-evals/docs/source/api/preview.rst, packages/phoenix-evals/docs/source/api/preview.templating.rst, packages/phoenix-evals/docs/source/index.md, tutorials/evals/evals_preview_examples.ipynb
Adds documentation in the form of: 
* auto docs in API reference
* markdown docs
* an example notebook
=> docs(evals): docs for evals preview module

packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
Updates to support new OpenAI SDK
=> feat: Handle new OpenAI tool types

helm/templates/phoenix/configmap.yaml
Related to: https://github.com/Arize-ai/phoenix/issues/9219
=> fix: self-hosted database environment variable templating

tutorials/prompts/react_prompting.ipynb
This migrates the react prompting notebook to the new client
=> docs: migrate react prompting notebook

src/phoenix/server/api/routers/v1/documents.py
=> fix: check bound on num docs for annotations

js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py, schemas/openapi.json, src/phoenix/experiments/functions.py, src/phoenix/server/api/routers/v1/experiment_runs.py, tests/unit/server/api/routers/v1/test_experiments.py
=> feat: inside run_experiment paginate get experiment runs

MIGRATION.md, src/phoenix/db/migrations/versions/0d25cd7dee22_add_dataset_splits_and_crosswalk_table.py, src/phoenix/db/models.py
=> feat: dataset split and examples migration

app/src/components/listbox/ListBox.tsx, app/src/pages/project/DatasetSelectorPopoverContent.tsx, app/src/pages/project/SpanSelectionToolbar.tsx, app/src/pages/project/TransferTracesButton.tsx, app/src/pages/project/__generated__/DatasetSelectorPopoverContentDatasetsQuery.graphql.ts, app/src/pages/project/__generated__/DatasetSelectorPopoverContentQuery.graphql.ts, app/src/pages/project/__generated__/DatasetSelectorPopoverContent_datasets.graphql.ts
refactors the dataset selector to match designs and accessibility constraints.
=> refactor: convert dataset selector to be an autocomplete

js/.changeset/upset-areas-study.md, js/packages/phoenix-client/examples/dataset_and_experiments_quickstart.ts, js/packages/phoenix-client/src/types/experiments.ts, js/packages/phoenix-evals/src/llm/ClassificationEvaluator.ts, js/packages/phoenix-evals/src/llm/LLMEvaluator.ts, js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts, js/packages/phoenix-evals/src/llm/createClassifierFn.ts, js/packages/phoenix-evals/src/llm/createDocumentRelevancyEvaluator.ts, js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts, js/packages/phoenix-evals/test/llm/createClassificationEvaluator.test.ts
Makes it possible to strongly type evaluator functions.
=> feat(js): add more support for generics in evals

pyproject.toml, tutorials/tracing/project_sessions_llama_index_query_engine.ipynb
Co-authored-by: Yasmine Frigui <yfrigui@arize.com>
=> fix: nix llama-index extra

tutorials/evals/evals-2/evals_2.0_rag_demo.ipynb
Forgot to update the notebook with the new dataframe utility.
=> chore(evals): update rag notebook

docs/tracing/llm-traces-1/README.md
=> docs: fix broken demo link in docs

js/packages/phoenix-client/src/__generated__/api/v1.ts, schemas/openapi.json, src/phoenix/db/models.py, src/phoenix/server/api/routers/v1/users.py
resolves [9191](https://github.com/Arize-ai/phoenix/issues/9191)
=> feat(db): add row for viewer role

packages/phoenix-evals/src/phoenix/evals/metrics/__init__.py, packages/phoenix-evals/src/phoenix/evals/metrics/document_relevance.py, packages/phoenix-evals/src/phoenix/evals/metrics/hallucination.py
=> feat(evals): add document relevance evaluator

.cursor/rules/evals-migration.mdc
Adds a cursor rule for migrating to the new evals
=> docs: add evals migration cursor rule
