Arize-ai/phoenix

app/src/components/datetime/LastNTimeRangeContext.tsx, app/src/components/datetime/LastNTimeRangePicker.tsx, app/src/components/datetime/constants.ts, app/src/components/datetime/types.ts, app/src/components/datetime/utils.ts, app/src/store/preferencesStore.tsx
Some users may need much finer grain last N if they are ingesting large amounts of data per minute. This restricts the time range in the UI.
=> feat: finer grain last N time range

tox.ini
putting `posargs` on everything doesn't make sense in the first place because it would not be compatible
=> ci: tox posargs for pytest only

src/phoenix/experiments/functions.py, src/phoenix/session/client.py, src/phoenix/utilities/client.py
resolves #4613 
- ensures that PHOENIX_API_KEY is properly propagated to the Client and Experiment modules
=> feat: Wire up API keys via env var for Phoenix clients and experiments

pyproject.toml
- Update dependency on `arize-phoenix-otel` to ensure that `register` picks up auth environment variables
=> fix: Update phoenix otel dependency

integration_tests/_helpers.py, integration_tests/auth/test_auth.py, src/phoenix/server/api/routers/auth.py
=> fix: users should not be asked to reset password again right after they reset their password

integration_tests/auth/test_auth.py, src/phoenix/db/models.py, src/phoenix/server/api/routers/auth.py
=> fix: user should be able to initiate password reset again before existing token is used or expires

docs/tracing/how-to-tracing/llm-evaluations.md
Simple fix for dataframe input example in Log Evaluations Results doc page. Column name 'value' in the example table is not correct, it should be 'score'.
=> docs: Change column name 'value' to 'score' in example SpanEvaluations dataframe

src/phoenix/auth.py
If the user is not yet authenticated with the OAuth2 IDP and has to sign in for the first time, strict cookies won't be sent back to the callback URL.
https://stackoverflow.com/a/42220786
```
I don't think that this can be done for security reasons. SameSite=Strict means that if user has been redirected or just clicked on link to your site (from other host), cookie shouldn't be send. And redirecting is like 'chaining' requests. So if your server redirects to another and this server redirects back immediately with 3xx code, cookie will be sent, because your server is 'on top' of this chain.
However if you redirect to oauth provider and user has to allow there you to access his account it means that this 'chain' is broken, and cookie will no longer be sent even if your site sets it (it is …
```
=> fix(auth): set oauth2 state and nonce cookies with lax samesite policy

.github/workflows/python-CI.yml, pyproject.toml, src/phoenix/server/app.py, tests/conftest.py, tests/datasets/test_experiments.py, tests/server/api/routers/v1/test_annotations.py, tests/server/api/routers/v1/test_spans.py, tests/trace/dsl/test_helpers.py
Updates our DB management strategy for unittests, this resolves the majority of stability issues we were seeing in CI.
=> fix: Fix DB unittest reliability

app/global-setup.ts, app/jest.config.js, app/playwright.config.ts, app/src/pages/settings/UserActionMenu.tsx, app/src/pages/settings/UsersCard.tsx, app/tests/getting-started.spec.ts, app/tests/user-management.spec.ts
resolves https://github.com/Arize-ai/phoenix/issues/4677
Switches playwright to use a global setup hook which guarantees the tests run AFTER setup.
This also contains code from @Parker-Stafford for the action menu options to hide reset password for local
=> fix: playwright scaffolding and user action menu rendering

src/phoenix/auth.py, src/phoenix/db/enums.py, src/phoenix/db/facilitator.py, src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py, src/phoenix/db/models.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/routers/auth.py, src/phoenix/server/api/types/User.py
strengthens check constraints related to auth methods
- `password_hash` and `password_salt` must be set or unset together
- `oauth2_client_id` and `oauth2_user_id` must be set or unset together
- a single user can have at most one auth method
resolves #4688
=> chore(auth): strengthen check constraints related to auth method

src/phoenix/config.py, src/phoenix/server/api/routers/oauth2.py, src/phoenix/server/app.py, src/phoenix/server/main.py
Adds `PHOENIX_BASE_URL` parameter. Similar to [`root_url` in Grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#root_url).
```
The URL used to access Phoenix from a browser. This is needed to ensure that the
`redirect_uri` parameter is correct during OAuth2 authorization code flows if an
OAuth2 IDP is configured. If you have a reverse proxy in front of Phoenix that
exposes Phoenix through a subpath, ensure that the subpath appears at the end of
this URL. Strongly consider using HTTPS since HTTP is insecure.
```
resolves #4690
=> feat(auth): add configurable base url

src/phoenix/config.py, src/phoenix/server/oauth2.py
Rename "server metadata url" to "oidc config url". Remove IDP-specific logic.
resolves #4712
=> refactor(auth): simplify config

src/phoenix/server/api/routers/oauth2.py
If a username is already taken when creating a new OAuth2 user, randomly generate a suffix and append to the username to avoid collisions.
resolves #4675
=> fix(auth): automatically resolve username collisions when creating oauth2 users

src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py, src/phoenix/db/models.py, src/phoenix/server/api/dataloaders/users.py, src/phoenix/server/api/mutations/api_key_mutations.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/auth.py
Hard-deletes user tuples rather than keeping a `deleted_at` timestamp column. Enables users to delete their account in order to re-use their email with another account (e.g., with an OAuth2 IDP).
resolves #4676
=> fix(auth): hard-delete users

app/playwright.config.ts
makes playwright rate limiting spec run last and bumps workers in ci
=> fix(playwright): make rate-limiting test run last

src/phoenix/config.py, src/phoenix/server/api/routers/oauth2.py, src/phoenix/server/app.py, src/phoenix/server/main.py
Remove the `PHOENIX_BASE_URL` environment variable, since we can infer the origin URL via the referer header.
resolves #4736
=> fix(auth): infer origin url

integration_tests/_helpers.py, integration_tests/auth/conftest.py, integration_tests/conftest.py, src/phoenix/server/jwt_store.py
It's not being used. Removal shortens the token character length.
=> fix: remove `exp` from `jwt`

src/phoenix/server/api/routers/oauth2.py
Ensures origin url is consistent between login re-route and callback for OAuth2 authorization code flow.
resolves #4747
=> fix(auth): ensure consistent origin url

pyproject.toml
This removes support for python 3.8 as it is being sunset at the end of October 2024
=> fix!: deprecate python 3.8

packages/phoenix-evals/src/phoenix/evals/templates.py, packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
resolves #4770 
Uses standard python string formatting with default curly brace variable delimiters ("{", "}")
=> fix: Use python string formatting for standard template delimiters

src/phoenix/trace/fixtures.py
Changes the agent demo project names to start with "demo_"
We haven't yet updated the demo instance of phoenix's yaml to include any of these names, so making this change here before we update that file
=> chore: apply naming convention for demo project fixtures

packages/phoenix-otel/src/phoenix/otel/otel.py
Fixes incorrect docstring.
resolves #4787
=> docs: fix incorrect env var in docstring

tutorials/integrations/tracing_and_evals_with_mongodb_and_llama_index.ipynb
Adds a notebook that shows a mongodb+llamaindex RAG pipeline, traced and evaluated. This is an updated version of an existing notebook that we used for a previous webinar, but doesn't look like it ever made it into our repo
=> docs: create MongoDB example notebook

pyproject.toml, src/phoenix/pointcloud/clustering.py, src/phoenix/pointcloud/projectors.py, tox.ini
resolves https://github.com/Arize-ai/phoenix/issues/4795
=> fix: support numpy 2

.gitignore, app/README.md
Let me know if there are any consequences to having .venv in the project dir that I can't think of
=> chore: Fix broken links in app README, support .venv convention

app/.eslintrc.js, app/package.json, app/pnpm-lock.yaml, app/src/contexts/DatasetContext.tsx, app/src/contexts/PlaygroundContext.tsx, app/src/contexts/PointCloudContext.tsx, app/src/contexts/PreferencesContext.tsx, app/src/contexts/TracingContext.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiments/ExperimentsTable.tsx, app/src/pages/trace/TraceDetails.tsx
this PR adds a new eslint rule "react-compiler" in preparation for react19 and the react-compiler
=> chore: add the new eslint rule

src/phoenix/trace/otel.py
resolves https://github.com/Arize-ai/phoenix/issues/4810
```
File /opt/anaconda3/envs/phoenix/lib/python3.11/site-packages/phoenix/trace/otel.py:197, in encode_span_to_otlp(span)
195 attributes.pop(key, None)
196 if key.endswith(JSON_STRING_ATTRIBUTES):
--> 197     attributes[key] = json.dumps(value)
```
=> fix: handle `ndarray` for `json.dumps` in `encode_span_to_otlp`

app/src/contexts/ViewerContext.tsx, app/src/contexts/__generated__/ViewerContextRefetchQuery.graphql.ts, app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts, app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts, app/src/pages/profile/ViewerProfileCard.tsx
Show option to reset password only for locally authenticated users. We're currently showing it to users authenticated via a third-party OAuth2 IDP, which doesn't make sense.
resolves #4727
=> fix(auth): show reset password button only for locally authenticated users

app/src/components/project/PythonProjectGuide.tsx
resolves #4844 
This corrects the hard-coded hosted phoenix URL that was in the authenticated guide
**before**
=> fix: remove incorrect URL in python guide

docker-compose.yml
getting the following error
```
db-1       |
db-1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1       |
db-1       | 2024-10-03 14:57:16.488 UTC [1] FATAL:  database files are incompatible with server
db-1       | 2024-10-03 14:57:16.488 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
db-1 exited with code 1
```
=> fix: pin postgres version at 16 for docker compose

app/schema.graphql, app/src/pages/playground/MessageRolePicker.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/store/playgroundStore.tsx, src/phoenix/server/api/input_types/ChatCompletionMessageInput.py, src/phoenix/server/api/subscriptions.py, src/phoenix/server/api/types/ChatCompletionMessageRole.py
resolves [4893](https://github.com/Arize-ai/phoenix/issues/4893)
Switches the input of the chat completion message to be a list of messages with roles.
```graphql
subscription {
chatCompletion(input: {
messages: [{ role: USER, content: "hello"}]
})
}
```
https://github.com/user-attachments/assets/dc042fd1-9c3b-4f45-98b7-685b9ac296a3
=> feat(playground): rudimentary graphql support for messages input

app/src/pages/playground/MessageRolePicker.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/store/playgroundStore.tsx
https://github.com/user-attachments/assets/d2a9d428-7817-4c82-939b-9c1290a9e6a7
=> feat(playground): Implement message role picker callback

app/src/openInference/tracing/__tests__/types.test.ts, app/src/openInference/tracing/types.ts, app/src/pages/trace/SpanDetails.tsx
resolves #4912 
Makes sure that llm message blocks contain lists of objects before rendering content. If malformed it just falls back to IO
=> fix: handle badly ingested llm spans gracefully

pyproject.toml, src/phoenix/config.py, src/phoenix/server/app.py, tests/integration/auth/conftest.py, tests/integration/auth/test_auth.py
=> fix: add middleware for checking Cross-Site Request Forgery (CSRF) when trusted origins are specified via environment variable

packages/phoenix-evals/src/phoenix/evals/models/openai.py
resolves #4462
Sends prompts as the system role for `OpenAIModel`: this is because Azure content restrictions (for toxicity, security) will often prevent evals from running. Rudimentary testing shows that both system prompting and user prompting behave similarly.
=> feat: Always prompt as system for OpenAI Models

tutorials/tracing/dspy_tracing_tutorial.ipynb
We've revamped our DSPy instrumentation for version v2.5.0 and above. This PR updates the DSPy tutorial notebook accordingly.
=> docs: update dspy notebook to reflect new instrumentation for v2.5 and above

app/src/components/AlphabeticIndexIcon.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundInstance.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/PlaygroundTools.tsx, app/src/pages/playground/TitleWithAlphabeticIndex.tsx, app/src/pages/playground/constants.tsx, app/src/store/playgroundStore.tsx
resolves #4949 
Allows up to 4 instances to be added, distinguishes them by alphabetic "index"
=> feat(playground): allow up to 4 instances, distinguish alphabetically

app/schema.graphql, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/ModelProvider.py
partially resolves #4858 
~Adds a `model_providers` query that lists available models given a specific provider as an input. This is currently incomplete, as I plan to add a DB-backed store for snapshotted models. I think it feels too bad to tie model definitions to the server version.~
Hardcodes all models for now
=> feat: Add model listing

app/src/@types/generative.d.ts, app/src/constants/generativeConstants.ts, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/ModelPicker.tsx, app/src/pages/playground/ModelProviderPicker.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts, app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/store/playgroundStore.tsx, app/src/utils/generativeUtils.ts
resolves #4887 
adds a rudimentary model selector.
=> feat(playground): model selector

src/phoenix/server/api/subscriptions.py
Creates LLM span for playground runs.
resolves #4856
=> feat(playground): create llm span for playground runs

app/src/components/templateEditor/language/fString/fStringTemplating.syntax.grammar, app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.syntax.grammar
Removes this warning from `pnpm dev`
=> fix(playground): Remove unused statements in language grammars

src/phoenix/server/api/subscriptions.py
Records model name for LLM spans created in playground.
resolves #4995
=> fix(playground): record model name for llm spans in playground

app/schema.graphql, app/src/pages/playground/PlaygroundCredentialsDropdown.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/store/credentialsStore.tsx, src/phoenix/server/api/subscriptions.py
Plumbs through API keys from frontend. If those keys are not present, any used in the backend will be used instead.
resolves #4974
=> fix(playground): plumb through credentials

app/src/components/templateEditor/TemplateEditor.tsx, app/src/components/templateEditor/constants.ts, app/src/components/templateEditor/language/fString/fStringTemplating.ts, app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.ts, app/src/components/templateEditor/templateEditorUtils.ts, app/src/components/templateEditor/types.ts, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/071dd2c8-df77-4cfd-ad4b-ebaead58eed4
=> feat(playground): Extract and display variables from all message templates as "inputs"

app/src/components/code/CodeWrap.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/VariableEditor.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/aabfe5ad-8d0a-4058-be8d-e1dc581e9e51
Uses codemirror without lang and with line wrapping.
Additionally, implements a variable value cache so that variable values stick around when changing syntax type or variable name.
=> feat(playground): Implement editable input variable textareas (#4987)

app/src/constants/generativeConstants.ts, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/constants.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
resolves #4998 
https://github.com/user-attachments/assets/3adad49d-73a0-4b15-a4eb-f278288447cd
Azure OpenAI api requires you to pass in a string model name which matches the deployment name which is user defined (backed by a real open ai model)
Note: Still missing - azure endpoint / api version: https://github.com/Arize-ai/phoenix/issues/5023
https://github.com/user-attachments/assets/bfc50f4f-50b2-4958-84af-281cae1d0195
=> feat(playground): parse model name and infer provider form span

.github/workflows/playwright.yaml, app/playwright.config.ts
We're skipping WebKit for CI because of recurring issues with caching, despite always installing it on cache-hit.
=> ci: skip webkit for playwright tests

app/src/components/generative/ToolChoiceSelector.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundTool.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts, src/phoenix/server/api/subscriptions.py
Wires up tool calling in the UI.
https://github.com/user-attachments/assets/789fa03a-341e-458b-9195-09ebf9efceb4
resolves #4988
=> feat(playground): wire up tool calling ui

.github/workflows/python-CI.yml, .gitignore, src/phoenix/evals, src/phoenix/otel, tox.ini
Checking in symlinks to git has been more trouble than it's worth given issues with CI. This PR adds helpers in tox for adding and removing symlinks, but ignores them for git.
=> chore: git ignore symbolic links

app/schema.graphql, app/src/pages/playground/ModelPicker.tsx, app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts, app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts, src/phoenix/db/migrations/versions/10460e46d750_datasets.py, src/phoenix/db/migrations/versions/3be8647b87d8_add_token_columns_to_spans_table.py, src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py, src/phoenix/db/models.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/GenerativeModel.py
makes the model listing more generic so that you can view a full list of available models.
=> feat: make model listing more generic

app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
Very large messages are hard to drag since the center never crosses the threshold of the message above. This makes it at least possible to drag it over.
https://github.com/user-attachments/assets/8eadd6ee-d289-4273-8650-bb873665a58d
=> fix(playground): make messages collapsible so they can be dragged

pyproject.toml
Adds OpenAI as a dependency for playground.
resolves #5075
=> fix(playground): add openai as a container dependency

app/src/pages/playground/PlaygroundOutput.tsx
When an error occurs during output generation we mark the instance as no longer running.
Output continues to say "running" however.
We should display an error message and revert the state of the output box back to its initial state most likely
=> fix: Re-enable run button on subscription error

app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/useDerivedPlaygroundVariables.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
This prevents stale variable inputs from being displayed on the playground.
~~TODO: fix render slowdown. This approach is slower, need to memoize some more things.~~
Performance profiling reveals that dropped frames while typing quickly is due to expensive over-re-rendering. We can fix this later or via react compiler in the future.
=> fix: Derive playground values instead of storing them in state

release-please-config.json
[exclude-paths](https://github.com/googleapis/release-please/blob/3202daa81d0a5ef8f8959ec48aa5f79159fde997/schemas/config.json#L214-L215): Path of commits to be excluded from parsing. If all files from commit belong to one of the paths it will be skipped
=> chore: expand exclude-paths for release please

app/schema.graphql, src/phoenix/server/api/subscriptions.py
returns span on last subscription payload
```graphql
subscription ChatCompletionSubscription($input: ChatCompletionInput!) {
chatCompletion(input: $input) {
... on TextChunk {
content
}
... on ToolCallChunk {
id
function {
name
arguments
}
}
... on FinishedChatCompletion {
span {
id
}
}
}
}
```
resolves #5037
resolves #5091
resolves #5037
=> feat(playground): return finalized span at end of subscription

.github/workflows/python-CI.yml, app/schema.graphql, requirements/integration-tests.txt, src/phoenix/db/insertion/span.py, src/phoenix/db/migrations/versions/4ded9e43755f_create_trace_session_table.py, src/phoenix/db/models.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Project.py, src/phoenix/server/api/types/ProjectSession.py, src/phoenix/server/api/types/Trace.py, tests/integration/_helpers.py, tests/integration/conftest.py, tests/integration/db_migrations/conftest.py, tests/integration/db_migrations/test_up_and_down_migrations.py, tests/integration/project_sessions/conftest.py, tests/integration/project_sessions/test_project_sessions.py, tests/integration/server/test_launch_app.py
resolves #4854 
resolves #5010
- Added `project_sessions` with foreign key on `traces`
- Since each span can have a different the project name, to eliminate ambiguity, the project for the session is defined by the span with the max `end_time`.
=> feat: add db table for trace sessions

packages/phoenix-evals/src/phoenix/evals/classify.py, packages/phoenix-evals/src/phoenix/evals/executors.py
Add new parameter to llm_classify to allow progress bar format to be customizable and to be disabled
This was because the logs were noisy and verbose does not disable the progress bar
=> fix: allow progress bar to be disabled

app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/RunMetadataFooter.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/__generated__/RunMetadataFooterQuery.graphql.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
resolves #5099 
https://github.com/user-attachments/assets/b1dc1962-335d-40d6-8294-78d947d94966
=> feat(playground): show span details when playground run ends

pyproject.toml, requirements/type-check.txt, src/phoenix/server/api/subscriptions.py
Adds support for anthropic
https://github.com/user-attachments/assets/c11c8ae6-1bc1-466d-8b88-0bfa676b13d5
resolves #4960
=> feat: Refactor subscription streaming and plumb through anthropic support

.github/workflows/python-CI.yml, requirements/unit-tests.txt, src/phoenix/server/api/subscriptions.py, tests/unit/conftest.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_text_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
- adds happy path api test for chat completion subscription with openai
- introduces `vcrpy` and `httpx-ws` as test dependencies. the latter extends `httpx.ASGITransport` to support websockets.
- introduces `AsyncGraphQLClient` as a testing gql client
resolves #4984
=> test(playground): add api test for chat completion subscription

app/src/pages/playground/PlaygroundChatTemplate.tsx
Text is now aligned with the left edge of collapse carets
See #5117
=> fix: Align vertical edge padding across playground message editors

tox.ini
=> chore: add descriptions for `tox list`

pyproject.toml, src/phoenix/session/session.py
ignore type errors when the symlink to `src/phoenix/evals` exists
=> chore: ignore additional packages for type check

app/.prettierignore
```
phoenix/app/src/components/templateEditor/language/fString/fStringTemplating.syntax.grammar
phoenix/app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.syntax.grammar
```
=> chore: ignore *.grammar for prettier

src/phoenix/experiments/evaluators/llm_evaluators.py
resolves #4289 
Adds a convenient scaffold for custom experiment evaluators that need to compare the task input to task output.
cc @AparnaDhinakaran
=> feat: Add LLMRelationalEvaluator to phoenix experiments

app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundTools.tsx, app/src/pages/playground/SpanPlaygroundPage.tsx
resolves #5153 
https://github.com/user-attachments/assets/a43561a9-bf60-4dbd-ab41-597a792033b9
=> fix(styles): make prompt section scrollable to the bottom

app/src/components/code/JSONEditor.tsx, app/src/components/code/LazyEditorWrapper.tsx, app/src/components/generative/ToolChoiceSelector.tsx, app/src/pages/playground/PlaygroundTool.tsx, app/src/pages/playground/PlaygroundTools.tsx
resolves #5113 
- fixes an issue where our json editors (and probably other code mirror editors) were being cut off or not rendering at all when initially rendered out of the view port
- checked datasets json editors for regressions
=> fix: update to properly initialize when brought into view

app/schema.graphql, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, src/phoenix/server/api/subscriptions.py, tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_emits_expected_payloads_and_records_expected_span_on_error[sqlite].yaml, tests/unit/server/api/test_subscriptions.py
https://github.com/user-attachments/assets/859af056-666f-4cb6-a92e-2eb055cb65b7
Improves error handling to yield an error type in the subscription so we can still return the final span at the end, even if an error occurs midway.
resolves #5187
=> fix(playground): improve playground error handling

app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/store/playground/types.ts
resolves #5020 
- parses message tool calls and adds them to the playground instance messages
- still missing tool id, needs to be added in instrumentation in https://github.com/Arize-ai/phoenix/issues/5195 and https://github.com/Arize-ai/phoenix/issues/5194
https://github.com/user-attachments/assets/df403d8e-eac2-4b39-8321-a79030b48a2b
=> feat(playground): plumb through message tool_calls from span to playground

app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/schemas.ts
resolves #5198
This allows errors to be displayed in the playground UI when the invocation parameters are totally incorrect on the span
This is what happens when I set invocation params to "'hi'" in the database
=> fix: Bubble errors up from nested invocation parameter schema transforms

app/src/pages/playground/Playground.tsx, app/src/pages/playground/SpanPlaygroundPage.tsx
https://github.com/user-attachments/assets/422e3171-1849-4d45-ae83-c3ebe3a7282c
In addition to removing `selectedSpanNodeId` from the url on playground page, fixing the original issue; I also added a key to the playground page component in order to reset the page's state when the spanId segment of the url changes. This is somewhat of a sledgehammer approach compared to selectively resetting state based on the span url, but it catches many more edge cases.
Resolves #5193
=> fix: Do not pin span in url for playground trace details slideover

app/src/pages/playground/PlaygroundOutput.tsx
Each card maintains its own state. Should they share the toggle state across all cards?
https://github.com/user-attachments/assets/67e4c08e-9392-44ad-b9b5-a32f4d228db9
Resolves #5112
=> feat: Add markdown toggle to playground output cards

app/src/Routes.tsx, app/src/components/table/TimestampCell.tsx, app/src/pages/trace/EditSpanAnnotationsButton.tsx, app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/SessionDetailsTraceList.tsx, app/src/pages/trace/SessionPage.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/sessionLoaderQuery.graphql.ts, app/src/pages/trace/sessionLoader.ts, app/src/typeUtils.ts, scripts/fixtures/multi-turn_chat_sessions.ipynb
resolves #5008 
- adds session details page with trace list
[mocks](https://www.figma.com/design/nvX5JTTdZddvLIYEjPIEM8/Phoenix-H2-2024?node-id=230-2347&node-type=canvas&t=HXKepzqUTr6Y3UZ2-0)
https://github.com/user-attachments/assets/a8bca8dc-903c-4f47-8998-38bf071420d5
=> feat(sesions): add session details page

app/src/pages/trace/TraceDetails.tsx, app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
resolves #5009 
- adds link to session page span details if the trace has a session associated with it
https://github.com/user-attachments/assets/d129e6fd-6453-496d-a6bc-cf16a776872b
=> feat(sessions): add ability to navigate from trace to session

tutorials/evals/evaluate_human_vs_ai_classifications.ipynb, tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb, tutorials/evals/evaluate_tool_calling.ipynb, tutorials/evals/evaluate_user_frustration_classifications.ipynb, tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb, tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb, tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
Several of our notebooks are breaking due to deprecated imports from `phoenix.trace.openai` and `phoenix.trace.langchain`.
resolves #5217
=> fix(docs): update legacy imports from phoenix.trace

app/schema.graphql, app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts, requirements/unit-tests.txt, src/phoenix/server/api/context.py, src/phoenix/server/api/dataloaders/__init__.py, src/phoenix/server/api/dataloaders/latency_ms_quantile.py, src/phoenix/server/api/dataloaders/session_trace_latency_ms_quantile.py, src/phoenix/server/api/types/Project.py, src/phoenix/server/api/types/ProjectSession.py, src/phoenix/server/app.py, tests/unit/server/api/dataloaders/conftest.py, tests/unit/server/api/dataloaders/test_annotation_summaries.py, tests/unit/server/api/dataloaders/test_latency_ms_quantiles.py, tests/unit/server/api/dataloaders/test_record_counts.py, tests/unit/server/api/dataloaders/test_session_trace_latency_ms_quantile.py, tests/unit/server/api/dataloaders/test_token_counts.py, tests/unit/server/api/types/test_ProjectSession.py
resolves #5232 
- adds trace_latency_ms_quantile field onto project session
- adds p50 to session details in ui
=> feat(sessions): add trace latency p50 to session details

app/schema.graphql, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/helpers/playground_registry.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/GenerativeProvider.py
resolves #5116 
`GenerativeProvider` will now have a `dependencies` field and `dependencies_installed` field that can be used to filter down to show only available providers
=> feat: Only show providers if dependencies are installed

app/schema.graphql, src/phoenix/server/api/mutations/__init__.py, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/mutations/playground_chat_mutations.py
resolves #4774 
Adds a `playgroundChatCompletion` mutation that returns a `FinishedChatCompletion` and accepts the same payload as the `chatCompletion` subscription
For simplicity, for now it simply reuses the streaming interfaces we've used, collates the results and returns them all at the end
=> feat: Add chat completion mutation

src/phoenix/config.py, src/phoenix/server/app.py
This enables specifying a list of:
- `FastAPI` [middleware](https://fastapi.tiangolo.com/tutorial/middleware/): `export PHOENIX_FASTAPI_MIDDLEWARE_PATHS=/path/to/module:middleware,/path/to/module:middleware2`
- `Strawberry` [Extensions](https://strawberry.rocks/docs/guides/custom-extensions#custom-extensions): `export PHOENIX_GQL_EXTENSION_PATHS=/path/to/extensions:extension`
- FastAPI middleware will be loaded for all REST API routes
- GQL extensions will be loaded for GQL resolvers
These can be used to extend the behavior of phoenix routes
=> feat: Add environment configuration for fastapi + gql extensions

src/phoenix/config.py, src/phoenix/server/app.py, src/phoenix/server/grpc_server.py
adds `PHOENIX_GRPC_INTERCEPTOR_PATHS` environment variable, that allows specifying
a list of `path:object`. If the object implements the [server interceptor interface](https://github.com/grpc/grpc/tree/master/examples/python/interceptors/async), they will extend our handling of all gRPC requests.
=> feat: Add env var configuration for grpc interceptor extensions

packages/phoenix-evals/src/phoenix/evals/models/base.py, packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py, packages/phoenix-evals/tests/phoenix/evals/models/test_litellm.py, packages/phoenix-evals/tests/phoenix/evals/models/test_mistralai.py, packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
=> fix(evals): only allow keyword arguments for model instantiation

src/phoenix/server/api/helpers/playground_clients.py
resolves #5238 
Adds a singleton rate-limiter per playground provider. These are set to throttle at a fairly low rate to prevent playground activity from monopolizing server CPU.
Notably, because the `Anthropic` SDK stream API has a synchronous entry point, I reused the synchronous version of the rate limiter. This might be problematic because in our old version sync throttles will be blocking (since we assumed sync functions would always be run in a sync context), severely impacting server performance.
I'll work on updating that method to accept a sync entry point but still allow the sleeps to yield control of the event loop. @axiomofjoy
=> feat: Add rate limiters to playground clients

.pre-commit-config.yaml, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundResponseFormat.tsx, app/src/pages/playground/__tests__/fixtures.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/constants.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/schemas/toolChoiceSchemas.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
https://github.com/user-attachments/assets/48780f20-8f0d-4b04-90cb-0a1bd3100f79
Resolves #5247 
Resolves #5233
=> feat: Support Response Format in Playground

app/src/pages/playground/Playground.tsx
=> fix: make playground prompts accordion the proper size when collapsed

app/src/components/table/styles.ts, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundDatasetPicker.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts, src/phoenix/server/api/queries.py
resolves #5327 
- fixes error handling for playground on dataset
- fixes dataset picker and clear button styles to be the same height
- fixes issue where playground project was no longer being returned
- fixes console warning about updates in a transition by removing transition when selecting a dataset and adding suspense and loader
=> fix(playground): fix dataset picker styles and error handling

app/src/components/code/JSONEditor.tsx, app/src/pages/playground/InvocationParameterJsonEditor.tsx, app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts, app/src/utils/jsonUtils.ts
Future proof the InvocationParamsForm with support for future json invocation params, so that they can be rendered automatically should any be defined on the backend.
> [!IMPORTANT]
> Fields displayed in the video are just for demonstration, and will not appear in production. We do not currently ship any JSON invocation parameters that are not handled elsewhere in the UI.
https://github.com/user-attachments/assets/233ad520-71d7-4d09-980d-3078ae335bdd
Resolves #5252
=> feat: Render field for JSON invocation params

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/playgroundUtils.ts
resolves #5284 
Shows template application errors for each dataset example and instance combination before the playground is run
https://github.com/user-attachments/assets/8e6f9a19-44f3-47f1-8be4-220b4c833143
=> feat(playground): pre-emptively show dataset example template application errors in playground dataset table

app/src/pages/experiment/ExperimentCompareTable.tsx
We were previously copying the incorrect contents.
=> fix: copy output contents on run example slideover

app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/ModelConfigButton.tsx
Send a hardcoded model name to the invocation params query in order to obtain the fallback set of invocation parameters for openai.
Additionally debounce the deployment name field so that it does not trigger modelName updates on each keystroke. There are a lot of effects and memoizations that are tied to modelName and cause the page to chug if it changes on keystroke. It typically only changes from a dropdown selection.
https://github.com/user-attachments/assets/d14fc808-932d-4d7e-b8cc-7575662bcb28
Note that only one network request is made for invocation parameters, the first time that model name is updated to _something_
Resolves #5386
=> fix: Prevent over-fetching when typing azure deployment name

src/phoenix/server/api/helpers/playground_clients.py
=> fix(playground): for Azure, handle initial chunk with no choices

app/src/pages/playground/ModelConfigButton.tsx, app/src/store/playground/playgroundStore.tsx
resolves #5388 
resolves #5405
- uses saved config for model information when switching providers if present, clears provider model related fields if no saved config
- also switching to the same provider will not clear model selection anymore
https://github.com/user-attachments/assets/ae0857ff-1f3b-4dcc-b8d5-21c2f50ff3f8
=> fix(playgroun): use saved model config for default model when switching providers

app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundChatTemplateFooter.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/__generated__/PlaygroundChatTemplateFooterResponseFormatQuery.graphql.ts, app/src/pages/playground/__generated__/PlaygroundChatTemplateResponseFormatQuery.graphql.ts
https://github.com/user-attachments/assets/35405368-3b07-4dc6-957a-d1c164ca62fb
Resolves #5385
Resolves #5384
=> fix: Hide Output Schema (response format) button on unsupported provider instances

app/src/pages/playground/InvocationParametersForm.tsx, app/src/pages/playground/PlaygroundResponseFormat.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/store/playground/playgroundStore.tsx, src/phoenix/server/api/types/GenerativeProvider.py, src/phoenix/server/api/types/Span.py, tests/unit/server/api/types/test_GenerativeProvider.py
resolves #5409 
The bug was happening because the parameter `invocationName` was `stop`, on the instance in the front end and the parameter `invocationName` was `stop_sequence` coming from the api. Until the values were filtered and coerced to match our api. (happened on first opening but did not cause an update to the form). Not sure why the form wasn't updating when the value got coerced however.
- makes invocation parameter comparison uniform
https://github.com/user-attachments/assets/54a26e57-d8b2-4005-97d6-2cbed947a10c
=> fix(playground): compare invocationName and canonical name in all places where we try to find invocation params

app/src/pages/playground/PlaygroundOutput.tsx
Still need better error messages themselves, but now they render until the next completion is kicked off.
Resolves #5383
=> feat: Display playground chat completion errors within output card

src/phoenix/config.py
When using open-source identity services such as Keycloak, users want to be able to run the identity service locally and point Phoenix toward a local OpenID Connect config URL during development.
resolves #5417
=> fix(auth): enable non-https OpenID Connect config URLs for development with local IDPs

app/src/pages/playground/playgroundUtils.ts, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/subscriptions.py
- allow playground to use api keys set serverside
- raise intelligible error message when llm client initialization fails
resolves #5392
=> fix(playground): allow serverside api keys

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
https://github.com/user-attachments/assets/76e0bbd9-8633-49c6-bfd1-2bbae5724265
https://github.com/user-attachments/assets/c61eb200-bbda-43f1-aa11-9e810e28880e
Resolves #5444
=> fix: Allow shrinking of playground dataset table cells that have long text

src/phoenix/server/api/subscriptions.py
- returns errors for timeouts and unexpected errors during chat completion over dataset subscription
- improves experience of writes to cap the amount of time a user has to wait to see token counts and latency in the ui
resolves #5448
=> fix(playground): return error messages for timeouts and unexpected errors during chat completion over dataset subscription

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Fixing css var name seems to have fixed resizing issues
https://github.com/user-attachments/assets/4a3af751-85b9-4f0e-99fb-cf07ded5d92d
Resolves: #5455
=> fix: Allow arbitrary column resizing without tail cell

app/package.json, app/pnpm-lock.yaml, app/src/components/ConfirmNavigation.tsx, app/src/pages/playground/InvocationParametersFormFields.tsx, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetSection.tsx, app/src/pages/playground/PlaygroundStreamToggle.tsx, app/src/pages/playground/__generated__/InvocationParametersFormFieldsQuery.graphql.ts, app/src/pages/playground/constants.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/store/playground/types.ts, app/src/store/preferencesStore.tsx
resolves #5464 
resolves #5460
resolves #5466 
- remembers streaming setting from playground in preferences store
- adds text to inform users that playground is still running and navigating may result in data los
- updates save config button and icon to be more clear as to its purpose (saving config as default, not applying the config to the current run
- small style tweaks on model config form
https://github.com/user-attachments/assets/48ef1ea0-cecf-47a0-a703-04588acbd656
Any feedback on wording here is much appreciated
https://github.com/user-attachments/assets/76f1910f-562a-4836-ad14-f10f747049b1
=> feat(playground): block navigation when runs are in progress

src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/subscriptions.py
resvoles #5457
The throttler was too permissive to ensure that the backend was successfully limiting playground streams. Because we are trying to optimize for backend availability instead of attempting to submit as many requests as possible without hitting rate limits, we should drop the enforcement window to near-zero.
=> fix: tighten up playground throttling

pyproject.toml, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/subscriptions.py
Improves error handling to surface up actionable messages to the user for missing API keys and other configuration.
resolves #5461
=> fix(playground): improve error handling when instantiating playground llm clients

app/src/pages/playground/Playground.tsx
Additionally fix minor padding misalignment
https://github.com/user-attachments/assets/0448a089-4703-4459-8b78-0315dc738ede
Resolves: #5458 
Resolves: #5456
=> fix: Prevent layout shift when scrollbars are introduced

src/phoenix/server/api/helpers/playground_clients.py
resolves #5390 
resolves #5490
- Also updates anthropic model name
- Moves deprecated `max_tokens` invocation parameter to `max_completion_tokens` for OpenAI models
=> fix: Add numeric playground defaults

src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/subscriptions.py
`asyncio.wait_for` raises an `asyncio.CancelledError` inside of the wrapped coroutine when a timeout happens. However, that cancellation error has no message content. As a result, tasks that time out when hitting the 90-second limit result in spans with an error status code but an empty status message. This PR implements a helper function that behaves like `asyncio.wait_for`, but allows sending `asyncio.CancelledError` with a custom message to the wrapped coroutine that will then be recorded in the span and displayed in the UI.
resolves #5454
resolves #5499
=> fix(playground): ensure playground timeout errors are displayed

app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundOutputMoveButton.tsx
This allows users to copy a desireable result from the playground back into their conversation, to continue iteration
https://github.com/user-attachments/assets/495ac133-cea1-42fb-92a9-dbcaa3f29aec
Resolves #5451
=> feat: Implement "Move Output" button on Playground Output

app/src/pages/playground/PlaygroundOutput.tsx, app/src/utils/errorUtils.ts, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/subscriptions.py
Blocks playground runs when app is readonly e.g., for demo isntances
Blocks and shows intelligible error for:
- streaming dataset
- streaming no dataset
- non streaming dataset
- non streaming no dataset
=> fix(playground): block playground runs when app is readonly

app/schema.graphql, app/src/pages/project/SessionsTable.tsx, app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts, app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts, app/src/pages/trace/SessionDetails.tsx, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts, src/phoenix/db/insertion/span.py, src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py, src/phoenix/db/models.py, src/phoenix/server/api/input_types/ProjectSessionSort.py, src/phoenix/server/api/types/Project.py, src/phoenix/server/api/types/ProjectSession.py, tests/integration/db_migrations/test_up_and_down_migrations.py, tests/integration/project_sessions/test_project_sessions.py, tests/unit/_helpers.py, tests/unit/server/api/dataloaders/conftest.py
resolves #5355
resolves #5354 
Also, populate `project_id` and `session_user` using only the values from the earliest root span. These values should remain unchanged for the session, even if later spans modify them. The earliest `session_user` is likely the user who initiated the conversation, making it a more accurate identifier. Similarly, the earliest `project_id` ensures consistency, preventing the session from shifting between projects.
=> fix(sessions): remove end_time from db and ui table

src/phoenix/server/api/helpers/playground_clients.py
- change default temperatures to 1
- remove default seed values so people get different generations each time they run
- fix type issue with top k parameter for gemini
resolves #5514
resolves #5528
=> fix(playground): improve playground default invocation parameters

tox.ini
tox invokes uv, which needs to be explicitly allowed in the latest tox from what I can tell.
=> chore(dx): add uv to tox allowlist

app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
the variable values come from the input, not the output
=> fix(playground): fix wording on missing input variable in playground over a dataset

src/phoenix/server/api/helpers/dataset_helpers.py, src/phoenix/server/api/mutations/dataset_mutations.py, src/phoenix/server/api/types/Span.py, tests/unit/server/api/helpers/test_dataset_helpers.py, tests/unit/server/api/mutations/test_dataset_mutations.py
- unnest retrieval documents
- write less metadata to revisions when converting from spans
- removes unnecessary internal span interface
resolves #5526
=> fix: ensure retrieval documents are unnested when converting from span to dataset example

src/phoenix/server/api/helpers/playground_spans.py, src/phoenix/server/api/mutations/chat_mutations.py, tests/unit/server/api/test_subscriptions.py
Use the same format for playground experiment run output as for dataset example revisions created from a span.
resolves #5525
=> fix(playground): use consistent playground experiment run format

app/src/pages/playground/playgroundUtils.ts
We made a helper to prevent bad "null canonical name" comparisons but we weren't using it here.
Implementing it fixes an issue where parameters without canonical names were converted incorrectly.
=> fix: Properly constrain/rename invocation params before submitting

requirements/unit-tests.txt
- need openai 1.55.3 to [this issue](https://community.openai.com/t/client-openai-returns-error-client-init-got-an-unexpected-keyword-argument-proxies/1035249)
- https://github.com/openai/openai-python/pull/1904/files
- openai==1.55.3 depends on typing-extensions>=4.11,<5
=> ci: remove version pin on typing extensions

packages/phoenix-evals/src/phoenix/evals/classify.py, packages/phoenix-evals/src/phoenix/evals/generate.py, packages/phoenix-evals/src/phoenix/evals/models/anthropic.py, packages/phoenix-evals/src/phoenix/evals/models/base.py, packages/phoenix-evals/src/phoenix/evals/models/bedrock.py, packages/phoenix-evals/src/phoenix/evals/models/litellm.py, packages/phoenix-evals/src/phoenix/evals/models/mistralai.py, packages/phoenix-evals/src/phoenix/evals/models/openai.py, packages/phoenix-evals/src/phoenix/evals/models/vertex.py, packages/phoenix-evals/src/phoenix/evals/models/vertexai.py, packages/phoenix-evals/src/phoenix/evals/templates.py, packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
This refactor enables the creation of `PromptTemplate` objects that include multiple messages that include mixed media types (e.g. audio, images, links, etc) and leave the handling of the message prompts to each model wrapper.
Should be fully backwards compatible
=> feat: Enable `phoenix.evals` to handle multimodal message templates

app/src/RelayEnvironment.ts, app/src/authFetch.ts, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/playground/PlaygroundRunButton.tsx, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts, tox.ini
Can cancel runs with and without datasets.
~~- [ ] Server side run cancellation~~ will do this in future work
- This means that work continues on the server, even if requests are cancelled, for both fetch and websocket initiated requests.
https://github.com/user-attachments/assets/46ff68f2-622a-476a-81b1-a3879f4d26f4
https://github.com/user-attachments/assets/abee5743-1b05-4fed-ad90-4c355a459bd4
resolves: #5484
=> feat: Add cancel button to playground runs

app/src/components/table/CellWithControlsWrapper.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
There was a deadzone on the control hovering styles caused by padding in the parent td element.
Now cell contents control their own padding, and fill available td space, so that the hover target matches the visible cell area.
Resolves #5554
=> fix: Remove deadzone when hovering example table cells

MIGRATION.md, src/phoenix/db/migrations/data_migration_scripts/populate_project_sessions.py, src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py, tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py
```shell
export PHOENIX_SQL_DATABASE_URL=sqlite:////phoenix.db
```
```shell
cd src/phoenix/db/migrations
alembic upgrade head
```
```shell
yes | uv run populate_project_sessions.py
```
=> fix(sessions): separate migration script for populating the project sessions table

MIGRATION.md
Denote that you need to install the pg extra to apply the migration with phoenix
=> docs(sessions): add note about pg extra

app/src/pages/project/ProjectPage.tsx
When the `title` attr is present on TabPane, hovering any child within the pane causes a native html tooltip to appear. We don't need the `title` attr on the panes.
=> fix: prevent useless tooltips from appearing in projects

app/schema.graphql, app/src/pages/trace/TraceDetails.tsx, app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts, src/phoenix/server/api/types/Trace.py
The latency of the trace is not always the same as the latency of the root span, e.g., when a root span returns a coroutine that is executed later.
resolves #5337
=> fix: compute trace latency rather than relying on root span latency

js/packages/phoenix-client/src/types/annotations.ts, js/packages/phoenix-client/src/types/core.ts, js/packages/phoenix-client/src/types/datasets.ts, js/packages/phoenix-client/src/types/experiments.ts
Adds types under client for now to get the abstractions right under the client.
=> chore(js): add rudamentary types for experiments

src/phoenix/server/api/auth.py, src/phoenix/server/api/context.py, src/phoenix/server/api/mutations/api_key_mutations.py, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/mutations/dataset_mutations.py, src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py, src/phoenix/server/api/mutations/user_mutations.py, src/phoenix/server/api/subscriptions.py
Enables custom GraphQL schema extensions to dynamically place the application in write-disabled mode, which disables create and update mutations but allows delete mutations.
resolves #5635
=> fix: add locked mode

.github/workflows/playwright.yaml, .github/workflows/python-CI.yml, .github/workflows/python-cron.yml, pyproject.toml, requirements/build-graphql-schema.txt, requirements/type-check.txt, src/phoenix/server/api/input_types/DataQualityMetricInput.py, src/phoenix/server/api/input_types/PerformanceMetricInput.py, src/phoenix/server/api/types/DataQualityMetric.py, src/phoenix/server/api/types/PerformanceMetric.py, src/phoenix/server/api/types/TimeSeries.py, src/phoenix/server/types.py
resolves #5082 
1. Python 3.13 is not supported on Intel x86_64 macOS due to issue with `wrapt`
2. `build_openapi_schema` fails `git diff` on Python 3.13 due to `Unprocessable Entity` being renamed as `Unprocessable Content`
=> fix: increase python upper bound to include python 3.13

docs/tracing/how-to-tracing/customize-spans/masking-span-attributes.md
The latest release of `python-openinference-instrumentation`: [v0.1.20](https://github.com/Arize-ai/openinference/releases/tag/python-openinference-instrumentation-v0.1.20) now supports masking invocation params with the `TraceConfig`. (related PR - https://github.com/Arize-ai/openinference/pull/1171)
This PR updates the [`Masking Span Attributes` ](https://github.com/Arize-ai/phoenix/blob/docs/docs/tracing/how-to-tracing/customize-spans/masking-span-attributes.md) page from the docs for the same.
=> docs: add support for hiding LLM invocation parameters in masking span attributes

app/schema.graphql, app/src/Routes.tsx, app/src/pages/Layout.tsx, app/src/pages/index.tsx, app/src/pages/prompt/PromptPage.tsx, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/index.tsx, app/src/pages/prompt/promptLoader.tsx, app/src/pages/prompts/PromptsPage.tsx, app/src/pages/prompts/PromptsTable.tsx, app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts, app/src/pages/prompts/__generated__/PromptsTable_datasets.graphql.ts, app/src/pages/prompts/__generated__/PromptsTable_prompts.graphql.ts, app/src/pages/prompts/__generated__/promptsLoaderQuery.graphql.ts, app/src/pages/prompts/index.tsx, app/src/pages/prompts/promptsLoader.ts, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Prompt.py
resolves #5725
Adds rudimentary listing of `Prompts`
=> feat(promts): skeleton UI for promts

.github/workflows/playwright.yaml
It's unclear why it timed out.
```
[WebServer] INFO:     Started server process [7932]
[WebServer] INFO:     Waiting for application startup.
[WebServer] INFO:     Application startup complete.
[WebServer] INFO:     Uvicorn running on http://0.0.0.0:6006/ (Press CTRL+C to quit)
Error: Timed out waiting 60000ms from config.webServer.
```
=> ci: remove windows for playwright tests

docs/evaluation/how-to-evals/evaluating-phoenix-traces.md
* Fix: Assigning `"score"` column before uploading evaluations to Phoenix
=> Doc Fix: Column Name in *Evaluating Phoenix Traces*

app/schema.graphql, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersion.py
=> feat: Spike out dummy PromptVersion connection

app/src/pages/prompt/PromptIndexPage.tsx, app/src/pages/prompt/PromptInvocationParameters.tsx, app/src/pages/prompt/PromptVersionDetailsPage.tsx, app/src/pages/prompt/PromptVersionsList.tsx, app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts, app/src/pages/prompt/__generated__/PromptInvocationParameters__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/promptVersionLoader.tsx, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersion.py
https://github.com/user-attachments/assets/be02c374-4a25-412e-88ca-a44b88a1d3ea
Resolves #5777
=> feat(prompts): Render model invocation params in prompt details view

app/src/Routes.tsx, app/src/components/CopyToClipboardButton.tsx, app/src/components/templateEditor/TemplateEditor.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/prompt/ChatTemplateMessage.tsx, app/src/pages/prompt/PromptChatMessages.tsx, app/src/pages/prompt/PromptIndexPage.tsx, app/src/pages/prompt/PromptInvocationParameters.tsx, app/src/pages/prompt/PromptVersionDetailsPage.tsx, app/src/pages/prompt/PromptVersionsList.tsx, app/src/pages/prompt/PromptVersionsPage.tsx, app/src/pages/prompt/__generated__/PromptChatMessages__main.graphql.ts, app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/__generated__/promptVersionsLoaderQuery.graphql.ts, app/src/pages/prompt/promptVersionLoader.tsx, app/src/pages/prompt/promptVersionsLoader.tsx, app/src/pages/prompt/schemas.ts, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Prompt.py
Depends on #5777
https://github.com/user-attachments/assets/7580baaa-1863-4326-8bf6-abc1dcb6478f
Syntax highlighting works as well
Resolves #5759
=> feat(prompts): Render prompt messages on prompt detail view

src/phoenix/server/api/helpers/playground_clients.py
See https://platform.openai.com/docs/models#o1
Specifically the o1 model name is available, along with output format / structured outputs support.
=> feat(playground): Update o1 model listing and params

app/src/components/code/styles.tsx, app/src/components/markdown/MarkdownBlock.tsx, app/src/components/utility/PrettyText.tsx, app/src/components/utility/index.tsx, app/src/hooks/usePrettyText.ts, app/src/pages/playground/PlaygroundOutput.tsx, app/src/pages/trace/SpanDetails.tsx
resolves #5140 
Detects if the string is JSON parsable or not and pretty prints it.
=> feat(tracing): pretty print JSON strings for structured data outputs

app/schema.graphql, src/phoenix/server/api/types/PromptVersion.py, src/phoenix/server/api/types/PromptVersionTag.py
resolves #5846 
Adds a strawman prompt_version_tag type
```graphql
{
prompts {
edges {
prompt: node {
id
promptVersions {
edges {
node {
tags {
id
name
}
}
}
}
}
}
}
}
```
=> chore(prompts): add prompt version tags graphql schema with mocks

app/schema.graphql, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/promptVersionLoader.tsx, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/JSONSchema.py, src/phoenix/server/api/types/Prompt.py, src/phoenix/server/api/types/PromptVersion.py, src/phoenix/server/api/types/ToolDefinition.py
resolves #5848 
```graphql
{
prompts {
edges {
prompt: node {
id
promptVersions {
edges {
node {
tools {
definition
}
}
}
}
}
}
}
}
``
=> feat(prompts): graphql types for tools, output_schema

app/src/components/code/PythonBlock.tsx, app/src/pages/prompt/PromptCodeExportCard.tsx, app/src/pages/prompt/PromptIndexPage.tsx, app/src/pages/prompt/PromptVersionDetailsPage.tsx, app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts, app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts, app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts, app/src/pages/prompt/promptCodeSnippets.tsx, app/src/pages/prompt/promptVersionLoader.tsx, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Prompt.py
https://github.com/user-attachments/assets/a171b067-d6b2-439c-b111-384a9c9482ff
Resolves #5776
=> feat(prompts): Implement prompts as code examples beneath prompt

app/src/pages/project/ProjectPageHeader.tsx, app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts, app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
resolves #5872 
Adds a breakdown of token counts to the header
=> feat: show a breakdown of tokens in the project header

app/src/pages/trace/SpanDetails.tsx
```python
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
endpoint = "http://127.0.0.1:6006/v1/traces"
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(OTLPSpanExporter(endpoint)))
with tracer_provider.get_tracer(__name__).start_as_current_span("test") as span:
span.set_attribute("openinference.span.kind", "LLM")
span.set_attribute("llm.input_messages.0.message.role", "assistant")
span.set_attribute("llm.input_messages.0.message.tool_calls.0.tool_call.function.name", "xyz")
```
=> fix: skip json parse if tool call function arguments attribute doesn't exist

app/.eslintrc.js, app/src/components/StopPropagation.tsx, app/src/components/button/styles.tsx, app/src/components/disclosure/Disclosure.tsx, app/src/components/disclosure/index.ts, app/src/components/disclosure/styles.tsx, app/src/components/index.tsx, app/src/pages/embedding/EventDetails.tsx, app/src/pages/embedding/ExportSelectionButton.tsx, app/src/pages/model/ModelPage.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundResponseFormat.tsx, app/src/pages/playground/PlaygroundTools.tsx, app/src/pages/trace/SpanFeedback.tsx, app/stories/Disclosure.stories.tsx, app/stories/Gallery.stories.tsx
Port from Accordion to React Aria Disclosure and DisclosureGroup
https://github.com/user-attachments/assets/2a4ee594-ad69-4218-9f37-b39f3136213f
Resolves #5855
=> feat(components): Disclosure (fka Accordion)

app/src/components/disclosure/Disclosure.tsx, app/src/components/index.tsx, app/src/pages/playground/Playground.tsx
You can scroll once again on the Playground page now that these class names are exposed on Disclosure components
=> fix(components): Add class names to Disclosure for backwards compatibility with Accordion

src/phoenix/server/api/types/Span.py
=> fix: coerce to string when output.value is not None (e.g. bool)

src/phoenix/server/api/dataloaders/token_counts.py
prompt / completion token aggregate totals should be 0 when there are no tokens overall
=> fix: default prompt / completion tokens to 0

packages/phoenix-evals/src/phoenix/evals/templates.py, packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
resolves #5815
- ClassificationTemplate instantiation would fail if not passed an explanation template
- Always set `explanation_template` even if not provided
- The fallback if `provide_explanation` is True will be the standard template
=> fix: Allow ClassificationTemplate w/o explanation template

app/src/pages/prompt/PromptCodeExportCard.tsx
=> fix(prompts): Fix code disclosure width on prompts ui

app/schema.graphql, app/src/pages/prompt/TagPromptVersionButton.tsx, app/src/pages/prompt/__generated__/TagPromptVersionButtonTagsQuery.graphql.ts, src/phoenix/server/api/types/Prompt.py
resolves #5906 
Show the prompt version tags that can be set on a particular version
=> feat(prompts): show the tags that can be set on a promt version

app/schema.graphql, src/phoenix/server/api/types/PromptVersion.py
resolves #5908 
Returns the last created PromptVersion on a specific Prompt
=> feat: Add `previous_version` resolver on `PromptVersion`

src/phoenix/server/api/routers/v1/traces.py
see https://opentelemetry.io/docs/specs/otlp/#full-success-1
following [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/blob/0ece6789195060e4157cfa46ae093170b46495da/receiver/otlpreceiver/otlphttp.go#L56)
=> fix: return 200 for POST v1/traces

src/phoenix/db/insertion/span.py, src/phoenix/trace/otel.py, tests/unit/trace/test_otel.py
This fixes cases where the instrumentor accidentally exports spans with string typed token counts, like llama-index + bedrock
=> fix: Coerce incoming span token counts to int

app/src/components/button/Button.tsx, app/src/components/disclosure/Disclosure.tsx, app/src/components/types/style.ts, app/src/pages/prompt/DeletePromptVersionTagButton.tsx, app/src/pages/prompt/TagPromptVersionButton.tsx, app/stories/Button.stories.tsx
=> refactor(components): only use css stylable props

requirements/unit-tests.txt
=> ci: update unit tests dependency respx>=0.22 for httpx>=0.28

pyproject.toml, requirements/unit-tests.txt
`litellm==1.57.5` broke Windows compatibility https://github.com/BerriAI/litellm/issues/7677
=> ci: pin upper bound on litellm to prevent windows break

pyproject.toml, requirements/type-check.txt, requirements/unit-tests.txt, src/phoenix/server/api/helpers/jsonschema.py, src/phoenix/server/api/helpers/prompts/models.py, tests/unit/server/api/helpers/test_models.py, tests/unit/server/api/mutations/test_prompt_mutations.py
LLM API providers support relatively advanced features of JSON schema for tools and response formats (e.g., recursive schemas) that are complex to implement in Pydantic. So this PR simplifies things and introduces a third-party library.
There are two main choices for third-party libraries in the Python ecosystem, `jsonschema` and `fastjsonschema`. As the name suggests, the latter is significantly faster (>10x in my benchmarking), but seems to be less actively maintained (no support for more recent formats and less overall activity in the repo). It also has a few quirks in implementation that deviate from the standard spec and make it more lax than other implementations in a way that could make it difficult to migrate to `jsonschema`. So I chose `jsonschema` to start.
I am relying on JSON …
=> refactor(prompts): validate jsonschema using third-party library

pyproject.toml, requirements/unit-tests.txt
LiteLLM fixed on Windows: https://github.com/BerriAI/litellm/issues/7677#issuecomment-2584658205
resolves #6005
=> ci: unpin litellm

packages/phoenix-otel/README.md, packages/phoenix-otel/src/phoenix/otel/otel.py, packages/phoenix-otel/src/phoenix/otel/settings.py
- resolves #5955 
While `PHOENIX_GRPC_PORT` is typically a server-side variable, this provides an intuitive mechanism to improve the port-inference logic used in `phoenix-otel`.
We should consider also adding an explicit override that will force using either gRPC or HTTP regardless of endpoint (which would be easier than our original proposed solution of explicitly setting the exporter).
=> feat: `phoenix.otel` infers GRPC port from env

app/schema.graphql, src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
=> feat: Add Prompt to setPromptVersionTag mutation

src/phoenix/server/api/schema.py
Without this change, the extensions were only ran once
=> fix: Update schema.py to make extensions a list, not chain

src/phoenix/server/api/types/Prompt.py
- We weren't resolving the globalid into a db id
=> fix: Resolve source prompts properly

app/schema.graphql, src/phoenix/server/api/mutations/prompt_mutations.py
=> feat: Add patchPromptDescription mutation

app/src/components/dataset/CreateDatasetForm.tsx, app/src/components/dataset/NewDatasetButton.tsx, app/src/pages/dataset/AddDatasetExampleDialog.tsx, app/src/pages/datasets/DatasetsPage.tsx, app/src/pages/datasets/DatasetsTable.tsx, app/src/pages/examples/ExampleSelectionToolbar.tsx, app/src/pages/experiments/ExperimentSelectionToolbar.tsx, app/src/pages/project/SpanSelectionToolbar.tsx, app/src/pages/settings/DeleteUserDialog.tsx, app/src/pages/settings/SystemAPIKeysTable.tsx, app/src/pages/settings/UserAPIKeysTable.tsx, app/src/pages/settings/UsersCard.tsx, app/src/pages/trace/SpanToDatasetExampleDialog.tsx
I searched the codebase for gql mutations that handle errors, and then prettified the errors before passing them through to notify, etc.
resolves: #6035
=> feat: Prettify mutations with user facing errors

app/schema.graphql, src/phoenix/server/api/types/Prompt.py
resovles #6019 
- Resolves latest PromptVersion on Prompts
- If passed an optional PromptVersion id, will resolve the specified PromptVersion
=> feat: Resolve versions on Prompt

packages/phoenix-evals/src/phoenix/evals/templates.py
Resolves #6043 
- Allows for the creation of eval templates that include string encoded "image" parts
=> feat: Support image template parts in `phoenix-evals`

src/phoenix/server/api/helpers/playground_clients.py
This model uses the legacy completions API, which we do not currently support.
resolves #6080
=> fix(playground): remove gpt-3.5-turbo-instruct

app/src/Routes.tsx, app/src/pages/example/ExampleDetailsDialog.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundDatasetPicker.tsx, app/src/pages/playground/PlaygroundExamplePage.tsx
https://github.com/user-attachments/assets/47051d3d-6dce-46c5-a5d0-ba93a60b451f
Resolves #6059
This prevents data-loss from re-parenting playground on a new route
Before:
/prompts/1234/playground -> click dataset -> /playground/datasets/9876 Causes remount, data loss
After:
/prompts/1234/playground -> click dataset -> /prompts/1234/playground?datasetId="9876" No remount, no data loss, just state updates
=> refactor(prompts): Use query parameters for datasetId and exampleId

app/src/components/button/Button.tsx, app/src/components/types/sizing.ts, app/src/components/types/variance.ts
- Fixes size props to use Exclude (for unions) over omit (for object keys)
- removes info variant for button
- adds quiet variant
=> fix(components): fix button size and variance props

app/src/pages/playground/Playground.tsx, app/src/pages/playground/PromptComboBox.tsx, app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
https://github.com/user-attachments/assets/0e083cfe-a1be-47d3-b76d-91f0a221cb32
Resolves #6074
Resolves #6092
- Update prompt in combobox with newly created or updated prompt
- Reset dirty state when prompt is saved / created
- Warn before navigations / tab close when any instance has a dirty state
=> feat(prompts): Improve post-save prompt ux

packages/phoenix-evals/src/phoenix/evals/templates.py
Reproduce:
```
>>> from phoenix.evals import PromptTemplate
>>>
>>> template = PromptTemplate("Hello {{var}}.", delimiters=["{{", "}}"])
>>> template.format({"var": "world"})
File "<stdin>", line 1, in <module>
File "/Users/james/work/prompt-library/.venv/lib/python3.10/site-packages/phoenix/evals/templates.py", line 100, in format
prompt_message = prompt_message.replace(
UnboundLocalError: local variable 'prompt_message' referenced before assignment
```
=> fix: local variable 'prompt_message' referenced before assignment

app/schema.graphql, app/src/pages/playground/__generated__/ModelSupportedParamsFetcherQuery.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/input_types/InvocationParameters.py, tox.ini
- o1 now supports "system" messages by converting them to "developer" before sending to openai
- o1 now supports "reasoning effort" parameter of values "low" "medium" and "high"
Limitations:
- o1 models no longer support streaming. Unclear if temporary regression.
- o1-mini does not support "developer" messages or "system" messages
- o1-mini does not support "reasoning effort"
=> feat: Add support for o1 dev messages + reasoning param

packages/phoenix-otel/README.md, packages/phoenix-otel/src/phoenix/otel/otel.py
- allows a user to pass `protocl="http" | "grpc"` to either use a specific endpoint, or force the use of that exporter for the given endpoint
=> feat: Explicit OTEL protocol override

app/src/pages/experiment/ExperimentCompareTable.tsx
resolves #5586
This allows text to break regardless of whitespace, allowing cells to be shrunk.
An alternative approach would be to enable horizontal overflow within a cell, but that seems cumbersome on an already scrolling page.
Or, we could consider truncating results and only displaying them in dialog
=> fix: Allow experiment table resize for large inputs

app/schema.graphql, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
=> feat: Add tags with prompt version create

app/schema.graphql, src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py, src/phoenix/db/models.py, src/phoenix/server/api/mutations/__init__.py, src/phoenix/server/api/mutations/prompt_label_mutations.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/PromptLabel.py
resolves #6041 
- adds `PromptLabel` node
- adds `Prompts` resolver to `PromptLabel` node
- adds `PromptLabel` to node interface
- adds `PromptLabel` query
- adds `createPromptLabel` mutation
- adds `patchPromptLabel` mutation
- adds `deletePromptLabel` mutation
- adds `setPromptLabel` mutation <- associates a Prompt with a PromptLabel
- adds `removePromptLabel` mutation <- disassociates a Prompt with a PromptLabel
=> feat: PromptLabel gql interface

app/src/Routes.tsx, app/src/pages/prompts/PromptsTable.tsx
Adds a quick link to open the prompt from the listing
=> feat(prompts): add open in playground action button on the table

app/package.json, app/pnpm-lock.yaml, app/src/@types/time.d.ts, app/src/components/datetime/DateField.tsx, app/src/components/datetime/TimeRangeForm.tsx, app/src/components/datetime/index.tsx, app/src/components/overlay/Popover.tsx, app/src/components/textfield/TextField.tsx, app/src/utils/timeFormatUtils.ts, app/stories/Popover.stories.tsx, app/stories/TimeRangeForm.stories.tsx
related to ad-hoc time range selection. This adds a simple form that encompasses start / end time.
=> feat(components): time range form

app/src/pages/playground/SavePromptForm.tsx, app/src/pages/prompt/NewPromptVersionTagDialog.tsx, app/src/utils/identifierUtils.ts, src/phoenix/db/types/identifier.py, tests/unit/db/types/test_identifier.py, tests/unit/server/api/routers/v1/test_prompts.py
resolves #6089 
Also relaxed rule to include underscores.
=> feat: add regex rule for identifier pattern on ui forms for prompt and tag names

app/src/pages/trace/SpanDetails.tsx
If an LLM produces tool call arguments that are not valid json, we now fallback to rendering the arguments as a string, instead of throwing an unparse-able error.
While we could render a specialized error in this case, I am not sure that every LLM will have a requirement for tool call arguments to be json parseable, so we may as well just display whatever is produced by the llm.
Resolves #6202
=> fix: Prevent error when parsing invalid json out of tool calls

app/src/GlobalStyles.tsx, app/src/pages/prompt/ClonePromptDialog.tsx, app/src/pages/prompt/PromptLayout.tsx, app/src/pages/prompt/__generated__/PromptLayout__main.graphql.ts, app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
resolves #6029 
Display the clone source prompt in the header
=> feat(prompts): display the cloned prompt in header

packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py, packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py, packages/phoenix-client/tests/canary/sdk/anthropic/test_messages.py, packages/phoenix-client/tests/canary/sdk/openai/test_chat.py, schemas/openapi.json, src/phoenix/db/models.py, src/phoenix/server/api/helpers/prompts/models.py, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/mutations/prompt_mutations.py, src/phoenix/server/api/routers/v1/prompts.py, src/phoenix/server/api/types/OutputSchema.py, src/phoenix/server/api/types/PromptVersion.py, src/phoenix/server/api/types/ToolDefinition.py, tests/canary/sdk/openai/test_chat_message.py, tests/unit/server/api/helpers/prompts/test_models.py, tests/unit/server/api/mutations/test_prompt_mutations.py, tests/unit/server/api/routers/v1/test_prompts.py
Store tool data in a normalized format.
=> fix(prompts): normalized tools

app/package.json, app/pnpm-lock.yaml, app/src/components/templateEditor/TemplateEditor.tsx, app/src/pages/playground/ChatMessageToolCallsEditor.tsx, app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/PlaygroundChatTemplateFooter.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/PlaygroundInput.tsx, app/src/pages/playground/PlaygroundOutputMoveButton.tsx, app/src/pages/playground/PlaygroundTemplate.tsx, app/src/pages/playground/PlaygroundTool.tsx, app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx, app/src/pages/playground/VariableEditor.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/useDerivedPlaygroundVariables.tsx, app/src/pages/prompt/ChatTemplateMessageCard.tsx, app/src/pages/prompt/PromptPlaygroundPage.tsx, app/src/store/playground/__tests__/playgroundStore.test.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/selectors.ts, app/src/store/playground/types.ts
Resolves: #6191
This PR contains two major changes, and should be viewed by-commit.
---
There is now a split in instance types:
- PlaygroundInstance
- PlaygroundNormalizedInstance
The main difference is that chat templates within a normalized instance only contain messageIds instead of message objects.
The PlaygroundStore now only deals in PlaygroundNormalizedInstance, and handles conversion from PlaygroundInstance to PlaygroundNormalizedInstance during initialization.
---
- TemplateEditor
- VariableEditor
- PlaygroundTool (editor)
---
All of this is in service of fixing a react-codemirror bug that breaks rendering when updates take too long, which was occurring because messages were stored deeply within an instance causing a cascade of re-renders on every keystroke.
=> refactor(prompts): Normalize playground instance messages

app/src/components/combobox/ComboBox.tsx, app/src/components/field/styles.ts, app/src/pages/playground/SavePromptForm.tsx
Before it was impossible to know why the submit form was invalidated when you had a bad identifier. This makes it so that the error shows up correctly.
https://github.com/user-attachments/assets/eb3e8d24-497f-4ac6-a7bd-b3b5d5bf023e
=> fix(prompts): fix regex validation logic so it shows up in the form

packages/phoenix-evals/src/phoenix/evals/models/openai.py
resolves #6237
Note that we've moved to put all messages in OpenAI prompts under the "system" due to content filter issues
=> feat: Support OpenAI reasoning models that don't use the "system" role

app/src/RelayEnvironment.ts, app/src/authFetch.ts, tox.ini
resolves #6124 
Adds retry logic to the websockets via `shouldRetry` and inserts refreshing the tokens.
=> fix(auth): refresh tokens on websockets

src/phoenix/session/session.py
resolves #6193
In general we don't really support attaching to postgres via launch_app. But it seems that this is being done in some capacity so this at least sanitizes the url just in case.
=> fix: sanitize db urls in launch_app

Dockerfile, app/package.json
The `corepack` package included with node-20:slim is too old to fetch package managers.
This PR replaces corepack with a direct installation of pnpm in the image.
Issue is discussed https://github.com/nodejs/corepack/issues/612
Resolves #6247
=> fix: Replace corepack with pinned pnpm version in Dockerfile

schemas/openapi.json, src/phoenix/server/api/helpers/jsonschema.py, src/phoenix/server/api/helpers/prompts/models.py, tests/unit/server/api/helpers/prompts/test_models.py, tests/unit/server/api/helpers/test_models.py
When storing JSON schema fields in the DB, nests them under a discriminated union to include the version of JSON schema that was used to validate them. This way, we can easily support new versions of the JSON schema standard in the future.
=> fix(prompts): nest json schema fields in discriminated union

app/schema.graphql, app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts, app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts, app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/pages/playground/playgroundUtils.ts, app/src/store/playground/types.ts, src/phoenix/server/api/helpers/playground_spans.py, src/phoenix/server/api/input_types/ChatCompletionInput.py, src/phoenix/server/api/mutations/chat_mutations.py
resolves #6151 
- `prompt_id` can now be optionally passed to playground `ChatCompletionInput` and `ChatCompletionOverDatasetInput`
- This `prompt_id` will be propagated to playground-generated spans
=> feat: Propagate prompt id to playground spans metadata

packages/phoenix-evals/src/phoenix/evals/classify.py, packages/phoenix-evals/src/phoenix/evals/executors.py, packages/phoenix-evals/src/phoenix/evals/generate.py, packages/phoenix-evals/src/phoenix/evals/models/anthropic.py, packages/phoenix-evals/src/phoenix/evals/models/base.py, packages/phoenix-evals/src/phoenix/evals/models/bedrock.py, packages/phoenix-evals/src/phoenix/evals/models/mistralai.py, packages/phoenix-evals/src/phoenix/evals/models/openai.py, packages/phoenix-evals/src/phoenix/evals/models/vertex.py
resolves #6198 
Enables a timeout override for `AsyncExecutor`s on a per-model basis. Some model wrappers now have an optional `timeout` argument that will override the internal timeout of 120s.
This original 120s timeout was determined to "feel good" when doing our initial internal throttler testing.
=> feat: Enable overriding executor timeouts per model

app/src/RelayEnvironment.ts
If authentication is disabled, there is no need to refresh tokens. This means that the option to refresh the tokens should be disabled as well as the option to retry.
=> fix(playground): disable retry and auth refresh if auth is disabled

src/phoenix/server/api/helpers/playground_clients.py
=> fix(playground): if base url is provided but not api key, use fake api key for openai client

app/schema.graphql, app/src/Routes.tsx, app/src/components/generative/GenerativeProviderIcon.tsx, app/src/components/generative/index.ts, app/src/pages/playground/PlaygroundCredentialsDropdown.tsx, app/src/pages/settings/GenerativeProvidersCard.tsx, app/src/pages/settings/SettingsPage.tsx, app/src/pages/settings/__generated__/GenerativeProvidersCard_data.graphql.ts, app/src/pages/settings/__generated__/settingsPageLoaderQuery.graphql.ts, app/src/pages/settings/index.tsx, app/src/pages/settings/settingsPageLoader.ts, src/phoenix/server/api/types/GenerativeProvider.py
resolves #6123 
Adds a central AI provider configuration that can be used to see how all the providers are configured.
=> feat(playground): central ai provider config

.github/workflows/playwright.yaml, .github/workflows/typescript-CI.yml, .github/workflows/typescript-packages-CI.yml, .github/workflows/typescript-packages-publish.yml, Dockerfile, app/package.json, js/package.json
Something is segfaulting in docker builds when we build the frontend.
I suspect it may be pnpm 9.15.5 as that released only 3 days ago.
Will try bringing pnpm up to latest, node to latest lts
=> chore: Upgrade pnpm version

src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/subscriptions.py
resolves #5972 
If a prompt was used to run a playground experiment, the prompt name will be included in the experiment name:
`prompt:{prompt_name}-playground-experiment`
=> feat: Name experiments after prompts

app/src/pages/prompts/PromptsTable.tsx
Stops propagation on the link button so that the onClick handler on the row doesn't fire and take over.
=> fix: stop propagation on playground button

js/packages/phoenix-client/examples/apply_prompt_vercel.ts, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/prompts/sdks/constants.ts, js/packages/phoenix-client/src/prompts/sdks/toAI.ts, js/packages/phoenix-client/src/prompts/sdks/toSDK.ts, js/packages/phoenix-client/src/prompts/sdks/types.ts, js/packages/phoenix-client/src/schemas/llm/messagePartSchemas.ts, js/packages/phoenix-client/src/schemas/llm/messageSchemas.ts, js/packages/phoenix-client/src/schemas/llm/toolChoiceSchemas.ts, js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts, js/pnpm-lock.yaml
See that it supports tool calls, and object generation (response format)
=> feat(prompts): Add support for Vercel AI sdk to TS phoenix-client

app/src/components/generative/ToolChoiceSelector.tsx, app/src/pages/playground/PlaygroundChatTemplateFooter.tsx, app/src/pages/playground/PlaygroundTool.tsx, app/src/pages/playground/PlaygroundTools.tsx, app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/schemas/toolChoiceSchemas.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts
We were essentially normalizing tool choice as openai, while later assuming that it would be in the correct provider shape before usage / saving.
This meant tool_choice was being ignored in anthropic invocations, and could not be validated correctly into a normalized prompt version format.
Now, we perform tool choice conversions before saving, before using in completions, and when switching models.
This feels a little messy because of code sprawl, the openai assumption has been long lived in playground code.
=> feat(prompts): Denormalize tool choice in playground

app/src/pages/prompt/ChatTemplateMessageCard.tsx, app/src/pages/prompt/PromptChatMessagesCard.tsx, app/src/pages/prompt/PromptModelConfigurationCard.tsx
Sometimes prompts and messages can get really long. This makes it easier to get to the bottom.
=> fix(prompts): make prompts and configuration collapsible

app/schema.graphql, app/src/pages/playground/ModelSupportedParamsFetcher.tsx, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts, app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts, app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts, app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts, app/src/pages/prompt/__generated__/PromptLLM__main.graphql.ts, app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts, app/src/store/playground/playgroundStore.tsx, app/src/store/playground/types.ts, src/phoenix/server/api/input_types/PromptVersionInput.py, src/phoenix/server/api/types/PromptVersion.py
If you saved an azure openai provider prompt, and then tried to load it back into playground, it would load as "openai" and you would lose your endpoint, and base url settings.
Now we properly carry over azure_openai, and we will restore any saved azure (or openai) specific settings when loading prompt into playground
Resolves #6304
=> fix(prompts): Restore azure openai params from prompt into playground

src/phoenix/db/engines.py
related to #6296
https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#prepared-statement-cache
=> fix: allow `prepared_statement_cache_size` for asyncpg

app/schema.graphql, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts, app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts, app/src/pages/playground/__tests__/fixtures.ts, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts, app/src/pages/prompt/promptCodeSnippets.tsx, app/src/schemas/messageSchemas.ts, app/src/schemas/toolCallSchemas.ts, app/src/store/playground/types.ts, src/phoenix/server/api/input_types/PromptVersionInput.py
Additionally fixes the openai code snippet on the prompt page. The playground does not require you to stringify tool call arguments, but openai sdk does...
Resolves #6313
=> fix(prompts): Save tool calls from playground message into prompt

app/src/pages/playground/ModelConfigButton.tsx, app/src/pages/playground/ModelProviderPicker.tsx
=> feat(prompts): use generative provider icon

app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx, app/src/pages/playground/playgroundUtils.ts, app/src/pages/prompt/PromptPlaygroundPage.tsx, app/src/pages/prompt/promptPlaygroundLoader.tsx
resolves #6369
This makes it so that the template when loaded dictates the playground template language at launch.
This uncovered https://github.com/Arize-ai/phoenix/issues/6374 which will be addressed separately.
=> fix(prompts): load f-string / none template format in playground from template

js/.changeset/tasty-maps-remember.md, js/packages/phoenix-client/README.md, js/packages/phoenix-client/examples/create_prompt_openai.ts, js/packages/phoenix-client/src/prompts/createPrompt.ts, js/packages/phoenix-client/src/prompts/index.ts, js/packages/phoenix-client/src/types/prompts.ts, js/packages/phoenix-client/src/utils/formatPromptMessages.ts, js/packages/phoenix-client/test/prompts/createPrompt.test.ts, js/packages/phoenix-client/test/utils/formatPromptMessages.test.ts
Adds support for prompt version creation from the typescript client
```typescript
import { createPrompt, promptVersion } from "@arizeai/phoenix-client";
const version = createPrompt({
name: "test-prompt",
description: "test-description",
version: promptVersion({
description: "version description here",
modelProvider: "OPENAI",
modelName: "gpt-3.5-turbo",
template: [
{
role: "user",
content: "{{ question }}",
},
],
invocationParameters: {
temperature: 0.8,
},
}),
});
```
=> feat(prompts): client prompt creation

scripts/testing/send_spans.py
Simply adds register to the top level of send_spans so the exporter gets configured
=> chore: add register to send_spans

src/phoenix/config.py, src/phoenix/server/api/helpers/playground_clients.py, src/phoenix/server/api/types/GenerativeProvider.py
This assumes that leading and trailing whitespace characters are inadvertent.
=> fix: strip leading and trailing whitespace characters from environment variables

app/src/schemas/toolSchemas.ts
This formerly invalid tool schema, is now valid and selectable in the tool choice list.
Resolves #6413
=> fix(prompts): Make tool schema properties field optional

app/src/pages/playground/PlaygroundChatTemplate.tsx, app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts
A span carrying tool results of every valid json type now parses all values correctly
Resolves #6429
=> fix(prompts): Parse tool result json correctly

js/.changeset/plenty-camels-end.md, js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb, js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb, js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb, js/packages/phoenix-client/src/prompts/sdks/toAI.ts, js/packages/phoenix-client/src/schemas/llm/constants.ts, js/packages/phoenix-client/src/schemas/llm/converters.ts, js/packages/phoenix-client/src/schemas/llm/openai/converters.ts, js/packages/phoenix-client/src/schemas/llm/types.ts, js/packages/phoenix-client/src/schemas/llm/utils.ts, js/packages/phoenix-client/src/schemas/llm/vercel/toolSchemas.ts
When updating the notebooks to use the npm import of phoenix-client, I discovered a bug where we were accidentally depending on the vercel ai package at runtime for a small util.
Pulled that out so that we don't depend on vercel at runtime. The old notebook imports must have installed all deps, not just normal dependencies
=> fix(client): Remove runtime dependency on vercel ai

src/phoenix/config.py, tests/unit/test_config.py
resolves #5307 
The db_connection string for postgres databases can now be configured with the following env vars
PHOENIX_POSTGRES_USER
PHOENIX_POSTGRES_PASSWORD
PHOENIX_POSTGRES_DB
PHOENIX_POSTGRES_PORT
PHOENIX_POSTGRES_HOST
=> feat: Allow configuration of postgres username/password/db/host using standard env vars

app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
resolves #6480 
When streaming is enabled, the table in the background can keep refetching and causing cache invalidation issues. This PR pauses the streaming state when the tables are no longer active in view.
=> feat(performance): don't fetch new traces when the traces slideover is visible

js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
partially related to #6500
Adds prompt creation to the notebook for a fully encapsulated example.
=> docs(prompts): add prompt create to deno notebook

.github/workflows/typescript-packages-publish.yml, .gitignore, js/package.json, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/client.ts, js/packages/phoenix-client/src/experiments/runExperiment.ts, js/packages/phoenix-client/src/prompts/constants.ts, js/packages/phoenix-client/src/prompts/createPrompt.ts, js/packages/phoenix-client/src/prompts/getPrompt.ts, js/packages/phoenix-client/src/prompts/sdks/toSDK.ts, js/packages/phoenix-client/src/utils/getDatasetBySelector.ts, js/packages/phoenix-client/src/utils/getPromptBySelector.ts, js/packages/phoenix-client/typedoc.jsonc, js/pnpm-lock.yaml
To use:
```shell
cd js/packages/phoenix-client
pnpm i
pnpm run docs # builds docs
pnpm run docs:preview # serves docs artifacts on local server
```
Includes some minor file reorganization, justifying the feat tag
https://github.com/user-attachments/assets/d5c89140-5139-49a9-9cf4-10aec014348d
=> feat(client): typedoc docs gen for phoenix-client

js/.changeset/brown-months-shout.md, js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py, packages/phoenix-client/tests/canary/sdk/openai/test_chat.py, schemas/openapi.json, src/phoenix/server/api/helpers/prompts/models.py, tests/integration/prompts/test_prompts.py
Pydantic was not allowing o1 models to be saved as prompts, due to max_completion_params not being defined in invocation param validation
Resolves #6366
=> fix: Add max_completion_tokens to openai param validation

app/schema.graphql, src/phoenix/server/api/queries.py, tests/__generated__/graphql/__init__.py, tests/unit/server/api/test_queries.py
Notes:
- SQLite freelist pages are excluded. So the total is not the size on disk, but the sum of existing pages. The size on disk includes pages that are deleted and can be re-used later. See [here](https://www.sqlite.org/dbstat.html) for more info.
screenshot below is using postgres v12
=> feat: graphql query to get byte size of each db table

pyproject.toml
At this point, we no longer use `hatch` for its environments and scripts, only for building and publishing the package.
=> ci: remove hatch environments

app/package.json, app/pnpm-lock.yaml, app/src/components/code/JSONBlock.tsx, app/src/components/code/JSONEditor.tsx
There seems to be times where we load two versions of codemirror. This reduces the number of codemirror dependancies to try to unify. I don't think this is the only cause of issues with codemirror dependancies but it solves a part of it.
=> chore(ui): remove codemirror deps

app/package.json, app/pnpm-lock.yaml, app/src/pages/trace/TraceDetails.tsx
this introduces the idea of pixel based re-sizing, which might be necessary when we want to set a constraint on the trace details views. Still unsure but good to upgrade none the less.
=> chore(ui): upgrade resizable panels

app/package.json, app/pnpm-lock.yaml, app/src/components/layout/Flex.tsx, app/src/components/trace/LatencyText.tsx, app/src/components/trace/TokenCount.tsx, app/src/components/trace/TraceTree.tsx, app/src/pages/trace/TraceDetails.tsx
resolves #6593
Makes it easier to really compact the trace tree when you say are needing more screen real-estate for annotations
https://github.com/user-attachments/assets/9e6ade8b-7364-408a-8bc1-efe37dff828a
=> feat(traces): make trace tree more readable on smaller sizes

app/src/components/button/Button.tsx, app/src/components/button/index.tsx, app/src/components/button/styles.tsx, app/src/components/toggleButtonGroup/ToggleButton.tsx, app/src/components/toggleButtonGroup/ToggleButtonGroup.tsx, app/src/contexts/SizeContext.tsx, app/src/contexts/index.tsx, app/stories/Gallery.stories.tsx, app/stories/ToggleButton.stories.tsx
resolves #6589 
Makes it so that the toggle button can be rendered in isolation.
=> feat(components): ToggleButton

app/src/pages/playground/AnthropicReasoningConfigField.tsx, app/src/pages/playground/InvocationParametersFormFields.tsx
Tested the following:
- Save and load from prompts
- Save and load from default model config
- Add/remove budget tokens value
- enable/disable thinking
Keep in mind that default model config is not applied over a saved prompt, so don't expect to see your default thinking config appear in a prompt unless you save it in that prompt
=> feat: Specialized UI for thinking budget parameter

app/src/pages/playground/AnthropicReasoningConfigField.tsx, app/src/pages/playground/fetchPlaygroundPrompt.ts, app/src/pages/playground/playgroundUtils.ts, src/phoenix/server/api/helpers/playground_clients.py
This only applies to outgoing requests containing invocation parameters, not to parameters saved in the playground store, as the latter process involves additional complications which we've decided to address at a later time.
=> fix: apply constraints related to extended thinking on anthropic invocation parameters

app/src/components/project/PythonProjectGuide.tsx
=> fix(onboarding): add space between link and text in new project guide

pyproject.toml, requirements/ci.txt, src/phoenix/server/api/helpers/playground_clients.py
resolves #6063
see e.g. 
- https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints#microsoft-entra-id-authentication
- https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python
=> fix: make azure api key optional for playground

app/src/pages/project/TracesTable.tsx, app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/project/__generated__/TracesTable_spans.graphql.ts, app/src/pages/trace/TraceDetails.tsx, app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
related to #6794 
This ultimately doesn't solve the problem that agent workflows use errors to change control flow.
It only makes there be less red
=> fix(langgraph): don't aggregate status

app/src/pages/projects/ProjectActionMenu.tsx
We get repeated questions on what "Clear Data" does vs "Remove Data". This changes the language to be "Clear All Data" to be abundantly clear
=> fix: update clear data button text

src/phoenix/server/api/queries.py, tests/unit/server/api/test_queries.py
only show the total without grouping by table names
=> fix: temporarily stop showing table names in db stats for SQLite

app/src/components/datetime/TimeRangeSelector.tsx
resolves #6861 
Closes the time range selector when you click the same value.
=> fix(UI): close time selector on duplicate selection

src/phoenix/trace/dsl/helpers.py
Add timeout parameter to helper query functions - `get_retrieved_documents` and `get_qa_with_reference`. This update allows developers to adjust the `timeout` value, extending beyond the default 5 seconds for long-running queries. If the `timeout` parameter is not provided, the previous default behavior of 5 seconds remains unchanged.
=> feat: Add timeout option to helper query functions

app/src/components/toggleButtonGroup/ToggleButton.tsx
=> fix: Prevent toggle button text from wrapping

app/src/pages/project/ProjectFilterConfigButton.tsx, app/src/pages/project/ProjectPage.tsx, app/src/pages/project/ProjectPageQueries.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts, app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts, app/src/pages/project/__generated__/SpansTable_spans.graphql.ts, app/src/store/projectStore.ts
resolve #6915 
Adds a toggle to enable treating orphan spans as root.
=> fix(perf): add a toggle to treat orphans as root

app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/store/preferencesStore.tsx
This is a pre-cursor to a larger refactor of having annotations show up directly next to the content.
=> refactor(ui): change the span aside to be a resizable panel

app/src/pages/project/StreamToggle.tsx
resolves #6935
This disables streaming when there's a dialog open since it's not necessary to keep polling the backend for more traces.
=> fix(perf): disable streaming when dialog is open

src/phoenix/server/api/types/Project.py, tests/unit/server/api/types/test_Project.py
| Query #    | Median (ms)  | Ratio    | P90 (ms)   | N Runs   | Rows Returned |
|------------|-------------:|---------:|-----------:|---------:|--------------:|
| Query 1    |       1115.3 |      1.6 |     1162.3 |       20 |          1000 |
| Query 2    |        684.5 |      1.0 |      789.5 |       20 |          1000 |
traces: 76,551
spans: 4,457,957
disk: 80 GiB
```sql
-- Query 1
SELECT spans.id, spans.start_time AS "startTime_span_sort_column"
FROM spans
JOIN traces ON traces.id = spans.trace_rowid
WHERE traces.project_rowid = 1
AND spans.start_time >= (NOW() - INTERVAL '2400 hours')
AND NOT (EXISTS (SELECT 1
FROM (SELECT spans.span_id AS span_id
FROM spans) AS parent_spans
WHERE spans.parent_id = parent_spans.span_id))
ORDER BY "startTime_span_sort_column" DESC NULLS LAST, spans.id …
```
=> fix: use CTE for orphan span query

app/src/pages/project/StreamToggle.tsx
- route tails had slash while tail check logic did not so streaming could never enable
- switch was disabled completely whenever streaming was turned off so you could not turn it back on
=> fix: Re-enable project stream toggle

app/src/pages/project/SessionsTable.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/StreamToggle.tsx, app/src/pages/project/TracesTable.tsx
Turns out the loaders were not responsible for this performance hit, we just needed to let relay fall back to the store for table results if the data is fresh enough. Streaming will still load in new results as expected.
In the video note that when I open and close the slide over, no additional SpanTableQuery is made. It will be made if relay decides that the data is stale.
https://github.com/user-attachments/assets/27363cda-4c1d-4e6b-b9b5-ed5ab257f0e9
Additionally backports a fix from #6969 that should have targeted main
Resolves #6907
=> perf: Cache project table results when toggling details slide over

DEVELOPMENT.md
docs: mention symlink step (tox run -e add_symlinks) in DEVELOPMENT.md
This PR updates `DEVELOPMENT.md` to include a missing but important step for contributors working from source: linking local submodules via `tox run -e add_symlinks`.
Without this step, contributors may encounter import errors such as:
`ModuleNotFoundError: No module named 'phoenix.evals'`
This is because several parts of Phoenix—like `phoenix.evals`, `phoenix.otel`, and `phoenix.client`—live in the `packages/` directory and are excluded from the standard build and install process.
Running:
```bash
tox run -e add_symlinks
```
creates symbolic links to make these modules available for import in the local development environment. This behavior is defined in the tox.ini file but not documented, which may confuse new …
=> docs: mention symlink step (tox run -e add_symlinks) in DEVELOPMENT.md

pyproject.toml
error stack trace when aiohttp is not present
```shell
phoenix-1  | GraphQL request:4:3
phoenix-1  | 3 | ) {
phoenix-1  | 4 |   chatCompletion(input: $input) {
phoenix-1  |   |   ^
phoenix-1  | 5 |     __typename
phoenix-1  | Traceback (most recent call last):
phoenix-1  |   File "/phoenix/env/azure/core/pipeline/transport/__init__.py", line 90, in __getattr__
phoenix-1  |     from ._aiohttp import AioHttpTransport
phoenix-1  |   File "/phoenix/env/azure/core/pipeline/transport/_aiohttp.py", line 45, in <module>
phoenix-1  |     import aiohttp
phoenix-1  | ModuleNotFoundError: No module named 'aiohttp'
phoenix-1  |
phoenix-1  | The above exception was the direct cause of the following exception:
phoenix-1  |
phoenix-1  | Traceback (most recent call last):
phoenix-1  |   File …
```
=> fix: add aiohttp to container for azure-identity

app/src/pages/experiment/ExperimentCompareTable.tsx
Just needed a container around the table segment of the page
https://github.com/user-attachments/assets/91da0352-9b4e-4d6c-9b35-2ec65ae3fb48
https://github.com/user-attachments/assets/34200be6-0313-4f26-8116-4ad4933af0ed
Resolves #6986
=> fix: Allow scrolling the entire experiment compare table

src/phoenix/session/session.py
Fixes #6192
This PR improves the error message when users attempt to use PostgreSQL with `launch_app()`. The new message:
1. Indicates that PostgreSQL was detected in the environment configuration
2. Specifies which environment variables might be causing this (PHOENIX_SQL_DATABASE_URL or PHOENIX_POSTGRES_*)
3. Explains that `launch_app()` is designed for SQLite in notebook environments
4. Suggests using `phoenix serve` as the correct alternative
5. Reminds users to install PostgreSQL extras
Users attempting to use PostgreSQL with `launch_app()` were receiving cryptic errors like "relation 'user_roles' does not exist" when using custom PostgreSQL schemas. This happens because `launch_app()` is not designed to work with PostgreSQL backends.
As noted by @mikeldking in the issue:
> …
=> fix(session): improve PostgreSQL error message in launch_app

js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py, packages/phoenix-client/src/phoenix/client/resources/projects/__init__.py, packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py, packages/phoenix-client/src/phoenix/client/utils/encode_path_param.py, schemas/openapi.json, src/phoenix/config.py, src/phoenix/db/helpers.py, src/phoenix/server/api/queries.py, src/phoenix/server/api/routers/v1/projects.py, src/phoenix/server/api/subscriptions.py, tests/integration/projects/test_projects.py, tests/unit/server/api/routers/v1/test_projects.py
resolves #7084
This PR enhances the project management API by introducing support for identifying projects through both IDs and names, making the API more flexible and user-friendly. The changes include simplifying the project creation request body structure, restricting project updates to description changes only, and adding validation for project names. The codebase has been improved with better error handling for invalid identifiers and special characters, while maintaining backward compatibility. Comprehensive test coverage has been added to ensure reliability, including tests for special characters, Unicode support, and both ID and name-based operations.
- Added support for identifying projects by both ID and hex-encoded name
- Introduced a new `_get_project_by_identifier` helper …
=> feat: allow project name as identifier in REST path

app/src/components/auth/AuthGuard.tsx, app/src/pages/settings/SettingsGeneralPage.tsx
Tested under the following conditions:
- Auth enabled, user is admin: visible
- Auth enabled, user is _not_ admin: invisible
- Auth disabled: visible
We should expand this to the backend as well if it does not already check for admin membership or auth disabled.
Resolves #6959
=> feat(retention): Add capability based access to retention policy

app/src/pages/project/SessionsTable.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
resolves #7103
The caching was introduced to eliminate reloads on navigations but it actually makes the payload never re-load.
=> fix: restore streaming

app/src/components/disclosure/Disclosure.tsx, app/src/openInference/tracing/types.ts, app/src/pages/trace/SpanDetails.tsx
This PR displays tool Ids, both call and result, in span details.
They are placed within disclosure headers, and can by copy/pasted via a copy button that only appears on hover.
Supports multiple tool calls
Supports tool results
Resolves #6427
=> feat: Display tool call and tool result Ids in span details

app/src/Routes.tsx
Users frequently try to access Phoenix through `/v1/traces` in their browser (which is the OpenTelemetry trace collector endpoint) and submit GitHub issues when they see a blank page or error. This PR redirects such requests to the root path to prevent confusion.
The OpenTelemetry collector still works since it uses POST requests, while this redirect only affects GET requests.
=> fix: redirect GET v1/* to home

packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
For `Nova` models, additionalModelRequestFields should be structured as the following:
```
additionalModelRequestFields = {
"inferenceConfig": {
"topK": 20
}
}
```
But in other models, should be structured like so:
`additionalModelRequestFields= {"top_k": 20}`
=> fix: Formatting of additionalModelRequestFields based on model

packages/phoenix-evals/src/phoenix/evals/models/openai.py
Found that azure models do not support max_completion_tokens yet so we are going to use max_tokens until available. We made an exception for o1 and o3 models.
Customer Issue: https://github.com/Arize-ai/arize/issues/43199
Before:
After:
=> fix: azure max tokens update

app/package.json, app/pnpm-lock.yaml, app/src/RelayEnvironment.ts, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundStreamToggle.tsx, app/src/window.d.ts, pyproject.toml, src/phoenix/config.py, src/phoenix/server/app.py, src/phoenix/server/main.py, src/phoenix/server/middleware/gzip.py, src/phoenix/services.py, src/phoenix/session/session.py, tests/unit/conftest.py
This PR removes the WebSocket-based GraphQL subscription implementation and replaces it with [multipart subscription](https://strawberry.rocks/docs/general/multipart-subscriptions).
- Removed WebSocket-related code and configuration:
- Removed `graphql-ws` dependency
- Removed WebSocket server setup and handlers
- Removed WebSocket configuration from environment variables
- Removed WebSocket-related UI configuration
- Added Apollo Client for GraphQL operations:
- Added `@apollo/client` dependency
- Updated Relay environment to use Apollo's subscription transport
- Special GZip compression handling:
- Prevented GZip compression for multipart/mixed content types
- Replaced `graphql-ws` with Apollo Client's built-in subscription support
- Removed `PHOENIX_ENABLE_WEBSOCKETS` environment …
=> fix: remove WebSocket dependency

app/src/components/auth/AuthGuard.tsx, app/src/components/retention/ProjectTraceRetentionPolicySelect.tsx, app/src/components/retention/__generated__/ProjectTraceRetentionPolicySelectFragment.graphql.ts, app/src/contexts/ViewerContext.tsx, app/src/contexts/index.tsx, app/src/pages/project/ProjectConfigPage.tsx, app/src/pages/project/ProjectPageQueries.tsx, app/src/pages/project/ProjectRetentionPolicyCard.tsx, app/src/pages/project/__generated__/ProjectConfigPageProjectRetentionPolicyCardQuery.graphql.ts, app/src/pages/project/__generated__/ProjectConfigPage_projectRetentionPolicyCard.graphql.ts, app/src/pages/project/__generated__/ProjectPageQueriesProjectConfigQuery.graphql.ts, app/src/pages/project/__generated__/ProjectRetentionPolicyCardQuery.graphql.ts, app/src/pages/project/__generated__/ProjectRetentionPolicyCardSetProjectRetentionPolicyMutation.graphql.ts, app/src/pages/project/__generated__/ProjectRetentionPolicyCard_policy.graphql.ts, app/src/pages/project/__generated__/ProjectRetentionPolicyCard_query.graphql.ts, app/src/pages/settings/RetentionPolicyForm.tsx, app/src/utils/retentionPolicyUtils.ts
resolves #7161 
This lets admins assign the retention policy of a project in the config tab.
https://github.com/user-attachments/assets/c68d00e4-5d05-4143-b5a8-45cb814f787e
=> feat(admin): project retention policy for admins

src/phoenix/server/api/mutations/project_trace_retention_policy_mutations.py, tests/unit/server/api/mutations/test_project_trace_retention_policy_mutations.py
Add validation to prevent deletion of default trace retention policy
This PR adds validation to prevent deletion of the default project trace retention policy (ID 0) and includes a test to verify this behavior. The changes:
1. Add a check in the `delete_project_trace_retention_policy` mutation to raise a BadRequest error if attempting to delete the default policy
2. Add a new test method `test_cannot_delete_default_policy` that verifies the validation works correctly
This ensures the default policy remains available as a fallback for projects that don't have a specific retention policy assigned.
=> fix: forbid deletion of default policy

src/phoenix/server/api/mutations/project_trace_retention_policy_mutations.py, tests/unit/server/api/mutations/test_project_trace_retention_policy_mutations.py
Prevent renaming of default project trace retention policy
This PR adds a safeguard to prevent renaming the default project trace retention policy. It includes:
- Added validation in the patch mutation to block name changes for the default policy
- Added a new test case to verify this behavior
=> fix: forbid renaming of default policy

app/src/components/trace/TraceTree.tsx
resolves #7055 
This makes it so that when the selectedSpanID is set, the UI at least makes sure that this span is scrolled into view so it's obvious where it is.
=> feat(tracing): scroll selected span into view when navigating to a trace

app/src/pages/settings/AnnotationConfigTable.tsx
=> fix(annotations): Truncate long category names in annotation config table

src/phoenix/db/types/annotation_configs.py, src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py, tests/unit/db/types/test_annotation_configs.py, tests/unit/server/api/mutations/test_span_annotation_mutations.py, tests/unit/server/api/types/test_SpanAnnotation.py, tests/unit/server/api/types/test_TraceAnnotation.py
Ensures that categorical annotation config values are non-empty and have unique labels. This is enforced at the level of DB types, so will protect both the REST and GraphQL APIs.
resolves #7234
=> fix(annotations): validate values for categorical annotation config

app/schema.graphql, app/src/pages/settings/SettingsAnnotationsPage.tsx, app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigsMutation.graphql.ts, src/phoenix/server/api/mutations/annotation_config_mutations.py
Allow batch deletions of annotation configs from the GraphQL perspective.
resolves #7224
=> refactor(annotations): allow batch deletion of annotation configs

app/schema.graphql, src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py, src/phoenix/server/api/mutations/span_annotations_mutations.py
Adds a mutation for creating span comments (with unique identifier) that only requires the span id and comment as an input payload
resolves #7261
=> feat: Add span comment mutation

app/src/pages/settings/GlobalRetentionPolicyCard.tsx
This adds a small UI tweak so that if an admin user wants to configure other policies they can quickly link to it on the bottom of the card
=> feat(admin): add a link to retention policies"

src/phoenix/db/migrations/versions/8a3764fe7f1a_change_jsonb_to_json_for_prompts.py, src/phoenix/db/migrations/versions/bb8139330879_create_project_trace_retention_policies_table.py, src/phoenix/db/models.py, tests/integration/db_migrations/test_change_jsonb_to_json_for_prompts.py, tests/integration/db_migrations/test_up_and_down_migrations.py
resolves #7254 
This PR changes the column type from JSONB to JSON for the `tools` and `response_format` columns in the `prompt_versions` table. This change addresses a core issue where JSONB was automatically reordering object keys alphabetically, which could cause problems when key order needs to be preserved.
The change:
- Adds a new migration to convert JSONB columns to JSON type
- Updates SQLAlchemy model definitions to use JSON instead of JSONB
- Includes comprehensive tests to verify the migration works correctly in both PostgreSQL and SQLite
- Maintains data integrity during both upgrade and downgrade operations
The switch to JSON type ensures that object key ordering is preserved exactly as specified, while maintaining full functionality across different database backends.
=> fix: db migrate from JSONB to JSON

src/phoenix/server/main.py
Right now, if you run phoenix in a terminal and stop it (via ctrl-c) you get a scary message and non-zero exit status (130) like this:
```
File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/phoenix/env/phoenix/server/main.py", line 436, in <module>
main()
File "/phoenix/env/phoenix/server/main.py", line 424, in main
server.run()
File …
```
=> feat: gracefully handle ctrl-c

app/src/components/table/styles.ts, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/project/SessionsTable.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx
I did a spot check on all tables that had the previous `height: 1` implementation, and they still look good on all 3 browsers.
Resolves #7306
=> fix: Improve browser compatibility for Table sizing features

app/schema.graphql, src/phoenix/server/api/queries.py, src/phoenix/server/api/types/Functionality.py
This query seems to be causing occasional issues when the home page is left idle. Not sure of the root cause, but either way, the part that actually hits the DB is legacy and no longer in use.
resolves #7337
=> fix: simplify homeLoaderQuery

src/phoenix/server/authorization.py, tests/unit/server/test_authorization.py
adds fastapi authorization primatives
To restrict any route to admin/system users, add Depends(require_admin) to the route’s dependencies.
Example:
```python
@router.post("/dangerous-thing", dependencies=[Depends(require_admin)])
async def dangerous_thing(...):
...
```
=> feat(api): add RBAC primitives for fastAPI / REST

app/src/components/annotation/AnnotationSummaryPopover.tsx, app/src/components/trace/SpanAnnotationInput.tsx
=> fix(annotations): Show 0 scores in summary labels

src/phoenix/config.py, src/phoenix/server/grpc_server.py, src/phoenix/server/main.py, tests/unit/test_config.py
resolves #7362 
This PR introduces separate controls for enabling TLS on HTTP and gRPC servers while maintaining a single TLS configuration. Previously, TLS was controlled by a single environment variable (`PHOENIX_TLS_ENABLED`), which enabled TLS for both servers simultaneously. Now, you can use the same TLS certificates and configuration but choose which servers to enable it for.
- Added new environment variables to control TLS enablement:
- `PHOENIX_TLS_ENABLED_FOR_HTTP`: Enables TLS for HTTP server
- `PHOENIX_TLS_ENABLED_FOR_GRPC`: Enables TLS for gRPC server
- Both new variables take precedence over the existing `PHOENIX_TLS_ENABLED` when set
- The underlying TLS configuration (certificates, keys, etc.) remains unified and shared
- Updated server configuration logic to handle …
=> feat: separate TLS enabled flags for HTTP and gRPC

app/src/pages/settings/AnnotationConfigDialog.tsx
This aligns the buttons to use the leadingVisual primitive rather than just using the icon as a child. Renders more consistently.
=> refactor: use leading visual for icons

app/src/components/FocusHotkey.tsx, app/src/components/KeyboardToken.tsx, app/src/components/content/Keyboard.tsx, app/src/components/index.tsx, app/src/components/table/styles.ts, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/constants/searchParams.ts, app/src/pages/example/ExampleDetailsDialog.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/playground/Playground.tsx, app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx, app/src/pages/playground/RunMetadataFooter.tsx, app/src/pages/playground/SpanPlaygroundPage.tsx, app/src/pages/project/ProjectSpansPage.tsx, app/src/pages/project/ProjectTracesPage.tsx, app/src/pages/project/SpansTable.tsx, app/src/pages/project/TracesTable.tsx, app/src/pages/trace/SessionDetailsTraceList.tsx, app/src/pages/trace/SpanAside.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/pages/trace/SpanNotesEditor.tsx, app/src/pages/trace/TraceDetails.tsx, app/src/pages/trace/TraceDetailsPaginator.tsx, app/src/pages/trace/TracePage.tsx, app/src/pages/trace/TracePaginationContext.tsx
https://github.com/user-attachments/assets/eb59405d-f684-46dd-b4d5-55850ade060f
Adds pagination to trace details, as well as a bunch of hotkeys for jumping around the details dialog:
- While no inputs are focused
- `j` change the dialog / url to the next trace/span
- `k` change the dialog / url to the previous trace/span
- `e` jump to the first span annotations editor input
- `n` jump to the span notes message bar
- While annotation span aside is closed
- `e` open the span annotations aside
Resolves #6485
=> feat(annotations): Paginate between traces on spans table or traces table

tests/integration/client/test_annotations.py
This PR adds comprehensive test coverage for zero score handling in span annotations. The new tests verify that:
- Zero scores are properly recorded and not treated as falsey values
- Both synchronous and asynchronous clients handle zero scores correctly
- Both admin and member users can create annotations with zero scores
- Optional fields (label, explanation) are properly stored as None when omitted
- Annotations can be retrieved and verified by name
The test suite includes:
- Direct annotation creation tests
- DataFrame-based annotation creation tests
- GraphQL API retrieval verification
- Coverage for both client types (sync/async) and user types (admin/member)
This test coverage helps ensure the robustness of the annotation system's handling of zero scores.
=> test: ensure 0 score for annotation is not treated as falsey

app/src/components/button/ExternalLinkButton.tsx, app/src/components/button/index.tsx, app/src/components/icon/Icons.tsx, app/src/components/index.tsx, app/src/components/table/TableEmpty.tsx, app/src/components/table/TableEmptyWrap.tsx, app/src/components/table/index.tsx, app/src/pages/datasets/DatasetsEmpty.tsx, app/src/pages/datasets/DatasetsTable.tsx
adds a tutorial and docs link to the dataset empty page.
=> feat(onboarding): datasets empty

app/src/RelayEnvironment.ts, app/src/components/annotation/AnnotationSummaryGroup.tsx, app/src/components/annotation/__generated__/AnnotationSummaryGroup.graphql.ts, app/src/components/trace/SpanAnnotationsEditor.tsx, app/src/components/trace/__generated__/SpanAnnotationsEditorCreateAnnotationMutation.graphql.ts, app/src/components/trace/__generated__/SpanAnnotationsEditorDeleteAnnotationMutation.graphql.ts, app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts, app/src/pages/project/AnnotationSummary.tsx, app/src/pages/project/__generated__/AnnotationSummaryQuery.graphql.ts, app/src/pages/project/__generated__/AnnotationSummaryValueFragment.graphql.ts, app/src/pages/project/__generated__/AnnotationSummaryValueQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts, app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts, app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts, app/src/pages/project/__generated__/TracesTableQuery.graphql.ts, app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts, app/src/pages/trace/__generated__/TraceHeaderRootSpanAnnotationsQuery.graphql.ts
If an annotation summary pie chart is displayed, and there is a categorical annotation config related to that annotation by name, the colors shown in the chart will always be the same based on the label order within the config. 
If the annotation config has scores with each category, they will be sorted based on score + optimization direction first. If not, it will fallback to server provided label order, but either way it will be stable until the config is changed again
Additionally fixes some query issues on the relay side:
- Reload project level annotation summaries when annotations are edited
- Prevent crashes from relay query cache emptying out project ids, by re-querying project id in mutation queries.
Resolves #7335
=> feat: Stabilize categorical annotation summary pie chart colors

app/src/pages/playground/__tests__/playgroundUtils.test.ts, app/src/pages/playground/playgroundUtils.ts, app/src/pages/playground/schemas.ts
This prevents scenarios where multi-part instrumented messages can't be replayed in the playground despite just having text contents as multi-part.
This is just the first small step towards supporting multi-part content that adds a little bit more value to playground
Resolves #7400
=> feat: Simple support for message_contents span content in playground

app/src/constants/generativeConstants.ts, app/src/hooks/useChatMessageStyles.ts, app/src/pages/playground/constants.tsx, app/src/pages/playground/playgroundUtils.ts
Gemini uses role of "model" for "ai" messages. This normalizes this and makes the translation map part of constants for re-use.
=> fix: normalize gemini roles

app/src/pages/project/TracesTable.tsx
When viewing broken traces, with parentage not in phoenix yet, this would cause the page to crash.
This doesn't happen anymore. Not sure what conditions in the db exactly trigger this, but my current local environment has a mess of traces with weird parentage so might as well fix it just in case
=> fix(annotations): Safeguard against null spanAnnotationSummaries

packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py, tutorials/human_feedback/chatbot_with_human_feedback.ipynb
- Adds `project_identifier` argument to `get_spans_dataframe`
- Breaks out `result` into `result.score` `result.label` and `result.explanation` columns
- Renames the `name` column in the annotations dataframe to `annotation_name` for easier joining
=> feat: Improve client semantics

app/src/pages/project/MetadataTooltip.tsx
fixes #7345 
This pull request updates the `makeMetadataTooltipFilterCondition` function in `MetadataTooltip.tsx` to enhance its handling of nested keys in metadata. The change ensures that keys with dot notation are correctly converted to bracket notation for Python compatibility.
* Updated the `makeMetadataTooltipFilterCondition` function to split keys by dots and convert them into bracket notation, enabling support for nested metadata keys. Numeric segments are wrapped in square brackets, while other segments are wrapped in single quotes.
=> fix: quick metadata filters for nested fields

src/phoenix/server/api/mutations/span_annotations_mutations.py, src/phoenix/server/api/mutations/trace_annotations_mutations.py
=> fix(annotations): ensure user identifiers are stable

app/src/components/KeyboardToken.tsx, app/stories/KeyboardToken.stories.tsx
This styles keyboard hotkeys to look a bit more skeuomorphic like https://dribbble.com/shots/14161157-Shortcuts
It also uppercases the character to be consistent with other hotkeys.
=> feat: style keyboard tokens to look more like keys

app/src/components/icon/Icons.tsx, app/src/components/layout/Group.tsx, app/src/components/layout/index.tsx, app/src/pages/trace/TraceDetailsPaginator.tsx, app/stories/Group.stories.tsx
Uses the `Group` component to display buttons as a group rather than using toggle button.
=> feat(ui): Group component with refactored pagination buttons

app/src/components/annotation/AnnotationSummaryGroup.tsx, app/src/components/annotation/FreeformAnnotationInput.tsx, app/src/components/trace/SpanAnnotationInput.tsx
One minor thing is that freeform annotations still appear in the top level project annotations summaries but they do not appear in the table rows
=> fix(annotations): Write to annotation explanation instead of label for freeform annotations

src/phoenix/trace/dsl/filter.py, tests/unit/trace/dsl/test_filter.py, tests/unit/trace/dsl/test_query.py
Enables querying for annotation/eval existence:
```
query = SpanQuery().where("annotations['user_feedback']")
spans = client.spans.get_spans_dataframe(query=query, project_identifier="default")
```
=> feat: Update spans dsl to search for annotation existence

src/phoenix/server/retention.py, tests/unit/server/test_retention.py
Fix trace retention sweeper crash by replacing joinedload with selectinload
The sweeper was crashing due to using `joinedload` when querying retention policies. This PR:
- Fixes the crash by replacing `joinedload` with `selectinload` for more reliable collection loading
- Adds comprehensive tests to verify the fix and prevent future regressions
- Tests cover both default and custom policies, multiple sweeps, and proper trace retention
=> fix: replace joinedload with selectinload for retention policy query

packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py, packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py, tutorials/human_feedback/chatbot_with_human_feedback.ipynb
These changes were clobbered in a previous rebase
Previously approved here: https://github.com/Arize-ai/phoenix/pull/7399
```
from phoenix.client import Client
from phoenix.client.types.spans import SpanQuery
client = Client()
query = SpanQuery().where("annotations['correctness']")
spans = client.spans.get_spans_dataframe(query=query, project_identifier="playground")
annotations = client.spans.get_span_annotations_dataframe(spans_dataframe=spans, project_identifier="playground")
annotations.join(spans, how="left")
```
=> fix: Improve client semantics 2

.github/workflows/clean_up_caches.yml, .github/workflows/collect-customer-issues.yaml, .github/workflows/openapi-schema.yaml, .github/workflows/playwright.yaml, .github/workflows/python-CI.yml, .github/workflows/python-cron.yml, .github/workflows/typescript-CI.yml, .github/workflows/typescript-packages-CI.yml, .github/workflows/typescript-packages-publish.yml
Potential fix for [https://github.com/Arize-ai/phoenix/security/code-scanning/42](https://github.com/Arize-ai/phoenix/security/code-scanning/42)
To fix the issue, we will add a `permissions` block at the root of the workflow to apply minimal permissions to all jobs. Since the workflow primarily involves running tests and does not require write access, we will set `contents: read` as the default permission. This ensures that the `GITHUB_TOKEN` has only the necessary permissions to read repository contents.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> fix(security): fix for code scanning alert no. 42: Workflow does not contain permissions

app/README.md
In order to run `/app` UI in development mode  you must fist run `pnpm run build` otherwise `pnpm run dev` will not serve the UI correctly. Given the unconventional nature of this flow it needs to be added to the docs.
This may be because static assets don't exist and or GraphQL queries are not compiled.
This is unconventional as normally react/node applications dev commands normally handles the compilation steps automatically.
=> fix: Add pre requisite build to `/app` develop docs

packages/phoenix-client/src/phoenix/client/utils/template_formatters.py, packages/phoenix-client/tests/utils/test_template_formatters.py
fixes #7405 
This pull request refactors the `_format` function in `template_formatters.py` to improve code readability and maintainability by simplifying the usage of the `re.sub` function.
Code readability and maintainability improvements:
* [`packages/phoenix-client/src/phoenix/client/utils/template_formatters.py`](diffhunk://#diff-a81d308fcb723dd36d645305ed1500d95a095570509fe95705faacbe0355d9e5L124-R126): Refactored the `_format` function by separating the regex pattern and replacement logic into distinct variables (`pattern` and `replacement`). Additionally, replaced the `repl` parameter with a lambda function to enhance clarity and flexibility.
=> fix: formatting issues incase of escaped characters

tutorials/mcp/tracing_between_mcp_client_and_server/client.py
Most calls will exceed the default timeout of 5s therefore this PR extends it to 30s to avoid timeout errors.
@Jgilhuly
=> fix: MCP tutorial extended timeout

internal_docs/vignettes/json-jsonb-demo/.eslintrc.cjs, internal_docs/vignettes/json-jsonb-demo/.gitignore, internal_docs/vignettes/json-jsonb-demo/.prettierrc.json, internal_docs/vignettes/json-jsonb-demo/README.md, internal_docs/vignettes/json-jsonb-demo/package.json, internal_docs/vignettes/json-jsonb-demo/pnpm-lock.yaml, internal_docs/vignettes/json-jsonb-demo/src/compare.ts, internal_docs/vignettes/json-jsonb-demo/src/config/db-config.ts, internal_docs/vignettes/json-jsonb-demo/src/index.ts, internal_docs/vignettes/json-jsonb-demo/src/performance.ts, internal_docs/vignettes/json-jsonb-demo/src/query-examples.ts, internal_docs/vignettes/json-jsonb-demo/src/services/db-service.ts, internal_docs/vignettes/json-jsonb-demo/src/types/db.types.ts, internal_docs/vignettes/json-jsonb-demo/tsconfig.json
This PR adds a comprehensive demonstration project that showcases the key differences between PostgreSQL's JSON and JSONB data types. The demo includes practical examples, performance benchmarks, and best practices for choosing between JSON and JSONB in different scenarios.
Here's a concrete example demonstrating the key ordering difference:
```
Original input order: ['QVZZCJFR', 'DAUFW', 'DXRMYF', 'SEETRJBUU', ...]
JSON output: {                | JSONB output: {
"QVZZCJFR": 8,              |   "B": 1,
"DAUFW": 5,                 |   "XT": 2,
"DXRMYF": 6,                |   "RHD": 3,
"SEETRJBUU": 9,             |   "YPSE": 4,
"YPSE": 4,                  |   "DAUFW": 5,
"DEGAZFI": 7,               |   "DXRMYF": 6,
"XT": 2,                    |   "DEGAZFI": 7,
"RHD": 3,                   | …
```
=> chore: add json vs jsonb demo scripts

app/src/components/markdown/styles.ts
fixes #7474 
This pull request introduces a small update to the `markdownCSS` styles in `app/src/components/markdown/styles.ts`. The change ensures that inline `code` elements will now wrap text appropriately.
* [`app/src/components/markdown/styles.ts`](diffhunk://#diff-26a9167d5917a9cfd3c5d54b7980b02d8164c5c3be5d3c036a781b6c5f40bec7R17-R19): Added a `text-wrap: wrap;` rule to the `code` selector within the `markdownCSS` styles.
=> fix: content wrap in markdown block

app/src/pages/trace/SpanAside.tsx
Opens panels when you press their hotkeys.
=> feat: Open span details sections when hotkeys are pressed

packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py, packages/phoenix-client/tests/client/resources/annotations/test_annotations.py
- Added support for `context.span_id` column as an alternative to `span_id` in DataFrame validation
- Added validation to prevent both `span_id` and `context.span_id` columns from being present simultaneously
- Updated error messages to be more specific about which column is causing validation issues
- Added comprehensive test cases for the new `context.span_id` functionality
- Added new test cases covering:
- Validation with `context.span_id` column
- Invalid cases (empty strings, None values, non-string values)
- Chunking functionality with `context.span_id`
- Error handling for duplicate span ID columns
=> fix: allow `context.span_id` as column name in pandas dataframe

packages/phoenix-evals/src/phoenix/evals/classify.py, packages/phoenix-evals/src/phoenix/evals/evaluators.py, packages/phoenix-evals/src/phoenix/evals/templates.py, packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
When setting `provide_explanation=True` in `llm_classify`, failing to provide a compatible label extraction function will sometimes lead to unexpected `NOT_PARSABLE` labels when trying to pull out the label from the LLM output.
This falls back to attempting to snap the entire LLM output to rails in case the default parsing function cannot split the label from the explanation (our internal convention is to delimit using `label:`
=> fix: Stabilize label extraction

.github/workflows/playwright.yaml
fixes #7601 
This pull request updates the `.github/workflows/playwright.yaml` file to refine the triggers for the workflow. Specifically, it adds path filters to ensure the workflow only runs when changes are made to specific directories.
Workflow trigger updates:
* [`.github/workflows/playwright.yaml`](diffhunk://#diff-b710b539e104e4351f3e7598f94f434b8c7aaafdba88e57b3280582c718f7b4bR8-R15): Added `paths` filters under both `push` and `pull_request` triggers to limit the workflow execution to changes within the `src/` and `app/` directories.
=> chore(ci): run Playwright tests on changes to src/ or app/ directories

js/.changeset/chatty-memes-look.md, js/packages/phoenix-client/src/experiments/runExperiment.ts, js/packages/phoenix-client/src/utils/urlUtils.ts, js/packages/phoenix-client/src/utils/urls.ts
similar to python client, log the link back to Phoenix UI on the created Dataset/Experiment #7629
test outputs(tested locally):
```
npx tsx js/packages/phoenix-client/examples/evaluate_experiment.ts
📊 View dataset: http://localhost:6006/datasets/RGF0YXNldDoxNQ==/examples
📺 View dataset experiments: http://localhost:6006/datasets/RGF0YXNldDoxNQ==/experiments
🔗 View this experiment: http://localhost:6006/datasets/RGF0YXNldDoxNQ==/compare?experimentId=RXhwZXJpbWVudDoxNg==
```
=> feat: Add URL logging for experiments in TypeScript client

app/src/components/filter/PrimaryInferencesTimeRange.tsx, app/src/pages/embedding/MetricSelector.tsx
=> refactor: migrate both metric and inferenceTime selector as both are in same tab

js/packages/phoenix-client/src/__generated__/api/v1.ts, packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py, schemas/openapi.json, src/phoenix/server/api/routers/v1/annotations.py, tests/integration/client/test_spans.py, tests/unit/server/api/routers/v1/test_annotations.py
While notes are implemented as annotations, they should not be returned alongside "normal" span annotations.
This adds filter options to `get_span_annotations` and `get_span_annotations_dataframe`
where `include_annotation_names=` and `exclude_annotation_names=` parameters passed into the client methods will filter annotations by name before being returned.
`exclude_annotation_names=` defaults to `["notes"]` in order to automatically filter out notes.
=> fix: Do not return notes from GET /span_annotations

src/phoenix/experiments/functions.py, src/phoenix/experiments/tracing.py, src/phoenix/server/telemetry.py, src/phoenix/trace/projects.py, tests/integration/_helpers.py
These type errors seem to have been resolved as of the latest OTel version.
=> ci: fix typecheck errors

app/package.json
By running `pnpm dev`, pnpm and uv will automatically invoke tox, adding symlinks for phoenix py monorepo packages
=> chore: Add symlinks automatically when running dev cmd

app/schema.graphql, src/phoenix/server/api/mutations/model_mutations.py, src/phoenix/server/api/queries.py, tests/unit/server/api/mutations/test_model_mutations.py
- adds validation for name pattern to be a regex (we may wish to move this into the ORM layer eventually)
- adds tests
- adds query to validate regex, needed for the model form below
resolves #8026
=> fix(cost): validate regex before creating or updating generative model

src/phoenix/server/email/sender.py, tests/integration/auth/test_auth.py, tests/integration/client/test_users.py
Welcome email always tries to force you to go to the forgot password link. There might be more wrong here but this is at least simpler in logic.
=> fix: make welcome email just send you to the instance

app/src/pages/experiment/ExperimentCompareTable.tsx
resolves #8334 
Clears the selected span so that the root span is selected on open. There was a bug where it would load the old span.
https://github.com/user-attachments/assets/efe37bc9-53e4-41cc-8700-f5af94596129
=> fix(experiments): Clear the selectedSpanNodeId when closing trace view

app/src/components/annotation/AnnotationTooltip.tsx, app/src/components/tooltip/RichTooltip.tsx, app/src/components/tooltip/Tooltip.tsx, app/src/components/tooltip/TriggerWrap.tsx, app/src/components/tooltip/index.tsx, app/src/components/tooltip/styles.ts, app/src/pages/project/AnnotationSummary.tsx, app/src/pages/project/MetadataTooltip.tsx
This PR migrates tooltips within `MetadataTooltip.tsx` and `AnnotationSummary.tsx` to the new rich tooltip component. This includes adding a `width` prop to `RichTooltip` that when set will override the existing max width of 300px. This is needed to preserve the existing behavior of `MetadataTooltip` having a width of 800px.
<details>
<summary>
Screenshots
</summary>
before:
after:
before:
after:
before:
after:
</details>
=> refactor: Migrate AnnotationSummary tooltips and Metadata tooltip to new component

src/phoenix/server/cost_tracking/cost_model_lookup.py
`.match()` - Always starts from the beginning of the string (not line)
`.search()` - Searches anywhere in the string
=> fix(cost): incorrect regex match method for model name

app/src/components/CopyToClipboardButton.tsx, app/src/components/filter/PrimaryInferencesTimeRange.tsx, app/src/components/filter/ReferenceInferencesTimeRange.tsx, app/src/components/pointcloud/CanvasModeRadioGroup.tsx, app/src/components/pointcloud/PointCloud.tsx, app/src/components/trace/AnnotationConfigList.tsx, app/src/pages/embedding/MetricSelector.tsx, app/src/pages/project/SpanFilterConditionField.tsx, app/src/pages/trace/SessionDetails.tsx
This PR migrates some more usages of the old tooltip component over to the newer phoenix components.
<details>
<summary>
</summary>
(same approach as https://github.com/Arize-ai/phoenix/pull/8469/files#diff-d3aa568be43f3d409c6851e027eb8c41db10bc4f9a7868f978ce9ed742240ebf)
before:
after:
before:
after:
</details>
<details>
<summary>
</summary>
before:
after:
</details>
<details>
<summary>
</summary>
before:
after:
before:
after:
before:
after:
before:
not sure why, but the old tooltips didn't seem to be working here
after:
before:
after:
</details>
<details>
<summary>
</summary>
(create annotation button)
before:
after:
</details>
<details>
<summary>
</summary>
before:
another case where the old tooltip didn't work, not sure why
after:
</details>
=> refactor: migrate more tooltips to phoenix library

pyproject.toml
resolves #8036
OTEL supports [v6](https://github.com/open-telemetry/opentelemetry-python/blame/14401e1dd82852fdea76ecf4d720fbd74834b705/opentelemetry-proto/pyproject.toml#L28)
=> fix: remove version upperbound on protobuf

src/phoenix/server/api/routers/oauth2.py
Improve OIDC error handling to provide a user-friendly message when the email scope is not returned from the OIDC provider.
resolves #8418
=> fix: Improve error message for missing email scope

packages/phoenix-client/src/phoenix/client/experiments/__init__.py, packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py, tests/integration/client/test_experiments.py
resolves https://github.com/Arize-ai/phoenix/issues/5137
- Add `get_experiment` method to retrieve a completed experiment. This returns a `RanExperiment` object that can be used to run further evaluations on completed Experiment examples.
- Adds top level `run_experiment` `get_experiment` and `evaluate_experiment` imports to `phoenix.client.experiments`. These methods accept arguments to instantiate a client with which to connect to the Phoenix server.
=> feat: Experiment enhancements

src/phoenix/config.py, src/phoenix/server/api/auth.py, src/phoenix/server/api/exceptions.py, src/phoenix/server/app.py, src/phoenix/server/authorization.py, src/phoenix/server/email/sender.py, src/phoenix/server/email/templates/db_disk_usage_notification.html, tests/integration/server/test_db_disk_usage_monitor.py
resolves [#8530](https://github.com/Arize-ai/phoenix/issues/8530)
This PR enhances error messaging when database operations are blocked due to insufficient storage by adding optional support email contact information. The changes introduce a new PHOENIX_SUPPORT_EMAIL environment variable and integrate it across GraphQL authorization (IsLocked class), REST API authorization (is_not_locked function), gRPC interceptors (DbDiskUsageInterceptor), and database usage notification emails. When configured, error messages now include actionable guidance like "Database operations are disabled due to insufficient storage. Please delete old data or increase storage. Need help? Contact us at {support_email}" instead of generic "operations not allowed" messages. This provides users with clear next steps …
=> feat: add environment variable for support email to be included in error messages

packages/phoenix-evals/src/phoenix/evals/templates.py, packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py, packages/phoenix-evals/tests/phoenix/evals/models/test_litellm.py
Give option to explicitly pass in list of variables
this is basically to give us the option of having a json included in the template we pass in. Before, it was being parsed as a variable, but with this, we should be able to skip the parse_variable step
=> feat: prompt variables skip parse

packages/phoenix-client/src/phoenix/client/utils/executors.py, packages/phoenix-client/tests/client/utils/test_executors.py
- This allows phoenix client evals to be runnable in background threads by disabling signal handling
- Previously, signal handling in threads was disabled in the `get_executor_on_sync_context` function, which is no longer used in the explicit sync/async Phoenix clients
=> fix: Allow executors to run in background threads

tests/integration/_helpers.py
(due to what i think is an incorrect [implementation](https://github.com/open-telemetry/opentelemetry-python/blob/57cb935e88123569063df8d4e471bee62e1a3d6b/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L165)) this parameter can result in negative values causing the exporter to crash
=> ci: remove timeout from span exporter fixtures

app/.eslintrc.js, app/src/components/button/IconButton.tsx, app/src/components/index.tsx, app/src/components/list/List.tsx, app/src/components/list/ListItem.tsx, app/src/components/list/index.ts, app/src/components/list/styles.ts, app/src/components/list/types.ts, app/src/components/progress/types.ts, app/src/pages/embedding/ExportSelectionButton.tsx, app/src/pages/prompt/PromptInvocationParameters.tsx, app/src/pages/prompt/PromptLLM.tsx, app/src/pages/trace/SpanDetails.tsx, app/stories/List.stories.tsx
This adds a new List component to replace the old one from @arize/components. I only copied over the variants we're currently using, which include a small and medium size list. Other than that, all the styles are copied over from the old component. The only differences are:
- renamed sizing from small/default to S/M to better align with Phoenix's sizing conventions
- removed listSize prop from ListItem. since ListItem inherits its sizing from List, I thought it would be best to have one spot to specify list sizing to keep things simple and reduce ambiguity.
Both the "LLM" and "Invocation parameters" section are each their own List.
before:
after:
before:
after:
before:
after:
=> refactor: migrate List component

js/.changeset/wise-beds-rush.md, js/packages/phoenix-client/src/datasets/getDataset.ts, js/packages/phoenix-client/src/datasets/getDatasetExamples.ts, js/packages/phoenix-client/src/datasets/getDatasetInfo.ts, js/packages/phoenix-client/src/datasets/index.ts, js/packages/phoenix-client/src/types/datasets.ts, js/packages/phoenix-client/test/datasets/getDataset.test.ts
#8570 
test output:
npx tsx test-client.ts
🧪 Testing Phoenix Client Dataset Version Support
📊 Dataset ID: RGF0YXNldDoyMA==
🔖 Version ID: RGF0YXNldFZlcnNpb246MjQ=
🌐 API Base URL: http://localhost:6006
Test 1: getDatasetExamples with versionId
✅ SUCCESS!
Version ID returned: RGF0YXNldFZlcnNpb246MjQ=
Number of examples: 11
First example ID: RGF0YXNldEV4YW1wbGU6Njg=
Test 2: getDataset with versionId
✅ SUCCESS!
Dataset ID: RGF0YXNldDoyMA==
Dataset name: Dataset 2025-06-17T21:44:39.467Z
Version ID: RGF0YXNldFZlcnNpb246MjQ=
Number of examples: 11
Test 3: getDataset without versionId (should get latest)
✅ SUCCESS!
Latest version ID: RGF0YXNldFZlcnNpb246MjQ=
Number of examples: 11
📈 Version Comparison:
Requested version: RGF0YXNldFZlcnNpb246MjQ=
Latest version: RGF0YXNldFZlcnNpb246MjQ=
Same …
=> feat: [ts] get dataset by version

app/src/pages/project/TopModelsByCost.tsx, app/src/pages/project/TopModelsByToken.tsx
This updates the `tickFormatter` used on the tops bar charts x-axes to be consistent with the formatting used in the tooltips.
=> fix: format x axis labels on tops bar charts consistently with tooltips

app/.eslintrc.js, app/src/components/card/Card.tsx, app/src/components/card/styles.ts, app/src/components/card/types.ts, app/src/pages/settings/AnnotationConfigDialog.tsx, app/src/pages/settings/AnnotationConfigSelectionToolbar.tsx, app/src/pages/settings/GenerativeProvidersCard.tsx, app/src/pages/settings/GlobalRetentionPolicyCard.tsx, app/src/pages/settings/SettingsAnnotationsPage.tsx, app/src/pages/settings/SettingsDataPage.tsx, app/src/pages/settings/SettingsGeneralPage.tsx, app/src/pages/settings/SettingsModelsPage.tsx, app/src/pages/settings/UsersCard.tsx, app/src/pages/trace/SpanDetails.tsx, app/src/pages/trace/SpanToDatasetExampleDialog.tsx, app/stories/Card.stories.tsx, app/stories/Disclosure.stories.tsx, app/stories/RadioGroup.stories.tsx, app/stories/Slider.stories.tsx, app/stories/Tabs.stories.tsx, app/stories/TitledPanel.stories.tsx, app/stories/ToggleButtonGroup.stories.tsx, app/stories/Token.stories.tsx
This completes the migration to use the new Card component, mainly by updating cards used in the settings page, span details page, and storybook stories. This also adds `titleSeparator` and `defaultOpen` props to Card, to maintain existing layout/behavior.  I'm not sure if we want to keep these since each prop is only used once, so definitely open to alternate ideas.
LLMSpanInfo card with no title separator:
RerankerSpanInfo card with defaultOpen=false:
Some other various screenshots of updated cards:
=> refactor: card migration pt 3

app/src/components/project/GradientCircle.tsx, app/src/components/project/GradientCircleRadio.tsx, app/src/components/project/GradientCircleRadioGroup.tsx, app/src/components/project/index.ts, app/src/pages/projects/ManualProjectGuide.tsx, app/src/pages/projects/NewProjectButton.tsx, app/src/pages/projects/NewProjectForm.tsx, app/src/pages/projects/ProjectsPage.tsx, app/src/pages/projects/__generated__/ManualProjectGuideCreateProjectMutation.graphql.ts
Add the ability to manually create projects
(e.g. to create a place to put other spans for things like transfer)
=> feat(projects): add the ability to manually create a project

app/src/openInference/tracing/__tests__/types.test.ts, app/src/openInference/tracing/types.ts
missing role gets [converted](https://github.com/Arize-ai/phoenix/blob/5e646183c11947b2e4c0e51a356db860e32cfc90/app/src/pages/trace/SpanDetails.tsx#L1420) to `unknown` anyway
Messages are not displayed at all.
=> fix: message role should not be required

app/schema.graphql, app/src/pages/experiment/ExperimentCompareMetricsPage.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiment/ExperimentMultiSelector.tsx, app/src/pages/experiment/__generated__/ExperimentCompareMetricsPage_experiments.graphql.ts, app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts, app/src/pages/experiment/__generated__/ExperimentCompareTable_comparisons.graphql.ts, app/src/pages/experiment/__generated__/ExperimentMultiSelector__data.graphql.ts, app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts, app/src/pages/experiment/experimentCompareLoader.ts, src/phoenix/server/api/types/Dataset.py
Needed since we are now computing aggregate statistics for each experiment for the grid view column headers. We're currently computing those statistics for every experiment. Will eventually do this via the query DSL once implemented.
=> fix(experiments): optimize compare experiments query

app/src/components/markdown/MarkdownBlock.tsx, app/src/pages/trace/SpanDetails.tsx
=> fix: missing markdown block for text in multi-part messages

app/src/pages/experiment/ExperimentRunFilterConditionField.tsx, app/src/pages/project/SpanFilterConditionField.tsx
resolves #9013 
Slight design cleanup to be closer to search fields.
=> chore(design): filter condition design consistency

app/src/GlobalStyles.tsx, app/src/components/annotation/MeanScore.tsx, app/src/components/code/JSONText.tsx, app/src/components/content/Text.tsx, app/src/components/table/FloatCell.tsx, app/src/components/table/IntCell.tsx, app/src/components/trace/LatencyText.tsx, app/src/components/trace/TokenCosts.tsx, app/src/components/trace/TokenCount.tsx, app/src/pages/project/ProjectPageHeader.tsx, app/src/pages/projects/ProjectsPage.tsx, app/stories/Text.stories.tsx, src/phoenix/server/templates/index.html
Add a mono font for showing values (e.x. numerics)
=> feat(design): add geist mono for values

packages/phoenix-evals/src/phoenix/evals/preview/__init__.py, packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py, packages/phoenix-evals/src/phoenix/evals/preview/metrics/exact_match.py, packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
Renames from `simple_evaluator` -> `create_evaluator` to follow decorator naming conventions and match existing experiments behavior.
Updates decorator implementation to convert decorated functions into valid `Evaluator` instances with an `evaluate` method.
=> fix: [evals] rename and update evaluator decorator 

packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
resolves #9068 
**Problem:**
Span timing information was being captured while still inside the span context (`with ExitStack()` block), causing:
- `end_time` to be `None` or set to an early preliminary value before the span actually completed
- Inaccurate timing measurements since the span operations hadn't finished
**Solution:**
Move span timing collection (`start_time`, `end_time`, `trace_id`) outside the span context so it's captured after the span has fully completed and all timing information is finalized.
=> fix: record end time after span ends

src/phoenix/config.py, tests/unit/test_config.py
resolves #9058 
Phoenix was automatically parsing **any** host string containing a colon as a `host:port` combination. While this was designed to be helpful, it broke complex host strings like Cloud SQL mount paths (`/cloudsql/project:region:instance-id`) and IPv6 addresses (`2001:db8::1`) that contain colons but are not `host:port` patterns.
Added a strict regex (`^[^:]+:\d{1,5}$`) that only matches simple host:port patterns, ensuring complex host strings are treated as complete host identifiers:
✅ Still works: localhost:5432 → parsed as host=localhost, port=5432
✅ Now works: /cloudsql/project:region:instance-id → treated as complete host
✅ Protected: IPv6 addresses, URLs with schemes, other complex paths
Existing deployments using simple host:port patterns continue to work unchanged. …
=> fix: split `ENV_PHOENIX_POSTGRES_HOST` only if matched (legacy) pattern

app/src/pages/settings/ModelsTable.tsx
=> fix: show custom provider in models table

src/phoenix/db/insertion/document_annotation.py, src/phoenix/db/insertion/span_annotation.py, src/phoenix/db/insertion/trace_annotation.py, src/phoenix/db/insertion/types.py
Note that the process falls back to inserting records individually when bulk insert fails.
SQLAlchemy bulk INSERT operations were failing when mixing records with explicit ID values (UPDATE scenarios) and records without ID fields (INSERT scenarios). This caused a `CompileError` because SQLAlchemy cannot compile a single bulk statement with inconsistent column structures.
```
sqlalchemy.exc.CompileError: INSERT value for column span_annotations.id is explicitly rendered as a boundparameter in the VALUES clause; a Python-side value or SQL expression is required
```
Removed the redundant `id_` field from insertable annotation classes:
- `SpanAnnotation`
- `TraceAnnotation` 
- `DocumentAnnotation`
The ID field was redundant because PostgreSQL's uniqueness constraints already handle record …
=> fix: remove redundant id in annotation insertables during bulk insert

packages/phoenix-evals/src/phoenix/evals/executors.py, packages/phoenix-evals/src/phoenix/evals/models/anthropic.py, packages/phoenix-evals/src/phoenix/evals/models/bedrock.py, packages/phoenix-evals/src/phoenix/evals/models/google_genai.py, packages/phoenix-evals/src/phoenix/evals/models/mistralai.py, packages/phoenix-evals/src/phoenix/evals/models/openai.py, packages/phoenix-evals/src/phoenix/evals/models/rate_limiters.py, packages/phoenix-evals/src/phoenix/evals/models/vertex.py, packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py, packages/phoenix-evals/tests/phoenix/evals/functions/test_concurrency_controller.py, packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
- The `AsyncExecutor` controls how many simultaneous async tasks can be started at once, which enables local throttling of submitted tasks in the event of rate limit errors
- However, if the allowed number of tasks is throttled too much, the executor will keep on trying to pick up throttled tasks, time out, and exhaust the total number of retries per task, leading to failed tasks
This PR adds dynamic feedback to the number of workers which either decreases or increases the concurrency if a rate limit error occurs in a configurable window (default 5s). Furthermore, if more than one rate limit error occurs within a larger window (30s) the concurrency will be dropped to 1.
=> feat: Dynamic concurrency

packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py, packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
Before: decorated functions had to return a `Score` object. 
Now: decorated functions can return many different things and the decorator will handle casting them to valid Score objects. 
The decorated function can return:
- A Score object (no conversion needed)
- A number or boolean (converted to Score.score)
- A short string (≤3 words, converted to Score.label)
- A long string (≥4 words, converted to Score.explanation)
- A dictionary with keys "score", "label", or "explanation"
- A tuple of values (only bool, number, str types allowed)
=> fix(evals): update `create_evaluator` decorator handle casting function outputs to valid Scores

packages/phoenix-client/docs/source/conf.py, packages/phoenix-client/src/phoenix/client/client.py, packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py, packages/phoenix-client/src/phoenix/client/resources/datasets/__init__.py, packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py, packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
This makes all python client docs conform to google spec. Otherwise it renders badly via napoleon https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
=> docs: fix client python docs

app/src/GlobalStyles.tsx, app/src/components/annotation/AnnotationDetailsContent.tsx, app/src/components/annotation/AnnotationLabel.tsx, app/src/components/annotation/AnnotationNameAndValue.tsx, app/src/components/annotation/AnnotationSummaryGroup.tsx, app/src/components/annotation/AnnotationTooltip.tsx, app/src/components/annotation/AnnotationTooltipContent.tsx, app/src/components/annotation/types.ts, app/src/components/overlay/Popover.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx
this is a pre-cursor to #8774 
This moves us towards being able to consistently displaying filters on the bottom. There are some cases that are not covered. Notably:
- Consolidate on the background color of dialogs vs tooltips (think they probably need to converge)
- Missing annotations on one grid view vs the other
- Button styling
- Padding on content vs bottom metrics
=> refactor(experiments): place annotations at the bottom

src/phoenix/server/api/helpers/playground_clients.py
- Adds explicit timeout to OpenAI SDK for playground
- This improves the stability as the OpenAI client will occasionally hang on some CloudFlare errors
=> fix: Add OpenAI timeout to playground client

app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiment/ExperimentRunAnnotationFiltersList.tsx
resolves #8774 
Adds the ability to filter by eval / annotation values
=> feat(experiments): eval / annotation quick filters

helm/README.md, helm/templates/_helpers.tpl, helm/templates/phoenix/deployment.yaml, helm/templates/phoenix/pvc.yaml, helm/values.yaml
This special cases `sqlite:///:memory:` so that we don't need persistent volumes, simplifying quick starts.
=> feat: special case sqlite:///:memory: in helm

helm/templates/phoenix/configmap.yaml
The Helm chart currently sets PostgreSQL environment variables unconditionally in the ConfigMap, even when postgresql.enabled: false. This causes Phoenix to attempt connecting to the non-existent "phoenix-postgresql" service instead of falling back to SQLite as documented.
- When postgresql.enabled: false is set (Strategy 1 - SQLite mode)
- PostgreSQL environment variables are still set in the ConfigMap:
- PHOENIX_POSTGRES_HOST: "phoenix-postgresql"
- PHOENIX_POSTGRES_PORT, PHOENIX_POSTGRES_USER, etc.
- Phoenix tries to connect to PostgreSQL instead of using SQLite
- Results in connection failures and prevents proper SQLite fallback
In `helm/templates/phoenix/configmap.yaml` lines 50-55, PostgreSQL environment variables are set unconditionally without checking if PostgreSQL is actually …
=> fix: default sqlite usage when postgresql.enabled false

helm/README.md, helm/templates/phoenix/deployment.yaml, helm/values.yaml
This PR introduces extraVolume and extraVolumeMounts which will be rendered in chart under default. This field is provided as is, it will render whatever yaml is specified under. For instance, in the values.yaml
```
extraVolumes:
- name: config-volume
configMap:
name: my-app-config
- name: cache-volume
emptyDir: {}
...
extraVolumeMounts:
- name: config-volume
mountPath: /etc/config
readOnly: true
- name: cache-volume
mountPath: /app/cache
```
would be valid ways of introducing new volumes to the phoenix deployment.
=> feat: extra volumes/volume mounts in helm

docs/tracing/how-to-tracing/advanced/suppress-tracing.md
While looking through the documentation, I found this outdated artifact, which was adjusted in https://github.com/Arize-ai/phoenix/pull/2700
The implementation for suppress_tracing has moved to openinference-instrumentation.
=> chore: update suppress-tracing.md documentation

docs/evaluation/preview/evaluators.md, packages/phoenix-evals/pyproject.toml, packages/phoenix-evals/src/phoenix/evals/preview/utils.py, packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py, packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_utils.py, requirements/dev.txt
`glom` uses nonstandard syntax for path spec. `jsonpath-ng` is more familiar (uses brackets to index lists, whereas glom uses dot syntax). Unlike `jmespath`, it is also possible to distinguish between nonexistent paths and paths which point to None values.
=> fix(evals): switch from glom to jsonpath-ng for input mapping

js/.changeset/clear-grapes-train.md, js/packages/phoenix-client/src/experiments/instrumention.ts, js/packages/phoenix-client/src/experiments/runExperiment.ts
resolves #9263 
This switches the experiment runner in the typescript client to use batching instead as this is probably the better solution for production usage.
=> fix(client): use batch span processor for experiments

packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py, packages/phoenix-evals/src/phoenix/evals/preview/llm/__init__.py, packages/phoenix-evals/src/phoenix/evals/preview/llm/wrapper.py, packages/phoenix-evals/src/phoenix/evals/preview/metrics/hallucination.py, packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
We originally had separate classes for sync and async LLMs. Combining them into one class with separate sync/async methods simplifies things significantly.
=> fix(evals): unify sync and async llm

MIGRATION.md, packages/phoenix-otel/pyproject.toml, src/phoenix/trace/projects.py
Start moving utilities outside of phoenix core package.
=> chore: add deprecation warning for using_project from inside phoenix.trace

js/packages/phoenix-evals/src/llm/ClassificationEvaluator.ts, js/packages/phoenix-evals/src/llm/LLMEvaluator.ts, js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts, js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts, js/packages/phoenix-evals/src/template/getTemplateVariables.ts, js/packages/phoenix-evals/src/template/index.ts, js/packages/phoenix-evals/src/types/evals.ts, js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts, js/packages/phoenix-evals/test/template/getTemplateVariables.test.ts
precursor to #9125 
Switches evaluators to be classes so that certain computed properties like template variables can be accessed and cached via dynamic programming.
=> refactor(evals): make evaluator a class, add ability to parse out variables

app/src/pages/experiment/ExperimentCompareListPage.tsx
Follow up PR to address [this comment](https://github.com/Arize-ai/phoenix/pull/9353#discussion_r2319714199) by updating the `TableRow` type defined on the experiment compare lists page to be derived from the relay-generated types.
This also includes a small change to add aria-labels to the ProgressBar component on this page, since I just noticed console warnings related to this.
=> refactor: update experiment compare list page typing

app/src/pages/experiment/ExperimentCompareDetails.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiment/ExperimentRunLatency.tsx, app/src/pages/experiment/ExperimentRunMetadata.tsx, app/stories/ExperimentTable.stories.tsx
resolves #9286 
This minimally refactors the dialog contents and makes the run outputs to be viewable side-by-side.
=> feat(experiments): minimal refactoring of experiment compare details

js/.changeset/heavy-horses-count.md, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/prompts/sdks/toAI.ts, js/packages/phoenix-client/src/schemas/llm/openai/converters.ts, js/packages/phoenix-client/src/schemas/llm/vercel/messagePartSchemas.ts, js/packages/phoenix-client/src/schemas/llm/vercel/toolSchemas.ts, js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts, js/pnpm-lock.yaml
This moves the client to vercel AI SDK 5.
Note that the vercel AI SDK 5 is significantly more complex with  regards to tools, notably there is a symbol used inside of zod that makes types not conform. I think we need to independently bump zod to 4 and re-consider the function parameter spreading strategy as I think it's just very difficult to maintain. I just turned it off for now.
=> feat!: switch to the vercel ai sdk 5

app/src/pages/experiment/ExampleDetailsPaginator.tsx, app/src/pages/experiment/ExperimentCompareDetails.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx
Enables paging between examples from the experiment compare details slideover, either with buttons or keyboard shortcuts. The keyboard shortcuts are J + K keys, same as in the trace details slideover.
https://github.com/user-attachments/assets/e0b6bab0-79ef-4d2d-a4a1-43e69b0ef251
=> feat(experiments): enable paging experiment compare details

app/src/pages/experiment/ExperimentCompareDetailsDialog.tsx, app/src/pages/experiment/ExperimentCompareListPage.tsx, app/src/pages/experiment/ExperimentCompareTable.tsx, app/src/pages/experiment/__generated__/ExperimentCompareDetailsDialogQuery.graphql.ts, app/src/pages/experiment/__generated__/ExperimentCompareListPage_aggregateData.graphql.ts, app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
This adds the experiment compare details slideover to the experiments list view, so that as we continue working on it, we can make sure it works in both spots.
This also makes pagination optional in the slideover and disables pagination when opened from the list view. This is because as currently implemented, pagination relies on a sequence of unique example IDs, which we can't guarantee anymore from the list view since we may have multiple rows for the same example ID if it has multiple repetitions. Rather than put too much thought into solving it now, it seemed better to just disable it and revisit when we have a better idea of how we want pagination to work on the list page.
https://github.com/user-attachments/assets/b7ab09ce-2fc6-4e55-8685-7c393e145505
=> feat(experiments): add experiment compare details slideover to list view

js/.changeset/hip-flowers-talk.md, js/examples/notebooks/deno_datasets_and_experiments_quickstart.ipynb, js/packages/phoenix-client/examples/dataset_and_experiments_quickstart.ts, js/packages/phoenix-client/package.json, js/packages/phoenix-client/src/experiments/runExperiment.ts, js/packages/phoenix-client/src/types/experiments.ts, js/pnpm-lock.yaml
resolves #9472
This fixes it so that the global tracer provider can be passed through to the evals to avoid the global tracer getting clobbered.
=> fix(js): allow the passthrough of tracer providers, switch to phoenix-evals in notebooks

.github/workflows/python-CI.yml
the github action keeps timing out after 10 minutes and we don't know why
=> ci: remove MacOS from integration tests

internal_docs/specs/server_evaluators.md
This is a spec / definition of how we want to define and run evaluations on the server. It will serve as a living document as the definitions evolve.
=> docs(spec): server evaluator

js/packages/phoenix-client/src/experiments/getExperimentRuns.ts, js/packages/phoenix-client/test/experiments/getExperimentRuns.test.ts
resolves #9384
pulls experiment runs by page size so as to not overwhelm the server.
=> feat(phoenix-client): paginate through runs when experiments are re-run

packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/adapter.py, packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/factories.py, packages/phoenix-evals/src/phoenix/evals/llm/wrapper.py
resolves #9567 
- Adds support for an `azure` provider
- kwargs passed into the `LLM` constructor are fowarded to client construction when applicable
=> feat: Add Azure provider support

scripts/ddl/postgresql_schema.sql, src/phoenix/db/facilitator.py, src/phoenix/db/helpers.py, src/phoenix/db/migrations/versions/deb2c81c0bb2_dataset_splits.py, src/phoenix/db/migrations/versions/e76cbd66ffc3_add_experiments_dataset_examples.py, src/phoenix/db/models.py, src/phoenix/server/api/dataloaders/table_fields.py, src/phoenix/server/api/mutations/chat_mutations.py, src/phoenix/server/api/routers/v1/experiments.py, src/phoenix/server/api/subscriptions.py, tests/integration/db_migrations/test_data_migration_e76cbd66ffc3_add_experiments_dataset_examples.py, tests/unit/_helpers.py, tests/unit/db/test_helpers.py, tests/unit/server/api/routers/v1/test_experiments.py, tests/unit/server/api/test_subscriptions.py
Introduces a junction table to capture which dataset examples belong to each experiment at creation time, enabling accurate historical tracking and supporting dataset splits functionality.
- **New junction table**: experiments_dataset_examples with composite primary key and proper foreign key constraints
- **Smart migration**: Backfills existing experiments using ROW_NUMBER() to select correct historical revisions  
- **Dataset splits support**: Automatically filters examples based on experiment's assigned splits
- **API integration**: Populates junction records across all experiment creation endpoints
- **Comprehensive testing**: Full unit and integration test coverage
- Cross-database compatible (PostgreSQL/SQLite)
- Efficient helper functions with granular, reusable components
- Proper …
=> feat: add junction table for taking snapshots of examples for experiments

scripts/ddl/postgresql_schema.sql, src/phoenix/db/migrations/versions/deb2c81c0bb2_dataset_splits.py, src/phoenix/db/models.py
This PR updates the crosswalk/junction tables in the dataset splits feature to use composite primary keys instead of separate auto-incrementing `id` columns with unique constraints, following the established pattern from `experiments_dataset_examples`.
- **`dataset_splits_dataset_examples`**: Removed `id` column, replaced `UniqueConstraint` with `PrimaryKeyConstraint(dataset_split_id, dataset_example_id)`
- **`experiments_dataset_splits`**: Removed `id` column, replaced `UniqueConstraint` with `PrimaryKeyConstraint(experiment_id, dataset_split_id)`
- **`DatasetSplitDatasetExample`**: Changed inheritance from `HasId` to `Base`, updated `__table_args__` to use `PrimaryKeyConstraint`
- **`ExperimentDatasetSplit`**: Changed inheritance from `HasId` to `Base`, updated `__table_args__` to use …
=> feat: use composite primary key for crosswalk tables

src/phoenix/server/api/routers/auth.py, src/phoenix/server/api/routers/oauth2.py, src/phoenix/server/api/routers/v1/__init__.py, src/phoenix/server/api/routers/v1/annotation_configs.py, src/phoenix/server/api/routers/v1/annotations.py, src/phoenix/server/api/routers/v1/datasets.py, src/phoenix/server/api/routers/v1/documents.py, src/phoenix/server/api/routers/v1/evaluations.py, src/phoenix/server/api/routers/v1/experiment_evaluations.py, src/phoenix/server/api/routers/v1/experiment_runs.py, src/phoenix/server/api/routers/v1/experiments.py, src/phoenix/server/api/routers/v1/projects.py, src/phoenix/server/api/routers/v1/prompts.py, src/phoenix/server/api/routers/v1/sessions.py, src/phoenix/server/api/routers/v1/spans.py, src/phoenix/server/api/routers/v1/traces.py, src/phoenix/server/api/routers/v1/users.py, src/phoenix/server/api/routers/v1/utils.py, src/phoenix/server/app.py, src/phoenix/server/authorization.py, src/phoenix/server/bearer_auth.py, tests/unit/server/api/routers/v1/test_annotation_configs.py, tests/unit/server/test_authorization.py
> DeprecationWarning: 'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated. Use 'HTTP_422_UNPROCESSABLE_CONTENT' instead.
=> refactor: use numeric http status code to avoid deprecation warnings
