pyproject.toml

Skip the NPM build if possible so that conda pipeline works

fix: don't compile js/html if exists - unblock conda

---

app/src/@types/event.d.ts
app/src/components/pointcloud/EventItem.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/types.ts

resolves #544 
Displays prompt response pairs in the embedding details view

feat(embeddings): show prompt and response for LLMs in event details

---

app/src/components/table/TextCell.tsx
app/src/components/table/index.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/PointSelectionTable.tsx
app/src/pages/embedding/types.ts

resolves #543 
Adds support for displaying a truncated prompt / response pair in the selection table.

feat(embeddings): display prompt response pairs in selection table

---

src/phoenix/core/model.py
src/phoenix/datasets/dataset.py
src/phoenix/datasets/errors.py
src/phoenix/datasets/schema.py
src/phoenix/datasets/validation.py
src/phoenix/server/app.py
tests/datasets/test_dataset.py
tests/datasets/test_schema.py
tests/datasets/test_validation.py

Adds the ability to log in prompt/response pairs. They are added to the embeddings features dictionary with the keys "prompt" and "response".
Closes #538 
Closes #539 
Closes #540

feat: Enable generative prompt/response pair

---

.pre-commit-config.yaml
app/src/components/pointcloud/EventItem.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/__generated__/PointSelectionPanelContentQuery.graphql.ts

Adds prompt / response pairs to the embeddings view

feat(embeddings): plumb through prompt / response pairs to the UI

---

src/phoenix/datasets/dataset.py
src/phoenix/datasets/schema.py
tests/datasets/test_schema.py

Schema serialization was not working for the process based app, which is used for the development flow. This restores this functionality. 
broken in #456

fix: restore schema JSON serialization

---

app/src/components/pointcloud/ClusteringSettings.tsx
app/src/constants/numberConstants.ts

Set 32bit int upper-bound on numeric fields for HDBSCAN

fix: set UI level upper-bounds on numerics for 32 bit ints

---

src/phoenix/core/model_schema.py

resolves https://github.com/Arize-ai/phoenix/issues/622
When the reference is missing, it's an empty DataFrame. Don't make guesses based that.

fix: don't guess data type when empty

---

src/phoenix/datasets/fixtures.py
tutorials/quickstart.ipynb
tutorials/sentiment_classification_tutorial.ipynb

Temporary workaround for #632
Adds prediction_id columns so the fields get revered and not discovered ad a feature

fix: add prediction_id to fixtures and tutorials

---

src/phoenix/core/model_schema.py

Floor datetimes to minute by taking round trips through string formatting because there isn't always an available function to strip the nanoseconds if present.

fix: floor datetime to minute

---

app/package-lock.json
app/package.json
app/src/pages/embedding/Embedding.tsx

Displays the cluster count in the tab for a better understanding of how many clusters have been found.

feat: show cluster count in tab header

---

app/package.json
app/schema.graphql
app/src/components/filter/PrimaryDatasetTimeRange.tsx
app/src/components/filter/ReferenceDatasetTimeRange.tsx
app/src/components/pointcloud/EventItem.tsx
src/phoenix/config.py
src/phoenix/core/embedding_dimension.py
src/phoenix/core/model_schema.py
src/phoenix/datasets/__init__.py
src/phoenix/datasets/dataset.py
src/phoenix/datasets/fixtures.py
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/Model.py
src/phoenix/server/main.py

resolves #535 
If a name is given to a dataset, the name is used throughout the UI strategically to make it clear what they are looking at.

feat: show human-friendly names for datasets in the UI

---

app/src/components/chart/ChartTooltip.tsx
app/src/components/chart/defaults.tsx
app/src/components/chart/index.tsx
app/src/pages/embedding/CountTimeSeries.tsx
app/src/pages/embedding/EuclideanDistanceTimeSeries.tsx
app/src/pages/home/Home.tsx

During development I wasn't sure how to plot timeseries data using recharts. This PR switches from using `categories` and instead moves to using `time` scale plus `number` to make things continuous on the xAxis.
Note on the composition model of recharts - recharts uses function components so you cannot wrap their component primitives. This PR introduces reasonable defaults for the axis and selections.

refactor: move to time axis

---

app/package.json
app/schema.graphql
src/phoenix/core/model_schema.py
src/phoenix/server/api/types/Dimension.py
src/phoenix/server/api/types/DimensionDataType.py
src/phoenix/server/api/types/DimensionShape.py
src/phoenix/server/api/types/DimensionType.py
tests/server/api/types/test_pagination.py

resolves #683 
unblocks #665 
Showing cardinality metrics doesn't really make sense in the case of continuous data. This PR adds a `DimensionShape` (not to confuse with data type) that exposes if the data is `discrete` or `continuous` so that certain fields can be hidden/shown without querying.
```graphql
{
model {
dimensions {
edges {
node {
name
shape
}
}
}
}
}
```
|| Discrete | Continuous |
|-|-|-|
| Categorical | Gender: M, F | (n/a) |
| Numeric | Length of stay: 1, 2, ... | Income: $23456, ... |
here's a [literature](https://www150.statcan.gc.ca/n1/edu/power-pouvoir/ch8/5214817-eng.htm) reference to make things more precise: 
|| Discrete | Continuous |
|-|-|-|
| Nominal | Gender: M, F | (n/a) |
| Ordinal | Grade: A, B, C, ... | (n/a) |
| Numeric | Length of stay: 1, 2, ... | Income: …

feat(gql): distinguish discrete vs continuous data

---

app/src/components/ViewSummaryAside.tsx
app/src/components/chart/colors.tsx
app/src/pages/dimension/Dimension.tsx
app/src/pages/dimension/DimensionCardinalityTimeSeries.tsx
app/src/pages/dimension/DimensionCountTimeSeries.tsx
app/src/pages/dimension/DimensionDriftBreakdownSegmentBarChart.tsx
app/src/pages/dimension/DimensionDriftTimeSeries.tsx
app/src/pages/dimension/DimensionPercentEmptyTimeSeries.tsx
app/src/pages/dimension/DimensionSegmentsBarChart.tsx
app/src/pages/dimension/__generated__/DimensionDriftBreakdownSegmentBarChartQuery.graphql.ts
app/src/pages/embedding/CountTimeSeries.tsx
app/src/pages/embedding/EuclideanDistanceTimeSeries.tsx

resolves #733 
Adds the ability to scrub through time and decipher the distribution at given points in thime.

feat(dimension): drift breakdown chart to isolate the difference in dimension segments distribution

---

DEVELOPMENT.md
docs/api/dataset-and-schema.md
src/phoenix/datasets/dataset.py
tests/datasets/test_dataset.py

Resolves #592 
1. Object dtype timestamp support and parameterized tests added, old invalid test modified.
2. Documentation updated.
3. Windows-friendly quotes change in phoenix dev install command. (Works in UNIX too)

feat: support ISO8601 formatted strings in timestamp column

---

.github/workflows/python-CI.yml
pyproject.toml
src/phoenix/core/model_schema.py
src/phoenix/metrics/binning.py
src/phoenix/metrics/mixins.py

resolves #680
numba now [supports](https://numba.readthedocs.io/en/stable/release-notes.html#version-0-57-0-1-may-2023) Python 3.11
1. use `hatch run test:tests` to run test for both python versions
2. the host python must be 3.8 (otherwise the 3.8 tests will not work)
3. python 3.11 forbids mutable defaults for dataclass fields, hence the code changes in the PR

ci: allow python 3.11

---

pyproject.toml

0.177.1 seems to be [unavailable](https://github.com/conda-forge/strawberry-graphql-feedstock/pulls?q=is%3Apr+is%3Aclosed) on conda, hence the need to bump its version to one that is actually found (0.178.0)

ci: re-pin version for strawberry-graphql

---

src/phoenix/server/api/interceptor.py
tests/server/api/test_interceptor.py

```pycon
>>> isinstance(np.array([np.nan], dtype=np.float16), float)
False
>>> isinstance(np.array([np.nan], dtype=np.float16), np.floating)
True
```

fix: bug with np.floating

---

pyproject.toml
src/phoenix/pointcloud/projectors.py

Resolves #709
Tested via jupyter(taylor_swift_lyrics.ipynb) & pytests from IDE. All numba.jit() deprecation warnings are suppressed as numba is transitively being used by umap.

fix: numba.jit() deprecation warning

---

app/package.json
app/schema.graphql
src/phoenix/server/api/input_types/DimensionFilter.py

Need the ability to return just numeric dimensions for filtering:
```graphql
{
model {
dimensions(include: { dataTypes: [numeric]} ) {
edges {
node {
name
type
dataType
}
}
}
}
}
```

feat(dimensions): Add the ability to filter by data_type

---

src/phoenix/core/model_schema.py

resolves https://github.com/Arize-ai/phoenix/issues/836
It turns out pandas can't work with `float16`: https://github.com/pandas-dev/pandas/blob/bc7b3948d2460439f2c476583feae78f57b60b9e/pandas/core/indexes/base.py#L575

fix: change float16 to float32 as dtype for the nan series

---

src/phoenix/metrics/__init__.py

- don't crash graphql because this exception can happen when binning columns with np.float16
- specifically https://github.com/pandas-dev/pandas/blob/bc7b3948d2460439f2c476583feae78f57b60b9e/pandas/core/indexes/base.py#L575
- add logging so it doesn't fail silently
here's how it looks like in jupyter notebook:

fix: return nan on NotImplementedError (when binning on np.float16)

---

app/src/store/pointCloudStore.ts

As a user, when I'm analyzing by a data quality metric (in particular against a context) - I want the "nullish" values to not be a part of the sort.

fix(embeddings): always place clusters with empty metrics at the bottom

---

src/phoenix/core/model_schema_adapter.py

resolves https://github.com/Arize-ai/phoenix/issues/852
A best-effort attempt at separating vector columns from scalar columns by examining the first non-null item of the column from each dataframe. If any item is `Iterable` and `Sized`, but not `str`, then the column is returned as `Embedding`, else it's returned as scalar.

fix: guess whether a column contains any vector or all scalars

---

src/phoenix/server/api/types/Segments.py

what the bug looks like
> Error fetching GraphQL query 'DimensionDriftBreakdownSegmentBarChartQuery' with variables '{"dimensionId":"RGltZW5zaW9uOjg=","timeRange":{"start":"2023-06-11T07:00:00.000Z","end":"2023-06-13T07:00:00.000Z"}}': [{"message":"Float cannot represent non numeric value: -inf","locations":[{"line":20,"column":17}],"path":["dimension","segmentsComparison","segments",0,"bin","range","start"]}]
what it looks like when it's fixed

fix: skip empty interval bin with infinity endpoints (when all data are missing values)

---

app/package.json
app/src/components/pointcloud/PointCloudClusters.tsx

The react reconciler was getting confused with regards to the opacity of the cluster. This forces the render key to be unique so that the reconciler runs again when the opacity changes.

fix(embeddings): force re-render clusters when opacity changes

---

src/phoenix/core/model_schema.py
src/phoenix/datasets/dataset.py

resolves https://github.com/Arize-ai/phoenix/issues/841
when dataset is empty, return `now` instead of NaT

fix: replace NaT (Not a Time) with now (when dataset is empty)

---

app/src/pages/embedding/Embedding.tsx
app/src/pages/embedding/MetricSelector.tsx
app/src/store/pointCloudStore.ts

resolves: #859 
Disables the metric selector while the main points are loading so that we don't have to cancel ongoing requests. Keeps the UI a bit simpler for now.

fix(embeddings): disable metric selector while loading points

---

src/phoenix/core/model_schema.py

resolves https://github.com/Arize-ai/phoenix/issues/888
In Python 3.11, `IntEnum` is printed differently than in prior Python versions
[changed in 3.11](https://docs.python.org/3/library/enum.html#enum.IntEnum:~:text=with%201.-,Changed%20in%20version%203.11%3A%20__str__()%20is%20now%20int.__str__()%20to%20better%20support%20the%20replacement%20of%20existing%20constants%20use%2Dcase.%20__format__()%20was%20already%20int.__format__()%20for%20that%20same%20reason.,-class%20enum.):
> Changed in version 3.11: [`__str__()`](https://docs.python.org/3/reference/datamodel.html#object.__str__) is now `int.__str__()` to better support the replacement of existing constants use-case. [`__format__()`](https://docs.python.org/3/reference/datamodel.html#object.__format__) was already `int.__format__()` …

fix: replace IntEnum with Enum for DatasetRole

---

pyproject.toml

HDBSCAN is failing due to the latest release of scikit-learn (1.3.0)
see https://github.com/scikit-learn-contrib/hdbscan/issues/597

fix: restrict scikit-learn version

---

app/src/store/__generated__/pointCloudStore_eventsQuery.graphql.ts
app/src/store/pointCloudStore.ts

resolves #914 
Neglected to notice that the prediction / actual dimensions are not a part of the dimensions resolved from an event and need special casing. This is a tad awkward and requires special casing but it works for now as a short term solution.

fix(embeddings): color by score values in the point-cloud

---

src/phoenix/session/session.py

resolves #945 
px.launch_app was failing when `corpus` was missing due to the `__call__` length validation in `Model`

fix: Only initialize the corpus model if it exists

---

pyproject.toml

resolves #937 
Due to the cython 3 release, HDBSCAN needed to issue a series of patches. This hopefully is the last one that downgrades their compilation to be compatible.

fix: pin HDBSCAN to cython3 compatible version

---

app/package-lock.json
app/package.json
app/src/@types/dataset.d.ts
app/src/components/pointcloud/PointCloudPointTooltip.tsx
app/src/contexts/DatasetsContext.tsx
app/src/pages/dimension/DimensionCardinalityStats.tsx
app/src/pages/dimension/DimensionPercentEmptyStats.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/types.ts
app/src/store/__generated__/pointCloudStore_eventsQuery.graphql.ts
app/src/store/pointCloudStore.ts
src/phoenix/datasets/fixtures.py

resolves #942 
This PR shows the retrieved documents for a retrieval embedding on the detail view so you can view the details of the retrieval.

feat: show retrieval in the slide-over

---

app/src/GlobalStyles.tsx
app/src/components/pointcloud/ClusterItem.tsx
app/src/components/pointcloud/EventItem.tsx
app/src/components/pointcloud/PointCloudPointTooltip.tsx
app/src/components/pointcloud/PointCloudPoints.tsx
app/src/pages/embedding/Embedding.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/MetricSelector.tsx
app/src/pages/embedding/MetricTimeSeries.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/PointSelectionTable.tsx
app/src/pages/embedding/__generated__/EmbeddingUMAPQuery.graphql.ts
app/src/pages/embedding/__generated__/PointSelectionPanelContentQuery.graphql.ts
app/src/pages/embedding/types.ts
app/src/store/__generated__/pointCloudStore_clusterMetricsQuery.graphql.ts
app/src/store/__generated__/pointCloudStore_clustersQuery.graphql.ts
app/src/store/pointCloudStore.ts
app/src/utils/metricFormatUtils.ts
src/phoenix/datasets/fixtures.py

resolves #928 
Adds a corpus ratio metric as "% query" to the clusters so you can identify clusters that have insufficient supporting documents. Not a perfect metric by any means and requires further investigation.

feat(embeddings): show corpus percent query

---

src/phoenix/metrics/__init__.py

fix: suppress numpy runtime warnings about empty inputs

---

src/phoenix/datasets/validation.py
tests/datasets/test_dataset.py

We need to allow ISO 8601 timestamps for compatibility with the [OpenInference timestamp format](https://github.com/Arize-ai/open-inference-spec/blob/main/spec/timestamp.md). Our current validation code prevents Phoenix from launching with strings in the timestamp column. I've removed this code and rely on the validation [here](https://github.com/Arize-ai/phoenix/blob/315147b9ebe25dfda1ac7cfb227342e934f6bfe7/src/phoenix/datasets/dataset.py#L431), which currently handles the case where the timestamp is a string.

feat: allow iso 8601 timestamps

---

src/phoenix/datasets/fixtures.py
src/phoenix/datasets/schema.py
tests/datasets/test_schema.py

resolves #941 
Adds attribute aliases to make corpus dataset construction more declarative. This avoids doing all the plumbing in favor of just re-mapping the columns as they serve the same functionality.
```python
corpus_schema=Schema(
id_column_name="id",
document_column_names=EmbeddingColumnNames(
vector_column_name="embedding",
raw_data_column_name="text",
),
)
```

feat(datasets): make corpus schema declaration more semantic

---

src/phoenix/core/model_schema.py
src/phoenix/core/model_schema_adapter.py
src/phoenix/metrics/binning.py
src/phoenix/metrics/timeseries.py
tests/core/test_model_schema.py
tests/metrics/test_binning.py

copy= for set_axis is new in pandas version 1.5.0

fix: remove copy= from set_axis for older pandas

---

app/schema.graphql
app/src/pages/trace/SpansTable.tsx
app/src/pages/trace/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/trace/__generated__/SpansTable_spans.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Model.py
src/phoenix/server/api/types/SortDir.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/trace_dataset.py

resolves #1062 
resolves #1069
NB: does not include UI sorting.
Adds graphql sorting support for start/end times and sorting based on the startTime. For now only supporting single column sort, though we could extend this pretty easily by making it a list of sorts in the future.

feat(tracing): graphQL span time bookends and sorting

---

app/package.json
app/src/contexts/TimeRangeContext.tsx

Snaps the timestamps to the end of the day for larger time ranges to make the time buckets more intuitive.

fix: snap to end of day

---

src/phoenix/datasets/dataset.py
src/phoenix/datasets/errors.py
tests/datasets/test_dataset.py

Fixes https://github.com/Arize-ai/phoenix/issues/404 (column not found :laughing:). The exception message now says:
> DatasetError: The following columns are declared in the Schema but are not found in the dataframe: prediction_id.
instead of:
> DatasetError: [MissingColumns]
More generally, the `DatasetError` message now shows the messages of the inner `ValidationError`s (separated by newlines) so dataset errors in general should become easier to understand.
I've removed the error logging because 'log and raise' is often considered an antipattern, and I'm *assuming* that the original motivation was that the inner error messages weren't visible otherwise as they are now, but I can easily revert that if the assumption is wrong.

fix(datasets): Show inner error messages in DatasetError.__str__

---

pyproject.toml
scripts/data/build_langchain_vector_store.py

> tests/experimental/callbacks/conftest.py:4: in <module>
from llama_index.embeddings.base import BaseEmbedding
../../../Library/Application Support/hatch/env/virtual/arize-phoenix/ms61Mhcn/test.py3.8/lib/python3.8/site-packages/llama_index/__init__.py:12: in <module>
from llama_index.data_structs.struct_type import IndexStructType
../../../Library/Application Support/hatch/env/virtual/arize-phoenix/ms61Mhcn/test.py3.8/lib/python3.8/site-packages/llama_index/data_structs/__init__.py:3: in <module>
from llama_index.data_structs.data_structs import (
../../../Library/Application Support/hatch/env/virtual/arize-phoenix/ms61Mhcn/test.py3.8/lib/python3.8/site-packages/llama_index/data_structs/data_structs.py:14: in <module>
from llama_index.schema import BaseNode, TextNode …

fix: restricting pydantic version for unit tests with llama-index

---

app/schema.graphql
app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
src/phoenix/server/api/types/Span.py

As an API consumer, it's better to be able to know if IO is entirely missing or does exist in it's entirety. This adjusts it so that the typing is simpler as a consumer.

refactor(tracing): make SpanIO type have mimetype value pair be required

---

scripts/data/build_langchain_vector_store.py
tutorials/internal/langchain_callback.ipynb

Makes paths a bit more consistent, makes the chain_type easier to swap out, and allows you to compare with langsmith runs.

chore: make langchain notebook and scripts a bit more re-usable

---

pyproject.toml

to side step a recurring problem with OpenAIEmbeddings
> scripts/data/build_langchain_vector_store.py:112: error: Missing named argument "client" for "OpenAIEmbeddings"  [call-arg]

ci: exclude scripts/data from type checks

---

src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py
src/phoenix/trace/semantic_conventions.py
tests/server/api/types/test_span.py

resolves #1253 
Aligns the messages to more closely corrolate with how OpenAI structures things and also conforms more closely to the semantic conventions.
expample: 
```json
[
{
"message.role": "system",
"message.content": "You are an expert Q&A system that is trusted around the world.\nAlways answer the query using the provided context information, and not prior knowledge.\nSome rules to follow:\n1. Never directly reference the given context in your answer.\n2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines."
},
{
"message.role": "user",
"message.content": "Context information is below.\n---------------------\nIf the 'Data Ingestion' tab shows values that deviate from what's expected, dig into potential ingestion issues …
```

refactor(tracing): change llm messages to a list of objects

---

pyproject.toml

Resolves #1277
From the [release notes for pandas 1.5.0](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html):

fix: pin pandas version greater than or equal to 1.5.0

---

src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py

Function calls touch external APIs and should be considered `tools`

fix(tracing): capture function calls as tools

---

src/phoenix/experimental/evals/__init__.py
src/phoenix/experimental/evals/functions/__init__.py
src/phoenix/experimental/evals/functions/binary.py
src/phoenix/experimental/evals/functions/common.py
src/phoenix/experimental/evals/functions/generate.py
src/phoenix/experimental/evals/templates/__init__.py
src/phoenix/experimental/evals/templates/template.py
tests/experimental/evals/functions/test_generate.py

resolves #1309 
This PR adds `llm_generate` which lets you use the LLM to synthesize data per row by applying the template. This is useful for debugging or even for synthesizing data that is needed for evaluation like a bad response or GPT answer to use as a comparison.

feat(evals): llm_generate for synthesizing data

---

pyproject.toml

earlier versions not compatible because they don't have `CBEventType.AGENT_STEP`

ci: bump llama-index version

---

src/phoenix/experimental/evals/functions/binary.py
src/phoenix/experimental/evals/models/base.py
tutorials/internal/logging.ipynb

Improves logging for users of `llm_eval_binary`.
For developers iterating on prompts in their notebook, they can enable logging in their notebook with the following lines:
```python
import logging
import sys
logging.basicConfig(level=logging.INFO, stream=sys.stdout)
```
Example output when using our RAG relevancy template.
```python
INFO:phoenix.experimental.evals.models.base:Prompt: 
You are comparing a reference text to a question and trying to determine if the reference text
contains information relevant to answering the question. Here is the data:
[BEGIN DATA]
************
[Question]: how are glacier caves formed?
************
[Reference text]: A partly submerged glacier cave on Perito Moreno Glacier . The ice facade is approximately 60 m high Ice formations in the Titlis glacier cave …
```

chore: improve logging for llm_eval_binary

---

src/phoenix/trace/llama_index/callback.py

resolves #1378 
Also see llama-index [source code](https://github.com/jerryjliu/llama_index/blob/5b8d3295665541232e9dc3ba0ed3946918e5fb9a/llama_index/llm_predictor/base.py#L127-L130)

fix: handle templating event in llama-index

---

src/phoenix/session/session.py

if server fails to start, the error message references the `port` variable, so it needs to be filled out beforehand

fix: missing `port` value in error message

---

pyproject.toml

note that both works, but underscore looks like a typo

fix: typo in requirements

---

src/phoenix/server/api/schema.py
tests/pointcloud/test_pointcloud.py

this fixes the unit tests for Python 3.11 (windows)
```TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.```

fix: np.stack argument deprecation

---

pyproject.toml
src/phoenix/server/app.py
src/phoenix/server/templates/index.html

resolves #1400 
Switches the mounding of index.html to be server-side so that we can inject environment variables and other config. This will potentially unblock mounting static assets for Sagemaker/Databricks notebooks as well as #1224 so that the defaults can be mounted into the browser runtime pre-react rendering.

feat(infra): server-side template for index.html

---

tutorials/evals/evaluate_toxicity_classifications.ipynb

- fixes bug preventing toxicity notebook from running
This bug is introduced by our formatter, which converts `df[df["toxic"] == True]` to `df[df["toxic"] is True]`. I changed it to something that the formatter won't mess up.

fix: toxicity notebook bug

---

src/phoenix/experimental/evals/retrievals.py

- contain `openai` dependency
We recently removed `openai` as a dependency in our `experimental` extra [here](https://github.com/Arize-ai/phoenix/pull/1470). We need to contain the dependency now.

fix: contain openai dependency

---

app/src/openInference/tracing/semanticConventions.ts
app/src/pages/trace/TracePage.tsx

resolves #1493 
Display the model name as the title if it exists

feat(trace): show the model name in the LLM span info

---

app/src/openInference/tracing/semanticConventions.ts
app/src/openInference/tracing/types.ts
app/src/pages/trace/TracePage.tsx

Adds prompt template UI in the LLM import card to display which parts is the template and which parts are variables.

feat(trace): prompt template UI

---

src/phoenix/experimental/evals/functions/binary.py
tests/experimental/evals/functions/test_binary.py

resolves https://github.com/Arize-ai/phoenix/issues/1331
- enhance `run_relevance_eval` to accept documents strings or objects in the document column
- simplify implementation
- update unit test

feat: enhance input types of run_relevance_eval

---

scripts/rag/llama_index_w_evals_and_qa.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/vertexai.py

This PR fixes the following error. When using a `VertexAIModel` the abstract methods were not included, hence the instantiation failed
```python
from phoenix.experimental.evals import VertexAIModel
model = VertexAIModel()
TypeError: Can't instantiate abstract class VertexAIModel with abstract methods encoder, get_text_from_tokens, get_tokens_from_text, max_context_size
```

fix: Add uninmplemented methods to `VertexAIModel` from abstract class

---

src/phoenix/server/thread_server.py

https://github.com/Arize-ai/phoenix/assets/80478925/90300cd5-edce-4255-a7b9-6d23479c1f87
https://github.com/Arize-ai/phoenix/assets/80478925/f804234d-1fb4-4d8a-9fff-f193459c58d2

fix: server thread should be daemon

---

README.md

I was running this example and noticed the model and template arguments are reversed.
Specifically, [`model` comes before `template`](https://github.com/Arize-ai/phoenix/blob/main/src/phoenix/experimental/evals/functions/binary.py#L24)

fix: llm_eval_binary Argument Order in README.md

---

app/package-lock.json
app/package.json
app/src/GlobalStyles.tsx
app/src/components/chart/defaults.tsx
app/src/components/nav/Navbar.tsx
app/src/components/pointcloud/ClusterItem.tsx
app/src/pages/dimension/DimensionCardinalityStats.tsx
app/src/pages/dimension/DimensionCardinalityTimeSeries.tsx
app/src/pages/dimension/DimensionCountStats.tsx
app/src/pages/dimension/DimensionCountTimeSeries.tsx
app/src/pages/dimension/DimensionDriftBreakdownSegmentBarChart.tsx
app/src/pages/dimension/DimensionDriftStats.tsx
app/src/pages/dimension/DimensionDriftTimeSeries.tsx
app/src/pages/dimension/DimensionPercentEmptyStats.tsx
app/src/pages/dimension/DimensionPercentEmptyTimeSeries.tsx
app/src/pages/dimension/DimensionQuantilesStats.tsx
app/src/pages/dimension/DimensionQuantilesTimeSeries.tsx
app/src/pages/dimension/DimensionSegmentsBarChart.tsx
app/src/pages/embedding/ClusterSortPicker.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/MetricTimeSeries.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/tracing/TracingHomePageHeader.tsx

This makes it so we use semantic color names rather than explicit colors so that we can eventually rotate the theme for light mode.
It also removes the crazy noise in the console.

chore: use semantic text color instead of white

---

scripts/data/build_llama_index_with_markdown_section_summaries.py

Adds the summary-embedding index builder to `scripts`.
This script persists a `LlamaIndex` `VectorStoreIndex` over our documentation. It loosely chunks over markdown sections, and uses the markdown section heirarchy and `QuestionsAnsweredExtractor` to generate metadata for each chunk. Embeddings are built on summaries of each chunk.
closes: #1503
TODO: automate uploading the index to GCS

chore: Add summary index builder script

---

app/schema.graphql
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/ValidationResult.py

resolves #1574 
This validation endpoint for the python query string is needed because the UI needs the ability to construct a query without the server erroring out and to place the error_message directly on the input validation.
```graphql
{
validateSpanFilterCondition(condition: "span_kind=='llm' and context.trace_id == 'abc'") {
isValid
errorMessage
}
}
```

feat(tracing): gql validate_span_filter_condition

---

src/phoenix/experimental/evals/models/bedrock.py

Without a type, this argument isn't settable in the constructor. I set to `Any` here to avoid a global requirement on boto

fix(evals): Set client type in bedrock.py for constructor

---

DEVELOPMENT.md
README.md
examples/anthropic_evals_persona.ipynb
examples/dolly-pythia-fine-tuned/dolly_vs_pythia.ipynb
examples/taylor_swift_lyrics.ipynb
scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
tutorials/credit_card_fraud_tutorial.ipynb
tutorials/evals/evaluate_QA_classifications.ipynb
tutorials/evals/evaluate_code_readability_classifications.ipynb
tutorials/evals/evaluate_hallucination_classifications.ipynb
tutorials/evals/evaluate_relevance_classifications.ipynb
tutorials/evals/evaluate_summarization_classifications.ipynb
tutorials/evals/evaluate_toxicity_classifications.ipynb
tutorials/example_datasets.ipynb
tutorials/internal/langchain_retrieval_qa_with_sources_chain_tracing_tutorial.ipynb
tutorials/internal/llama_index_tracing_example.ipynb
tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb
tutorials/llama_index_search_and_retrieval_tutorial.ipynb
tutorials/llm_summarization_tutorial.ipynb
tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb
tutorials/sentiment_classification_tutorial.ipynb
tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb
tutorials/tracing/openai_tracing_tutorial.ipynb

Removes `-q`, `-qq`, and `-qqq` flags from all notebooks and installation guides. These flags are swallowing the "Restart Runtime" button on Colab when there is an installation issue, making it more difficult for users to troubleshoot installation issues themselves.

fix: remove quiet flags

---

src/phoenix/trace/llama_index/callback.py
src/phoenix/utilities/error_handling.py
tests/trace/llama_index/test_callback.py
tests/utilities/test_error_handling.py

`phoenix` instrumentation should not cause errors in user code. Here I add a pattern to gracefully degrade the behavior of methods that might raise exceptions in situations where an error would be undesirable.
The motivation is that we want to avoid simply suppressing exceptions in our instrumentation code because that will make it extremely hard to debug issues in the future. As an alternative, we can use a graceful degredation pattern where we fall back to more limited, but less-error prone codepath. Additionally, any time we fall back the error we encountered is logged instead of raised.
resolves #1579

fix: `LlamaIndex` callback handler should fail gracefully

---

src/phoenix/experimental/evals/models/openai.py

resolves #1586 
Removes trivial warnings that were producing needless noise.
I did a scan through some other warnings we raise and I thought these might also be candidates for removal:
- A warning about `tiktoken` fallbacks if an appropriate model can't be found
- A warning about not finding excluded columns when processing data
What do you think @mikeldking?

fix: Remove trivial warnings

---

pyproject.toml
src/phoenix/utilities/error_handling.py

resolves #1619 
This PR also puts a version ceiling on `typing-extensions<4.6.0` for our CI because that's what's in Colab right now.
> tensorflow 2.13.0 requires typing-extensions<4.6.0

fix: failed imports from typing_extensions 4.5.0 in Colab

---

app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
src/phoenix/__init__.py

Because every keystroke invokes a query, the suspense boundary is getting hit. This should make the boundary not hit but I should also consider adding a throttling. https://github.com/Arize-ai/phoenix/issues/1623

fix(tracing): suspense boundary causing search to lose focus

---

src/phoenix/experimental/evals/models/openai.py

I'm finding I'm needing to set this to 20 for a lot of general use cases for timeouts and backoffs to work correctly. Setting this to the default, as not sure most people will figure this out on their own.

feat(evals): default retry to 20, needs to be higher

---

.pre-commit-config.yaml

ci: Exclude evals notebooks from cleaning output in .pre-commit-config.yaml

---

.github/workflows/publish-to-pypi.yml
src/phoenix/__init__.py

Based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows

ci: add git workflow for pypi publishing

---

src/phoenix/trace/evaluation_conventions.py
src/phoenix/trace/semantic_conventions.py

resolves #1585 
This PR aims to outline the MVP set of span attributes that would be used to start annotating span attributes with the necessary evals to augment the trace data for analysis based on evals.
Note that this data doesn't have to exist with the span but the colocation does result in an easily digestible payload that can be stored.
Example attributes payload where evaluation values are added in addition to the runtime conventions.
```json
{
"attributes": {
"eval.documents_relevancy_percent": 66.6,
"eval.precision_at_1": 1,
"eval.precision_at_2": 0.5,
"eval.precision_at_3": 0.66,
"documents": [
{
"eval.document_relevancy": 1,
},
{
"eval.document_relevancy": 0,
},
{
"eval.document_relevancy": 1,
}
]
}
}
```
- prefixing all evals with the eval moniker seemed like the cleanest way …

feat(rag): eval relevancy conventions

---

.github/workflows/python-CI.yml
src/phoenix/trace/evaluation_conventions.py

ci: stub out open AI key during CI to avoid embedding model downloads in llama_index

---

src/phoenix/trace/langchain/tracer.py

adds `name=` to `Run`
mirrors langchain [commit](https://github.com/langchain-ai/langchain/commit/3d5e92e3ef0506f8f5b937767c5a58b584d6e58d#diff-7097b49b501f7bcb4e4c3fff6f0976d4d8462be875b665894df1df5d8d1eb2c8)

fix: type check issue in langchain tracer

---

pyproject.toml

because #1671 results in runtime incompatibility with older versions of langchain

ci: increase langchain version for hatch env

---

src/phoenix/trace/llama_index/callback.py
tests/trace/llama_index/conftest.py
tests/trace/llama_index/test_callback.py

resolves #1667 
When custom models are implemented, it seems as though the usage payload can be appended to the `additional_kwargs` as a dictionary. This adds a bit of redundancy that to look for the usage metrics in either place. This provides a bit more flexibility for custom models. 
In addition this adds a bit of robustness arround the type `usage` - as it now handles both `Mapping` and `object` - a tad confusing as `Mapping` so it seems like `get` could be the common method?

fix(traces): support token counts for custom models in llama_index

---

examples/dolly-pythia-fine-tuned/create_data_with_dolly_and_pythia.ipynb
pyproject.toml
src/phoenix/trace/langchain/tracer.py
src/phoenix/trace/v1/__init__.py
tutorials/evals/evaluate_QA_classifications.ipynb
tutorials/evals/evaluate_summarization_classifications.ipynb
tutorials/llm_generative_gpt_4.ipynb

resolves #1658 
Simplify CI toolchain by removing `black` in favor of `ruff format`
With the release of [ruff formatter](https://github.com/astral-sh/ruff/releases/tag/v0.1.3), we can use ruff for both formatting and linting, improving consistency and issues with black and ruff disagreeing with eachother.
For now I'm leaving out the jupyter notebook extension, since reformatting our notebooks will lead to a significant number of changes.

ci: Use ruff formatter

---

app/package.json
app/src/Routes.tsx
app/src/contexts/StreamStateContext.tsx
app/src/pages/ErrorElement.tsx
app/src/pages/TracingRoot.tsx
app/src/pages/index.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/StreamToggle.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/TracingHomePage.tsx
app/src/pages/tracing/TracingHomePageHeader.tsx
app/src/pages/tracing/__generated__/TracingHomePageHeaderQuery.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageHeader_stats.graphql.ts

resolves #1674 
From a user's perspective, this makes it so that you can continue to stream traces / spans even when you have a filter condition set.
This fixes the fact that `react-relay` makes the refetchable fragments "stateful" once the params are changed. This means that a new query at the root query has no bearing on the fragment (e.g. it becomes detached). This PR adds a `fetchKey` that tracks the number of traces and refeches all fragments related to. traces if that key changes.

fix(traces): refetch traces and spans even when searching

---

app/package-lock.json
app/package.json
app/src/pages/tracing/SpanColumnSelector.tsx
app/src/pages/tracing/SpanFilterConditionField.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/styles.tsx

related to #1639 
This adds scaffolding for hiding columns on the span and traces tables, leaving room for adding dynamic columns such as evaluation results of spans. This PR doesn't encompass some potential follow-ups such as local storage and syncing of columns across tabs.
https://github.com/Arize-ai/phoenix/assets/5640648/bd0df3ca-13b4-4f92-a833-8031a01a6f6f

feat(traces): span table column visibility controls

---

src/phoenix/experimental/evals/models/__init__.py

Adds the ability for the user to import `BedrockModel` in the following manner
```python
from phoenix.experimental.evals.models import BedrockModel
```
in keeping with other model types.

fix: enable BedrockModel to be imported directly from phoenix.evals.models sub-module

---

pyproject.toml
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/models/rate_limiters.py
tests/experimental/evals/functions/test_classify.py
tests/experimental/evals/functions/test_generate.py

This implements clientside ratelimiting for the OpenAI API.
recreating #1680 due to a rebase messing with the diff
Our objective is to submit API requests as fast as possible without running into rate limit issues. Our solution is to implement a clientside ratelimiter that throttles asyncronous ChatCompletion calls. For the time being I've overridden the generate method on the OpenAI model. Our other models do not have a rate limiter implemented yet and so cannot move to this asyncronous submission pattern.

feat: Asyncronously submit openai requests 

---

cspell.json
src/phoenix/trace/semantic_conventions.py
tests/trace/test_schemas.py
tests/trace/test_tracer.py

Just removing dead code that was a strawman of the semantic conventions organization

chore(traces): remove unused semantic conventions

---

app/src/Routes.tsx

resolves #1708
The traces route was no longer still mounting the home page due to how a react-router outlet was added to the root of the rooute and the index route then became a sibling.

fix(traces): Keep traces visible behind the details slideover

---

src/phoenix/experimental/evals/__init__.py
src/phoenix/experimental/evals/functions/__init__.py
src/phoenix/experimental/evals/functions/classify.py

- removes `llm_eval_binary`, which has been deprecated in favor of `llm_classify`

feat: remove llm_eval_binary

---

pyproject.toml

OpenAI released a major upgrade with breaking changes. This PR pins the `openai` dependency below 1.0.0 for the time being so the pipeline doesn't break.

fix: pin openai version below 1.0.0

---

pyproject.toml
src/phoenix/experimental/evals/functions/classify.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/models/vertexai.py
src/phoenix/utilities/logging.py
tests/experimental/evals/functions/test_classify.py

- Updates `llm_classify` to snap to rail after each LLM call.
- Edits `__call__` on `BaseEvalModel` to use single-record `_generate` rather than batch `generate`. This makes more sense since `__call__` is invoked on single records. It is also needed to avoid weird behavior with progress bars.
- Converts `_verbose_generation_info` to `verbose_generation_info` (i.e., makes it a public method) and moves the responsibility for verbose logging to the caller.
- Changes `printif` to use `tqdm.auto.tqdm.write` for compatibility with `tqdm` progress bars.

refactor: snap to rail after each llm call

---

src/phoenix/trace/langchain/tracer.py

resolves #1719 
Matching prefix is effectively the same as calling [`isinstance`](https://github.com/langchain-ai/langchain/blob/58da6e0d476d3b3554c30d68c847ce93b5194924/libs/langchain/langchain/schema/messages.py#L43). It's not totally clear what's specifically distinct about [`AIMessageChunk`](https://github.com/langchain-ai/langchain/blob/58da6e0d476d3b3554c30d68c847ce93b5194924/libs/langchain/langchain/schema/messages.py#L207). All we know right now is that it's a subclass of `AIMessage`.

fix(traces): handle AIMessageChunk in langchain tracer by matching prefix in name

---

src/phoenix/trace/openai/instrumentor.py
tests/trace/openai/test_instrumentor.py
tutorials/evals/evaluate_code_readability_classifications.ipynb
tutorials/evals/evaluate_hallucination_classifications.ipynb
tutorials/evals/evaluate_relevance_classifications.ipynb
tutorials/tracing/openai_tracing_tutorial.ipynb

- updates `OpenAIInstrumentor` to support `openai>=1.0.0`
- deprecates support for `openai<1.0.0`
- improves test fixtures to instantiate client from reloaded modules (necessary since the originally imported modules are patched by `OpenAIInstrumentor.instrument`)
- updates structured data extraction tutorial notebook and pins `openai>=1.0.0`

feat: update OpenAIInstrumentor to support openai>=1.0.0 and deprecate support for openai<1.0.0

---

.github/workflows/publish-to-pypi.yml

This reverts commit 286ac4adb4d0cda7bbd0b20aaa331f4e3df037eb.

chore: Revert "chore: publish to pypi when a release is published (#1726)"

---

src/phoenix/experimental/evals/functions/generate.py
tests/experimental/evals/functions/test_generate.py

resolves #1713
In more custom cases, there's a need to parse the output of llm_generate - e.x. trying to extract two labels at once. This also supports providing explanations as part of JSON output if needed. Also GPT-4-Turbo has JSON mode so this helps with that as well.
NB: this is a breaking change but it's under experimental so treating it as a feature.

feat(evals): add an output_parser to llm_generate

---

src/phoenix/trace/langchain/instrumentor.py
src/phoenix/trace/langchain/tracer.py

> src/phoenix/trace/langchain/tracer.py:286: error: Class cannot subclass "BaseTracer" (has type "Any")  [misc]
> src/phoenix/trace/langchain/instrumentor.py:37: error: Unused "type: ignore" comment  [unused-ignore]

ci: fix type checks

---

app/src/pages/trace/TracePage.tsx
integration-tests/trace/llama_index/test_callback.py
pyproject.toml
src/phoenix/trace/llama_index/callback.py
src/phoenix/trace/utils.py
tests/trace/llama_index/test_callback.py

resolves #1747 
1. Added `tool` as a new message role, because the `function` role is deprecated. (This is the result of the function call that we send back to openai as part of a chat)
2. Check the minimum version for llama-index at `0.9.0` at when initializing the tracer.
3. For the `ToolMetata` object from llama-index, change `tool_metadata.to_openai_function()["parameters"]` to `tool_metadata.to_openai_tool()["function"]["parameters"]` because the former is deprecated, and its underlying dictionary structure has changed.
4. Multiple function calls is now possible in the OpenAI response message (i.e. the new `tool_calls` is a list, the old `function_call`, which is singular, is deprecated). But we're only capturing the first one for now. A follow-up PR will be needed to capture all.

fix: update tracer for llama-index 0.9.0

---

src/phoenix/server/main.py

for a future PR with evaluations (in addition to spans)

refactor: generalize helper function for streaming simulation

---

Dockerfile
app/src/RelayEnvironment.ts
app/src/Routes.tsx
app/src/window.d.ts
cspell.json
src/phoenix/__init__.py
src/phoenix/config.py
src/phoenix/server/app.py
src/phoenix/server/templates/index.html
src/phoenix/session/session.py
src/phoenix/trace/exporter.py

resolves: #675 
Adds support for sagemaker by detecting the notebook environment and also adjusting the `basename` of the application to be `/proxy/6006`. It seems 6006 is the port of choice since it's left open for tensorboard so just made the shift to that port.

feat: sagemaker nobebook support

---

src/phoenix/__init__.py
src/phoenix/config.py
src/phoenix/session/session.py

Give a way for the user to set the notebook environment manually so that if the feature detection via imports fails, the user can still declare the notebook environment they are using. sagemaker seems to be failing feature detection.

chore: give a way to manually set the notebook environment

---

src/phoenix/services.py

Process session was broken due to the fact that the params were out of order.

fix: restore process session

---

src/phoenix/server/thread_server.py

resolves #1353
This resolves the issue that nest asyncio makes the application fail to launch. Many notebooks, including ones from llamaIndex, have nest_asyncio applied at the top. In these cases the server cannot crash. This makes it so that the server runs via the "asyncio" eventloop when it is applied.
```python
import os
import phoenix as px
import logging
import nest_asyncio
nest_asyncio.apply()
logging.basicConfig(level=logging.INFO)
px.launch_app()
```
```
INFO:phoenix.session.session:Running Phoenix in a process
INFO:phoenix.services:command: [/Users/mikeldking/.virtualenvs/phoenix/bin/python](https://file+.vscode-resource.vscode-cdn.net/Users/mikeldking/.virtualenvs/phoenix/bin/python) main.py --export_path [/var/folders/1s/4vdv59n15b1ghg42frdd8f480000gn/T/tmp1z1xx6_c/exports](htt …
```

fix: make the app launchable when nest_asyncio is applied

---

src/phoenix/config.py
src/phoenix/trace/exporter.py
tests/trace/test_exporter.py

resolves #1793 
This PR introduces an `endpoint` config for the exporter so that we don't assume that the phoenix server is running locally. This is needed for various use-cases:
Phoenix can now be running on an EC2 instance or other
Phoenix might have to be running in Sagemaker studio in a separate process (Networking failing right now but in theory this might be the configuration)

feat(traces): configurable endpoint for the exporter

---

src/phoenix/experimental/evals/functions/classify.py

- pass synchronous function to `SyncExecutor`

fix: pass sync function to executor

---

src/phoenix/trace/v1/utils.py

resolves #1758
based on the types found in [_SetStructValue](https://github.com/protocolbuffers/protobuf/blob/5a3dac894157bf3618b2c906a8b9073b4cad62b6/python/google/protobuf/internal/well_known_types.py#L733C42) which is shown below
Note that our protobuf version (3.20) does not accept `tuple`, so we have to convert it to list.
```python
def _SetStructValue(struct_value, value):
if value is None:
struct_value.null_value = 0
elif isinstance(value, bool):
struct_value.bool_value = value
elif isinstance(value, str):
struct_value.string_value = value
elif isinstance(value, (int, float)):
struct_value.number_value = value
elif isinstance(value, (dict, Struct)):
struct_value.struct_value.Clear()
struct_value.struct_value.update(value)
elif isinstance(value, (list, ListValue)): …
```

fix(traces): convert (non-list) iterables to lists during protobuf construction due to potential presence of ndarray when reading from parquet files

---

pyproject.toml

LlamaIndex recently updated their callback system so that exceptions are attached to the same. This PR pins the version of LlamaIndex below this most recent change until we've updated the callbacks to reflect the change.
Related PRs and issues:
- https://github.com/run-llama/llama_index/issues/9070
- https://github.com/Arize-ai/phoenix/issues/1618

fix: pin llama-index temporarily

---

tests/trace/llama_index/test_callback.py
tutorials/internal/llama_index_tracing_stream_example.ipynb

research for #1572 
Adds a notebook that uses llama-index `query_engine` streaming. Demonstrates that while we successfully log queries, the streaming generator has already been consumed and will not yield results.

chore: Add LlamaIndex streaming notebook

---

pyproject.toml
src/phoenix/core/evals.py
src/phoenix/trace/exporter.py

Notes:
1. `assert_never` is only available in typing-extension 4.1.0+. See [here](https://typing.readthedocs.io/en/latest/source/unreachable.html) for more info.
2. strawberry has typing-extension>=4.5 since [0.187.1](https://github.com/strawberry-graphql/strawberry/releases/tag/0.187.1) (6/21/23), so setting it lower by us than that won't change anything
3. colab has typing-extension 4.5.0
4. sagemaker has typing-extension 4.1.1, which will be upgraded when strawberry is installed

refactor: type check for exhaustive branching (using `assert_never` from typing-extension 4.1.0+)

---

app/package-lock.json
app/package.json
app/src/components/table/styles.ts
app/src/pages/trace/SpanEvaluationsTable.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/SpanEvaluationsTable_evals.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
app/src/pages/tracing/SpansTable.tsx

resolves #1774 
Displays a span's evaluations in the trace details view for troubleshooting the span itself.

feat(evals): show span evaluations in trace details slideout

---

src/phoenix/core/traces.py
src/phoenix/proto/trace/v1/trace.proto
src/phoenix/trace/v1/trace_pb2.py
src/phoenix/trace/v1/trace_pb2.pyi
src/phoenix/trace/v1/utils.py
tests/trace/test_schemas.py

I think it was a mistake to use bytes to begin with, since string is much simpler overall. It's also much more readable as string when it's converted to JSON.

refactor: use string for span and trace id in protos

---

pyproject.toml
src/phoenix/trace/llama_index/callback.py
tests/trace/llama_index/test_callback.py
tutorials/internal/llama_index_tracing_example.ipynb

LlamaIndex recently changed the way their callback system handles exception information. Previously, exceptions always resulted in independent exception callback events. Now, whenever possible, exception information is passed via the `on_event_end` callback hook for the callback event that caused the exception. When that is not possible (e.g., when the exception arises outside of any event), the callback system produces an independent exception event containing the exception information. This latter scenario should be rare and indicates that there is a bug in LlamaIndex itself.
This PR adjusts our callback handler to accommodate these changes. In particular, it searches each callback event payload for an `EventPayload.EXCEPTION` key, and if present, grabs the exception information from …

fix: enhance llama-index callback support for exception events

---

app/src/contexts/TracingContext.tsx
app/src/pages/TracingRoot.tsx
app/src/pages/tracing/SpanColumnSelector.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
app/src/store/index.tsx
app/src/store/tracingStore.tsx
cspell.json

resolves #1807 
Makes the column selector work on the spans tab and keeps the visibility state in sync across the two tabs by creating a central zustand store (which will be extended).

fix(traces): make column selector sync'd between tabs

---

app/src/components/trace/types.ts
app/src/pages/tracing/EvaluationLabel.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts

resolves #1163 
This PR adds a single "evaluations" column so that you can at a glance view all the evaluations. There will be a follow-up to display each evaluation in it's own column for sorting but this lets you view all the evals at a glance and is MVP ready.

feat(traces): show all evaluations in the table"

---

app/schema.graphql
app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
src/phoenix/core/evals.py
src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/schema.py
tests/server/api/input_types/test_SpanSort.py

resolves #1776 
https://github.com/Arize-ai/phoenix/assets/80478925/b0407ceb-2083-49aa-abe3-c45625764677

feat(traces): server-side sort of spans by evaluation result (score or label)

---

app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts

resolves: #1822 
Adds an evaluations section alongside each document to display the relevance of each document. Highlights irrelevant documents in red to make it stand out.

feat(traces): display document evaluations alongside the document

---

app/src/components/trace/SpanStatusCodeIcon.tsx
app/src/components/trace/useSpanStatusCodeColor.ts
app/src/pages/trace/TracePage.tsx
app/src/pages/tracing/TracingHomePageHeader.tsx
cspell.json

resolves #1827 
Adds a header to the trace page to show the trace level info, notably shows the evaluations that correl
ate with the entire trace.

feat(traces): Trace page header with latency, status, and evaluations

---

src/phoenix/trace/openai/instrumentor.py
src/phoenix/trace/schemas.py
src/phoenix/trace/tracer.py
tests/trace/llama_index/test_callback.py
tests/trace/openai/test_instrumentor.py

Overview
- adds support for openai synchronous streaming
- for synchronous streams, returns an instrumented stream that records span stream events and updates the original span when the stream is exhausted or when an exception is encountered midstream
- adds corresponding unit tests
Future Work
- plumb everything through the ui
- implement support for asynchronous streaming
- implement support for streaming function calls and tool calls

feat: support instrumentation for openai synchronous streaming

---

.pre-commit-config.yaml
src/phoenix/core/traces.py
src/phoenix/trace/openai/instrumentor.py
src/phoenix/trace/tracer.py
tests/trace/openai/test_instrumentor.py
tutorials/internal/openai_request_types.ipynb

- creates a new span only once upon end of iteration
- only creates an event for the first streaming token event, not for each event (otherwise, there are too many events to make sense)
- fix bug preventing span updates, although span updates are not used in this PR
- add notebook for running openai sdk requests of various request types
Trace
First Token Event

feat: openai streaming spans show up in the ui

---

src/phoenix/trace/openai/instrumentor.py
tests/trace/openai/test_instrumentor.py
tutorials/internal/openai_request_types.ipynb

- adds support to `OpenAIInstrumentor` for asynchronous streaming LLM requests
- refactors logic that previously resided in StreamWrapper into a context manager for reusability across synchronous and asynchronous contexts
- adds corresponding unit tests
- adds corresponding section in the openai request types notebook

feat: openai async streaming instrumentation

---

src/phoenix/__init__.py
src/phoenix/session/evaluation.py
src/phoenix/trace/span_evaluations.py
src/phoenix/trace/trace_dataset.py
tests/trace/test_span_evaluations.py
tutorials/internal/trace_eval_ingestion_testing.ipynb

resolves #1701 
1. Add `DocumentEvaluations` alongside `SpanEvaluations`
- Improve validation mechanics 
2. Add `log_evaluations`, which uses an internal `HttpExporter`. This is not ideal, but works for now.
https://github.com/Arize-ai/phoenix/assets/80478925/b73ab200-dfa3-4836-b03b-a34a3f0bd113

refactor(traces): log span and document evaluations

---

src/phoenix/experimental/evals/models/rate_limiters.py

working with @jlopatec 
In rare cases, the task that unsets the event that allows workers to process requests might be timed out and never unsets, locking up the workers. I don't think the locks are strictly necessary so I'm removing them.

fix: Remove the retry handling lock

---

tests/experimental/evals/functions/test_classify.py

this fixes the following errors
> FAILED tests/experimental/evals/functions/test_classify.py::test_llm_classify - RuntimeError: OpenAI's API key not provided. Pass it as an argument to 'api_key' or set it in your environment: 'export OPENAI_API_KEY=sk-****'
FAILED tests/experimental/evals/functions/test_classify.py::test_llm_classify_shows_retry_info - RuntimeError: OpenAI's API key not provided. Pass it as an argument to 'api_key' or set it in your environment: 'export OPENAI_API_KEY=sk-****'
FAILED tests/experimental/evals/functions/test_classify.py::test_classify_tolerance_to_exceptions - RuntimeError: OpenAI's API key not provided. Pass it as an argument to 'api_key' or set it in your environment: 'export OPENAI_API_KEY=sk-****'
FAILED …

ci: add missing `api_key` fixtures in unit tests

---

src/phoenix/experimental/evals/functions/classify.py
src/phoenix/experimental/evals/models/rate_limiters.py

This implements a better way of adding a failsafe for deadlocks caused by waiting on an event forever. We also extend the outer loop timeout to 720 seconds (6 minutes).

fix: Add lock failsafe

---

src/phoenix/server/app.py
src/phoenix/server/main.py

Create a read-only mode flag so that phoenix can be hosted on data but reject appending spans and evals to it. Needed for a demo site.

chore: add a read-only mode

---

src/phoenix/server/templates/index.html

Now that you can host phoenix, we want to have clear titles and open-graph images.

chore: add open graph tags for sharing phoenix via social media

---

src/phoenix/core/traces.py

List is a problem for duplicated spans (e.g. updates).

refactor(traces): use Set instead of List for child span ids graph

---

app/src/pages/trace/TracePage.tsx

Ensures that the alerts icon for exception events is visible. The issue appears to be caused by the fact that the `View` component from the Arize component library has `overflow: hidden`.
https://github.com/Arize-ai/ui-components/blob/adb81aab5ca9cc686a2b73aeabae20726b336e4f/src/view/View.tsx#L35

fix: make alert icon for exceptions visible

---

src/phoenix/trace/otel.py

- Fixes a bug in the LlamaIndex trace callback that was causing bytes to fail to be encoded.
- Improves log messages for uncaught types.

fix: ensure llamaindex spans are correctly encoded

---

src/phoenix/server/main.py

If a network error prevent the fixtures from being read, it should be a fatal error, and the app should not launch.

refactor: materialize fixtures before loading by thread

---

src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/vertex.py
src/phoenix/experimental/evals/templates/default_templates.py
tests/experimental/evals/functions/test_classify.py

resolves #2072
Gemini will not always accept prompts that contains the word "irrelevant", which we are using as a classification label for relevance evals. To avoid needing to store a different prompt for each model, we're changing the "irrelevant" label to "unrelated", which seems to work very similarly.

fix: Adjust evaluation templates and rails for Gemini compatibility

---

src/phoenix/trace/fixtures.py

The previous fixture had deprecated semantic conventions, causing the fixture to not load (see #2012) This simply updates the fixture to the up to date messages conventions

chore(traces): update calculator agent fixture

---

src/phoenix/session/session.py
src/phoenix/trace/errors.py
src/phoenix/trace/span_evaluations.py
src/phoenix/trace/trace_dataset.py
tests/trace/test_span_evaluations.py
tests/trace/test_trace_dataset.py

1. Adds ability to read and write `TraceDataset` instances to parquet while automatically reading and writing any appended evaluations.
Usage with user-specified directory:
```python
dataset = TraceDataset(...)
dataset_id = dataset.save(directory)
loaded_dataset = TraceDataset.load(dataset_id, directory)
```
Usage with default directory:
```python
dataset = TraceDataset(...)
dataset_id = dataset.save()
loaded_dataset = TraceDataset.load(dataset_id)
```
2. Changes API of `Evaluations`. Previously, there were `to_parquet` and `from_parquet` methods uses paths as inputs and outputs. The API has been changed to `save` and `load` methods similar to `TraceDataset`.
Usage with user-specified directory:
```python
evals = SpanEvaluations(...)
eval_id = evals.save(directory)
loaded_evals = …
```

feat: add ability to save and load TraceDatasets

---

src/phoenix/session/session.py

For notebook setting like databricks, we have to listen on 0.0.0.0, but the URL constructed is confusing by default so this presents local notebooks as localhost for a simpler, clearer message.

fix: show localhost when the notebook is running locally

---

src/phoenix/experimental/evals/models/anthropic.py
src/phoenix/experimental/evals/models/bedrock.py

Removes warnings when a tokenizer cannot be loaded for a non-openai model. These warnings were causing confusion.

chore: remove tokenizer warnings

---

src/phoenix/experimental/evals/models/bedrock.py

Resolves #2113
- Properly formats input payload for ai21 Jurassic models
- Properly parses Amazon Titan model outputs

fix: Resolves Bedrock model compatibility issues

---

src/phoenix/experimental/evals/templates/default_templates.py

The same paragraph was added in 2 separate spots in the `HALLUCINATION_PROMPT_BASE_TEMPLATE` and this removes one of the duplicate paragraphs.

chore(evals): Removes duplicate paragraph in hallucination prompt base template

---

src/phoenix/exceptions.py
src/phoenix/experimental/evals/models/anthropic.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/bedrock.py
src/phoenix/experimental/evals/models/openai.py

resolves #2065 
Requests to an LLM with a prompt that exceeds the maximum context window will never succeed, so we should stop retrying on these errors.
Due to the lack of concrete errors that are scoped to exceeding the context window size, we match on the error message instead. OpenAI, Anthropic and Bedrock models have been modified to not retry on the context limit window being hit.
I haven't been able to induce a concrete error using a Gemini model (it will simply hang), so a fix hasn't been implemented for Gemini.

fix: Do not retry when context window has been exceeded

---

pyproject.toml

This fixes following mypy error on github CI. Potential [cause](https://github.com/pydantic/pydantic/pull/8666).
> /home/runner/.local/share/hatch/env/virtual/arize-phoenix/C8K4HrkP/type/lib/python3.8/site-packages/openai/_models.py:408: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
File "mypy/semanal.py", line 6475, in accept
version: 1.5.1
/home/runner/.local/share/hatch/env/virtual/arize-phoenix/C8K4HrkP/type/lib/python3.8/site-packages/openai/_models.py:408: : note: use --pdb to drop into pdb
File "mypy/nodes.py", line 1141, in accept
File "mypy/semanal.py", line 1600, in …

chore: pin pydantic version for mypy

---

src/phoenix/trace/otel.py
tests/trace/test_otel.py

For the following attributes, support both json strings and flattened mappings (with latter for backward compatibility).
- DOCUMENT_METADATA
- LLM_PROMPT_TEMPLATE_VARIABLES
- TOOL_PARAMETERS

refactor: support json string attributes in addition to flattened mappings

---

src/phoenix/trace/fixtures.py

this is a follow-up to #2143 
SpanIDs are no longer UUIDs. So the string representation should not have hyphens.

fix: remove hyphens from span_id in evaluation fixtures

---

src/phoenix/trace/exporter.py
tests/trace/test_exporter.py

This eliminates the problem of double-slash if the `base_url` string has a slash at the end, e.g. `http://localhost:6006//v1/spans`

refactor: use urljoin for urls

---

src/phoenix/trace/exporter.py
tests/trace/test_exporter.py

We recently changed the default Phoenix port to `0.0.0.0`. The default collector endpoint was implicitly changed to `http://0.0.0.0:6006`. This appears to work fine on Mac, but breaks on Windows. This PR sets the collector endpoint to `http://127.0.0.1:6006` if the Phoenix port is set to `0.0.0.0`.

fix: default collector endpoint breaks on windows

---

src/phoenix/experimental/evals/models/anthropic.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/bedrock.py
src/phoenix/experimental/evals/models/litellm.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/models/vertex.py
src/phoenix/experimental/evals/models/vertexai.py
tests/experimental/evals/functions/test_classify.py

Resolves #2177 
Retries are now handled by `Executors`, and `tenacity` is no longer required as a dependency.

feat!: Remove model-level tenacity retries

---

app/package.json
app/src/pages/trace/TracePage.tsx

resolves #2198 
Rather than relying on browser history, this now always navigates to the tracing view.
https://github.com/Arize-ai/phoenix/assets/5640648/cf169294-a2f9-4e11-82bf-61b063a4db3b

fix(trace): return to /tracing url when dismissing trace slide over

---

app/src/components/pointcloud/EventItem.tsx
app/src/components/pointcloud/PointCloudPointHoverHalo.tsx
app/src/components/pointcloud/SelectionDisplayRadioGroup.tsx
app/src/components/pointcloud/SelectionGridSizeRadioGroup.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/store/pointCloudStore.ts

resolves #814 
This does not fully resolve #814 but can be used to solve some of the pain points.
Adds a search field in the selection panel and the ability to hover on points in the grid to try to identify a point.
What a user might ultimately want is actually search on all the points displayed - and this most certainly is the case. However this requires a bit more design and thought and this at least lets you narrow down the selection vector space.

feat(embeddings): add search by text and ID on selection

---

app/src/contexts/TimeRangeContext.tsx

resolves #2243 
Add hour time ranges which will use minute granularity. Feature request from community.

feat(ui): add hour time range

---

src/phoenix/experimental/evals/models/litellm.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/models/vertexai.py
tests/experimental/evals/functions/test_generate.py
tests/experimental/evals/models/test_openai.py

resolves #2252 
Soft-deprecates the model_name param in favor of model which is the common param name for openAI and other SDKs.

chore(evals): soft deprecate model_name param

---

src/phoenix/session/session.py

So that `px.Client()` doesn't use the failed session (or one that has ended).

fix: set global session to None if it fails to start

---

src/phoenix/experimental/evals/models/vertex.py

Small bug fix, we were printing a non string object, need to cast it to a string. This is blocking large runs with vertex that hit this error.

fix: cast message to string in vertexai model

---

app/src/pages/trace/TracePage.tsx

resolves #2290 
Sometimes different runtimes dump malformed json (e.g. JSON.dumps in python serializes NaNs) - this is a very strange (https://bugs.python.org/issue40633) however the reality. This makes the parsing safe in the UI so at least the attributes are visible.

fix(ui): safely parse JSON and fallback to string for span attributes

---

app/package.json
app/src/pages/trace/TracePage.tsx
tutorials/tracing/langchain_tracing_tutorial.ipynb

resolves #2296 
Displays metadata in the trace page. This does not show the metadata in the table (https://github.com/Arize-ai/phoenix/issues/2305) which requires a graphql change.
Also updates the notebook to have metadata

feat(trace): display metadata in the trace page UI

---

tutorials/tracing/dspy_tracing_tutorial.ipynb

A few issues:
- I had the wrong package name in the pip install statement.
- DSPy conflicts with the pre-installed version of `regex` on Google Colab, which breaks our instrumentation. I install a compatible version and add a warning message to restart the kernel on Colab.

fix: make dspy notebook work on colab

---

app/src/components/trace/utils.ts
app/src/pages/trace/TracePage.tsx
src/phoenix/core/traces.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/main.py
tests/core/test_traces.py

resolves #2350 
Spans with incomplete traces will only show up in the Spans tab, and not the Trace tab.
- The header is is a just placeholder because the true root span is not present.
- All partitions of the tree are shown at the same time. (There are two partitions in the screenshot.)
- Note that the header is now shown because it displays values based on the root span (i.e. the span whose parent is null)
- A breakpoint can be placed e.g. at the print() statement.
- Uncomment the raise statement to test exception handling.
```python
import openai
from openinference.instrumentation.openai import OpenAIInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk …
```

feat: show span as soon as they arrive

---

pyproject.toml

for reference: https://hatch.pypa.io/1.9/config/build/#packages
> The packages option is semantically equivalent to only-include (which takes precedence) except that the shipped path will be collapsed to only include the final component.

chore: exclude `packages` folder from source distribution

---

pyproject.toml
src/phoenix/__init__.py
src/phoenix/_evals.py

resolves #2368 
- Adds `phoenix.evals` as an optional extra install for `phoenix`
- Imports from `phoenix.evals` will either warn a user about the missing dependency or forward the import

feat: Add `phoenix.evals` bridge to `phoenix` and add `evals` extra install

---

packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
src/phoenix/evals

Adds a symlink to make `pip install -e '.[dev]'` work out of the box

chore: add symlink

---

app/src/pages/trace/TracePage.tsx

resolves #2397 
Adds scrolling to the trace tree for long traces

fix(traces): add y scroll on trace tree

---

Dockerfile

resolves #2403
symbolic links [not allowed](https://github.com/moby/moby/issues/1676#issuecomment-23878459)

fix: remove symbolic links for docker build

---

src/phoenix/trace/span_json_encoder.py

fix: remove __computed__ attributes from exported dataframe

---

packages/phoenix-evals/pyproject.toml

parity with phoenix [here](https://github.com/Arize-ai/phoenix/blob/f17c4ba60956895d905c3134e993edf243dec176/pyproject.toml#L103-L104)
before
after

chore: remove tests from source distribution

---

src/phoenix/trace/dsl/query.py
tests/trace/dsl/test_query.py

resolves #2437 
```python
import phoenix as px
from phoenix.trace.dsl.query import SpanQuery
px.Client().query_spans(SpanQuery().select("parent_id", "span_kind", "trace_id"))
```

fix: turn span_kind enums into string because it's not serializable by pyarrow

---

packages/phoenix-evals/src/phoenix/evals/generate.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_generate.py

Resolves #2434 
- Explicitly use row-order-preserving dataframe constructor
- Ensure the output index preserves the input index
- Ensure that custom output parser columns work with error handling

fix: `llm_generate` now preserves input index when constructing the output

---

pyproject.toml

Put a lower bound on instrumentation versions to ensure users are running on recent versions of our instrumentation

chore: pin instrumentation versions

---

tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb

Resolves #1654 
Adds a tutorial on tracing a more complex LlamaIndex RAG application that uses a router to pick between a SQL retriever and VectorStoreIndex.

docs: Add SQL retriever tracing tutorial

---

packages/phoenix-evals/pyproject.toml
packages/phoenix-evals/src/phoenix/evals/__init__.py
packages/phoenix-evals/src/phoenix/evals/models/__init__.py
packages/phoenix-evals/src/phoenix/evals/models/anthropic.py

Resolves #2488 
Updates the `AnthropicModel` wrapper to use the new `messages` API. This also enables the use of `claude-3` models.

feat: Update `AnthropicModel` to use `messages` API

---

src/phoenix/session/session.py

The `host` and `port` parameters in `launch_app` are footguns because they change the settings for Phoenix without changing the settings for our instrumentation and exporters. We're moving to environment variables to avoid these footguns.
resolves #2083

chore: add deprecation message for launch_app port and host parameters

---

src/phoenix/config.py
src/phoenix/session/client.py
src/phoenix/session/session.py
src/phoenix/trace/langchain/instrumentor.py
src/phoenix/trace/llama_index/callback.py
src/phoenix/trace/openai/instrumentor.py

resolves #2377 
Adds the ability to set the project name via an environment variable so that all the instrumentation goes to one project across instrumentations and so that loading evals and dataframes just works out of the box.

feat(projects): add support for the PHOENIX_PROJECT_NAME param

---

src/phoenix/trace/llama_index/callback.py

Adds support for minimal LlamaIndex installations, i.e., when only the `llama-index-core` module is installed but not the full `llama-index` package.
resolves #2509

fix: support minimal llama-index installations

---

app/package.json
app/src/components/table/TextCell.tsx
app/src/pages/trace/SpanEvaluationsTable.tsx

Displays newlines in explanations in the UI
resolves #2529

fix: display newlines in explanations

---

.github/workflows/python-CI.yml
packages/phoenix-evals/pyproject.toml
packages/phoenix-evals/src/phoenix/evals/models/vertex.py
packages/phoenix-evals/src/phoenix/evals/models/vertexai.py

Add support for `phoenix-evals` for python 3.12
resolves #2534

feat: add phoenix-evals support for python 3.12

---

app/src/pages/project/SpanColumnSelector.tsx

resolves #2526 
Scrolls the dropdown for columns when there are too many evals to show on the screen

fix(ui): scroll column selector when long

---

src/phoenix/trace/span_json_encoder.py
tests/trace/test_span_json_encoder.py

numpy arrays in spans can exist when user loads data from a parquet file that's generated from pyarrow, which turns lists into ndarrays. In order to export spans containing these numpy elements via `get_spans_dataframe`, we need convert these numpy objects in the span to json encoder.

fix: support numpy arrays in span to json encoder

---

src/phoenix/server/api/routers/evaluation_handler.py
src/phoenix/session/client.py

resolves #2452 
`log_evaluations` can be optionally be passed a `project_name`

feat: Add project name to `client.log_evaluations`

---

app/schema.graphql
src/phoenix/core/project.py
src/phoenix/core/traces.py
src/phoenix/server/api/schema.py

Adds `deleteProject` and `archiveProject` mutations. No deletion currently happens, we simply mark the project as archived and don't return it from the `projects` field on `Query`.

feat: project archiving and deletion

---

app/src/pages/home/homeLoader.ts

resolves #2568
It doesn't make too much sense to direct the user to a specific project when there are multiple projects with data. For example if you run indexing first, you will keep getting redirected to that project even though you want to see all.

fix(projects): the home page should direct you to the projects page if there are multiple projects with data

---

src/phoenix/core/traces.py

Previously, we required that at least one project exists at all times, but you could delete the default project if you had at least one other project. Now, we require that the default project in particular is not deleted.

chore: protect default project from deletion

---

src/phoenix/core/traces.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/node.py

Raises an exception when id passed to deleteProject and archiveProject mutations corresponds to a non-Project node

chore: raise exception for unexpected node types for deleteProject and archiveProject mutations

---

app/src/pages/trace/TracePage.tsx
pyproject.toml
src/phoenix/core/project.py
tests/core/test_project.py

resolves #2069 
resolves #2621 
A root span is defined to be a span whose parent span is not in our collection. This includes spans whose parent is None and spans whose parent has not arrived (or will not arrive). For spans whose parent is not None, the root span status is temporary and will be revoked when its parent span arrives.
Below is code used for testing. Lengthen the sleep seconds if more time is needed to observe the interim states.
```python
from random import random
from time import sleep
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
endpoint = "http://127.0.0.1:6006/v1/traces" …
```

fix(trace): redefine root span

---

src/phoenix/trace/dsl/helpers.py

Adds `start_time` and `end_time` arguments to `get_qa_with_reference` and `get_retrieved_documents`.
resolves #2644

feat: add time range arguments to span query helper functions

---

packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
pyproject.toml

resolves #2658 
- Enables JSON output format: `MistralAIModel(response_format={"type": "json_object"})`

feat: Add `response_format` argument to `MistralAIModel`

---

examples/cron-evals/.gitignore
examples/cron-evals/README.md
examples/cron-evals/build_vector_store.py
examples/cron-evals/requirements.txt
examples/cron-evals/run_chain.py
examples/cron-evals/run_evals.py

Adds example using `cron` for online Phoenix evals.
resolves #2614

docs: example using cron for online phoenix evals

---

packages/phoenix-evals/src/phoenix/evals/models/bedrock.py

Evals using new claude 3 are failing due to messages API not being supported. Copied format for claude function from anthropic.py

feat: update bedrock.py to use messages API for claude

---

.pre-commit-config.yaml
app/package-lock.json
app/package.json
app/relay.config.js
app/src/components/form/__generated__/DimensionPickerQuery.graphql.ts
app/src/pages/__generated__/ModelRootQuery.graphql.ts
app/src/pages/embedding/__generated__/EmbeddingPageModelQuery.graphql.ts
app/src/pages/embedding/__generated__/ExportSelectionButtonExportsQuery.graphql.ts
app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
app/src/pages/project/__generated__/EvaluationSummaryValueFragment.graphql.ts
app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
app/src/pages/project/__generated__/StreamToggle_data.graphql.ts
app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts

- updates `relay-compiler` to 16.2.0
- updates eslint versions used in pre-commit hooks to match the lower bounds defined in `package.json`
- migrates `relay.config.js`
- `customScalars` -> `customScalarTypes` (https://github.com/facebook/relay/releases/tag/v16.2.0)
- adds `"typescriptExcludeUndefinedFromNullableUnion": true` to preserve generation of nullable types pre v16.0.0. (https://github.com/facebook/relay/releases/tag/v16.0.0)
resolves #2651

chore: update relay-compiler to v16

---

.dockerignore
Dockerfile

- Changes production image to distroless. This makes the image more lightweight and secure.
- Converts docker to use `pnpm`.
- Uses multi-stage builds.
- Switches up `.dockerignore` to enable better caching by ignoring `Dockerfile`. Also, since we're doing multi-stage builds, there's no need to ignore all the files, since only the built packages will wind up in the production stage.

feat: change docker base image to distroless

---

app/src/markdown/MarkdownDisplayContext.tsx
app/src/pages/trace/TracePage.tsx

Had broken context when using markdown that was causing an error to throw. Made the context fault tolerent.

fix(ui): broken context for markdown

---

src/phoenix/server/app.py

We cannot use websockets because of colab so this just removes them

chore: remove unused websockets

---

cspell.json
pyproject.toml
src/phoenix/db/__init__.py
src/phoenix/db/alembic.ini
src/phoenix/db/database.py
src/phoenix/db/migrate.py
src/phoenix/db/migrations/README
src/phoenix/db/migrations/env.py
src/phoenix/db/migrations/script.py.mako
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/main.py

resolves #2742 
This adds runtime migration support via alembic.
NB: Migrations DO NOT work on in memory sqlite so Base.metadata.create_all() is necessary.
Of note that this PR adds naming convention rules as well.

feat(persistence): migrations support

---

src/phoenix/db/alembic.ini
src/phoenix/db/bulk_inserter.py
src/phoenix/db/engines.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/api/routers/trace_handler.py
src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/session/session.py

resolves #2806 
This PR implements the queuing method described below.
Two strategies for write transactions:
1. Each request has a separate writer.
- Pro: Returning a 200 response means data is persisted.
- Con: Lock contention/starvation, which is probably rare. Granular transactions are less efficient overall.
2. Queue the requests in a buffer and funnel them into a single bulk-writer.
- Pro: Bulk writing is more efficient, and having a single writer also means no lock contention.
- Con: Buffer is volatile an can be lost if crashed, so returning a 200 response is not a genuine confirmation of data persistence. Also, transaction errors are not propagated back the client.

feat(persistence): experimental bulk inserter for spans

---

packages/phoenix-evals/src/phoenix/evals/models/litellm.py

Retries are no longer managed by the model wrappers, these params are no longer used.

chore: Remove unused litellm params

---

cspell.json
src/phoenix/__init__.py
src/phoenix/db/migrations/env.py
src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/session/session.py

resolves #2815 
This makes it so that launch app runs in the notebook using `sqlite` non-memory mode. This PR also adds `px.reset_all` which lets the user reset the working_directory if they desire.

feat(persistence): launch app with persist

---

src/phoenix/db/alembic.ini
src/phoenix/db/migrate.py
src/phoenix/db/migrations/env.py

resolves #2825 
This fixes that logging was permanently broken post migrations. This also increases the log level while running migrations for debugging purposes.

fix: preserve loggers across migrations

---

app/schema.graphql
app/src/pages/project/ProjectPageHeader.tsx
app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
pyproject.toml
src/phoenix/db/bulk_inserter.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders.py
src/phoenix/server/api/dataloaders/latency_ms_quantile.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/app.py
tests/server/api/types/conftest.py

resolves #2807
We use ddsketch here because sqlite doesn't have percentile functions unless we compile it with the `percentile.c` extension, like how it's done in the Python package https://github.com/nalgeon/sqlean.py.

feat(persistence): fetch latency_ms percentiles using sql with dataloaders

---

src/phoenix/db/bulk_inserter.py

Removes an error in a logging statement causing #2841 and improves error handling and logging.
resolves #2778

fix: improve error handling and logging for eval insertions

---

src/phoenix/config.py
src/phoenix/db/engines.py
src/phoenix/db/migrate.py
src/phoenix/session/session.py

resolves #2853 
This PR resolves the issue that migrations were not running via launch_app. Note that now there's a bunch of logging (https://github.com/Arize-ai/phoenix/issues/2856) which will be cleaned up.

feat(persistence): ensure migrations run for TreadSession

---

src/phoenix/db/alembic.ini
src/phoenix/db/migrate.py
src/phoenix/db/migrations/env.py
src/phoenix/server/main.py
src/phoenix/settings.py

resolves #2856 
Lets you control the settings so that migrations only get logged when running in container mode.

chore: log level control over migrations

---

src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/latency_ms_quantile.py
src/phoenix/server/api/dataloaders/span_evaluations.py
src/phoenix/server/api/types/Evaluation.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/app.py

Makes the GraphQL resolver for span evaluations read from the database, using a data loader.
resolves #2777
Coauthored-by: Mikyo King mikeldking@gmail.com

feat: make graphql api for span evaluations read from database

---

src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/document_evaluations.py
src/phoenix/server/api/types/Evaluation.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/app.py

GraphQL API reads document evaluations from database using a dataloader.
resolves #2777

feat: graphql api for document evaluations

---

src/phoenix/inferences/inferences.py

Resolves https://github.com/Arize-ai/phoenix/issues/2872
- `Inferences` was going to drop support for the `from_open_inference` method, but we're restoring it for now due to too many failures in notebooks.

fix: Restore `from_open_inference` method on `Inferences`

---

src/phoenix/db/bulk_inserter.py

Safely unpack Evaluations proto. `label`, `explanation` and `score` are not guaranteed to exist on the result and need to be checked for.

fix: safely unpack Evaluations proto in bulk inserter

---

src/phoenix/core/project.py
src/phoenix/db/models.py
src/phoenix/server/api/types/Project.py

feat: document evaluation aggregation

---

app/schema.graphql
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/trace_evaluations.py
src/phoenix/server/api/types/Evaluation.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/api/types/Trace.py
src/phoenix/server/app.py

makes graphql api pull trace evaluations from db
resolves #2777

feat: convert graphql api to pull trace evaluations from db

---

src/phoenix/session/client.py
tests/session/test_client.py

resolves #2805
- Allows passing in a `project_name` parameter

feat: Add `log_traces` method that sends `TraceDataset` traces to Phoenix

---

docs/api/evals.md

Noticed this when we were reading the documentation for a work related task. Pulled the rest of the documentation from [this line](https://github.com/Arize-ai/phoenix/blob/main/packages/phoenix-evals/src/phoenix/evals/classify.py#L248)

fix(docs): add the remainder of the sentence to run_evals concurrency

---

src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/app.py
src/phoenix/session/client.py

- adds support for span annotations to the GET evaluations endpoint.
- fixes bug with query name parameter for `get_evaluations` client function
resolves #2894

feat: support for span evaluations to get evaluations endpoint

---

src/phoenix/db/bulk_inserter.py

Because the buffers are grabbed at different times, a span can miss the span buffer and stays in the queue, while its eval can be include the eval buffer, leading to eval insertion failure because eval can't insert if the span it references doesn't exist in the db.

fix(persistence): db race condition between spans and evals

---

cspell.json
src/phoenix/db/engines.py
src/phoenix/db/migrations/env.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
tests/db/test_engines.py

Ensures that the postgres URL is properly formed for authentication and so that down migrations run in the proper order

fix(persistence): postgres down migration and url support

---

pyproject.toml

fix: ensure recent version of opentelemetry-proto is used

---

app/schema.graphql
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Project.py

resolves #2926 
MVP of wiring up project gradient colors. This is done just to avoid a migration in the future.

feat: add gradient start/end to projects table

---

app/src/pages/project/SpansTable.tsx
app/src/pages/project/TracesTable.tsx

resolves #2927 
Disables JS sorting and relies entirely on server-side sorting.

fix: disable client-side sorting on trace/span tables

---

app/schema.graphql
cspell.json
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/api/schema.py

resolves #2539
Adds the ability to clear traces from the DB. Currently doesn't include a time range but can in the future.
```graphql
mutation {
clearProject(id: "UHJvamVjdDox") {
projects {
edges {
node {
... on Project {
name
traceCount
}
}
}
}
}
}
```

feat(persistence): clear project

---

app/src/pages/projects/ProjectActionMenu.tsx
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectActionMenuClearMutation.graphql.ts
app/src/pages/projects/__generated__/ProjectActionMenuDeleteMutation.graphql.ts

resolves #2540 
adds a UI to clear traces

feat(persistence): clear traces UI

---

src/phoenix/server/telemetry.py
tests/server/test_telemetry.py

Makes sure that the URL doesn't include irrelevant info or trailing /v1/traces
resolves #2997

fix: normalize telemetry url before setup

---

Dockerfile
src/phoenix/config.py
src/phoenix/server/main.py

- add support for a `PHOENIX_ENABLE_PROMETHEUS` environment variable
- add a deprecation warning for the existing `--enable-prometheus` command line argument
resolves #2712

feat: allow Prometheus to be configured via an environment variable

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

- removes manual names for uniqueness constraints, which are redundant when using naming conventions and were actually conflicting with and overriding the naming conventions
- changes our naming conventions to better support compound indexes and compound uniqueness constraints (i.e., those that involve multiple columns)
Previously, if we created a compound index or uniqueness constrain, the automatically generated name would only include the first column, which makes naming collisions possible.
resolves #2975

chore(persistence): improve naming for indexes and constraints

---

app/src/pages/trace/TracePage.tsx

Just removes the padding from the all attributes card.

chore: remove card padding

---

src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/session/client.py
src/phoenix/session/data_extractor.py
src/phoenix/session/session.py
src/phoenix/trace/dsl/query.py
tests/trace/dsl/test_query.py

- adds default limit of 1000 to `/v1/spans`
- similarly updates default in `phoenix.Client` and `phoenix.Session` methods
- fixes openapi schema, which was in a broken state
resolves #3017

feat: add default limit to `/v1/spans` and corresponding client methods

---

src/phoenix/server/api/types/Project.py

add a default limit of 1000 to the spans resolver. this is hard-coded and is purely for testing purposes until we get pagination out.

chore: default spans limit

---

app/src/RelayEnvironment.ts
src/phoenix/server/main.py

Changes the url for graphql so that basic auth can be properly initialized

feat: Support basic auth

---

app/src/pages/projects/ProjectActionMenu.tsx

resolves #3058 
The issue here is that deleting a project while the project is receiving spans really doesn't do anything but clear the traces as the project gets immediately reconstructed. I filed #3068 to figure out what the right solution is there.

fix: close delete modal on delete

---

src/phoenix/server/api/dataloaders/document_evaluation_summaries.py
src/phoenix/server/api/dataloaders/evaluation_summaries.py
src/phoenix/server/api/dataloaders/latency_ms_quantile.py
src/phoenix/server/api/dataloaders/record_counts.py
src/phoenix/server/api/dataloaders/token_counts.py

Set TTL=3600 (1-hour) because time intervals are always moving forward, but interval endpoints are [rounded down](https://github.com/Arize-ai/phoenix/pull/3079) to the hour by the UI, so anything older than an hour most likely won't be a cache-hit anyway.

refactor: use TTL for project cache for dataloaders

---

src/phoenix/db/migrations/env.py

```
INFO  [sqlalchemy.engine.Engine] INSERT INTO alembic_version (version_num) VALUES ('cf03bd6bae1d') RETURNING version_num
INFO  [sqlalchemy.engine.Engine] [generated in 0.00034s] ()
INFO  [sqlalchemy.engine.Engine] ROLLBACK
```
```
INFO  [sqlalchemy.engine.Engine] INSERT INTO alembic_version (version_num) VALUES ('cf03bd6bae1d') RETURNING version_num
INFO  [sqlalchemy.engine.Engine] [generated in 0.00010s] ()
INFO  [sqlalchemy.engine.Engine] COMMIT
```

fix: commit insert into alembic_version at the end of migration

---

docs/deployment/persistence.md
docs/setup/configuration.md

Hey :)
I'm opening this MR to update the docs relatively to the default value for `PHOENIX_WORKING_DIR`. It would be nice to know where the default folder for tracing is (e.g. to delete the files or to load the sqlite db in a different tool), so I added it in the documentation.
Open to feedback!
Best,
Martino

PHOENIX_WORKING_DIR default value documentation

---

packages/phoenix-evals/src/phoenix/evals/evaluators.py
packages/phoenix-evals/tests/phoenix/evals/test_evaluators.py

The way I previously did the factory method for instantiating evaluators was overly complex and led to incorrect type hints for end users.
resolves #2638

fix: evaluators no longer have incorrect type hints

---

packages/phoenix-evals/src/phoenix/evals/models/openai.py
packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py

Our fix for adding custom header for azure openai client has been removed so we are adding it again.

feat: Added support for default_headers for azure_openai.

---

src/phoenix/config.py
src/phoenix/server/main.py
src/phoenix/session/client.py
src/phoenix/session/evaluation.py
src/phoenix/trace/exporter.py
tests/session/test_client.py
tests/trace/test_exporter.py

Fixes #2918 
Allow for a root path parameter so that Phoenix can be hosted behind a proxy with a path prefix.
`Session` code has not been adjusted because the adjustment of the root path is probably not needed in this scenario.
`Client` and `Exporter` code have not been adjusted because they provide explicit `endpoint` parameters where a full URL can be given.

feat: Add ASGI root path parameter to Phoenix server

---

src/phoenix/db/models.py

This issue affects Postgres 12, since the result of `EXTRACT` changed from double precision to numeric in postgres 14. https://stackoverflow.com/questions/72375207/extract-returns-numeric-instead-double-precision/72375709#72375709

fix: resolve rounding issue in postgres

---

kustomize/base/phoenix.yaml

Updates `kustomize` configuration to use `4.1.1` version of Phoenix, which fixes an issue when running on Postgres 12.

chore: update kustomize

---

app/src/components/dataset/CreateDatasetForm.tsx
app/src/components/dataset/__generated__/CreateDatasetFormMutation.graphql.ts
app/src/components/table/IndeterminateCheckboxCell.tsx
app/src/pages/datasets/DatasetsPage.tsx
app/src/pages/project/DatasetSelectorPopoverContent.tsx
app/src/pages/project/SpanSelectionToolbar.tsx
app/src/pages/project/SpansTable.tsx
app/src/pages/project/TracesTable.tsx
app/src/pages/project/__generated__/DatasetSelectorPopoverContentDatasetsQuery.graphql.ts
app/src/pages/project/__generated__/DatasetSelectorPopoverContentQuery.graphql.ts
app/src/pages/project/__generated__/DatasetSelectorPopoverContent_datasets.graphql.ts
app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
app/src/pages/project/__generated__/SpanSelectionToolbarAddSpansToDatasetMutation.graphql.ts
app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
app/src/pages/project/__generated__/TracesTable_spans.graphql.ts

resolves #3202 
Adds the ability to add spans as examples to a dataset from the tables

feat(datasets): multi-select on span / traces tables

---

packages/phoenix-evals/src/phoenix/evals/executors.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py

- Refactor of #3240 
- enables full sync compatibility if `run_sync=True`
- Falls back to sync executor if running `llm_classify` not in the main thread

fix: Bypass signal handler if running in a thread

---

src/phoenix/db/README.md

Triggers pipeline to publish new Docker images.
Small change to a file in the `arize-phoenix` package is needed, otherwise, it will trigger release-please on `arize-phoenix-evals`.

feat: docker image runs as root by default with tags for nonroot and debug images

---

app/package.json
app/pnpm-lock.yaml
app/src/components/code/JSONEditor.tsx
app/src/components/code/index.tsx
app/src/pages/trace/SpanToDatasetExampleDialog.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/SpanToDatasetExampleDialogAddExampleToDatasetMutation.graphql.ts
app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
app/src/utils/__tests__/jsonUtils.test.ts
app/src/utils/jsonUtils.ts
src/phoenix/server/api/mutations/dataset_mutations.py

resolves #3208 
Adds the ability to add a span to a dataset.Has some follow-up UI elements that will be filed separately.

feat(datasets): add span to dataset from the trace page

---

tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb

Temporary fix for #3317 
Resolves breaking changes in langchain tutorials with langchain >= 0.2.0

docs: Update Langchain dependencies in notebook tutorials

---

app/src/pages/dataset/DatasetPage.tsx
app/src/pages/datasets/DatasetsPage.tsx

feat(datasets): download csv button

---

app/schema.graphql
src/phoenix/server/api/input_types/DeleteDatasetExamplesInput.py
src/phoenix/server/api/mutations/dataset_mutations.py

resolves #3301 
Adds the ability to delete dataset examples
```graphql
mutation delteExamples($input: DeleteDatasetExamplesInput!) {
deleteDatasetExamples(input: $input) {
dataset {
id
}
}
}
```
```json
{
"input": {
"exampleIds": ["RGF0YXNldEV4YW1wbGU6MQ=="],
"datasetVersionDescription": "mikyo-foo"
}
}
```

feat(datasets): delete examples mutation

---

packages/phoenix-evals/src/phoenix/evals/classify.py
packages/phoenix-evals/src/phoenix/evals/exceptions.py
packages/phoenix-evals/src/phoenix/evals/executors.py
packages/phoenix-evals/src/phoenix/evals/generate.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py

resolves #3313 
- Adds `exit_on_error` flag to `llm_classify` that will optionally continue to process evals, even if one fails
- Adds `include_exceptions` flag to `llm_classify` that optionally returns an `exceptions` column that logs errors running evals on each row and an `execution_status` column that summarizes whether or not each eval completed

feat: Allow skipping on template mapping errors, returning debug info

---

src/phoenix/server/api/routers/v1/dataset_examples.py
tests/server/api/routers/v1/test_dataset_examples.py

resolves #3374 
- updates query param to `?version-id` instead of `?version` as per spec

feat: tweaks to get versioned dataset examples

---

app/src/pages/trace/TracePage.tsx

feat(ui): display input and output for tool spans

---

app/src/pages/ErrorElement.tsx
app/src/pages/dataset/DatasetExamplePage.tsx
app/src/pages/dataset/EditDatasetExampleButton.tsx
app/src/pages/dataset/EditDatasetExampleDialog.tsx
app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts
app/src/pages/dataset/__generated__/EditDatasetExampleDialogMutation.graphql.ts
app/src/pages/project/SpanSelectionToolbar.tsx
app/src/pages/trace/SpanToDatasetExampleDialog.tsx

resolves #3368 
Adds a slide-over UI to edit a dataset example

feat(datasets): UI to edit a dataset example

---

src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py
src/phoenix/server/api/routers/v1/experiment_evaluations.py
tests/server/api/conftest.py

- Renames `experiment_evaluations` table to `experiment_annotations`.
- Adds `annotator_kind` column with a check constraint.
- Updates source and tests.
resolves #3425

chore: update tables for human annotations on experiment runs

---

app/schema.graphql
src/phoenix/server/api/types/DatasetExample.py
src/phoenix/server/api/types/Experiment.py
tests/server/api/types/test_DatasetExample.py

Adds an `experiments` resolver to the `DatasetExample` type and adds corresponding tests.
resolves #3399

feat: add experiments resolver to DatasetExample gql type

---

src/phoenix/server/main.py

**No Host Root Path**
Ensures welcome message URLs are valid and do not have unnecessary trailing slashes.
*Before*
```
|  🚀 Phoenix Server 🚀
|  Phoenix UI: http://0.0.0.0:6006/
|  Log traces:
|    - gRPC: http://0.0.0.0:4317
|    - HTTP: http://0.0.0.0:6006//v1/traces
|  Storage: sqlite:////Users/xandersong/.phoenix/phoenix.db
```
*After*
```
|  🚀 Phoenix Server 🚀
|  Phoenix UI: http:/0.0.0.0:6006
|  Log traces:
|    - gRPC: http://0.0.0.0:4317
|    - HTTP: http:/0.0.0.0:6006/v1/traces
|  Storage: sqlite:////Users/xandersong/.phoenix/phoenix.db
```
**WIth Host Root Path**
(no changes)
*Before*
```
|  🚀 Phoenix Server 🚀
|  Phoenix UI: http://0.0.0.0:6006/test
|  Log traces:
|    - gRPC: http://0.0.0.0:4317
|    - HTTP: http://0.0.0.0:6006/test/v1/traces
|  Storage: …
```

fix: ensure welcome message urls are valid

---

src/phoenix/server/api/types/Dataset.py
tests/server/api/types/test_Dataset.py

If the sort column is tied, use the row ID as a tiebreak
resolves #3485

fix: add tiebreak to versions resolver

---

schemas/openapi.yaml
src/phoenix/server/api/routers/v1/dataset_examples.py
tests/server/api/routers/v1/test_dataset_examples.py
tests/server/api/routers/v1/test_experiments.py

refactor: update GET /v1/datasets/{datasetId}/examples to return dataset and version IDs as part of payload

---

app/src/Routes.tsx
app/src/pages/datasets/DatasetsTable.tsx
app/src/pages/experiment/ExperimentComparePage.tsx
app/src/pages/experiment/ExperimentMultiSelector.tsx
app/src/pages/experiment/__generated__/ExperimentMultiSelector__experiments.graphql.ts
app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
app/src/pages/experiment/experimentCompareLoader.ts
app/src/pages/experiment/index.tsx
app/src/pages/experiments/ExperimentSelectionToolbar.tsx
app/src/pages/experiments/ExperimentsTable.tsx

Just adds the navigation to the experiment comparison view. A pre-cursor to building out the table

feat(experiments): navigation to experiments view

---

.pre-commit-config.yaml
pyproject.toml
src/phoenix/core/model_schema.py
src/phoenix/metrics/binning.py
src/phoenix/server/api/types/Segments.py
tests/metrics/test_binning.py
tests/metrics/test_scalar_drift.py

resolves #3530 
resolves #2261
Notes
- restrict numpy < 2 because of hdbscan [issue](https://github.com/Arize-ai/phoenix/issues/3530) (although the issue seems intermittent)
- numpy related code changes are done by ruff. see [here](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin)
- pandas related code changes are due to `pandas-stubs==2.0.3.230814`
- also updated pytest, mypy, and strawberry

fix: hdbscan incompatibility with numpy 2.0

---

pyproject.toml

The latest [pandas](https://pypi.org/project/pandas/) has dropped support for 3.8, so there may be linting errors not visible on 3.8.
`pandas-stubs==2.0.3.230814` is the last version supporting python 3.8.

chore: fix pandas linting for python 3.9+

---

src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/routers/v1/experiments.py

metadata can be `None` in the JSON payload

fix(dataset): get metadata as `{}` when its value is `None` in JSON

---

app/src/components/code/JSONText.tsx
app/src/components/nav/Navbar.tsx
app/src/components/table/styles.ts
app/src/pages/experiment/ExperimentComparePage.tsx
app/src/pages/experiment/ExperimentCompareTable.tsx

resolves #3547 
Adds a toggle to let you view the full-text in the table view

feat(experiments): full-text toggle for experiments table

---

cspell.json
src/phoenix/config.py
src/phoenix/datasets/experiments.py
src/phoenix/session/client.py
src/phoenix/trace/exporter.py
src/phoenix/utilities/re.py
tests/session/test_client.py
tests/utilities/test_re.py

resolves #2738 
Lets you add auth headers (and anything else you might need) to access phoenix from a client

feat(auth): universal set of headers to be used by the client

---

schemas/openapi.yaml
src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/server/api/routers/v1/traces.py
src/phoenix/server/openapi/docs.py

This PR hides all non-datasets related routes for now until they are well-documented and ready for consumption

chore: hide openapi routes that are not usable in the playground

---

src/phoenix/server/api/helpers/dataset_helpers.py
tests/server/api/helpers/test_dataset_helpers.py
tests/server/api/mutations/test_dataset_mutations.py

chore: rename "retrieval_documents" to "documents" in examples

---

Dockerfile

- **Purpose**: Update Dockerfile to support ARM64 architecture.
- **Change**:
- Added a comment and an option to use gcr.io/distroless/python3-debian12:nonroot-arm64 for ARM64 deployments.
- **Use Case**: Enables deployment on devices like Raspberry Pi and Apple Silicon.
This change ensures compatibility with ARM64 architecture, enhancing the flexibility of the Phoenix project to run on various hardware platforms.

fix: Update Dockerfile to work with ARM64 chips.

---

src/phoenix/server/api/helpers/dataset_helpers.py
tests/server/api/helpers/test_dataset_helpers.py

fix: json input and output values are properly parsed when adding examples

---

app/src/pages/experiment/ExperimentCompareTable.tsx
app/src/pages/experiments/ErrorRateCell.tsx
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts

resolves #3656 
Also displays error traces which were hidden before.

feat(experiments): experiment error rate column

---

src/phoenix/datasets/evaluators/utils.py

this is useful for using `partial` to fill in values. below is an example

feat(datasets): allow unrecognized parameters in the evaluator function with default values

---

app/src/components/experiment/AnnotationLabel.tsx
app/src/pages/experiment/ExperimentCompareTable.tsx
tutorials/experiments/experiments_txt2sql.ipynb

resolves #3613 
resolves #3665 
Displays the evaluator trace when clicked.

feat(experiments): evaluator trace slide-over

---

app/src/pages/experiments/ExperimentsTable.tsx

resolve #3711
Show a full bar when you get all 1s.

fix(datasets): show full bar on evals of all 1s

---

pyproject.toml

It would be nice to have types in the `api_reference` section, but ignoring for now to get CI back to green.

ci: mypy ignore api_reference

---

pyproject.toml

pyyaml is available in colab etc. but not in the container. This fixes the rendering via a hosted phoenix.

fix: openapi yaml parsing for containers

---

app/src/pages/experiments/ExperimentsTable.tsx
src/phoenix/server/api/types/ExperimentRun.py

fix(experiments): order annotations by name to make output deterministic

---

.gitignore
packages/phoenix-evals/src/phoenix/evals/models/openai.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_generate.py
packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py

`AzureOpenAI` and `AsyncAzureOpenAI` don't need an API key if using Active Directory. The combinations of valid parameters and environment variables is complex (`azure_ad_token`, `azure_ad_token_provider`, `AZURE_OPENAI_API_KEY`, `AZURE_OPENAI_AD_TOKEN`). This PR allows the OpenAI SDK to parse environment variables and validate rather than us trying to parse and validate.
resolves #3813

fix: allow invocations of OpenAIModel without api key

---

app/src/pages/trace/SpanCodeDropdown.tsx
app/src/pages/trace/TraceDetails.tsx
app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts

resolves #3894 
adds the ability to copy paste a span or trace id

feat(annotations): ability to copy span and trace IDs

---

packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py

Wraps synchronous calls in an executor for async support in Bedrock evals.
The current code makes a synchronous call in an async function. As a result, calling `run_evals`:
1. Doesn't actually parallelize while using bedrock, resulting in very low throughput
2. Doesn't properly display the progress bar since all calls are made before the `gather`. This confuses the user and makes them think something is wrong.
Proper async support in boto3 has been [asked for for years](https://github.com/boto/botocore/issues/458), so I don't think we can count on it any time soon. Wrapping in an executor ties up some threads on I/O, but still results in significantly higher throughput, which I think eval users (including myself) require.

fix: Run Bedrock calls in executor for async

---

app/package.json
app/pnpm-lock.yaml
app/src/App.tsx
app/src/components/markdown/MarkdownDisplayContext.tsx
app/src/components/markdown/MarkdownModeRadioGroup.tsx
app/src/contexts/PreferencesContext.tsx
app/src/pages/trace/TraceDetails.tsx
app/src/store/preferencesStore.tsx

resolves #3898
Adds a new preferences context and uses local storage to persist the information automatically. Used to store whether or not the user prefers markdown display or not.
https://github.com/user-attachments/assets/d417d4bb-266a-4eba-9007-1c6b84d040ae

feat(UI): user preferences context with markdown preferences

---

app/schema.graphql
src/phoenix/server/api/types/Project.py

resolves #3830 
Adds the ability to pull all annotation names on a project. This will enable users to populate annotations with consistent names
```graphql
node(id: "UHJvamVjdDox") {
... on Project {
spanAnnotationNames 
}
}
}
```

feat(annotations): graphql resolver for all annotation names on a project

---

src/phoenix/server/app.py

Our web build now generates static assets (css / js) in chunks with unique hashes. This allows us to re-enable caching of these files.

fix: re-enable server side caching

---

app/schema.graphql
src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py
src/phoenix/server/api/input_types/CreateTraceAnnotationInput.py
src/phoenix/server/api/input_types/PatchAnnotationInput.py
src/phoenix/server/api/mutations/span_annotations_mutations.py
src/phoenix/server/api/mutations/trace_annotations_mutations.py
tests/server/api/types/test_SpanAnnotation.py
tests/server/api/types/test_TraceAnnotation.py

Makes the types correctly singular in the graphql types and moves the annotator kind to be an enum

refactor: annotator graphql types

---

packages/phoenix-evals/src/phoenix/evals/models/openai.py

docs: Fix docstring

---

app/src/components/dataset/CreateDatasetForm.tsx
app/src/contexts/FeatureFlagsContext.tsx
app/src/pages/trace/AnnotationActionMenu.tsx
app/src/pages/trace/EditSpanAnnotationsButton.tsx
app/src/pages/trace/EditSpanAnnotationsDialog.tsx
app/src/pages/trace/NewSpanAnnotationForm.tsx
app/src/pages/trace/SpanAnnotationActionMenu.tsx
app/src/pages/trace/SpanAnnotationForm.tsx
app/src/pages/trace/TraceDetails.tsx
app/src/pages/trace/__generated__/EditSpanAnnotationsDialogNewAnnotationQuery.graphql.ts
app/src/pages/trace/__generated__/EditSpanAnnotationsDialogQuery.graphql.ts
app/src/pages/trace/__generated__/NewSpanAnnotationFormMutation.graphql.ts
app/src/pages/trace/__generated__/SpanAnnotationActionMenuDeleteMutation.graphql.ts
app/src/store/preferencesStore.tsx

resolves #3825 
This is a minimum working pre-release UI for adding annotations to spans. It does not include edits, only additions and deletions. There are known UX issues that will be addressed as follow-ups.

feat(annotations): annotations UI

---

src/phoenix/session/client.py
tests/session/test_client.py

It's currently possible for timestamps to have different resolutions in the DB. Timestamps created by `server_default=func.now()` have second-level resolution, while manually created timestamps have more granular timing information. So you wind up with timestamps that look like this:
```
["2024-07-23T17:32:06.646881+00:00", "2024-07-23T17:32:01+00:00"]
```
resolves #3959

fix: get_dataset_versions client method does not break on mixed timestamp formats

---

src/phoenix/server/api/routers/v1/datasets.py

This pull request addresses a syntax error occurring in the `list_datasets` function when filtering datasets by name, specifically when using PostgreSQL 16.
When querying the `/v1/datasets` endpoint with PostgreSQL 16, the function encounters a syntax error. The error occurs due to the use of SQLAlchemy's `is_()` method for comparing the dataset name, which is typically used for NULL comparisons. This resulted in a PostgreSQL syntax error near "$1" when the query was executed.
Error logs revealed:
```
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "$1"
[SQL: SELECT datasets.id, datasets.name, datasets.description, datasets.metadata, datasets.created_at, datasets.updated_at …
```

fix: replace is_() with == in dataset name filter

---

app/schema.graphql
app/src/pages/project/DatasetSelectorPopoverContent.tsx
app/src/pages/trace/EditSpanAnnotationsDialog.tsx
app/src/pages/trace/NewSpanAnnotationForm.tsx
app/src/pages/trace/SpanAnnotationActionMenu.tsx
app/src/pages/trace/__generated__/EditSpanAnnotationsDialogSpanAnnotationsQuery.graphql.ts
app/src/pages/trace/__generated__/EditSpanAnnotationsDialog_spanAnnotations.graphql.ts
app/src/pages/trace/__generated__/NewSpanAnnotationFormMutation.graphql.ts
app/src/pages/trace/__generated__/SpanAnnotationActionMenuDeleteMutation.graphql.ts
src/phoenix/server/api/mutations/span_annotations_mutations.py
src/phoenix/server/api/mutations/trace_annotations_mutations.py

resolves #3963 
Adds query to mutation responses so data can be refetched.

feat(annotations): refetch annotations on annotation changes

---

src/phoenix/experiments/functions.py
src/phoenix/server/app.py
src/phoenix/session/client.py
src/phoenix/utilities/client.py

feat: Version mismatch checks

---

docs/quickstart/evals.md

Changes made
1. Clarify what the schema of the dataframe is for the Q&A and Hallucination evaluators are
2. Remove unnecessary tab

docs: clarify evaluators quickstart

---

app/src/components/markdown/MarkdownDisplayContext.tsx
app/src/contexts/StreamStateContext.tsx
app/src/pages/project/StreamToggle.tsx
app/src/store/preferencesStore.tsx

resolves #4023 
Adds `traceStreamingEnabled` into preferences context to preserve project page streaming preferences across sessions
https://github.com/user-attachments/assets/6731821c-6103-4f12-bda3-075b49d2615c

feat: add trace stream toggle into preferences context

---

src/phoenix/experiments/types.py

couple ValueError in post init functions under experiments/types.py are missing the raise keywords

fix: add raise keyword before exceptions in experiments.types

---

app/src/components/trace/SpanItem.tsx
app/src/components/trace/TokenCount.tsx
app/src/components/trace/TraceTree.tsx
app/src/pages/project/SpansTable.tsx
app/src/pages/project/TracesTable.tsx
app/src/pages/trace/SpanAside.tsx
app/src/pages/trace/SpanDetails.tsx
app/src/pages/trace/TraceDetails.tsx
app/src/pages/trace/__generated__/SpanAsideSpanQuery.graphql.ts
app/src/pages/trace/__generated__/SpanAside_span.graphql.ts
app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
app/src/store/preferencesStore.tsx

resolves #4029 
Adds a span aside section that can be collapsed that contains timing info. Will add annotations next.

feat(trace): add a span aside with timing info and feedback

---

app/src/pages/trace/SpanAnnotationForm.tsx

resolves #4075
Makes the annotation explanation collapsed by default so that more annotations are visible

feat(annotations): default collapse annotation explanations

---

src/phoenix/trace/dsl/filter.py
tests/conftest.py
tests/trace/dsl/conftest.py
tests/trace/dsl/test_query.py

resolves #4017 
Because filtering is done in SQL, logical negations require additional consideration with respect to `NULL` values.
For example, the logical negation of 
```python
evals["correctness"].score == 1
```
is actually not 
```python
evals["correctness"].score != 1
```
but it is instead the following
```python
evals["correctness"].score != 1 or evals["correctness"].score is None
```
This is because `NULL != 1` is actually false in SQL.

fix: use outerjoin for evals filter

---

src/phoenix/session/session.py

resolves #4106
Adds a slug to the session.view so that we can show different screens in the notebook during tutorials

feat(session): support a slug to the seesion.view

---

app/schema.graphql
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/annotation_summaries.py
src/phoenix/server/api/types/AnnotationSummary.py
src/phoenix/server/api/types/EvaluationSummary.py
src/phoenix/server/api/types/LabelFraction.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/app.py
tests/server/api/dataloaders/test_annotation_summaries.py

resolves #3829
Adds `AnnotationSummaries` to the `projects` table.
Currently a pure duplication of `EvaluationSummary` as we plan to generalize summaries to include both LLM and Human supplied annotations.

feat: Add annotation summaries to projects

---

app/package.json
app/src/contexts/FeatureFlagsContext.tsx
app/src/pages/trace/AnnotationActionMenu.tsx
app/src/pages/trace/EditSpanAnnotationsDialog.tsx
app/src/pages/trace/NewSpanAnnotationForm.tsx
app/src/pages/trace/SpanAnnotationActionMenu.tsx
app/src/pages/trace/SpanAnnotationForm.tsx
app/src/pages/trace/SpanDetails.tsx
app/src/pages/trace/__generated__/EditSpanAnnotationsDialogEditAnnotationMutation.graphql.ts
app/src/pages/trace/__generated__/EditSpanAnnotationsDialogNewAnnotationQuery.graphql.ts
src/phoenix/server/api/mutations/span_annotations_mutations.py

resolves #4076 
- adds the ability to edit human span annotations
https://github.com/user-attachments/assets/4898a20d-301d-4a67-bc2e-4c2412b6abe6

feat(annotations): add ability to edit human span annotations

---

src/phoenix/server/api/mutations/dataset_mutations.py
tests/server/api/mutations/test_dataset_mutations.py

resolves #3912 
When creating a dataset example from a span, the annotations associated with that span will be "snapshotted" and included in the span metadata under a new key: `annotations`. This key will always be present and empty if the span has no annotations.
If the span does have annotations, the structure of the annotations will be a mapping:
```
metadata:
annotations:
annotation_name:
label: label
score: score
explanation: explanation
metadata: metadata
annotator_kind: kind
```

feat: Add span annotations to dataset example metadata

---

src/phoenix/server/api/types/Span.py

fix: ensure span annotations appear in sorted order by name

---

app/schema.graphql
pyproject.toml
src/phoenix/db/bulk_inserter.py
src/phoenix/db/insertion/document_annotation.py
src/phoenix/db/insertion/span_annotation.py
src/phoenix/db/insertion/trace_annotation.py
src/phoenix/db/insertion/types.py
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/mutations/experiment_mutations.py
src/phoenix/server/api/mutations/project_mutations.py
src/phoenix/server/api/mutations/span_annotations_mutations.py
src/phoenix/server/api/mutations/trace_annotations_mutations.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/server/api/routers/v1/experiments.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/server/api/routers/v1/traces.py
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/app.py
src/phoenix/server/dml_event.py
src/phoenix/server/dml_event_handler.py
src/phoenix/server/types.py
tests/conftest.py
tests/server/api/routers/v1/test_annotations.py

resolves #4121 
This PR implements an internal event handling system for database events. Each handler handles events in batches, sleeping briefly between each batch. Events are generated by graphql mutations, REST API endpoints for insertions and deletions, as well as the bulk inserter for span and annotation ingestion.
One of the event handlers maintains the `last_updated_at` cache. This is used by the UI for automatic page refresh. Right now only the project page (with the traces and spans tables) gets refreshed automatically. After this PR, other pages that can also implement auto-refresh include projects overview, datasets overview, and experiment runs overview.
Other event handlers maintain the `cache_for_dataloaders`, which is currently only used by SQLite.

fix: cache invalidation

---

app/src/pages/project/ProjectPage.tsx
app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts

Previously both the traces table and the spans table was loaded when you hit the project page. This changes the logic so that the spans table only loads when you hit the spans tab.

fix(ui): lazy load the spans table on a project

---

app/package.json
app/pnpm-lock.yaml
app/src/components/trace/TraceTree.tsx
app/src/components/trace/TraceTreeContext.tsx
app/src/store/preferencesStore.tsx

Adds the ability to hide metrics (token counts, timing) as well as the ability to collapse the tree so you can expand as you go.
resolves #4145

feat(ui): add trace tree controls

---

app/src/pages/trace/EditSpanAnnotationsDialog.tsx
app/src/pages/trace/SpanAnnotationsEmpty.tsx
app/src/pages/trace/SpanFeedback.tsx

resolves #4142 
- adds cta to both annotate dialog and feedback tab on span details - only displays when there are no annotations of either type (human / llm)

feat(annotations): add cta for span annotations

---

app/src/components/ErrorBoundary.tsx
app/src/pages/trace/SpanAside.tsx
app/src/pages/trace/SpanDetails.tsx

If semantic attributes are not properly setup, we can end up with parsing or JS errors. This adds an error boundary lower down so we can catch it within the tab

chore(ui): add an error boundary arround span info to catch malformed attributes

---

app/src/pages/dataset/RunExperimentButton.tsx

The `RunExperimentButton` uses shows incorrect import path. This fixes the docstring.

fix: Correct import path in UI

---

src/phoenix/config.py

Adds auth-related environment variables, including:
- `DANGEROUSLY_SET_PHOENIX_ENABLE_AUTH`
- `DANGEROUSLY_SET_PHOENIX_SECRET`
These will eventually become:
- `PHOENIX_ENABLE_AUTH`
- `PHOENIX_SECRET`
when auth is officially released.
resolves #3728
resolves #4041

chore(auth): add auth-related environment variables

---

pyproject.toml
src/phoenix/db/migrations/future_versions/README.md
src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
src/phoenix/db/migrations/versions/.gitignore
src/phoenix/db/models.py

Adds the following database tables:
- `user_roles`
- `users`
- `api_keys`
- `audit_api_keys`
Adds migrations to create these tables, to populate the `user_roles` with system, admin, and member roles, and to populate the `users` table with a system user and an initial admin user.
Adds temporary `hatch` commands for development purposes:
- `hatch run auth:link` to add a symlink to the auth migration.
- `hatch run auth:unlink` to remove that symlink.
- `hatch run auth:up` to run the auth up-migration.
- `hatch run auth:down` to run the auth down-migration.
resolves #4043

chore(auth): add auth-related tables and migration

---

src/phoenix/experiments/functions.py
src/phoenix/experiments/types.py
src/phoenix/server/api/routers/v1/experiment_runs.py
tests/datasets/conftest.py
tests/datasets/test_experiments.py

resolves #4209 
This PR fixes the following error, when `evaluate_experiment` is executed on an existing experiment run, i.e. when the experiment run entries are pulled from the phoenix server.
```
166 @classmethod
167 def from_dict(cls, obj: Mapping[str, Any]) -> Dataset:
168     examples = tuple(map(Example.from_dict, obj.get(“examples”) or ()))
169     return cls(
--> 170         id=obj["id"],
171         version_id=obj[“version_id”],
172         examples={ex.id: ex for ex in examples},
```

fix: evaluate existing experiment runs

---

.github/workflows/release.yml

> google-github-actions/release-please-action is deprecated, please use googleapis/release-please-action instead.

ci: update `googleapis/release-please-action@v4`

---

app/src/App.tsx
app/src/Routes.tsx
app/src/config.ts
app/src/contexts/FunctionalityContext.tsx
app/src/pages/Layout.tsx
app/src/pages/index.tsx
app/src/pages/settings/SettingsPage.tsx
app/src/pages/settings/index.tsx
app/src/window.d.ts
cspell.json
src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/server/templates/index.html
src/phoenix/session/session.py
tests/conftest.py

resolves #4192 
Plumbs through the auth enabled flag and displays UI in the new settings page for user and api key management

feat(auth): plumb auth_enabled flag, add a settings page

---

src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/types/Span.py

Resolves #4167 
Span annotations should be propagated to dataset example metadata when added. However this functionality wasn't available on all mutations that created dataset examples.
This PR ensures that even if creating a dataset example via the `add_examples_to_dataset` mutation, associated span annotations are added to the metadata.

fix: Propagate span annotation metadata to examples on all mutations

---

packages/phoenix-evals/pyproject.toml

CI is failing due to breaking changes

ci(evals): limit `mistralai` below version 1.0

---

src/phoenix/experiments/functions.py

feat(experiments): ability to specify concurrency in run_experiment and evaluate_experiment

---

docs/datasets-and-experiments/how-to-experiments/run-experiments.md

The `ds` variable is never defined. This should have been `df` which is defined on line 32.

docs: fix variable name typo in run experiments doc

---

app/schema.graphql
pyproject.toml
src/phoenix/server/api/context.py
src/phoenix/server/api/mutations/__init__.py
src/phoenix/server/api/mutations/api_key_mutations.py
src/phoenix/server/api/mutations/auth.py
src/phoenix/server/app.py
src/phoenix/server/main.py

resolves #4234
This introduces create system API creation mutation. It is not wored up, is intended for scaffolding a working UI.
```graphql
mutation {
createSystemApiKey(input: { name: "system-api-key"}) {
jwt
apiKey {
name
description
createdAt
expiresAt
}
}
}
```
Payload
```json
{
"data": {
"createSystemApiKey": {
"jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3lzdGVtLWFwaS1rZXkiLCJkZXNjcmlwdGlvbiI6bnVsbCwiaWF0IjoxNzIzNjg3NTI4LCJpZCI6OH0.29TOm3JM2aY5vdALWnNlLA7cJXM1r3UZu3ApiqfEhpg",
"apiKey": {
"name": "system-api-key",
"description": null,
"createdAt": "2024-08-15T02:05:28+00:00",
"expiresAt": null
}
}
}
}
```

feat(auth): create system key

---

tutorials/human_feedback/chatbot_with_human_feedback.ipynb

resolves #4197 
This adds an end-to-end tutorial on how to build a manually-instrumented chatbot with user feedback. This feedback is recorded as a `SpanAnnotation` and automatically associated with the span that instrumented the generation of the chatbot response.
These annotations are directly viewable in the Phoenix UI.

docs: Add human feedback notebook tutorial

---

src/phoenix/server/api/routers/v1/spans.py

Defaults to `sync=False` on the `/span_annotations` route. This allows us to send annotations even if the span has not yet been exported by default.

fix: Default to adding span annotations to queue

---

app/src/pages/trace/SpanDetails.tsx

Some re-rankers such as this [Lost-in-the-middle re-ranker](https://docs.haystack.deepset.ai/docs/lostinthemiddleranker#in-a-pipeline) do not require queries. So we display the query card in the span details only conditionally.
resolves [#916](https://github.com/Arize-ai/openinference/issues/916)

fix: conditionally display re-ranker queries in span details

---

app/schema.graphql
app/src/pages/settings/UsersTable.tsx
app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
src/phoenix/db/models.py
src/phoenix/server/api/mutations/api_key_mutations.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/types/UserRole.py

refactor(auth): name it role.name

---

app/src/pages/dataset/DatasetCodeDropdown.tsx
app/src/pages/project/AnnotationSummary.tsx
app/src/pages/settings/APIKeysCard.tsx
app/src/pages/settings/CreateSystemAPIKeyDialog.tsx
app/src/pages/settings/SettingsPage.tsx
app/src/pages/settings/SystemAPIKeysTable.tsx
app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts
app/src/pages/settings/__generated__/CreateSystemAPIKeyDialogMutation.graphql.ts
app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts
app/src/pages/settings/__generated__/SystemAPIKeysTableRefetchQuery.graphql.ts

feat(auth): system api keys ui

---

packages/phoenix-otel/README.md
packages/phoenix-otel/src/phoenix/otel/__init__.py
packages/phoenix-otel/src/phoenix/otel/otel.py

- The high-level OTel wrappers will now print a summary of the TracerProvider that has been configured
- Defaults Phoenix endpoint to: `http://localhost:6006`
- Better handling of endpoints set via environment variables, defaults to using GRPC transport for spans
- Fixes small bugs

feat: Improve OTel wrapper ergonomics

---

pyproject.toml

`scipy==1.14.1` appears to be causing installations issues on MacOS.

ci: exclude buggy scipy version

---

.github/workflows/python-CI.yml

Sometimes github is slow and test can be flaky

ci(python): increase timeout for integration test

---

app/src/pages/experiments/ExperimentsTable.tsx

feat(experiments): add the ability to copy experiment IDs to the clipboard

---

pyproject.toml

`scipy` was missing a wheel for MacOS on this particular version. They have manually resolved the issue.
For context, see: https://github.com/scipy/scipy/issues/21424

chore: loosen scipy version

---

.github/workflows/python-CI.yml
integration_tests/server/test_launch_app.py

Sometimes when things fail, there can be an enormous amount of blank lines for some reason.

refactor: eliminate consecutive blank lines in log for integration test

---

src/phoenix/server/api/routers/v1/utils.py

Looks like I unnecessarily imported `TypeVar` from `typing_extensions` rather than `typing`, which is not supported by `pydantic` versions in the range `2.4.1<=pydantic<=2.7.1`.
For details, see https://github.com/pydantic/pydantic/issues/9499
resolves #4310

fix: support `pydantic` in the range `2.4.1<=pydantic<=2.7.1`

---

app/src/Routes.tsx
app/src/components/nav/Logo.tsx
app/src/pages/index.tsx
app/src/pages/login/LoginPage.tsx
app/src/pages/login/index.tsx

resolves #4311 
Creates a login form that uses an http POST for now as that's how it's setup
https://github.com/user-attachments/assets/2ba834ae-f25c-411e-ba6e-33774664c649

feat(auth): minimal login page

---

.github/workflows/typescript-CI.yml
app/.npmrc
app/package.json
app/pnpm-lock.yaml

https://github.com/pnpm/pnpm/releases/tag/v9.7.0
https://github.com/pnpm/pnpm/pull/8363
In order for the packageManger field to be picked up global pnpm must be >=9.7.0.
After that when you're in phoenix/app any pnpm commands will use the version specified in package json

chore: update pnpm version and pin in package.json

---

src/phoenix/server/api/dataloaders/dataset_example_revisions.py
src/phoenix/server/api/exceptions.py
src/phoenix/server/api/mutations/auth_mutations.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/mutations/experiment_mutations.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/schema.py
tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb

With this PR, the default behavior of GraphQL resolvers will be to return an error message of "an unexpected error occurred" for unhandled exceptions. If we wish for the resolver to return a more granular error message, you can return an instance of `CustomGraphQLError` or one of its subclasses. This prevents implementation details and potentially sensitive data from unintentionally leaking through the GraphQL API.

chore: mask unexpected error messages in graphql api

---

packages/phoenix-otel/src/phoenix/otel/otel.py
packages/phoenix-otel/src/phoenix/otel/settings.py

- If a HEADER that's passed using `PHOENIX_CLIENT_HEADERS` environment variable is not URL encoded, we will attempt to URL encode the header along while also printing a warning message. This PR mangles the header values, in case sensitive information such as authorization tokens are included in them.
- Furthermore, this PR fixes a bug where headers were not always properly being piped through when using the GRPC SpanExporter

feat: Improve urlencoding logic + bug fixes

---

pyproject.toml
src/phoenix/otel

Add the `arize-phoenix-otel` package a dependency for a Phoenix.
This is an independently-installable wrapper for OpenTelemetry primitives that helps simplify the OTel configuration process.

feat: Add arize-phoenix-otel as a dependency

---

schemas/openapi.json
src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
src/phoenix/server/api/routers/v1/experiments.py

resolves #4126 
- Includes the Experiments REST API in the OpenAPI Schema
cc @mikeldking per a previous comment you made, I think we should consider removing the `project` field entirely from the Experiment response object

feat: Add Experiments API to OpenAPI Schema

---

packages/phoenix-evals/src/phoenix/evals/models/openai.py

resolves #3821 
Azure API keys for OpenAI are passed using the `AZURE_OPENAI_API_KEY` environment variable. This PR removes the ability to fall back to the `OPENAI_API_KEY` environment variable if the API key cannot be found.

chore: Remove support for passing Azure env var via OpenAI env var

---

.github/workflows/docker-build-release.yml

Makes the Docker image a multi-architecture build with support for ARM64.
resolves #4383
resolves #3636

fix(docker): support arm64 architecture in docker images

---

packages/phoenix-otel/src/phoenix/otel/otel.py

Makes the kwarg for setting the default tracer provider maximally explicit. This was suggested by @mikeldking in a previous PR.

chore: Make keyword argument more explicit

---

src/phoenix/session/client.py

removes the previously deprecated `dataset_description` parameter in the `append_to_dataset` client method
resolves #3957

chore: remove dataset_description parameter in append_to_dataset client method

---

src/phoenix/session/client.py
tests/session/test_client.py

Improves the error message for the `query_spans` client method by providing explicit instructions to increase the `timeout` parameter upon timeout. This should provide the same error message for `get_trace_dataset`.
resolves #4331

fix: improve timeout error message for `query_spans` client method

---

src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/experiment_run_annotations.py
src/phoenix/server/api/types/ExperimentRun.py
src/phoenix/server/app.py

I noticed the experiment comparison page was making a ton of queries because I forgot to use a dataloader for experiment run annotations.
resolves #4396

fix: use dataloader for experiment run annotations

---

src/phoenix/server/api/dataloaders/dataset_example_revisions.py

The important thing this PR does is place a max batch size on the dataloader.
resolves #4401

fix(experiments): ensure compare experiments page does not break for experiments that contain a large number of examples

---

src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/trace/fixtures.py
src/phoenix/trace/utils.py

Using the `--scaffold-dataset` parameter results in the ingestion of dataset defined in the project/trace fixture that was passed in with `with-projects` or `with-trace-fixtures`.
resolves #4248, #4247, #4357

docs: demo dataset ingestion

---

api_reference/source/api/otel.rst
api_reference/source/conf.py
api_reference/source/index.md

resolves #4358 
Adds `phoenix.otel` API documentation

docs: Add OTEL module to API documentation

---

app/src/hooks/useInterval.ts
app/src/pages/projects/ProjectsAutoRefreshToggle.tsx
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
app/src/store/preferencesStore.tsx

partially addresses #4399
Allows you to turn off auto-refresh of projects so that pagination doesn't get reset as you scroll

feat(ui): add the ability to turn off auto-refresh of projects

---

src/phoenix/config.py

Detects if `PHOENIX_PORT` appears to be auto-generated by Kubernetes and adds an error message with instructions to resolve.
resolves #3899

fix: error message for PHOENIX_PORT env vars auto-generated by kubernetes

---

src/phoenix/server/app.py
src/phoenix/server/rate_limiters.py
tests/server/test_rate_limiters.py

resolves #4344 
- Implements a configurable rate limiter that can be applied to both GQL and REST routes
- Currently rate limits the `login` route by IP
- The IP cache rotates automatically and resets if not accessed for too long

feat: Implement serverside rate limiter

---

scripts/fixtures/vision.ipynb
tutorials/demos/demo_llama_index_rag.ipynb
tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
tutorials/evals/evaluate_rag.ipynb
tutorials/experiments/langchain_email_extraction.ipynb
tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
tutorials/experiments/llama-index/guideline_eval.ipynb
tutorials/experiments/llama-index/pairwise_eval.ipynb
tutorials/experiments/run_experiments_with_llama_index.ipynb
tutorials/experiments/summarization.ipynb
tutorials/human_feedback/chatbot_with_human_feedback.ipynb
tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
tutorials/integrations/bedrock_tracing_tutorial.ipynb
tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
tutorials/llm_ops_overview.ipynb
tutorials/mistral/evaluate_rag--mistral.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb
tutorials/tracing/crewai_tracing_tutorial.ipynb
tutorials/tracing/dspy_tracing_tutorial.ipynb
tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb
tutorials/tracing/tracing_with_projects_tutorial.ipynb

Update all notebooks to use `phoenix.otel` (except for the manual instrumentation notebook, which is raw opentelemetry)

chore: Use `phoenix.otel` in notebooks

---

app/src/components/project/PythonProjectGuide.tsx

There is a small typo in the app where the word `batching` is spelled as `baching`.

style: fix small typo in app

---

src/phoenix/server/api/routers/v1/__init__.py

resolves #4275 
Caveat: `Bearer ` prefix must be [manually added](https://stackoverflow.com/a/32995636) when entering the token.

feat: auth for swagger UI

---

app/schema.graphql
src/phoenix/server/api/queries.py
src/phoenix/server/api/types/ApiKey.py
src/phoenix/server/api/types/User.py

resolves #4452 
Adds an optional `api_keys` field to the `User` node. The `viewer` node will populate these API keys on the user if any exist.

feat: api keys on viewer node

---

tests/conftest.py

This marks all postgres tests with `xfail` and will fail the entire test suite if the number of `xfails` exceeds a threshold. For now this will allow us to develop with some degree of CI signal.

chore: Modify conftest to allow a threshold of flaky postgres tests

---

.github/workflows/python-CI.yml
tests/conftest.py

Enables flaky test allowance when run in CI. This is off by default, so we can still run tests normally locally.

chore: Enable flaky test allowance in CI only

---

app/schema.graphql
src/phoenix/server/api/mutations/user_mutations.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/types/User.py

resolves #4491 
resolves #4448

feat(gql): indicate whether user password needs reset

---

app/schema.graphql
integration_tests/auth/conftest.py
integration_tests/auth/test_auth.py
src/phoenix/auth.py
src/phoenix/db/facilitator.py
src/phoenix/server/api/exceptions.py
src/phoenix/server/api/mutations/user_mutations.py

feat(auth): add deleteUsers mutation

---

integration_tests/_helpers.py
integration_tests/auth/test_auth.py

Because the tests can be run concurrently, and we need the default admin to create database entities (e.g. to add new users), the default admin should never log out once logged in, because logging out invalidates all existing access tokens, resulting in a race among the tests. The approach here is to add a middleware to block any inadvertent use of the default admin's access tokens for logging out.

ci: forbid default admin from logging out when running tests concurrently

---

integration_tests/auth/test_auth.py
src/phoenix/server/api/dataloaders/users.py
src/phoenix/server/api/mutations/api_key_mutations.py
src/phoenix/server/api/mutations/user_mutations.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/routers/auth.py

Instead of deleting actual tuples in the `users` table, just soft-delete users by adding the `deleted_at` timestamp. Update other routes and resolvers accordingly.
resolves #4561

fix(auth): soft-delete users

---

README.md

Adds a link to the docs to the readme file. We have this in the buttons up top but it's suspiciously absent from the community links section

docs: add docs link to readme

---

src/phoenix/auth.py
src/phoenix/config.py
src/phoenix/server/api/routers/auth.py
src/phoenix/server/app.py
src/phoenix/server/main.py
tests/test_config.py

Adds environment variables for token expiries:
- `PHOENIX_ACCESS_TOKEN_EXPIRY` (default 10 min)
- `PHOENIX_REFRESH_TOKEN_EXPIRY` (default 1 week)
If a unitless integer or decimal is passed, assumes it is in seconds. Also accepts duration strings containing units that [can be parsed by `pandas.Timedelta`](https://pandas.pydata.org/docs/user_guide/timedeltas.html#parsing), e.g.,
- `1 days 2 hours`
- `1d 2h`
- `2 w`
- `P0DT0H1M0S` (ISO-8601 duration)
resolves #4584

feat(auth): add environment variables for token expiries

---

src/phoenix/config.py
src/phoenix/db/facilitator.py
src/phoenix/server/api/openapi/schema.py
src/phoenix/server/api/routers/__init__.py
src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/app.py
src/phoenix/server/main.py

Avoids the pattern of reading environment variables more than once. With this change, we read auth-related environment variables once and use dependency injection to get the values elsewhere.
resolves #4586

refactor(auth): ensure auth environment variables are read once

---

docs/quickstart/phoenix-inferences/README.md

PR is not related to an existing open issue. 
Corrects [published documentation](https://docs.arize.com/phoenix/inferences/phoenix-inferences) (believed to be located at `docs/quickstart/phoenix-inferences/README.md`) to address a problem with the provided example. 
Step 4 previously threw an error because "Inference" was not defined. There are two issues here: the class name should be "Inferences" (plural) and referenced via the `px` object. Additionally, instructions referring to the singular "inference" were updated for consistency.
This contribution was identified during a public workshop hosted by the Brain Wave Collective (@brainwavecollective). We learned about Phoenix from our friend Mikyo King (@mikeldking) who spoke at an RMAIIG meeting in Colorado. Credit for this contribution …

docs(quickstart): update inferences documentation to correct example syntax

---

packages/phoenix-otel/README.md
packages/phoenix-otel/src/phoenix/otel/otel.py
packages/phoenix-otel/src/phoenix/otel/settings.py

resolves #4536 
Automatically adds an auth header sensitivity to `phoenix.otel` if PHOENIX_API_KEY is set as an environment variable.
*NOTE* this PR also fixes a bug: in `python=3.8` `inspect.signature` generates the signature off of the `__new__` method of classes instead of `__init__` which can sometimes lead to inconsistencies. In this PR I've normalized how we create generate the instatiation signature so we can properly merge in auth headers if necessary

feat: Pick up authorization headers from environment variable

---

integration_tests/_helpers.py
integration_tests/auth/test_auth.py
src/phoenix/server/api/routers/__init__.py
src/phoenix/server/api/routers/embeddings.py
src/phoenix/server/app.py

Ensures that `/exports` is secured when auth is enabled.
resolves #4588

feat(auth): secure `/exports` when auth is enabled

---

src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
src/phoenix/db/models.py

Each refresh token should correspond to exactly one access token.
resolves #4607

fix(auth): add unique constraint on refresh_token_id in access_tokens table

---

app/src/components/auth/DeleteAPIKeyButton.tsx
app/src/pages/settings/DeleteUserButton.tsx
app/src/pages/settings/UsersTable.tsx
app/src/pages/settings/__generated__/DeleteUserButtonMutation.graphql.ts
app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
app/src/pages/settings/__generated__/UsersTable_users.graphql.ts

resolves #4553 
- allows for deleting users, does not show delete button for default admin user
https://github.com/user-attachments/assets/d4e340f3-4fd7-44c8-8bb4-92972c6b5be9

feat(auth): add delete user ui

---

docs/quickstart/phoenix-inferences/README.md

This is not related to an existing issue. However, this is another change similar to #4592.
In Quickstart: Inferences Step 6b, the model schema is defined as 'prod_schema'. However, in Step 6c, the px.Inferences sets schema to 'schema'. To enhance the documentation, the px.Inferences sets schema to 'prod_schema'. https://docs.arize.com/phoenix/inferences/phoenix-inferences.

docs (quickstart): fix incorrect object reference in Inferences example

---

tutorials/quickstarts/inferences_quickstart.ipynb

PR is not related to an existing open issue. 
Realized when following the [inferences quickstart](https://docs.arize.com/phoenix/inferences/phoenix-inferences) that an example notebook did not exist but the instructions at would be easy to convert. Note that the related change for PR #4592 is also reflected in this notebook.
This contribution was inspired by a public workshop hosted by the Brain Wave Collective (@brainwavecollective).

docs(quickstart): convert Phoenix inferences instructions to notebook

---

packages/phoenix-evals/src/phoenix/evals/models/openai.py
packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py

Ensures that the model payload is compatible with gpt-o1 preview

feat: OpenAI support for o1 preview
