src/phoenix/core/model.py

resolves https://github.com/Arize-ai/phoenix/issues/594

fix: exclude bool from numeric

---

src/phoenix/server/api/types/Dataset.py

resolves https://github.com/Arize-ai/phoenix/issues/604

fix: events with prompt-response pairs

---

DEVELOPMENT.md

Document the release process in DEVELOPMENT.md

docs: release process

---

src/phoenix/metrics/mixins.py

resolves https://github.com/Arize-ai/phoenix/issues/615

fix: return nan on TypeError

---

README.md

docs: Add a gif of the product to the README

---

src/phoenix/core/model_schema.py

> ValueError: NaTType does not support astimezone
> ValueError: NaTType does not support strftime

fix: add try except for pd.NaT

---

src/phoenix/core/model_schema.py
tests/core/test_model_schema.py

resolves https://github.com/Arize-ai/phoenix/issues/632

fix: remove uniqueness requirement on dimension roles

---

src/phoenix/core/model_schema.py
tests/core/test_model_schema.py

follow-up to https://github.com/Arize-ai/phoenix/pull/603

fix: add tests

---

src/phoenix/datasets/fixtures.py
src/phoenix/server/main.py

resolves https://github.com/Arize-ai/phoenix/issues/650

fix: saving fixtures locally (for development)

---

.github/workflows/typescript-CI.yml
app/jest.config.js
app/package-lock.json
app/package.json
app/src/components/chart/__tests__/getFormatFromSamplingInterval.test.ts
app/src/components/chart/index.tsx
app/src/components/chart/useTimeTickFormatter.ts
app/src/pages/embedding/CountTimeSeries.tsx
app/src/pages/embedding/EuclideanDistanceTimeSeries.tsx
app/src/utils/timeSeriesUtils.ts
app/tsconfig.json

This PR adds time formatting based on sampling interval to the charting. It also adds jest unit tests.

feat(ui): time formatting on x axis

---

src/phoenix/metrics/metrics.py

Remove type check errors on main

ci: lift casting to float

---

examples/README.md
examples/anthropic_evals_persona.ipynb

resolves #620 
Re-adds the /examples directory with showcase examples

docs: anthropic evals exploration use-case

---

app/schema.graphql
src/phoenix/server/api/types/DatasetRole.py
src/phoenix/server/api/types/Dimension.py
src/phoenix/server/api/types/EmbeddingDimension.py
src/phoenix/server/api/types/TimeSeries.py

resolves #682 
https://user-images.githubusercontent.com/80478925/236916793-20f81dd7-90db-4e10-abef-e0365af8667d.mov

feat: add dataset role to graphql endpoints for data quality metrics

---

src/phoenix/datasets/dataset.py

fix: retain filtered index at timestamp creation

---

docs/concepts/llm-observability.md

docs: update llm-observability.md

---

src/phoenix/server/api/types/UMAPPoints.py

fix: buggy formula for drift ratio

---

app/src/components/chart/ChartTooltip.tsx
app/src/pages/dimension/Dimension.tsx
app/src/pages/dimension/DimensionSegmentsBarChart.tsx
app/src/pages/dimension/__generated__/DimensionQuery.graphql.ts
app/src/pages/dimension/__generated__/DimensionSegmentsBarChart_dimension.graphql.ts

resolves #663 
Shows the histogram / bar char for all dimension types. Requires some formatting work as cleanup but will do this as a follow-up.

feat(dimension): dimension segments bar chart

---

docs/README.md
docs/concepts/llm-observability.md

chore: "docs: sync 5-18-2023"

---

app/schema.graphql
src/phoenix/server/api/input_types/Coordinates.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/EmbeddingDimension.py
src/phoenix/server/api/types/Event.py

feat: graphql endpoint for hdbscan

---

src/phoenix/core/embedding_dimension.py
src/phoenix/core/model_schema.py
src/phoenix/metrics/binning.py
src/phoenix/metrics/metrics.py
src/phoenix/metrics/mixins.py
src/phoenix/server/api/types/Segments.py
src/phoenix/server/api/types/UMAPPoints.py
tests/core/test_model.py
tests/core/test_model_schema.py
tests/metrics/test_binning.py
tests/metrics/test_cardinality.py
tests/metrics/test_scalar_drift.py
tests/server/api/test_interceptor.py

numpy [constants](https://numpy.org/doc/stable/reference/constants.html) are shorter to type and are faster (because they are lookups and not function calls)

ci: replace float(...) with numpy constants

---

app/src/components/table/PercentCell.tsx
app/src/pages/dimension/Dimension.tsx
app/src/pages/dimension/DimensionCardinalityStats.tsx
app/src/pages/dimension/DimensionPercentEmptyStats.tsx
app/src/pages/dimension/__generated__/DimensionCardinalityStats_dimension.graphql.ts
app/src/pages/dimension/__generated__/DimensionPercentEmptyStats_dimension.graphql.ts
app/src/pages/dimension/__generated__/DimensionQuery.graphql.ts
app/src/utils/numberFormatUtils.ts

resolves #743 
Shows reference values for % empty and cardinality. Punting on quantiles pending design changes by @theandylu

feat(dimension): show reference dataset data quality stats

---

src/phoenix/core/model_schema.py

ci: use 2 bytes each instead of 8 for nan series

---

app/package-lock.json
app/package.json
app/schema.graphql
app/src/@types/geometry.d.ts
app/src/components/pointcloud/ClusteringSettings.tsx
app/src/components/pointcloud/PointCloud.tsx
app/src/components/pointcloud/PointCloudClusters.tsx
app/src/components/pointcloud/PointCloudPoints.tsx
app/src/components/pointcloud/types.ts
app/src/constants/pointCloudConstants.tsx
app/src/pages/embedding/Embedding.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/__generated__/EmbeddingUMAPQuery.graphql.ts
app/src/store/__generated__/pointCloudStore_clustersQuery.graphql.ts
app/src/store/pointCloudStore.ts
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/EmbeddingDimension.py

resolves #745 
resolves #744 
Adds HDBSCAN tuning to the point-cloud. 
NB: there are still some optimizations that need to be made for the point-cloud to not reset the zoom.
https://github.com/Arize-ai/phoenix/assets/5640648/70d20e7f-6a0b-45f6-b7a6-efe538803f9e

feat: hdbscan tuning

---

app/package.json
app/src/pages/embedding/PointSelectionTable.tsx

feat(embeddings): show the dataset in the table

---

app/schema.graphql
src/phoenix/metrics/__init__.py
src/phoenix/metrics/metrics.py
src/phoenix/metrics/mixins.py
src/phoenix/metrics/timeseries.py
src/phoenix/pointcloud/pointcloud.py
src/phoenix/server/api/helpers.py
src/phoenix/server/api/input_types/DataQualityMetricInput.py
src/phoenix/server/api/input_types/DimensionFilter.py
src/phoenix/server/api/input_types/TimeRange.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Cluster.py
src/phoenix/server/api/types/DatasetValues.py
src/phoenix/server/api/types/Dimension.py
src/phoenix/server/api/types/EmbeddingDimension.py
src/phoenix/server/api/types/Segments.py
src/phoenix/server/api/types/UMAPPoints.py
tests/pointcloud/test_pointcloud.py

feat: data quality metric by cluster

---

app/schema.graphql
src/phoenix/pointcloud/pointcloud.py
src/phoenix/server/api/input_types/ClusterInput.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Cluster.py

resolves https://github.com/Arize-ai/phoenix/issues/807

feat: add stand-alone clusters endpoint for GraphQL query

---

app/src/pages/embedding/ClusterSortPicker.tsx
app/src/pages/embedding/Embedding.tsx
app/src/store/pointCloudStore.ts

related to #825
Adds the ability to sort clusters. This only lets you sort by drift and size. Performance will be done as a follow-up.

feat(embeddings): cluster sorting

---

app/schema.graphql
src/phoenix/server/api/types/Event.py
src/phoenix/server/api/types/EventMetadata.py

resolves https://github.com/Arize-ai/phoenix/issues/809

feat(gql): add prediction id to event metadata

---

src/phoenix/datasets/dataset.py
tests/datasets/test_dataset.py

resolves https://github.com/Arize-ai/phoenix/issues/697
In Colab, it takes about about `1 min 12s` to convert 1M lists with 1K elements each.

fix: coerce lists to arrays

---

app/package-lock.json
app/package.json
app/src/pages/ErrorElement.tsx

fix: show not found error when server is no longer running

---

app/schema.graphql
src/phoenix/server/api/types/PerformanceMetric.py

Camel-cases all metrics to be consistent across the board wrt graphql

chore: camel-case metrics

---

app/src/pages/embedding/Embedding.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/__generated__/EmbeddingUMAPQuery.graphql.ts
app/src/pages/embedding/__generated__/PointSelectionPanelContentQuery.graphql.ts
app/src/pages/embedding/types.ts
app/src/store/pointCloudStore.ts

resolves https://github.com/Arize-ai/phoenix/issues/810

feat: show prediction id in selection details

---

app/package.json
app/src/components/pointcloud/index.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/PointSelectionPanelContent.tsx
app/src/pages/embedding/PointSelectionTable.tsx
app/src/pages/embedding/__generated__/PointSelectionPanelContentQuery.graphql.ts
app/src/pages/embedding/types.ts
app/src/store/pointCloudStore.ts

resolves #824 
Cleans up the detail view to not repeat information.

fix(ui): cleanup event details for llm use-case

---

app/schema.graphql
src/phoenix/core/model_schema.py
src/phoenix/server/api/types/ExportEventsMutation.py

resolves https://github.com/Arize-ai/phoenix/issues/784

feat(gql): export multiple clusters at the same time

---

app/src/pages/embedding/Embedding.tsx
app/src/pages/embedding/EmbeddingActionMenu.tsx
app/src/pages/embedding/__generated__/EmbeddingActionMenuExportClustersMutation.graphql.ts

resolves #784 
Export all clusters in a single dataframe

feat(embeddings): export all clusters

---

src/phoenix/__init__.py
src/phoenix/datasets/dataset.py
src/phoenix/datasets/schema.py
tests/datasets/test_dataset.py
tests/datasets/test_schema.py

resolves #878 
Adds the concept of a relationship that maps an inference to another ID'd entity (e.g. a row in another dataset).

feat(retrieval): relationships schema and parsing

---

src/phoenix/datasets/fixtures.py

resolves https://github.com/Arize-ai/phoenix/issues/897

ci: add fixture for semantic search

---

pyproject.toml
src/phoenix/__init__.py

adjust to changes for https://github.com/scikit-learn-contrib/hdbscan/issues/600

ci: bump hdbscan to deal with cython builds

---

src/phoenix/datasets/schema.py

resolves https://github.com/Arize-ai/phoenix/issues/950

fix: restore truthiness

---

app/src/components/pointcloud/DatasetVisibilitySettings.tsx
app/src/components/pointcloud/PointCloudPoints.tsx
app/src/components/pointcloud/ShapeIcon.tsx

feat: display corpus points as octahedrons

---

app/schema.graphql
src/phoenix/server/api/types/Cluster.py

feat: primary to corpus ratio

---

src/phoenix/core/model.py
src/phoenix/core/model_schema.py
src/phoenix/core/model_schema_adapter.py
src/phoenix/datasets/dataset.py
src/phoenix/datasets/fixtures.py
src/phoenix/datasets/schema.py
src/phoenix/datasets/validation.py
src/phoenix/server/api/types/Event.py

resolves: https://github.com/Arize-ai/phoenix/issues/851

feat: allow string only responses (i.e. without embedding)

---

app/schema.graphql
src/phoenix/server/api/types/Dimension.py
src/phoenix/server/api/types/EmbeddingDimension.py
src/phoenix/server/api/types/TimeSeries.py

feat: calculate euclidean distance retrieval metric time series against the corpus dataset

---

app/src/pages/embedding/MetricTimeSeries.tsx
app/src/pages/embedding/__generated__/MetricTimeSeriesQuery.graphql.ts

resolves #958 
The UI portion of showing query to corpus euclidean distance top-level.

feat(embeddings): show retrieval distance timeseries

---

app/package-lock.json
app/package.json
app/src/App.tsx
app/src/Routes.tsx
app/src/components/model/ModelEmbeddingsTable.tsx
app/src/components/model/ModelSchemaTable.tsx
app/src/index.tsx
app/src/pages/ModelRoot.tsx
app/src/pages/__generated__/ModelRootQuery.graphql.ts
app/src/pages/dimension/DimensionPage.tsx
app/src/pages/dimension/__generated__/DimensionPageQuery.graphql.ts
app/src/pages/dimension/index.tsx
app/src/pages/embedding/EmbeddingPage.tsx
app/src/pages/embedding/__generated__/EmbeddingPageModelQuery.graphql.ts
app/src/pages/embedding/__generated__/EmbeddingPageUMAPQuery.graphql.ts
app/src/pages/embedding/index.tsx
app/src/pages/embedding/types.ts
app/src/pages/home/index.tsx
app/src/pages/index.tsx
app/src/pages/model/ModelPage.tsx
app/src/pages/model/__generated__/ModelPageQuery.graphql.ts
app/src/pages/model/index.tsx

resolves #1016 
Moves all model related queries under /model

feat(traces): move single model view under /model

---

src/phoenix/trace/schemas.py
src/phoenix/trace/span_json_decoder.py
src/phoenix/trace/span_json_encoder.py
src/phoenix/trace/tracer.py
tests/trace/test_tracer.py

resolves #1017 
Strawman implementation of a Tracer that allows you to create a `span` and accumulate it in buffers.

feat(tracing): strawman tracer implementation

---

scripts/data/generate_traces.py
src/phoenix/__init__.py
src/phoenix/trace/fixtures.py
src/phoenix/trace/schemas.py
src/phoenix/trace/tracer.py
src/phoenix/trace/utils.py

Resolves #1032 
Adds tracing fixture data for easy loading for development. Currently builds on the tracer branch.

chore(tracing): traces fixtures

---

pyproject.toml
src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/trace/tracer.py
tests/experimental/callbacks/test_langchain_tracer.py

resolves: https://github.com/Arize-ai/phoenix/issues/1019

feat: add langchain tracer (experimental)

---

app/src/components/model/ModelEmbeddingsTable.tsx
app/src/pages/trace/SpansTable.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/trace/__generated__/SpansTable_spans.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts

resolves #1061
Adds a rudimentary table of spans to just get started.

feat(tracing): spans table

---

app/schema.graphql
app/src/pages/trace/SpansTable.tsx
app/src/pages/trace/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/trace/__generated__/SpansTable_spans.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/trace_dataset.py

resolves #1070 
Adds a latency column.
NB: does not include UI sorting.

feat(tracing): add latency column

---

tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb

fix: var not defined for langchain notebook

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/trace/semantic_conventions.py
src/phoenix/trace/span_json_decoder.py
tests/experimental/callbacks/test_langchain_tracer.py

feat: semantic convention for input and output span attributes

---

src/phoenix/__init__.py
src/phoenix/session/session.py

resolves #1082
fixes the tracing init

fix(tracing): launch fix for traces

---

tutorials/internal/llama_index_tracing.ipynb

docs: llama index tracing internal notebook

---

tutorials/ragas_retrieval_evals_tutorial.ipynb

resolves #1097 
Allows you to color the point cloud based on `context_relevancy`, `answer_relevancy` and `faithfulness` and find clusters with a high density of problems.
https://github.com/Arize-ai/phoenix/assets/5640648/bd2a1ae2-53de-42a2-a2ec-1b50e5adf9bf

docs: ragas tutorial

---

app/schema.graphql
src/phoenix/server/api/types/Span.py

feat(gql): span attributes as json string

---

app/schema.graphql
src/phoenix/server/api/schema.py

feat(gql): filter spans by trace id

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/trace/schemas.py

fix: add unknown span kind enum

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/trace/semantic_conventions.py
tests/experimental/callbacks/test_langchain_tracer.py

feat: semantic convention for prompt template

---

src/phoenix/experimental/callbacks/langchain_tracer.py

Resolves this issue
```
ERROR:phoenix.experimental.callbacks.langchain_tracer:Failed to convert run to spans
File "/Users/xandersong/phoenix/src/phoenix/experimental/callbacks/langchain_tracer.py", line 106, in _persist_run
self._convert_run_to_spans(run.dict())
File "/Users/xandersong/phoenix/src/phoenix/experimental/callbacks/langchain_tracer.py", line 100, in _convert_run_to_spans
self._convert_run_to_spans(child_run, span)
File "/Users/xandersong/phoenix/src/phoenix/experimental/callbacks/langchain_tracer.py", line 100, in _convert_run_to_spans
self._convert_run_to_spans(child_run, span)
File "/Users/xandersong/phoenix/src/phoenix/experimental/callbacks/langchain_tracer.py", line 86, in _convert_run_to_spans …
```

fix: langchain tracer prompt template issue

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/trace/semantic_conventions.py
src/phoenix/trace/span_json_decoder.py
tests/experimental/callbacks/test_langchain_tracer.py

feat(trace): exception event

---

pyproject.toml
src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/semantic_conventions.py
src/phoenix/trace/trace_dataset.py
tests/experimental/callbacks/conftest.py
tests/experimental/callbacks/test_llama_index_trace_callback_handler.py
tutorials/internal/llama_index_tracing.ipynb

resolves #1077 
Adds input output values for llama_index traces

feat(tracing): llama_index IO

---

app/package.json
app/src/components/table/Table.tsx
app/src/components/table/TableEmpty.tsx
app/src/components/table/TimestampCell.tsx
app/src/components/table/styles.ts
app/src/components/trace/SpanKindLabel.tsx
app/src/pages/Layout.tsx
app/src/pages/embedding/PointSelectionTable.tsx
app/src/pages/trace/SpansTable.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/trace/__generated__/SpansTable_spans.graphql.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
app/src/typeUtils.ts

feat(tracing): span table with sorting and pagination

---

app/schema.graphql
scripts/data/build_langchain_vector_store.py
src/phoenix/core/traces.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Span.py
tests/core/test_traces.py

feat(trace): gql descendant spans list

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py
src/phoenix/trace/tracer.py
tests/experimental/callbacks/test_langchain_tracer.py
tests/experimental/callbacks/test_llama_index_trace_callback_handler.py
tutorials/internal/llama_index_tracing.ipynb

Just make the ergonomics of the code look better and not expose internals when possible.

feat(tracing): Expose get spans method

---

app/package.json
app/src/components/trace/TraceTree.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracingHomePage.tsx
scripts/data/build_langchain_vector_store.py
src/phoenix/trace/fixtures.py
tutorials/internal/llama_index_tracing.ipynb

resolves #1063
Adds a tree view of the spans to visualize the hierarchy

feat(tracing): tree view of traces

---

app/schema.graphql
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
src/phoenix/server/api/types/MimeType.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/semantic_conventions.py

resolves: #1140 
resolves: #1141

feat(trace): gql span input/output

---

app/package-lock.json
app/package.json
app/src/components/table/IntCell.tsx
app/src/components/table/TableExpandButton.tsx
app/src/components/trace/SpanItem.tsx
app/src/components/trace/TraceTree.tsx
app/src/components/trace/__tests__/utils.test.ts
app/src/components/trace/types.ts
app/src/components/trace/utils.ts
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/TracingHomePage.tsx
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts

resolves #1136 
Creates a expandable table view for traces to look at root spans.

feat(tracing): traces table

---

src/phoenix/trace/fixtures.py

useful for development and testing

ci: restore random fixture

---

tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb

docs: Update milvus_llamaindex_search_and_retrieval_tutorial.ipynb

---

app/schema.graphql
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
src/phoenix/core/traces.py
src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/trace_dataset.py
tests/core/test_traces.py

feat(trace): gql cumulative token count

---

app/src/Routes.tsx
app/src/components/table/TimestampCell.tsx
app/src/pages/tracing/TracingHomePage.tsx
app/src/pages/tracing/TracingHomePageHeader.tsx
app/src/pages/tracing/__generated__/TracingHomePageHeader_stats.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts

resolves #1192 
We probably want total token count but we will do that in a follow-up

feat(traces): add tracing overview stats

---

src/phoenix/experimental/callbacks/langchain_tracer.py
src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py
src/phoenix/trace/semantic_conventions.py
tests/experimental/callbacks/test_langchain_tracer.py
tests/server/api/types/test_span.py

feat(trace): semantic convention for retrieval documents

---

tutorials/internal/llama_index_tracing.ipynb

Cleanup work to make it more concise

chore(tracing): feature parity for llama-index tracing notebook

---

tutorials/internal/llama_index_tracing.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb

fix(notebook): KeyError in os.environ

---

app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
src/phoenix/__init__.py

fix: disable sorting as a stopgap

---

app/schema.graphql
app/src/components/trace/SpanItem.tsx
app/src/components/trace/types.ts
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
src/phoenix/server/api/types/Span.py

from langchain after keyboard interrupt
https://github.com/Arize-ai/phoenix/assets/80478925/ed930986-a2b6-449c-981c-479dccbcfea5

fix(trace): allow null end times

---

src/phoenix/server/api/schema.py

when the operand is an empty dataframe

fix: pandas `.apply` returns DataFrame when it should return Series

---

src/phoenix/experimental/evals/__init__.py
src/phoenix/experimental/evals/utils.py

I don't currently have access to `phoenix-assets`. Writing JSONL files to cloud storage for now.

feat: download evaluation dataset

---

pyproject.toml
src/phoenix/experimental/evals/__init__.py
src/phoenix/experimental/evals/functions/__init__.py
src/phoenix/experimental/evals/functions/binary.py
src/phoenix/experimental/evals/models/__init__.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/templates/__init__.py
src/phoenix/experimental/evals/templates/prebuilt_templates.py
src/phoenix/experimental/evals/templates/template.py
src/phoenix/experimental/evals/utils/downloads.py
src/phoenix/experimental/evals/utils/threads.py
src/phoenix/experimental/evals/utils/types.py

Closes #1202 
Closes #1203
Closes #1204
Closes #1206
Closes #1247

feat: Add binary evals using OpenAI model

---

integration-tests/experimental/callbacks/test_llama_index_callback_handler.py
src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py

feat(trace): token counts for llama-index callback

---

src/phoenix/__init__.py
src/phoenix/config.py
src/phoenix/server/main.py
src/phoenix/server/thread_server.py
src/phoenix/services.py
src/phoenix/session/session.py

Tested in Docker with a matrix of `run_in_thread` equal to `True` and `False` and `host` equal to `0.0.0.0` and the default `127.0.0.1`. Works as expected.

feat: add host parameter to launch_app

---

src/phoenix/config.py
src/phoenix/server/main.py
src/phoenix/server/thread_server.py
src/phoenix/services.py
src/phoenix/session/session.py
src/phoenix/trace/trace_dataset.py

resolves #1258 
Caveat: it can still take almost 20s to start.

fix: process server start in Colab (infinite loop)

---

tests/trace/test_schemas.py

tested with `protobuf==4.24.3`

fix: protobuf attributes nan test

---

pyproject.toml

This reverts commit a90956a865d8b24eb4d96cdba89a949324655e49.

fix: relax pandas version

---

pyproject.toml
tests/metrics/test_wrappers.py

resolves #1281 
resolves #1297

fix: pin pandas==1.4.0 for tests

---

tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb

Adjusted notebook to get the data loaded into the DB properly using new syntax

docs: Update milvus_llamaindex_search_and_retrieval_tutorial.ipynb 

---

src/phoenix/experimental/evals/__init__.py
src/phoenix/experimental/evals/templates/__init__.py
src/phoenix/experimental/evals/templates/default_templates.py
tutorials/evals/evaluate_hallucination_classifications.ipynb
tutorials/evals/evaluate_relevance_classifications.ipynb

feat: colocate rails with templates

---

src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py

resolves: #1312 
`messages` in llama_index is used for the input to an agent, which is different from QUERY_STR, this makes these consistent for the spans to work and also only populates the LLM attributes with messages when the spanKind is LLM

fix(tracing): map message to input, parse messages only for LLM

---

integration-tests/experimental/callbacks/test_llama_index_callback_handler.py
src/phoenix/experimental/callbacks/llama_index_trace_callback_handler.py

resolves #1270 
See llama-index source code [here](https://github.com/jerryjliu/llama_index/blob/ec33979f702c67ec7ba7bd924ba432e00b761dbc/llama_index/llms/openai.py#L169-L179) and [here](https://github.com/jerryjliu/llama_index/blob/ec33979f702c67ec7ba7bd924ba432e00b761dbc/llama_index/llms/openai.py#L279-L280).

feat: add LLM invocation parameters for llama-index

---

src/phoenix/session/session.py

feat: get port number from environment variable

---

.pre-commit-config.yaml
app/package.json
integration-tests/experimental/callbacks/test_langchain_tracer.py
pyproject.toml
src/phoenix/server/api/types/DataQualityMetric.py
src/phoenix/server/api/types/ExportEventsMutation.py
src/phoenix/server/api/types/TimeSeries.py
src/phoenix/trace/fixtures.py
src/phoenix/trace/span_json_decoder.py
tests/datasets/test_validation.py
tests/metrics/test_timeseries.py
tests/trace/test_span_json_decoder.py

Most recent jsonl load was failing on document metadata parsing
```
File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/mikeldking/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/mikeldking/work/phoenix/src/phoenix/server/main.py", line 122, in <module>
traces.put(span)
File "/Users/mikeldking/work/phoenix/src/phoenix/core/traces.py", line 130, in put
self._queue.put(encode(span) if isinstance(span, Span) else span)
File "/Users/mikeldking/work/phoenix/src/phoenix/trace/v1/__init__.py", line 56, in encode
retrieval, _attributes = _excise_retrieval(_attributes)
File …
```

fix(tracing): document metadata parsing

---

app/src/openInference/tracing/semanticConventions.ts
app/src/openInference/tracing/types.ts
app/src/pages/trace/TracePage.tsx

feat(tracing): embedded txt

---

docs/concepts/langchain-and-llamaindex-traces.md
src/phoenix/session/session.py
tutorials/tracing/llama_index_tracing_tutorial.ipynb

fix(tracing): span plural for export

---

tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb

docs: update google palm tracing notebook and add vertex ai tracing notebook

---

tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb
tutorials/llama_index_search_and_retrieval_tutorial.ipynb
tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb

See https://github.com/jerryjliu/llama_index/issues/7713#issuecomment-1723903025

fix: pin langchain version

---

app/package.json
app/src/openInference/tracing/semanticConventions.ts
app/src/pages/trace/TracePage.tsx
src/phoenix/trace/fixtures.py

resolves #1348 
Adds the details of tools

feat(tracing): tool details ui

---

app/src/openInference/tracing/semanticConventions.ts
app/src/pages/trace/TracePage.tsx
app/src/typeUtils.ts
src/phoenix/trace/fixtures.py

feat: add prompts list to ui

---

tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb

chore: add dataframe export to end of google notebooks

---

src/phoenix/server/api/types/Span.py

fix: hide embedding vector in graphql attributes

---

pyproject.toml
src/phoenix/trace/llama_index/callback.py

refactor: remove openai from import for llama-index tracer

---

pyproject.toml
tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb
tutorials/llama_index_search_and_retrieval_tutorial.ipynb
tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb

resolves #1381 
see llama-index [0.8.29](https://github.com/jerryjliu/llama_index/pull/7716/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6)

fix: unpin langchain version

---

.tours/app.tour

resolves #1284 
Adds a code-tour four the app

docs(development): app tour

---

integration-tests/trace/llama_index/test_callback.py
src/phoenix/trace/llama_index/callback.py

fix: capture function call output in llama-index

---

tutorials/internal/llama_index_data_agent_tracing_example.ipynb

resolves #1360
see https://github.com/Arize-ai/phoenix/issues/1360#issuecomment-1726258561

fix(notebook): change `.chat` to `.query` in llama-index agent call

---

src/phoenix/session/session.py
src/phoenix/trace/trace_dataset.py
src/phoenix/trace/utils.py

fix: set `max_level=1` in `json_normalize` to prevent splintering

---

src/phoenix/trace/langchain/tracer.py
tests/trace/langchain/test_tracer.py

feat: langchain llm message attributes

---

src/phoenix/trace/langchain/tracer.py

feat: agent span kind for langchain

---

app/package-lock.json
app/package.json
app/src/components/trace/LatencyText.tsx
app/src/components/trace/SpanItem.tsx
app/src/components/trace/SpanKindIcon.tsx
app/src/components/trace/SpanKindLabel.tsx
app/src/components/trace/TraceTree.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx

resolves #1423 
Colors the latency by duration so that it highlights areas that are slow.

feat(tracing): highlight slow spans

---

app/src/components/Link.tsx
app/src/components/table/styles.ts
app/src/components/trace/TraceTree.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx

resolves #1382 
Makes the rows clickable

feat(tracing): make row clickable

---

docs/integrations/langchain.md
docs/integrations/llamaindex.md

resolves #1430 
Adds integration guidelines for tracing frameworks

docs: langchain and llama_index integration

---

README.md

docs: update README with tracing

---

app/schema.graphql
app/src/pages/tracing/TracingHomePageHeader.tsx
app/src/pages/tracing/__generated__/TracingHomePageHeader_stats.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
src/phoenix/core/traces.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/DatasetInfo.py

feat: add total token count for trace page header

---

app/src/openInference/tracing/semanticConventions.ts
app/src/pages/trace/TracePage.tsx
integration-tests/trace/langchain/test_tracer.py
integration-tests/trace/llama_index/test_callback.py
src/phoenix/trace/langchain/tracer.py
src/phoenix/trace/llama_index/callback.py
src/phoenix/trace/semantic_conventions.py
tests/server/api/types/test_span.py
tests/trace/langchain/test_tracer.py

feat: add `LLM_OUTPUT_MESSAGES` and change `LLM_MESSAGES` to `LLM_INPUT_MESSAGES`

---

pyproject.toml
src/phoenix/__init__.py

Not needed as now html is a template

fix: remove html as ensured-targets

---

src/phoenix/core/traces.py

fix: typo in token count formula

---

README.md

docs: update RAG terminology

---

tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb

- ensures session url is present at the end of each tracing notebook

docs: add session info for notebooks

---

tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb

resolves #1488 
Will merge after release. Switches to using the Instrumentor instead of the tracer directly.

docs(tracing): update langchain notebooks to use the instrumentor

---

src/phoenix/experimental/evals/functions/binary.py
tests/experimental/evals/functions/test_binary.py

- add unit test
- add case-insensitivity for parsing

fix: case-insensitive rails parsing

---

.github/workflows/python-CI.yml
pyproject.toml
src/phoenix/experimental/evals/functions/binary.py
src/phoenix/experimental/evals/functions/generate.py
src/phoenix/experimental/evals/functions/processing.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/templates/template.py
tests/experimental/evals/functions/test_binary.py
tests/experimental/evals/functions/test_generate.py
tests/trace/langchain/test_tracer.py
tests/trace/llama_index/test_callback.py

Closes #1445 
It is still pending to [Implement context window overflow for `vertexai` models ](https://github.com/Arize-ai/phoenix/issues/1517)

feat: Add processing functions file and token methods to OpenAIModel

---

app/schema.graphql
app/src/components/trace/LatencyText.tsx
app/src/pages/tracing/TracingHomePageHeader.tsx
app/src/pages/tracing/__generated__/TracingHomePageHeader_stats.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
pyproject.toml
src/phoenix/core/traces.py
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/DatasetInfo.py

feat: add latency P50 and P99 to tracing page header

---

scripts/rag/llamaindex_retrieval_chunk_eval.ipynb

CI breaking on `main` at the moment.

fix: notebook style

---

src/phoenix/experimental/evals/templates/default_templates.py

bug due to llm returning lowercase "good" / "bad" was causing issues with NaN value. Changed the mapping and prompt to adjust

fix(evals): update prompt template for summarization eval and rails mapping to use lower case "good" / "bad"

---

src/phoenix/experimental/evals/models/openai.py

resolves #1482 
screenshot below shows the additional parameters that are necessary

feat(evals): add Azure parameters to `OpenAIModel`

---

.pre-commit-config.yaml
tutorials/tracing/openai_tracing_tutorial.ipynb

- demonstrate structured data extraction using OpenAI function calling
- demonstrate `OpenAIInstrumentor`
Follow-up: [Add evals for structured data extraction](https://github.com/Arize-ai/phoenix/issues/1581)

docs: OpenAIInstrumentor tutorial notebook

---

src/phoenix/trace/filter.py

fix(trace): remove unnecessary exclusion of semantic conventions for filter validation

---

tutorials/tracing/llama_index_tracing_tutorial.ipynb

Not sure how this got in there.

docs: remove langchain from llama_index tutorial

---

app/package-lock.json
app/package.json
app/src/pages/tracing/SpanFilterConditionField.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/pages/tracing/__generated__/SpanFilterConditionFieldValidationQuery.graphql.ts
app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts

resolves #1541 
Adds filter condition support for filtering down the traces. This still needs some ergonomic fixes as it's pretty hard to type out some of the filters.
Semi-blocked by #1593 for containment search

feat(tracing): trace and span filter / search field

---

app/src/pages/tracing/SpanFilterConditionField.tsx
src/phoenix/core/traces.py
src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/filter.py

feat: add computed values (e.g. latency) to filterable quantities

---

src/phoenix/experimental/evals/models/openai.py

resolves: #1399 
```
precision    recall  f1-score   support
hallucinated       0.87      0.80      0.84        51
factual       0.81      0.88      0.84        49
```
```
precision    recall  f1-score   support
readable       0.69      1.00      0.82        52
unreadable       1.00      0.52      0.68        48
```
```
precision    recall  f1-score   support
good       0.55      0.98      0.71        53
bad       0.83      0.11      0.19        47
```
```
precision    recall  f1-score   support
correct       0.89      0.96      0.92        51
incorrect       0.96      0.88      0.91        49
```
```
precision    recall  f1-score   support
toxic       0.72      1.00      0.84        47
non-toxic       1.00      0.66      0.80        53
```
```
precision    recall  f1-score   support …
```

feat(eval): add gpt-3.5-turbo-instruct to OpenAIModel

---

app/package.json
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx

Restores streaming for now for initial load. Need to investigate further on issues around refetch

fix: fix relay issue with refetch making the pagination stateful

---

.github/workflows/release.yml

Integrates `release-please` into our CI process.

ci: Add release-please github-action

---

cspell.json
src/phoenix/experimental/evals/models/openai.py
tests/experimental/evals/models/test_openai.py

Support for openAI azure
```
model = OpenAIModel(
model_name="gpt-4-32k",
azure_endpoint="https://arize-internal-llm-canada-east.openai.azure.com/",
api_version="2023-03-15-preview"
)
```

feat(evals): AzureOpenAI support for openAI 1.0

---

pyproject.toml

Updates `ruff` to the latest version

ci: Update Ruff 🐶

---

docs/api/evals.md
src/phoenix/experimental/evals/functions/generate.py

Adds documentation for #1736 
Targets main so it can go out with the next release

docs(evals): document llm_generate with output parser

---

tests/trace/llama_index/test_callback.py

part of #1796
this reverts #1794

ci: fix tracer unit test for llama-index 0.9.5

---

app/package-lock.json
app/package.json
app/src/App.tsx
app/src/contexts/FeatureFlagsContext.tsx
app/src/pages/trace/TracePage.tsx

resolves #1702 
Adds a feature flags context and set of controls that's visible via `ctr + shift + f`.
https://github.com/Arize-ai/phoenix/assets/5640648/23e5d301-6da6-4dea-b5b7-e725d40537c3

feat: feature flags context

---

tutorials/internal/trace_eval_ingestion_testing.ipynb

refactor: add notes to the internal notebook for evaluation result ingestion demo

---

tutorials/build_arize_docs_index_langchain_pinecone.py
tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb

not sure why this doesn't show up locally, but only on github

refactor: fix formatting error for github hatch run

---

tests/trace/llama_index/test_callback.py

- fixes a llamaindex patch broken by a recent update
https://github.com/run-llama/llama_index/pull/9301

fix: llama-index patch

---

src/phoenix/__init__.py
src/phoenix/session/evaluation.py
src/phoenix/trace/span_evaluations.py
src/phoenix/trace/trace_dataset.py
tests/trace/test_span_evaluations.py
tutorials/internal/trace_eval_ingestion_testing.ipynb

chore: Revert "refactor(traces): log span and document evaluations"

---

src/phoenix/session/evaluation.py
src/phoenix/session/session.py
src/phoenix/trace/dsl/__init__.py
src/phoenix/trace/dsl/helpers.py
src/phoenix/trace/dsl/query.py
tests/trace/dsl/test_query.py
tutorials/internal/span_query_language.ipynb
tutorials/internal/trace_eval_ingestion_testing.ipynb

feat(traces): query spans into dataframes

---

pyproject.toml
src/phoenix/__init__.py
src/phoenix/session/evaluation.py
src/phoenix/trace/span_evaluations.py
src/phoenix/trace/trace_dataset.py
tests/trace/test_span_evaluations.py
tutorials/internal/trace_eval_ingestion_testing.ipynb

chore: Revert "chore: Revert "refactor(traces): log span and document evaluations""

---

src/phoenix/trace/llama_index/callback.py
src/phoenix/trace/llama_index/streaming.py
src/phoenix/trace/tracer.py
tests/trace/llama_index/test_callback.py

partially resolves #1867 
We add instrumentation to LlamaIndex streaming responses to update the appropriate trace when the stream has been consumed.
Fast follow required: due to time constraints we will need to add testing and error handling to our implementation

feat: Instrument LlamaIndex streaming responses

---

src/phoenix/trace/__init__.py

places all the dataset classes under the same top level module

chore: export evaluation result datasets

---

src/phoenix/trace/openai/instrumentor.py
tests/trace/openai/test_instrumentor.py

- adds function call message attributes for streaming in both sync and async contexts
- forgoes adding the general LLM function call attribute, since there is no single function call attribute to serialize in the streaming context

feat: openai streaming function call message support

---

app/package.json
app/src/components/pointcloud/EventItem.tsx
app/src/components/pointcloud/PointCloudPointTooltip.tsx
app/src/pages/embedding/EventDetails.tsx
app/src/pages/embedding/PointSelectionGrid.tsx
app/src/utils/urlUtils.ts
src/phoenix/__init__.py

feat(embeddings): audio support

---

examples/using_llamaindex_with_huggingface_models.ipynb
pyproject.toml

See https://github.com/Arize-ai/phoenix/actions/runs/7175877405/job/19539891865

ci: fix linting on main

---

tutorials/evals/evaluate_rag.ipynb

docs: update rag evals docs

---

src/phoenix/experimental/evals/functions/classify.py
src/phoenix/experimental/evals/functions/executor.py
src/phoenix/experimental/evals/functions/generate.py
tests/experimental/evals/functions/test_executor.py

Add a flag to force synchronous submission.

chore: Add sync executor bypass

---

.dockerignore
Dockerfile

Slim down the docker image as much as possible and start with a thinner base image.

chore: slim down docker image

---

src/phoenix/core/traces.py

fix(traces): span summary root span filter

---

src/phoenix/trace/langchain/tracer.py

Naive datetimes are a problem for the OTLP migration.
Langchain [uses](https://github.com/langchain-ai/langchain/blob/320c3ae4c827ea7b752c8a29f06a06ae07d2a3b2/libs/core/langchain_core/tracers/base.py#L147) `utcnow()` which is timezone naive and is deprecated in Python 3.12.

refactor(traces): timezone awareness for start and end times in langchain tracer

---

src/phoenix/core/evals.py
src/phoenix/core/traces.py

https://github.com/Arize-ai/phoenix/assets/80478925/389be3a6-8cb7-4e77-823f-b088223716c8
https://github.com/Arize-ai/phoenix/assets/80478925/d43dcce2-fa44-4192-9a2d-b5dc9e4ef4ea

refactor: use `.get` for defaultdict

---

scripts/rag/llama_index_w_evals_and_qa.py

docs: update RAG evaluation script

---

.github/workflows/cla.yml

ci: run CLA workflow on merge commit

---

.github/workflows/cla.yml

Revert "ci: run CLA workflow on merge commit"

---

src/phoenix/session/evaluation.py

fix(traces): remove nan from log_evaluations

---

.github/workflows/release.yml

chore: Revert "chore: publish to PyPI after release"

---

app/package.json
app/src/pages/embedding/ExportSelectionButton.tsx

chore: make export code snippet into a code block

---

integration-tests/trace/llama_index/test_callback.py
src/phoenix/trace/llama_index/callback.py

fix(traces): prevent missing key exception when extracting invocation parameters in llama-index

---

src/phoenix/session/evaluation.py
src/phoenix/session/session.py

adds support for launching phoenix with evaluations

feat: launch phoenix with evaluations

---

tutorials/ragas_retrieval_evals_tutorial.ipynb

Update ragas notebook to the current implementation

docs(evals): update ragas integration notebook

---

src/phoenix/core/evals.py
src/phoenix/session/session.py

- adds `get_evaluations` method to Phoenix session object

feat: support eval exports for session

---

src/phoenix/session/session.py

adds `get_trace_dataset` method to session

feat: add get_trace_dataset method to session

---

src/phoenix/session/session.py

`shell` is None in Python console

fix: databricks check crashes in python console

---

src/phoenix/trace/otel.py

follow-up to https://github.com/Arize-ai/phoenix/pull/2148

refactor: catch all exceptions including TypeError when decoding json strings

---

src/phoenix/session/client.py

fix: localhost address for px.Client

---

src/phoenix/session/session.py

resolves #2205 
Warn the user that they are launching an app while the traces are being sent to a different endpoint.

fix(traces): warn if collector endpoint is set but launch app is called

---

scripts/rag/llama_index_w_evals_and_qa.py
src/phoenix/experimental/evals/evaluators.py
src/phoenix/experimental/evals/functions/classify.py
src/phoenix/experimental/evals/functions/generate.py
src/phoenix/experimental/evals/functions/processing.py
src/phoenix/experimental/evals/models/__init__.py
src/phoenix/experimental/evals/models/anthropic.py
src/phoenix/experimental/evals/models/base.py
src/phoenix/experimental/evals/models/bedrock.py
src/phoenix/experimental/evals/models/litellm.py
src/phoenix/experimental/evals/models/openai.py
src/phoenix/experimental/evals/models/vertex.py
src/phoenix/experimental/evals/models/vertexai.py

rename `BaseEvalModel` to `BaseModel`

refactor: rename BaseEvalModel to BaseModel

---

src/phoenix/session/session.py

resolves https://github.com/Arize-ai/phoenix/issues/2193

fix: endpoint for client inside ProcessSession

---

app/package.json
app/src/components/filter/PrimaryDatasetTimeRange.tsx
app/src/contexts/TimeRangeContext.tsx

fix(ui): add last_hour, fix end of hour rounding

---

src/phoenix/trace/otel.py

fix: handle ndarray during ingestion

---

scripts/rag/llamaindex_retrieval_chunk_eval.ipynb

Pins the version of phoenix / llama_index on the scripts directory

chore: pin llama-index on scripts/ directory

---

src/phoenix/trace/fixtures.py
src/phoenix/trace/trace_dataset.py
tutorials/example_datasets.ipynb

resolves #2174
Make dataset IDs unique by instance

fix(trace): Make dataset IDs unique by instance for TraceDataset

---

pyproject.toml

This will make all the notebooks just work out of the box, no extra install.

chore: add llama-index-callbacks-arize-phoenix to extras

---

tutorials/integrations/bedrock_tracing_tutorial.ipynb

Resolves https://github.com/Arize-ai/phoenix/issues/2133

docs: Add bedrock instrumentation notebook

---

tutorials/evals/evals_quickstart.ipynb
tutorials/evals/evaluate_rag.ipynb
tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
tutorials/llm_ops_overview.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb

docs: update notebooks for log_evaluations

---

docs/how-to/define-your-schema/llm-evaluations.md
docs/llm-evals/quickstart-retrieval-evals/README.md
docs/quickstart/evals.md
docs/use-cases/rag-evaluation.md

docs: update markdowns for `px.Client().log_evaluations()`

---

README.md
packages/phoenix-evals/README.md

docs(evals): add README

---

packages/phoenix-evals/pyproject.toml
pyproject.toml

fix: source distribution build

---

tutorials/tracing/autogen_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
tutorials/tracing/llama_index_tracing_tutorial.ipynb

docs(evals): update tracing tutorials with arize-phoenix-evals

---

app/package-lock.json
app/package.json
app/src/Routes.tsx
app/src/components/Link.tsx
app/src/components/nav/Navbar.tsx
app/src/components/trace/SpanKindIcon.tsx
app/src/pages/Layout.tsx
app/src/pages/home/homeLoader.ts
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/trace/TracePage.tsx
app/src/pages/tracing/SpansTable.tsx
app/src/pages/tracing/TracesTable.tsx
app/src/window.d.ts
cspell.json
src/phoenix/server/app.py
src/phoenix/server/templates/index.html

resolves #2351 
Re-organizes the left nav to add support for projects and adds a dummy project called `default` for when there is no project.

feat(ui): new side nav with projects

---

pyproject.toml
tests/experimental/evals/functions/test_generate.py

chore: downsize hatch dependencies

---

scripts/rag/llama_index_w_evals_and_qa.py
scripts/rag/llamaindex_retrieval_chunk_eval.ipynb

The existing rag optimization script and associated notebook has been updated for `llama-index>0.10.0`

chore: Update llama-index rag optimization script

---

README.md

resolves #2373 
Moves evals out of experimental, fixes llama-index code example to work with 0.10

docs: update readme for phoenix.evals, fix llama-index example

---

pyproject.toml
src/phoenix/server/main.py

resolves #2291 
Adds a server banner to guide the user if they are running using the command line or a container.

docs: log information about the server at startup

---

app/schema.graphql
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Project.py

- adds Project type satisfying node interface
- copies fields from TraceDatasetInfo onto this type

chore: add graphql scaffolding for projects

---

app/src/pages/project/SpansTable.tsx

see [trace table](https://github.com/Arize-ai/phoenix/blob/3e46d88bbddd5ef85fd4e2e3f61f4d75321bea9c/app/src/pages/project/TracesTable.tsx#L346-L346)

fix(ui): link to span in spans table

---

app/src/GlobalStyles.tsx
app/src/components/nav/Navbar.tsx
app/src/pages/Layout.tsx

resolves #2457 
Adds the ability to expand the side nav when hovering over it.
https://github.com/Arize-ai/phoenix/assets/5640648/facd97ba-df26-4c92-b439-b34b761d176e

feat(ui): auto-expand side nav on hover

---

src/phoenix/server/api/schema.py

Need the project node interface for building out project page.

feat(projects): project node interace

---

app/package.json
app/src/Routes.tsx
app/src/pages/Layout.tsx
app/src/pages/home/homeLoader.ts
app/src/pages/project/__generated__/projectLoaderQuery.graphql.ts
app/src/pages/project/index.tsx
app/src/pages/project/projectLoader.ts
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts

resolves #2446 
Lists out the projects that are configured and adds nav links to the appropriate pages

feat(projects): project listing

---

src/phoenix/core/traces.py
src/phoenix/server/api/routers/span_handler.py
src/phoenix/server/api/routers/trace_handler.py
src/phoenix/server/main.py
src/phoenix/session/session.py

refactor: remove post method on span handler

---

app/schema.graphql
app/src/pages/project/DocumentEvaluationSummary.tsx
app/src/pages/project/__generated__/DocumentEvaluationSummaryQuery.graphql.ts
app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
app/src/pages/project/__generated__/DocumentEvaluationSummaryValueQuery.graphql.ts
src/phoenix/server/api/schema.py

refactor(ui): fetch document evaluation summary from project

---

app/schema.graphql
app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
src/phoenix/core/project.py
src/phoenix/core/traces.py
src/phoenix/server/api/types/Project.py
tests/core/test_project.py

feat(gql): add trace count to gql project

---

app/schema.graphql
src/phoenix/server/api/types/Project.py

refactor: Add `streaming_last_updated_at` to Project model

---

app/schema.graphql
src/phoenix/server/api/types/Project.py

adds validate_span_filter_condition to project type

refactor: add validate_span_filter_condition to project type

---

app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
app/src/pages/home/homeLoader.ts

feat(ui): show first non-empty project

---

src/phoenix/core/traces.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/api/types/Span.py
tests/server/api/input_types/test_SpanSort.py

feat(graphql): embed project inside graphql span as private attribute

---

src/phoenix/trace/__init__.py
tests/trace/test_suppress_tracing.py

feat(trace): context manager to pause tracing

---

src/phoenix/session/session.py

Improves the reliability of detecting the Sagemaker notebook environment.

fix: parse files to detect sagemaker

---

src/phoenix/trace/__init__.py
src/phoenix/trace/projects.py
tests/trace/test_projects.py

resolves #2378
- Adds a context manager that dynamically overrides the project name for new spans

feat: Enable dynamic project switching

---

.github/workflows/python-CI.yml
pyproject.toml

add support for python 3.12
update dependencies to versions supporting 3.12

feat: add arize-phoenix support for python 3.12

---

src/phoenix/trace/langchain/instrumentor.py
src/phoenix/trace/llama_index/callback.py
src/phoenix/trace/openai/instrumentor.py

The limit value (i.e. 10,000) is arbitrary, but much larger than the default value of 128.

fix: increase span attributes limit to 10000

---

src/phoenix/trace/dsl/helpers.py

resolves #2566
resolves #2567
Adds optional `project_name` filter to client helper methods

feat: Add project name to client helper functions

---

src/phoenix/server/api/types/Span.py

fix: handle numpy types in json.dumps for gql

---

packages/phoenix-evals/src/phoenix/evals/classify.py

fix: pass verbose to evaluators

---

src/phoenix/core/project.py
src/phoenix/server/api/types/Span.py

resolves https://github.com/Arize-ai/phoenix/issues/2623

fix(trace): numpy array truth ambiguity

---

app/package-lock.json
app/package.json

Updates TypeScript version and related dependencies.
resolves #2629

chore: update typescript and related dependencies

---

app/src/pages/trace/TracePage.tsx
app/src/pages/trace/__generated__/TracePageQuery.graphql.ts

fix(ui): increase pagination size to 1000 for TracePage

---

src/phoenix/server/api/routers/evaluation_handler.py
src/phoenix/server/api/types/Span.py

fix: project name for evaluation ingestion

---

src/phoenix/trace/dsl/query.py
tests/trace/dsl/test_query.py

numpy array is not a `Sequence`

fix(trace): query dsl for numpy arrays

---

cspell.json
tutorials/mistral/evaluate_rag--mistral.ipynb

Add mistral instrumentation to the notebook

docs: add mistral instrumentation to notebook

---

tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
tutorials/mistral/evaluate_rag--mistral.ipynb

- docs: add mistral instrumentation to notebook
- Add mistral instrumentations
- docs: add mistral instrumentation to mistral example

docs: add mistral instrumentor to mistral tutorial

---

app/src/pages/trace/TracePage.tsx

Was passing the original string instead of the formatted JSON.

fix(ui): show formatted JSON for attributes

---

examples/manually-instrumented-chatbot/.gitignore
examples/manually-instrumented-chatbot/Makefile
examples/manually-instrumented-chatbot/README.md
examples/manually-instrumented-chatbot/app.py
examples/manually-instrumented-chatbot/chat/app.py
examples/manually-instrumented-chatbot/chat/types.py
examples/manually-instrumented-chatbot/pyproject.toml

manually instrumentation example

docs: manually instrumented chatbot

---

pyproject.toml
src/phoenix/db/database.py
src/phoenix/db/models.py

refactor: sqlite with SQLAlchemy

---

pyproject.toml
src/phoenix/server/app.py

- add `/healthz` route for health check
resolves #2799

chore: add /healthz route for healthchecks

---

src/phoenix/datasets/schema.py
src/phoenix/session/evaluation.py
src/phoenix/session/session.py

These things are no longer experimental

docs: remove experimental tags in code

---

Dockerfile
pyproject.toml
src/phoenix/config.py
src/phoenix/db/alembic.ini
src/phoenix/db/engines.py
src/phoenix/server/main.py
src/phoenix/session/session.py

feat(persistece): configurable sql engine

---

Dockerfile

fixes broken builds https://hub.docker.com/repository/registry-1.docker.io/arizephoenix/phoenix/builds/848e2ab9-1999-47b6-b23a-10ce17a6175f

fix: fix docker build for sql

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

feat(persistence): span annotation tables

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

adds trace annotations table
resolves #2776

chore: add trace annotations table

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

adds document annotations table
resolves #2776

chore: add document annotations table

---

cspell.json
pyproject.toml

On mac M1, you need this sub-package to run https://docs.sqlalchemy.org/en/20/faq/installation.html

ci(persistence): add asyncio to add greenlet for mac

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py

adds down migrations for annotation tables
resolves #2776

chore: add down migrations for annotation tables

---

src/phoenix/db/alembic.ini
src/phoenix/db/engines.py
src/phoenix/db/migrations/README.md
src/phoenix/db/migrations/env.py

#2794 
Makes it possible to run alembic via the commandline
```
alembic upgrade head
alembic downgrade -1
`

chore: make alembic runnable via command line

---

src/phoenix/db/bulk_inserter.py
src/phoenix/server/api/routers/evaluation_handler.py
src/phoenix/server/app.py

adds sqlite support for span evals ingested via pyarrow
resolves #2778

feat: ingest pyarrow span evals into sqlite

---

src/phoenix/db/bulk_inserter.py

feat: ingest document evals

---

src/phoenix/db/bulk_inserter.py

feat: ingest trace evals

---

examples/anthropic_evals_persona.ipynb
examples/dolly-pythia-fine-tuned/create_data_with_dolly_and_pythia.ipynb
examples/dolly-pythia-fine-tuned/dolly_vs_pythia.ipynb
examples/taylor_swift_lyrics.ipynb
tutorials/credit_card_fraud_tutorial.ipynb
tutorials/find_cluster_export_and_explore_with_gpt.ipynb
tutorials/image_classification_tutorial.ipynb
tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
tutorials/llama_index_search_and_retrieval_tutorial.ipynb
tutorials/llm_generative_gpt_4.ipynb
tutorials/llm_ops_overview.ipynb
tutorials/llm_summarization_tutorial.ipynb
tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
tutorials/mistral/evaluate_rag--mistral.ipynb
tutorials/ragas_retrieval_evals_tutorial.ipynb
tutorials/sentiment_classification_tutorial.ipynb

- `px.Dataset` has been deprecated, update all references to `px.Inferences` instead

chore: Update Dataset references in notebooks

---

README.md
src/phoenix/inferences/inferences.py
src/phoenix/server/main.py
src/phoenix/session/session.py

- Update more references to `px.Inferences`

chore: More `Inferences` cleanup

---

pyproject.toml
src/phoenix/db/migrations/env.py

Makes sure migration files are included in the bundle and image

fix: include migration files

---

src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/session/client.py

chore: Standardize query params

---

src/phoenix/server/api/types/EvaluationSummary.py
src/phoenix/server/api/types/Project.py

feat: Update eval summaries to use persistence

---

src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/services.py
src/phoenix/session/client.py
src/phoenix/session/session.py

resolves #2843 
By default phoenix uses a temp directory and can be overridden via a flag to `launch_app`

feat(persistence): make launch_app runnable on tmp directory

---

src/phoenix/config.py
src/phoenix/db/__init__.py
src/phoenix/db/engines.py
src/phoenix/server/main.py

resolves #2929 
Promotes the PHOENIX_SQL_DATABASE env var out of experimental and obfuscates the password

chore: promote PHOENIX_SQL_DATABASE_URL to a first-class env var

---

pyproject.toml
src/phoenix/db/engines.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/trace/dsl/filter.py
tests/trace/dsl/conftest.py
tests/trace/dsl/test_filter.py
tests/trace/dsl/test_query.py

This gives:
- SQLite v3.45.1
- `JSONB`
- `text_contains` (case sensitive substring search)

feat(persistence): use sqlean v3.45.1 as sqlite engine 

---

src/phoenix/server/api/types/Project.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/api/types/Trace.py

feat: fetch document retrieval metrics using SQL

---

src/phoenix/server/api/types/Project.py
src/phoenix/trace/dsl/filter.py
src/phoenix/trace/dsl/query.py

feat(persistence): fetch evaluation names

---

src/phoenix/db/bulk_inserter.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py
src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/types/Evaluation.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/api/types/Span.py

refactor: rename document index to document position in document_annotations table

---

src/phoenix/server/api/input_types/SpanSort.py
src/phoenix/server/api/types/Project.py

feat(persistence): add support for sorting by eval scores and labels

---

src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/span_descendants.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/app.py

feat(persistence): dataloader for span descendants

---

pyproject.toml
src/phoenix/config.py
src/phoenix/server/api/schema.py
src/phoenix/server/app.py
src/phoenix/server/main.py
src/phoenix/server/telemetry.py

feat: add opentelemetry trace instrumentation for Phoenix server

---

MIGRATION.md

docs: Add migration guide for `Dataset` -> `Inferences`

---

src/phoenix/db/bulk_inserter.py
src/phoenix/server/api/types/Span.py
src/phoenix/trace/schemas.py

fix: span event to dict conversion

---

src/phoenix/server/api/types/Project.py

fixes span and trace evaluation summaries
resolves #3002

fix: span and trace evaluation summaries

---

scripts/data/generate_traces.py
src/phoenix/server/api/routers/v1/evaluations.py

chore: script to generate spans and evaluations

---

DEVELOPMENT.md

resolves #2912 
Makes it explicit that you need to build the web app for phoenix to work

docs(development): make it explicit that you need to run pnpm build

---

src/phoenix/server/app.py
src/phoenix/server/openapi/docs.py

feat: openapi ui for api exploration

---

src/phoenix/server/api/types/Span.py

refactor: hide embedding vector

---

pyproject.toml
src/phoenix/db/bulk_inserter.py
src/phoenix/server/app.py
src/phoenix/server/grpc_server.py

Timers should be at the transactions (with disk write) and not at the statements (no disk write).

fix: prometheus for bulkloader

---

src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

feat: Add indexes on Annotation tables

---

src/phoenix/datetime_utils.py
src/phoenix/db/models.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/session/client.py

fix: normalize datetime for phoenix client

---

Dockerfile

fix: run docker as nonroot user

---

src/phoenix/db/engines.py
src/phoenix/db/insertion/span.py
src/phoenix/db/models.py
src/phoenix/server/api/types/Project.py

chore: clear todo tags

---

.github/workflows/python-CI.yml
.release-please-manifest.json
release-please-config.json

chore: Revert "ci: reset release please"

---

src/phoenix/trace/otel.py

fix: coerce `input.value` to string at ingestion

---

src/phoenix/db/migrations/types.py
src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
src/phoenix/db/models.py

Adds tables related to datasets, including:
- datasets
- dataset_versions
- examples
- example_revisions
resolves #3159

feat: add dataset-related tables

---

app/schema.graphql
app/src/store/pointCloudStore.ts
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Dataset.py

resolves #3163 
resolves #3164 
```graphql
{
datasets {
edges {
node {
id
name
description
createdAt
updatedAt
}
}
}
dataset: node(id: "RGF0YXNldDox") {
... on Dataset {
name
}
}
}
```

feat(datasets): datasets gql node and connection

---

app/schema.graphql
src/phoenix/server/api/schema.py
src/phoenix/server/api/types/Dataset.py

resolves #3161 
```graphql
mutation createDataset {
createDataset(name: "mikyo-8", description: "egg-fuu", metadata: "{}") {
id
name
description
createdAt
updatedAt
metadata
}
}
```

feat(datasets): gql dataset create

---

app/src/Routes.tsx
app/src/pages/Layout.tsx
app/src/pages/apis/APIsPage.tsx
app/src/pages/apis/index.tsx
app/src/pages/index.tsx

feat(datasets): expose the API playgrounds

---

src/phoenix/server/api/routers/v1/datasets.py

fix(datasets): api spec for upload endpoint

---

app/src/pages/datasets/CreateDatasetForm.tsx
app/src/pages/datasets/DatasetsPage.tsx
app/src/pages/datasets/__generated__/CreateDatasetFormMutation.graphql.ts

resolves #3209 
Adds a dialog to create a new "empty" dataset

feat(datasets): create dataset UI

---

app/schema.graphql
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/DatasetVersion.py

resolves #3201 
```graphql
{
datasets {
edges {
node {
... on Dataset {
name
versions {
edges {
version: node {
id
createdAt
}
}
}
}
}
}
}
}
```

feat(dataset): gql dataset versions connection

---

README.md

docs: new updated readme

---

app/schema.graphql
app/src/pages/datasets/CreateDatasetForm.tsx
app/src/pages/datasets/DatasetsPage.tsx
app/src/pages/datasets/__generated__/CreateDatasetFormMutation.graphql.ts
src/phoenix/server/api/input_types/CreateDatasetInput.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/types/CreateDatasetPayload.py

We are standardizing our mutations to use input and output types.
resolves #3219

refactor: use input and output types for create datasets mutation

---

app/schema.graphql
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/DatasetExample.py
tests/server/api/types/test_Dataset.py

feat: gql resolver for dataset examples

---

tests/server/api/mutations/test_dataset_mutations.py

Improves test case for adding span to dataset.
Depends on #3238.

test: improve test case for add span to dataset

---

src/phoenix/trace/dsl/helpers.py

fix: join on `trace_id` in `get_qa_with_reference`

---

tests/server/api/types/test_Project.py

- adds fixture for llama-index-rag
- adds test cases for pagination on `Project` spans resolvers

test: pagination

---

app/schema.graphql
app/src/components/dataset/__generated__/CreateDatasetFormMutation.graphql.ts
app/src/pages/project/__generated__/SpanSelectionToolbarAddSpansToDatasetMutation.graphql.ts
src/phoenix/server/api/input_types/AddExamplesToDatasetInput.py
src/phoenix/server/api/input_types/DatasetExampleInput.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/types/AddSpansToDatasetPayload.py

resolves #3233 
```graphql
mutation addExamples($input: AddExamplesToDatasetInput!){
addExamplesToDataset(input: $input) {
dataset {
name
}
}
}
```

feat(datasets): gql for adding examples

---

src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/dataset_examples.py
tests/server/api/conftest.py
tests/server/api/routers/v1/test_dataset_examples.py

resolves #3227 
resolves #3228

feat: List Dataset Examples

---

.github/workflows/docker-build-release.yml

- "on tag push" did not trigger on the last release
- try triggering on release directly

ci: Try to trigger image builds more reliably on release

---

src/phoenix/server/api/context.py
src/phoenix/server/api/schema.py
src/phoenix/server/app.py

Stopgap solution until we implement a more comprehensive version including the UI.

fix(gql): don't clear data if read_only

---

DEVELOPMENT.md

resolves #3212 
Adds minimum guidance on REST api design

docs: rest api guidance

---

app/src/pages/dataset/DatasetExamplesTable.tsx
app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/DatasetExamplesTableFragment.graphql.ts
app/src/pages/dataset/__generated__/DatasetExamplesTableQuery.graphql.ts
app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts

feat(datasets): add pagination to dataset examples table

---

app/src/pages/dataset/DatasetPage.tsx
src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/session/client.py
tests/server/api/routers/v1/test_datasets.py
tests/session/test_client.py

resolves #3308
resolves #3309
resolves #3310
resolves #3311

refactor: make csv download more restful

---

app/src/pages/trace/TracePage.tsx

- updates broken link to openinference spec
- improves copy

fix: update link to openinference spec

---

packages/phoenix-evals/src/phoenix/evals/models/bedrock.py

Quick addition to Bedrock Model to support mistral flavors

feat: Support mistral

---

src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/session/client.py
tests/server/api/conftest.py
tests/server/api/routers/v1/test_datasets.py
tests/session/test_client.py

feat(datasets): JSON endpoint to get dataset versions

---

app/schema.graphql
src/phoenix/server/api/input_types/DeleteDatasetInput.py
src/phoenix/server/api/mutations/dataset_mutations.py
tests/server/api/mutations/test_dataset_mutations.py

feat(datasets): Delete dataset mutation

---

app/src/Routes.tsx
app/src/components/code/index.tsx
app/src/pages/dataset/DatasetExamplePage.tsx
app/src/pages/dataset/DatasetExamplesTable.tsx
app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts
app/src/pages/dataset/index.tsx
app/src/pages/trace/TracePage.tsx

feat: dataset example slideover

---

app/src/pages/dataset/DatasetPage.tsx
app/src/pages/datasets/DatasetActionMenu.tsx
app/src/pages/datasets/DatasetsTable.tsx
app/src/pages/datasets/__generated__/DatasetActionMenuDeleteMutation.graphql.ts

resolves #3335 
Add the ability to delete a dataset from the datasets table.

feat(datasets): Delete dataset UI

---

pyproject.toml
src/phoenix/db/insertion/dataset.py
src/phoenix/server/api/routers/v1/datasets.py
tests/server/api/routers/v1/test_datasets.py

feat(datasets): synchronously upload dataset examples returning `dataset_id` in JSON

---

app/src/pages/dataset/DatasetExamplesTable.tsx
app/src/pages/dataset/ExampleSelectionToolbar.tsx
app/src/pages/dataset/__generated__/ExampleSelectionToolbarDeleteExamplesMutation.graphql.ts
app/src/pages/datasets/DatasetActionMenu.tsx
app/src/pages/datasets/DatasetsTable.tsx
app/src/pages/project/SpanSelectionToolbar.tsx
app/src/pages/project/SpansTable.tsx
app/src/pages/project/TracesTable.tsx

feat(datasets): Delete examples

---

pyproject.toml

chore: remove pytest-lazy-fixture

---

app/src/pages/datasets/DatasetActionMenu.tsx
app/src/pages/datasets/DatasetFromCSVForm.tsx
app/src/pages/datasets/DatasetsPage.tsx

resolves #3353 
Supports creating a dataset from a CSV file
https://github.com/Arize-ai/phoenix/assets/5640648/a0cd3b79-2357-44a4-a730-708f539dbcfc

feat(datasets): csv upload to create a dataset

---

app/src/pages/datasets/DatasetFromCSVForm.tsx
src/phoenix/server/api/routers/v1/datasets.py
tests/server/api/routers/v1/test_datasets.py

fix(datasets): json return payload for upload csv endpoint

---

app/schema.graphql
src/phoenix/server/api/input_types/DatasetVersionSort.py
src/phoenix/server/api/types/Dataset.py

resolves #3365 
```graphql
{
dataset: node(id: "RGF0YXNldDozNQ==") {
... on Dataset {
versions(sort: { col: createdAt, dir: desc}) {
edges {
node {
createdAt
}
}
}
}
}
}
```

feat(datasets): sort on version

---

app/schema.graphql
pyproject.toml
src/phoenix/server/api/input_types/PatchDatasetExamplesInput.py
src/phoenix/server/api/mutations/dataset_mutations.py
tests/server/api/mutations/test_dataset_mutations.py

feat: add patchDatasetExamples mutation

---

src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py

feat: add experiment-related tables and migrations

---

src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py

chore: add description column to experiment table

---

tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
tutorials/tracing/langchain_tracing_tutorial.ipynb
tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb

LangChain broke out their dependencies into several subpackages as part of 0.2.0. This PR adds those dependencies.
resolves #3317

fix: add separate package installations to notebooks

---

src/phoenix/db/migrate.py

resolves https://github.com/Arize-ai/phoenix/issues/3402
See [here](https://github.com/python/cpython/blob/14e1506a6d7056c38fbbc0797268dcf783f91243/Lib/configparser.py#L407-L408) and [here](https://stackoverflow.com/a/73899199)

fix: percentage sign for alembic configparser

---

app/schema.graphql
src/phoenix/server/api/queries.py
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/Experiment.py

resolves #3400 
```graphql
{
dataset: node(id: "RGF0YXNldDox") {
... on Dataset {
experiments {
edges {
node {
description
}
}
}
}
}
}
```

feat(experiments): gql resolver for experiments

---

app/schema.graphql
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/span_projects.py
src/phoenix/server/api/types/Project.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/app.py
tests/server/api/types/test_Span.py

feat: add project resolver on span

---

app/package.json
app/src/pages/dataset/DatasetExamplePage.tsx
app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts

feat(datasets): link to view source span

---

app/src/pages/dataset/AddDatasetExampleButton.tsx
app/src/pages/dataset/AddDatasetExampleDialog.tsx
app/src/pages/dataset/DatasetExamplesTable.tsx
app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/AddDatasetExampleDialogMutation.graphql.ts
app/src/pages/dataset/__generated__/DatasetExamplesTableFragment.graphql.ts
app/src/pages/dataset/__generated__/DatasetExamplesTableQuery.graphql.ts
app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts

feat(datasets): add example modal

---

src/phoenix/trace/dsl/filter.py

chore: add support for querying by datetime

---

app/schema.graphql
src/phoenix/server/api/types/Dataset.py
tests/server/api/types/test_Dataset.py

feat: gql resolver for dataset example count

---

src/phoenix/db/README.md

Edits a readme to trigger correct pipeline
resolves #3415

fix: add support for querying datetimes

---

app/schema.graphql
src/phoenix/server/api/types/Dataset.py
tests/server/api/types/test_Dataset.py

feat(datasets): gql resolver for experiment count

---

app/src/pages/dataset/DatasetHistoryButton.tsx
app/src/pages/dataset/DatasetHistoryDialog.tsx
app/src/pages/dataset/DatasetHistoryTable.tsx
app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/DatasetHistoryDialogQuery.graphql.ts
app/src/pages/dataset/__generated__/DatasetHistoryTableVersionsQuery.graphql.ts
app/src/pages/dataset/__generated__/DatasetHistoryTable_versions.graphql.ts

resolves #3438 
Displays the history of the dataset in a modal (MVP)

feat(datasets): version history modal

---

src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py
src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/server/api/routers/v1/experiments.py
tests/server/api/conftest.py
tests/server/api/routers/v1/test_experiments.py

@axiomofjoy the subquery strategy does not work for postgres

test: Add experiment fixtures, some tests and fix associated bugs

---

app/src/pages/dataset/ExampleSelectionToolbar.tsx
app/src/pages/datasets/DatasetsTable.tsx
app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
app/src/pages/project/SpanSelectionToolbar.tsx

Displays counts on the datasets table

feat(datasets): example and experiment count on datasets table

---

src/phoenix/server/api/types/Dataset.py
tests/server/api/mutations/test_dataset_mutations.py
tests/server/api/types/test_Dataset.py

feat(datasets): gql resolver returns examples in descending order

---

app/src/pages/dataset/DatasetExperimentsTable.tsx
app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/DatasetExperimentsTableFragment.graphql.ts
app/src/pages/dataset/__generated__/DatasetExperimentsTableQuery.graphql.ts
app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
app/src/pages/dataset/datasetLoader.ts

resolves #3450 
Add a minimum viable experiments table

feat(experiments): experiments table

---

src/phoenix/db/insertion/dataset.py
src/phoenix/server/api/routers/v1/datasets.py
tests/server/api/routers/v1/test_datasets.py

fix(datasets): allow duplicate keys for csv upload

---

app/schema.graphql
src/phoenix/db/models.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/api/types/ExperimentRun.py
tests/server/api/types/test_Experiment.py

feat: add runs resolver on Experiment type

---

app/schema.graphql
src/phoenix/server/api/queries.py
src/phoenix/server/api/types/AnnotatorKind.py
src/phoenix/server/api/types/ExperimentRun.py
src/phoenix/server/api/types/ExperimentRunAnnotation.py
tests/server/api/types/test_ExperimentRun.py

feat: add annotations resolver on DatasetRun type

---

app/schema.graphql
src/phoenix/server/api/types/DatasetExample.py
tests/server/api/types/test_DatasetExample.py

chore: change experiments resolver to experiment runs resolver on DatasetExample type

---

app/src/Routes.tsx
app/src/components/experiment/AnnotationLabel.tsx
app/src/components/experiment/index.tsx
app/src/pages/example/ExampleExperimentRunsTable.tsx
app/src/pages/example/ExamplePage.tsx
app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
app/src/pages/example/__generated__/ExampleExperimentRunsTableQuery.graphql.ts
app/src/pages/examples/ExamplesTable.tsx
app/src/pages/experiment/ExperimentComparePage.tsx
app/src/pages/experiment/index.tsx
app/src/pages/experiments/ExperimentsPage.tsx
app/src/pages/index.tsx
tutorials/evals/evaluate_rag.ipynb

resolves #3487 
Displays the the experiment runs of a specific example to track previous generations / task runs.

feat(datasets): example experiment runs

---

app/schema.graphql
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/experiment_sequence_number.py
src/phoenix/server/api/types/Dataset.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/app.py
tests/server/api/types/conftest.py
tests/server/api/types/test_Dataset.py
tests/server/api/types/test_Experiment.py

feat(datasets): add sequence number for experiments

---

src/phoenix/server/api/types/Experiment.py
tests/server/api/types/test_Experiment.py

fix: order runs in descending order in runs resolver on Experiment type

---

app/package.json
app/pnpm-lock.yaml
app/src/pages/project/TracesTable.tsx

Row selection was broken because `.rows` only returns the top level rows while `flatRows` returns the nested ones as well.
https://github.com/Arize-ai/phoenix/assets/5640648/58bfe25e-be6b-408e-925b-87ad1ebdd2f5

fix(datasets): select nested rows on traces

---

schemas/openapi.yaml
src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/datasets.py
tests/server/api/conftest.py
tests/server/api/routers/v1/test_datasets.py

feat(datasets): download jsonl for openai

---

schemas/openapi.yaml
src/phoenix/server/api/mutations/auth.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/mutations/export_events_mutations.py
src/phoenix/server/api/mutations/project_mutations.py
src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/dataset_examples.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/server/api/routers/v1/traces.py

feat(datasets): deny v1 routes and gql mutations if readonly

---

src/phoenix/session/client.py
src/phoenix/session/datasets.py
tests/session/test_client.py

feat: implement get_dataset method on phoenix.Client

---

app/src/pages/trace/TracePage.tsx

fix(ui): light mode for messages

---

app/schema.graphql
src/phoenix/datasets/experiments.py
src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py
src/phoenix/server/api/queries.py
src/phoenix/server/api/routers/v1/experiments.py
src/phoenix/server/api/types/Experiment.py
tests/datasets/test_experiments.py
tests/server/api/conftest.py
tests/server/api/types/conftest.py
tests/server/api/types/test_Dataset.py
tests/server/api/types/test_DatasetExample.py
tests/server/api/types/test_Experiment.py
tests/server/api/types/test_ExperimentRun.py

resolves #3494 
With experiments, it's pretty difficult to know what experiment to pick from a dropdown. This adds the ability to add a shorter name to and experiment so it's easier to find in the dropdowns. also will help with search

feat(experiments): add experiment name 

---

src/phoenix/db/models.py

fix: resolve warning for remote

---

app/package.json
app/pnpm-lock.yaml
app/src/pages/experiment/ExperimentMultiSelector.tsx
app/src/pages/experiment/__generated__/ExperimentMultiSelector__experiments.graphql.ts
app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
app/src/pages/experiments/ExperimentSelectionToolbar.tsx
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts

feat(experments): Switch UI to use experiment name

---

app/schema.graphql
app/src/pages/datasets/DatasetsTable.tsx
app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
src/phoenix/server/api/input_types/DatasetSort.py
src/phoenix/server/api/queries.py

feat(datasets): sort by name and created at

---

app/schema.graphql
src/phoenix/server/api/input_types/DeleteExperimentInput.py
src/phoenix/server/api/input_types/DeleteExperimentsInput.py
src/phoenix/server/api/mutations/experiment_mutations.py
tests/server/api/mutations/test_experiment_mutations.py

refactor: make deleteExperiments resolver support multiple deletions at once

---

app/src/components/table/styles.ts
app/src/pages/examples/ExampleSelectionToolbar.tsx
app/src/pages/experiments/ExperimentSelectionToolbar.tsx
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentSelectionToolbarDeleteExperimentsMutation.graphql.ts

resolves #3544 
delete experiments UI

feat(experiments): delete experiments ui

---

schemas/openapi.yaml
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/session/client.py
tests/session/test_client.py
tutorials/experiments/internal/run_experiments.ipynb

resolves #3537 
Adds a convenience method to be able to get a dataset by name in case the user doesn't want to leave the notebook

feat(datasets): get_dataset by name

---

src/phoenix/datasets/experiments.py

resolves #3484 
resolves #3520

feat: Add basic evaluators for string experiment outputs

---

app/src/components/ViewSummaryAside.tsx
app/src/components/code/JSONBlock.tsx
app/src/components/code/index.tsx
app/src/pages/example/ExamplePage.tsx
app/src/pages/experiment/ExperimentCompareTable.tsx

feat(experiments): select example / slideover on compare view

---

app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
app/src/pages/dataset/datasetLoader.ts
app/src/pages/datasets/DatasetsTable.tsx

resolves #3559 
If you have never run an experiment, it's confusing to land on experiments. This makes it so that you only land on experiments if you have run one before.

feat(datasets): navigate to examples if no experiments exist

---

app/src/RelayEnvironment.ts
app/src/components/code/PythonBlock.tsx
app/src/components/code/PythonBlockWithCopy.tsx
app/src/components/code/index.tsx
app/src/components/code/styles.tsx
app/src/config.ts
app/src/pages/dataset/DatasetCodeDropdown.tsx

resolves #3567 
Adds python instructions on how to download the dataset

feat(datasets): python instructions

---

src/phoenix/datasets/experiments.py
tests/datasets/test_experiments.py
tests/server/api/types/test_Experiment.py
tutorials/experiments/internal/run_experiments.ipynb

docs(datasets): print useful URLs, disable repetitions

---

app/schema.graphql
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/experiment_error_rates.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/app.py
tests/server/api/types/test_Experiment.py

feat: error rate resolver on Experiment type

---

src/phoenix/datasets/evaluators.py
src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py
tests/server/api/types/test_Experiment.py

chore: unique constraint on experiment_run_annotations table

---

src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py

Adds unique constraint on (experiment_id, dataset_example_id, repetition_number).
resolves #3593

chore: add unique constraint on experiment runs table

---

app/src/components/nav/Navbar.tsx
app/src/window.d.ts
src/phoenix/server/app.py
src/phoenix/server/templates/index.html

chore: display the platform version in the UI

---

src/phoenix/session/client.py
src/phoenix/trace/fixtures.py
tutorials/experiments/internal/run_experiments.ipynb
tutorials/experiments/run_experiments_with_llama_index.ipynb

chore: rename upload_dataset_examples to upload_dataset and add return type

---

packages/phoenix-evals/src/phoenix/evals/models/litellm.py
packages/phoenix-evals/src/phoenix/evals/models/vertexai.py

fix: resolve phoenix-eval type errors

---

docs/api/evals.md
packages/phoenix-evals/src/phoenix/evals/__init__.py
packages/phoenix-evals/src/phoenix/evals/evaluators.py

Added SQLEvaluator in the evaluators package that can be used to evaluate the SQL and the corresponding response generated by the LLM.

feat: added SQLEvaluator

---

src/phoenix/datasets/experiments.py
src/phoenix/server/api/openapi/schema.py

fix(experments): fix colab links

---

src/phoenix/session/client.py

feat(datasets): print the URL to the dataset when uploaded

---

cspell.json
pyment.conf
pyproject.toml
src/phoenix/datasets/tracing.py

This allows you to run pyment to generate documentation stubs using google format.
```sh
pyment -w -c ./pyment.conf ./src/phoenix/datasets/tracing.py
```

chore: add pyment config

---

schemas/openapi.yaml
src/phoenix/db/insertion/dataset.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/session/client.py
tests/db/insertion/test_dataset.py
tests/server/api/routers/v1/test_datasets.py
tutorials/experiments/langchain_email_extraction.ipynb

feat(datasets): upload JSON for dataset examples

---

src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/types/ExperimentRunAnnotation.py

fix(dataset): missing annotation trace id

---

src/phoenix/datasets/experiments.py

fix: support functools.partial for experiment tasks

---

app/schema.graphql
app/src/components/dataset/CreateDatasetForm.tsx
app/src/components/nav/Navbar.tsx
app/src/constants/timeConstants.ts
app/src/pages/RemoveProjectDataForm.tsx
app/src/pages/RemoveProjectTracesForm.tsx
app/src/pages/__generated__/RemoveProjectDataFormMutation.graphql.ts
app/src/pages/__generated__/RemoveProjectTracesFormMutation.graphql.ts
app/src/pages/projects/ProjectActionMenu.tsx
app/src/pages/projects/ProjectsPage.tsx
cspell.json
src/phoenix/db/migrations/versions/10460e46d750_datasets.py
src/phoenix/db/models.py
src/phoenix/server/api/input_types/ClearProjectInput.py
src/phoenix/server/api/mutations/project_mutations.py

resolves #3671
resolves #3641 
Adds the ability to clear traces older than X for a given project. Also fixes DB constraint errors that were introduced that caused clear traces to fail.

feat: ability to clear data older than X date, fix DB constraint errors for span.id from datasets to projects

---

packages/phoenix-evals/src/phoenix/evals/models/vertex.py

This code change resolves the issue https://github.com/Arize-ai/phoenix/issues/3592.
This adds a optional parameter 'credentials' which can be used to authenticate the vertexai GenerativeModel object.

fix: resolves the authentication issue for GeminiModel in evals model

---

tutorials/experiments/summarization.ipynb

docs(experiments): prompt template iteration for summarization task

---

app/schema.graphql
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/experiment_run_counts.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/app.py
tests/server/api/types/test_Experiment.py

feat(experiments): run count resolver on experiments

---

src/phoenix/db/insertion/evaluation.py
src/phoenix/db/insertion/helpers.py
src/phoenix/db/insertion/span.py
src/phoenix/server/api/routers/v1/experiments.py
tests/db/insertion/test_helpers.py

test: tests for insert on conflict

---

src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/experiment_evaluations.py

chore: add support for upserts for experiment evals

---

app/src/components/code/JSONText.tsx
app/src/pages/RemoveProjectDataForm.tsx
app/src/pages/example/ExampleExperimentRunsTable.tsx
app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
app/src/pages/example/__generated__/ExampleExperimentRunsTableQuery.graphql.ts
app/src/pages/example/__generated__/ExamplePageQuery.graphql.ts
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/projects/ProjectsPage.tsx

feat(experments): add the ability to view experiment metadata in full

---

app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts

feat(experiments): Show run count

---

app/src/pages/dataset/DatasetPage.tsx
app/src/pages/dataset/RunExperimentButton.tsx
app/src/pages/experiments/ExperimentsTable.tsx
app/src/store/datasetStore.tsx

resolves #3698
Still a lot more work on how to add LLM Evals etc. but want this placeholder as I work on the design.

feat(experments): minimum viable dialog showing how to run an experiment

---

src/phoenix/datasets/evaluators/__init__.py
tutorials/experiments/datasets_and_experiments_quickstart.ipynb

docs(notebook): datasets and experiments quickstart

---

app/src/components/dataset/CreateDatasetForm.tsx
app/src/contexts/NotificationContext.tsx
app/src/pages/trace/DatasetPicker.tsx
app/src/pages/trace/SpanToDatasetExampleDialog.tsx
app/src/pages/trace/TraceDetails.tsx
app/src/pages/trace/__generated__/DatasetPickerRefetchQuery.graphql.ts
app/src/pages/trace/__generated__/DatasetPicker__datasets.graphql.ts
app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts

resolves #3710 
Let's you create a dataset right before adding a span

feat(datasets): add the ability to create a dataset dynamically

---

.readthedocs.yaml
docs/api_sphinx/requirements.txt
docs/api_sphinx/source/conf.py

docs(api-ref): fix readthedocs build issues

---

MIGRATION.md

chore: Update MIGRATION.md for migrating parquet files from 3.x to 4.0

---

pyproject.toml
src/phoenix/config.py
src/phoenix/datasets/experiments.py
src/phoenix/datasets/types.py
src/phoenix/datasets/utils.py
src/phoenix/datetime_utils.py
src/phoenix/server/api/routers/v1/dataset_examples.py
src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/server/api/routers/v1/experiments.py
tests/server/api/routers/v1/test_experiments.py
tutorials/experiments/experiments_txt2sql.ipynb
tutorials/experiments/langchain_email_extraction.ipynb
tutorials/experiments/summarization.ipynb

resolves #3624 
resolves #3630 
resolves #3682 
Plus a `dry_run: bool` option

feat(datasets): print experiment summaries

---

packages/phoenix-evals/src/phoenix/evals/executors.py

chore: remove mention of llm_classify inside executor warning message

---

tutorials/experiments/txt2sql.ipynb

resolves #3576 
Adds synthetic data creation as well as the possibility of using OpenAI ft at the end

docs(experiments): txt2sql

---

app/src/components/code/JSONText.tsx
app/src/components/experiment/AnnotationLabel.tsx
app/src/components/table/styles.ts
app/src/pages/dataset/RunExperimentButton.tsx
app/src/pages/experiment/ExperimentCompareTable.tsx
app/src/pages/experiments/ExperimentsTable.tsx

Column resizing was miserable. This fixes this and makes the table much more performant with memoizing. Also eliminates a lot of distractions.

fix(experiments): Improve the performance of the table via caching

---

src/phoenix/datasets/types.py

feat(datasets): add dataframe property to dataset

---

DEVELOPMENT.md
schemas/openapi.yaml
src/phoenix/datasets/experiments.py
src/phoenix/server/api/routers/v1/dataset_examples.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/server/api/routers/v1/evaluations.py
src/phoenix/server/api/routers/v1/experiments.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/session/client.py
tests/server/api/routers/v1/test_dataset_examples.py
tests/server/api/routers/v1/test_datasets.py
tests/server/api/routers/v1/test_experiments.py
tests/session/test_client.py

chore: change query params to use underscores rather than dashes

---

app/src/pages/example/ExampleDetailsDialog.tsx
app/src/pages/example/ExamplePage.tsx
app/src/pages/example/__generated__/ExampleDetailsDialogDialogQuery.graphql.ts
app/src/pages/example/__generated__/ExampleDetailsDialogQuery.graphql.ts
app/src/pages/experiment/ExperimentCompareTable.tsx

feat(datasets): show example details in a slide-over

---

packages/phoenix-evals/src/phoenix/evals/executors.py

fix: remove mention of llm_classify in warning message (#3731)

---

app/schema.graphql
app/src/components/trace/LatencyText.tsx
app/src/pages/experiments/ExperimentsTable.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
src/phoenix/server/api/context.py
src/phoenix/server/api/dataloaders/__init__.py
src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
src/phoenix/server/api/types/Experiment.py
src/phoenix/server/app.py
tests/server/api/types/test_Experiment.py

feat: display average run latency in the experiments table

---

tests/server/api/test_queries.py
tests/server/api/types/test_Project.py

test: experiment projects are omitted

---

src/phoenix/session/client.py

refactor: rename append_dataset client method to append_to_dataset

---

src/phoenix/experiments/functions.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/server/api/routers/v1/experiments.py
tests/server/api/routers/v1/test_datasets.py
tests/server/api/routers/v1/test_experiments.py

chore: Nest experiment payloads under `data` key

---

pyproject.toml
src/phoenix/experiments/evaluators/utils.py
src/phoenix/experiments/functions.py
src/phoenix/experiments/types.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/session/client.py
src/phoenix/utilities/json.py
tests/datasets/test_experiments.py
tests/session/test_client.py
tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
tutorials/experiments/llama-index/guideline_eval.ipynb
tutorials/experiments/llama-index/pairwise_eval.ipynb

- Added dataframes for `Experiment` and its evaluations
- Added `__repr__` to help users build their intuitions and onboard faster. See below.

feat(datasets): usability enhancements

---

tutorials/experiments/summarization.ipynb

fix: dataset.examples list

---

tutorials/experiments/txt2sql.ipynb

fix: upload examples in txt2sql

---

schemas/openapi.yaml
src/phoenix/server/api/routers/v1/experiment_evaluations.py
src/phoenix/server/api/routers/v1/experiment_runs.py
src/phoenix/server/api/routers/v1/experiments.py

chore: Add OpenAPI specs to experiment routes

---

src/phoenix/experiments/evaluators/utils.py
src/phoenix/experiments/functions.py
src/phoenix/experiments/types.py
src/phoenix/experiments/utils.py
src/phoenix/session/client.py
tests/datasets/test_experiments.py
tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
tutorials/experiments/llama-index/guideline_eval.ipynb
tutorials/experiments/llama-index/pairwise_eval.ipynb

feat(datasets): add `reference` as alias of `expected` for evaluator argument bindings

---

src/phoenix/experiments/functions.py

chore: print experiment errors to console

---

src/phoenix/session/client.py
tests/session/test_client.py

chore: remove download_dataset_examples client_method

---

app/src/components/experiment/AnnotationLabel.tsx

fix(UI): explanation overflow

---

app/package.json
app/pnpm-lock.yaml
app/src/openInference/tracing/types.ts
app/src/pages/trace/TraceDetails.tsx

feat(image): add image rendering on messages

---

app/src/pages/projects/ProjectsPage.tsx
app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts

fix: make projects page scrollable

---

tutorials/experiments/llama-index/guideline_eval.ipynb

stopgap for this [bug](https://github.com/Arize-ai/phoenix/issues/3844)

chore: change task function to be async in notebook

---

src/phoenix/experiments/functions.py
src/phoenix/experiments/types.py
tests/datasets/test_experiments.py
tutorials/experiments/llama-index/guideline_eval.ipynb

resolves #3844 
I have not bottomed out the issue, but running in threads seemed to have helped.

fix: do client.post in thread

---

app/src/pages/datasets/DatasetActionMenu.tsx
app/src/pages/experiments/ExperimentSelectionToolbar.tsx
schemas/openapi.yaml
src/phoenix/db/helpers.py
src/phoenix/server/api/dataloaders/project_by_name.py
src/phoenix/server/api/mutations/dataset_mutations.py
src/phoenix/server/api/mutations/experiment_mutations.py
src/phoenix/server/api/routers/v1/__init__.py
src/phoenix/server/api/routers/v1/datasets.py
src/phoenix/server/api/utils.py
tests/server/api/routers/v1/test_datasets.py
tests/server/api/routers/v1/test_experiments.py

feat: REST endpoint to delete dataset

---

src/phoenix/db/bulk_inserter.py

Reverts Arize-ai/phoenix#3870
Reverting this because I did not consider the fact that updates could be clobbered.

revert: "feat: retry eval insertions"

---

app/src/pages/dataset/RunExperimentButton.tsx

This is broken in hosted phoenix @axiomofjoy

fix: remove phoenix.daasets imports

---

src/phoenix/server/api/mutations/project_mutations.py

resolves #3880 
`UNSET` is not `None`

fix(graphql): clear project when `end_time` is `UNSET`

---

app/schema.graphql
app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
src/phoenix/server/api/input_types/CreateSpanAnnotationsInput.py
src/phoenix/server/api/input_types/CreateTraceAnnotationsInput.py
src/phoenix/server/api/input_types/DeleteAnnotationsInput.py
src/phoenix/server/api/input_types/PatchAnnotationsInput.py
src/phoenix/server/api/mutations/__init__.py
src/phoenix/server/api/mutations/span_annotations_mutations.py
src/phoenix/server/api/mutations/trace_annotations_mutations.py
src/phoenix/server/api/routers/v1/spans.py
src/phoenix/server/api/routers/v1/traces.py
src/phoenix/server/api/types/AnnotatorKind.py
src/phoenix/server/api/types/ExperimentRunAnnotation.py
src/phoenix/server/api/types/SpanAnnotation.py
src/phoenix/server/api/types/TraceAnnotation.py
tests/server/api/types/test_SpanAnnotation.py
tests/server/api/types/test_TraceAnnotation.py

resolves #3769 
resolves #3770 
resolves #3824

feat: Add GQL mutations for Span + Trace Annotations

---

src/phoenix/server/main.py

See Python [doc](https://docs.python.org/3/library/argparse.html#action)

fix: debug flag should be `store_true`

---

app/schema.graphql
app/src/pages/experiments/ErrorRateCell.tsx
app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
src/phoenix/server/api/dataloaders/experiment_error_rates.py
src/phoenix/server/api/dataloaders/experiment_run_counts.py
src/phoenix/server/api/types/Experiment.py
tests/server/api/types/test_Experiment.py

fix(experiments): ensure experiments table appears even when an experiment has no runs

---

pyproject.toml
src/phoenix/db/bulk_inserter.py
tests/conftest.py
tests/db/insertion/test_helpers.py
tests/server/api/conftest.py
tests/server/api/routers/v1/test_spans.py

chore: fix Starlette lifespan for tests

---

src/phoenix/session/client.py

chore: allow kwargs for get_dataset_version first argument

---

src/phoenix/session/client.py

chore: deprecate and remove dataset_description parameter in append_to_dataset client method

---

.github/workflows/release.yml
app/package.json
app/pnpm-lock.yaml

- remove rimraf
- remove clean from pipeline

fix: remove clean step from release pipeline and remove rimraf dev dep

---

examples/proxy/.gitignore
examples/proxy/README.md
examples/proxy/routes.toml
examples/proxy/traefik.toml

docs: add reverse proxy example

---

app/package.json
app/vite.config.mts
src/phoenix/server/templates/index.html

resolves #3996
- Removes watch from dev:ui script as that is now taken care of vite
- updates vite config to allow for accessing ui in development from local host or 0.0.0.0

fix: remove invalid command from dev:ui script

---

app/src/pages/project/SpanFilterConditionField.tsx

resolves #4000 
resolves #4001 
Adds simple annotation macro and snippet to SpanFilterConditionField
https://github.com/user-attachments/assets/e9ba8a54-aef0-4fbc-846b-53493d957f7e

feat(annotations): add annot ation macro and filter condition snippet to project page

---

app/schema.graphql
src/phoenix/server/api/input_types/SpanAnnotationSort.py
src/phoenix/server/api/input_types/TraceAnnotationSort.py
src/phoenix/server/api/types/Span.py
src/phoenix/server/api/types/Trace.py

feat: Add sort order argument to Span- and Trace- Annotation fields

---

app/src/components/ColorSwatch.tsx
app/src/components/annotation/AnnotationColorSwatch.tsx
app/src/components/annotation/AnnotationLabel.tsx
app/src/pages/project/RetrievalEvaluationLabel.tsx

feat(annotations): update RetrievalEvaluationLabel styles to match AnnotationLabel

---

app/src/pages/project/SpansTable.tsx
app/src/pages/project/TracesTable.tsx

docs(annotations): add a feedback tooltip

---

src/phoenix/session/client.py

fix: ensure rest api urls include custom root path
